// Generated by MarrowScript compiler. DO NOT EDIT.
// React hooks for the MarrowForge API.
//
// Pair with sdk/client.ts. Pass an instance of <System>Client to <ApiProvider>.

import { useCallback, useEffect, useState, createContext, useContext, ReactNode, createElement } from "react";

export interface ForgeRequest {
  id: string;
  created_at: string;
  updated_at: string;
  title: string;
  description: string;
  desired_kind: string;
  target_path: string;
  complexity: number;
}

export interface ForgeResult {
  id: string;
  created_at: string;
  updated_at: string;
  request_id: string;
  kind: string;
  summary: string;
  target_path: string;
  target_symbol: string;
  artifact: string;
  plan: string;
  confidence: number;
  ast_compiles: boolean;
  tier_used: string;
  trace_id: string;
}

export interface RepoForgeRequest {
  id: string;
  created_at: string;
  updated_at: string;
  title: string;
  description: string;
  preset: string;
  repo_a_url: string;
  repo_b_url: string;
  repo_a_ref: string;
  repo_b_ref: string;
  target_path: string;
  complexity: number;
}

export interface ApiClient {
  baseUrl: string;
  getToken: () => string | null;
}

async function apiFetch<T>(client: ApiClient, method: string, path: string, body?: unknown): Promise<T> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  const token = client.getToken();
  if (token) headers["Authorization"] = "Bearer " + token;
  const res = await fetch(client.baseUrl + path, {
    method,
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    let errMsg = "Request failed: " + res.status;
    try { const j = await res.json() as { error?: { message?: string } }; if (j.error?.message) errMsg = j.error.message; } catch {}
    throw new Error(errMsg);
  }
  if (res.status === 204) return undefined as unknown as T;
  return await res.json() as T;
}

const ApiContext = createContext<ApiClient | null>(null);

export interface ApiProviderProps {
  client: ApiClient;
  children: ReactNode;
}

export function ApiProvider(props: ApiProviderProps) {
  return createElement(ApiContext.Provider, { value: props.client }, props.children);
}

function useApi(): ApiClient {
  const ctx = useContext(ApiContext);
  if (!ctx) throw new Error("useApi must be used inside <ApiProvider>");
  return ctx;
}

export interface QueryState<T> {
  data: T | null;
  loading: boolean;
  error: Error | null;
  refetch: () => Promise<void>;
}

export interface MutationState<TInput, TOutput> {
  mutate: (input: TInput) => Promise<TOutput>;
  loading: boolean;
  error: Error | null;
  reset: () => void;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}

function useQueryGeneric<T>(method: string, path: string, deps: unknown[]): QueryState<T> {
  const client = useApi();
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const fetchOnce = useCallback(async () => {
    setLoading(true); setError(null);
    try { const result = await apiFetch<T>(client, method, path); setData(result); }
    catch (e: unknown) { setError(e instanceof Error ? e : new Error(String(e))); }
    finally { setLoading(false); }
  }, [client, method, path]);
  useEffect(() => { void fetchOnce(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, deps);
  return { data, loading, error, refetch: fetchOnce };
}

function useMutationGeneric<TInput, TOutput>(builder: (input: TInput) => { method: string; path: string; body?: unknown }): MutationState<TInput, TOutput> {
  const client = useApi();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  const mutate = useCallback(async (input: TInput): Promise<TOutput> => {
    setLoading(true); setError(null);
    try { const req = builder(input); return await apiFetch<TOutput>(client, req.method, req.path, req.body); }
    catch (e: unknown) { const err = e instanceof Error ? e : new Error(String(e)); setError(err); throw err; }
    finally { setLoading(false); }
  }, [client, builder]);
  const reset = useCallback(() => setError(null), []);
  return { mutate, loading, error, reset };
}

// ─── ForgeRequest ───────────────────────────────────────────────────────────

export function useListForgeRequest(): QueryState<PaginatedResponse<ForgeRequest>> {
  return useQueryGeneric<PaginatedResponse<ForgeRequest>>("GET", "/forge_requests", []);
}

export function useForgeRequest(id: string | null): QueryState<ForgeRequest> {
  return useQueryGeneric<ForgeRequest>("GET", id ? `/forge_requests/${id}` : "/forge_requests", [id]);
}

export function useCreateForgeRequest(): MutationState<Partial<ForgeRequest>, ForgeRequest> {
  return useMutationGeneric<Partial<ForgeRequest>, ForgeRequest>((input) => ({ method: "POST", path: "/forge_requests", body: input }));
}

export function useUpdateForgeRequest(): MutationState<{ id: string; patch: Partial<ForgeRequest> }, ForgeRequest> {
  return useMutationGeneric<{ id: string; patch: Partial<ForgeRequest> }, ForgeRequest>(({ id, patch }) => ({ method: "PUT", path: `/forge_requests/${id}`, body: patch }));
}

export function useDeleteForgeRequest(): MutationState<string, void> {
  return useMutationGeneric<string, void>((id) => ({ method: "DELETE", path: `/forge_requests/${id}` }));
}

export function useCapabilitySliceCodebase(): MutationState<{ r: ForgeRequest }, unknown> {
  return useMutationGeneric<{ r: ForgeRequest }, unknown>((input) => ({ method: "POST", path: "/forge_requests/slice-codebase", body: input }));
}

export function useCapabilityForge(): MutationState<{ r: ForgeRequest }, { ok: boolean; action: string; trace_id: string | null; results: Record<string, unknown> }> {
  return useMutationGeneric<{ r: ForgeRequest }, { ok: boolean; action: string; trace_id: string | null; results: Record<string, unknown> }>((input) => ({ method: "POST", path: "/forge_requests/forge", body: input }));
}

export function useCapabilityScopeRequest(): MutationState<{ r: ForgeRequest }, unknown> {
  return useMutationGeneric<{ r: ForgeRequest }, unknown>((input) => ({ method: "POST", path: "/forge_requests/scope-request", body: input }));
}

export function useCapabilityGenerateRequest(): MutationState<{ r: ForgeRequest }, unknown> {
  return useMutationGeneric<{ r: ForgeRequest }, unknown>((input) => ({ method: "POST", path: "/forge_requests/generate-request", body: input }));
}

// ─── ForgeResult ───────────────────────────────────────────────────────────

export function useListForgeResult(): QueryState<PaginatedResponse<ForgeResult>> {
  return useQueryGeneric<PaginatedResponse<ForgeResult>>("GET", "/forge_results", []);
}

export function useForgeResult(id: string | null): QueryState<ForgeResult> {
  return useQueryGeneric<ForgeResult>("GET", id ? `/forge_results/${id}` : "/forge_results", [id]);
}

export function useCreateForgeResult(): MutationState<Partial<ForgeResult>, ForgeResult> {
  return useMutationGeneric<Partial<ForgeResult>, ForgeResult>((input) => ({ method: "POST", path: "/forge_results", body: input }));
}

export function useUpdateForgeResult(): MutationState<{ id: string; patch: Partial<ForgeResult> }, ForgeResult> {
  return useMutationGeneric<{ id: string; patch: Partial<ForgeResult> }, ForgeResult>(({ id, patch }) => ({ method: "PUT", path: `/forge_results/${id}`, body: patch }));
}

export function useDeleteForgeResult(): MutationState<string, void> {
  return useMutationGeneric<string, void>((id) => ({ method: "DELETE", path: `/forge_results/${id}` }));
}

export function useCapabilitySaveForgeResult(): MutationState<{ res: ForgeResult }, unknown> {
  return useMutationGeneric<{ res: ForgeResult }, unknown>((input) => ({ method: "POST", path: "/forge_results/save-forge-result", body: input }));
}

export function useCapabilityMarkForgeFailed(): MutationState<{ res: ForgeResult; reason: string }, unknown> {
  return useMutationGeneric<{ res: ForgeResult; reason: string }, unknown>((input) => ({ method: "POST", path: "/forge_results/mark-forge-failed", body: input }));
}

// ─── RepoForgeRequest ───────────────────────────────────────────────────────────

export function useListRepoForgeRequest(): QueryState<PaginatedResponse<RepoForgeRequest>> {
  return useQueryGeneric<PaginatedResponse<RepoForgeRequest>>("GET", "/repo_forge_requests", []);
}

export function useRepoForgeRequest(id: string | null): QueryState<RepoForgeRequest> {
  return useQueryGeneric<RepoForgeRequest>("GET", id ? `/repo_forge_requests/${id}` : "/repo_forge_requests", [id]);
}

export function useCreateRepoForgeRequest(): MutationState<Partial<RepoForgeRequest>, RepoForgeRequest> {
  return useMutationGeneric<Partial<RepoForgeRequest>, RepoForgeRequest>((input) => ({ method: "POST", path: "/repo_forge_requests", body: input }));
}

export function useUpdateRepoForgeRequest(): MutationState<{ id: string; patch: Partial<RepoForgeRequest> }, RepoForgeRequest> {
  return useMutationGeneric<{ id: string; patch: Partial<RepoForgeRequest> }, RepoForgeRequest>(({ id, patch }) => ({ method: "PUT", path: `/repo_forge_requests/${id}`, body: patch }));
}

export function useDeleteRepoForgeRequest(): MutationState<string, void> {
  return useMutationGeneric<string, void>((id) => ({ method: "DELETE", path: `/repo_forge_requests/${id}` }));
}

export function useCapabilityIngestRepoA(): MutationState<{ r: RepoForgeRequest }, unknown> {
  return useMutationGeneric<{ r: RepoForgeRequest }, unknown>((input) => ({ method: "POST", path: "/repo_forge_requests/ingest-repo-a", body: input }));
}

export function useCapabilityIngestRepoB(): MutationState<{ r: RepoForgeRequest }, unknown> {
  return useMutationGeneric<{ r: RepoForgeRequest }, unknown>((input) => ({ method: "POST", path: "/repo_forge_requests/ingest-repo-b", body: input }));
}

export function useCapabilityForgeFromRepos(): MutationState<{ r: RepoForgeRequest }, { ok: boolean; action: string; trace_id: string | null; results: Record<string, unknown> }> {
  return useMutationGeneric<{ r: RepoForgeRequest }, { ok: boolean; action: string; trace_id: string | null; results: Record<string, unknown> }>((input) => ({ method: "POST", path: "/repo_forge_requests/forge-from-repos", body: input }));
}

export interface CognitionSpan {
  span_id: string;
  trace_id: string;
  parent_span_id: string | null;
  workflow: string;
  step: string;
  kind: string;
  prompt: string | null;
  model: string | null;
  provider: string | null;
  validate_result: string | null;
  confidence: number | null;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  cost_usd: number | null;
  latency_ms: number;
  cache_hit: boolean;
  status: string;
  error_code: string | null;
  started_at: number;
  finished_at: number | null;
}

export interface CognitionTrace {
  trace_id: string;
  span_count: number;
  spans: CognitionSpan[];
}

/** Fetch every span recorded for a trace_id. Pass null to keep the hook idle. */
export function useCognitionTrace(trace_id: string | null): QueryState<CognitionTrace> {
  return useQueryGeneric<CognitionTrace>("GET", trace_id ? `/cognition_traces/${trace_id}` : "/cognition_traces", [trace_id]);
}
