// Generated by MarrowScript compiler. DO NOT EDIT.
// Service: ListingService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import rateLimit from "express-rate-limit";
import { auditLog } from "../audit";
import { logger } from "../logger";
import { counter } from "../metrics";
import { ListingCreateSchema, ListingUpdateSchema } from "../schemas";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

import { transitionListing, LISTING_INITIAL } from "../state_machines/listing";

export const listingsRouter = Router();

// Rate limiter from policy declaration
const __routeRateLimit = rateLimit({ windowMs: 60000, max: 200, standardHeaders: true, legacyHeaders: false });

// CREATE
listingsRouter.post("/", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  // Validate the request body against the generated Zod schema.
  const __parsed = ListingCreateSchema.safeParse(req.body);
  if (!__parsed.success) {
    return res.status(400).json({ error: { code: "VALIDATION_FAILED", message: "Invalid request body", issues: __parsed.error.flatten() } });
  }
  const __body = __parsed.data;
  try {
    const id = uuid();
    const { seller_id, title, description, price, stock, category } = __body as any;
    const state = LISTING_INITIAL;
    const sql = `INSERT INTO listings (id, seller_id, title, description, price, stock, category, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING *`;
    const rows = await query(sql, [id, seller_id, title, description, price, stock, category, state]);
    counter("entity.created", { entity: "Listing" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
listingsRouter.get("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const row = await queryOne(`SELECT * FROM listings WHERE id = $1`, [req.params.id]);
    if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.json(row);
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// LIST
listingsRouter.get("/", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
    const offset = (page - 1) * pageSize;
    const rows = await query(`SELECT listings.*, row_to_json(seller.*) as seller FROM listings LEFT JOIN sellers seller ON listings.seller_id = seller.id ORDER BY listings.created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
    const [{ count }] = await query(`SELECT COUNT(*) as count FROM listings`);
    res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// UPDATE
const __listingsUpdatable = new Set<string>(["seller_id","title","description","price","stock","category","state"]);
listingsRouter.put("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  // 1. Validate body shape and types via Zod (UpdateSchema is partial).
  const __parsed = ListingUpdateSchema.safeParse(req.body);
  if (!__parsed.success) {
    return res.status(400).json({ error: { code: "VALIDATION_FAILED", message: "Invalid request body", issues: __parsed.error.flatten() } });
  }
  // 2. Reject unknown columns (defense in depth — Zod would already strip them).
  const __unknown = Object.keys(req.body || {}).filter(k => !__listingsUpdatable.has(k));
  if (__unknown.length > 0) {
    return res.status(400).json({ error: { code: "UNKNOWN_FIELDS", message: `Unknown fields: ${__unknown.join(", ")}`, fields: __unknown } });
  }
  // 3. Use the Zod-parsed object as the update set.
  const fields: Record<string, unknown> = __parsed.data as Record<string, unknown>;
  if (Object.keys(fields).length === 0) {
    return res.status(400).json({ error: { code: "NO_FIELDS", message: "No updatable fields supplied" } });
  }
  // State machine enforcement
  if (fields.state !== undefined) {
    const current = await queryOne<{ state: string }>(`SELECT state FROM listings WHERE id = $1`, [req.params.id]);
    if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    // Find the trigger for this state transition
    const trigger = `${current.state}_to_${fields.state}`;
    const tr = transitionListing(current.state as any, trigger);
    if (!tr.ok) return res.status(422).json({ error: { code: "INVALID_TRANSITION", message: `Cannot transition from ${current.state} to ${fields.state}` } });
  }
  const keys = Object.keys(fields);
  const sets = keys.map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = keys.map(k => fields[k]);
  const sql = `UPDATE listings SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
listingsRouter.delete("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const count = await execute(`DELETE FROM listings WHERE id = $1`, [req.params.id]);
    if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.status(204).send();
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// CAPABILITY: publish_listing [transactional]
listingsRouter.post("/publish-listing", __routeRateLimit, requireAuth, auditLog("publish_listing", "Listing"), async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const seller = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.body.seller_id || req.params.id]);
    if (!seller) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "seller not found" } });
    }
    const listing = await queryOne(`SELECT * FROM listings WHERE id = $1`, [req.body.listing_id || req.params.id]);
    if (!listing) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "listing not found" } });
    }

    // Preconditions
    if (!(auth?.actor_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "caller.id == seller.id" } });
    }
    if (!(seller?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "seller.state == \\\"active\\\"" } });
    }
    if (!(listing?.state === "draft")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.state == \\\"draft\\\"" } });
    }
    if (!(listing?.seller_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.seller_id == seller.id" } });
    }
    if (!(listing?.stock > 0)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.stock > 0" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE listings SET state = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["active", req.body.listing_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: listing.state = \"active\"");
    }

    res.json({ ok: true, action: "publish_listing", entity: seller });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: archive_listing [transactional]
listingsRouter.post("/archive-listing", __routeRateLimit, requireAuth, auditLog("archive_listing", "Listing"), async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const seller = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.body.seller_id || req.params.id]);
    if (!seller) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "seller not found" } });
    }
    const listing = await queryOne(`SELECT * FROM listings WHERE id = $1`, [req.body.listing_id || req.params.id]);
    if (!listing) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "listing not found" } });
    }

    // Preconditions
    if (!(auth?.actor_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "caller.id == seller.id" } });
    }
    if (!(seller?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "seller.state == \\\"active\\\"" } });
    }
    if (!(listing?.seller_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.seller_id == seller.id" } });
    }
    if (!(listing?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.state == \\\"active\\\"" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE listings SET state = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["archived", req.body.listing_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: listing.state = \"archived\"");
    }

    res.json({ ok: true, action: "archive_listing", entity: seller });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: place_order [transactional]
listingsRouter.post("/place-order", __routeRateLimit, requireAuth, auditLog("place_order", "Listing"), async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    const { quantity } = req.body;

    // Fetch entities
    const buyer = await queryOne(`SELECT * FROM buyers WHERE id = $1`, [req.body.buyer_id || req.params.id]);
    if (!buyer) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "buyer not found" } });
    }
    const listing = await queryOne(`SELECT * FROM listings WHERE id = $1`, [req.body.listing_id || req.params.id]);
    if (!listing) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "listing not found" } });
    }

    // Preconditions
    if (!(auth?.actor_id === buyer?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "caller.id == buyer.id" } });
    }
    if (!(buyer?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "buyer.state == \\\"active\\\"" } });
    }
    if (!(listing?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.state == \\\"active\\\"" } });
    }
    if (!(listing?.stock >= quantity)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.stock >= quantity" } });
    }
    if (!(quantity >= 1)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "quantity >= 1" } });
    }
    if (!(buyer?.balance >= listing?.price * quantity)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "buyer.balance >= listing.price * quantity" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE listings SET stock = stock - $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [quantity, req.body.listing_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: listing.stock -= quantity");
    }
    const __effect_1 = await query(`UPDATE buyers SET balance = balance - $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [listing?.price * quantity, req.body.buyer_id || req.params.id]);
    if (!__effect_1 || __effect_1.length === 0) {
      throw new Error("Effect failed: buyer.balance -= (listing.price * quantity)");
    }

    // Emit events
    await eventBus.publish("OrderPlaced", { buyer_id: buyer?.id, listing_id: listing?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "ListingService", auth.trace_id, __client);

    res.json({ ok: true, action: "place_order", entity: buyer });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});
