// Generated by MarrowScript compiler. DO NOT EDIT.
// Service: ReviewService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import rateLimit from "express-rate-limit";
import { auditLog } from "../audit";
import { logger } from "../logger";
import { counter } from "../metrics";
import { ReviewCreateSchema, ReviewUpdateSchema } from "../schemas";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

export const reviewsRouter = Router();

// Rate limiter from policy declaration
const __routeRateLimit = rateLimit({ windowMs: 60000, max: 200, standardHeaders: true, legacyHeaders: false });

// CREATE
reviewsRouter.post("/", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  // Validate the request body against the generated Zod schema.
  const __parsed = ReviewCreateSchema.safeParse(req.body);
  if (!__parsed.success) {
    return res.status(400).json({ error: { code: "VALIDATION_FAILED", message: "Invalid request body", issues: __parsed.error.flatten() } });
  }
  const __body = __parsed.data;
  try {
    const id = uuid();
    const { order_id, buyer_id, seller_id, rating, comment } = __body as any;
    const sql = `INSERT INTO reviews (id, order_id, buyer_id, seller_id, rating, comment) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *`;
    const rows = await query(sql, [id, order_id, buyer_id, seller_id, rating, comment]);
    counter("entity.created", { entity: "Review" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
reviewsRouter.get("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const row = await queryOne(`SELECT * FROM reviews WHERE id = $1`, [req.params.id]);
    if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.json(row);
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// LIST
reviewsRouter.get("/", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
    const offset = (page - 1) * pageSize;
    const rows = await query(`SELECT * FROM reviews ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
    const [{ count }] = await query(`SELECT COUNT(*) as count FROM reviews`);
    res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// UPDATE
const __reviewsUpdatable = new Set<string>(["order_id","buyer_id","seller_id","rating","comment"]);
reviewsRouter.put("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  // 1. Validate body shape and types via Zod (UpdateSchema is partial).
  const __parsed = ReviewUpdateSchema.safeParse(req.body);
  if (!__parsed.success) {
    return res.status(400).json({ error: { code: "VALIDATION_FAILED", message: "Invalid request body", issues: __parsed.error.flatten() } });
  }
  // 2. Reject unknown columns (defense in depth — Zod would already strip them).
  const __unknown = Object.keys(req.body || {}).filter(k => !__reviewsUpdatable.has(k));
  if (__unknown.length > 0) {
    return res.status(400).json({ error: { code: "UNKNOWN_FIELDS", message: `Unknown fields: ${__unknown.join(", ")}`, fields: __unknown } });
  }
  // 3. Use the Zod-parsed object as the update set.
  const fields: Record<string, unknown> = __parsed.data as Record<string, unknown>;
  if (Object.keys(fields).length === 0) {
    return res.status(400).json({ error: { code: "NO_FIELDS", message: "No updatable fields supplied" } });
  }
  const keys = Object.keys(fields);
  const sets = keys.map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = keys.map(k => fields[k]);
  const sql = `UPDATE reviews SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
reviewsRouter.delete("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const count = await execute(`DELETE FROM reviews WHERE id = $1`, [req.params.id]);
    if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.status(204).send();
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});
