// Generated by MarrowScript compiler. DO NOT EDIT.

export type PlayerState = "active" | "suspended" | "banned" | "deleted";

export const PLAYER_INITIAL: PlayerState = "active";

const TRANSITIONS: Record<PlayerState, Record<string, PlayerState>> = {
  "active": { "active_to_suspended": "suspended" },
  "suspended": { "suspended_to_banned": "banned" },
  "banned": { "banned_to_deleted": "deleted" },
  "deleted": {  },
};

export function transitionPlayer(
  current: PlayerState,
  trigger: string
): { ok: true; next: PlayerState } | { ok: false; error: string } {
  const next = TRANSITIONS[current]?.[trigger];
  if (!next) return { ok: false, error: `Invalid transition: ${current} --[${trigger}]--> ?` };
  return { ok: true, next };
}
