// Generated by MarrowScript compiler. DO NOT EDIT.
import { Request, Response, NextFunction } from "express";
import jwt from "jsonwebtoken";
import { v4 as uuid } from "uuid";

// JWT_SECRET must be set in production. The server will refuse to start without it
// when NODE_ENV is "production" to prevent accidental use of a weak fallback.
const JWT_SECRET = (() => {
  const secret = process.env.JWT_SECRET;
  if (!secret) {
    if (process.env.NODE_ENV === "production") {
      console.error("[FATAL] JWT_SECRET environment variable is not set. Refusing to start in production.");
      process.exit(1);
    }
    console.warn("[WARN] JWT_SECRET is not set. Using insecure default — do not use in production.");
    return "marrowscript-dev-secret-do-not-use-in-production";
  }
  if (secret.length < 32) {
    console.warn("[WARN] JWT_SECRET is shorter than 32 characters. Use a longer secret in production.");
  }
  return secret;
})();

export interface AuthContext {
  authenticated: boolean;
  actor_id: string | null;
  trace_id: string;
}

// Trace IDs are server-generated. We accept a client-supplied X-Trace-Id only
// if it parses as a UUID, so callers can correlate their own logs without
// being able to forge correlation IDs in audit / event records.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function resolveTraceId(req: Request): string {
  const supplied = req.headers["x-trace-id"];
  if (typeof supplied === "string" && UUID_RE.test(supplied)) return supplied;
  return uuid();
}

export function authMiddleware(req: Request, res: Response, next: NextFunction): void {
  const header = req.headers.authorization;
  const traceId = resolveTraceId(req);
  if (!header || !header.startsWith("Bearer ")) {
    (req as any).auth = { authenticated: false, actor_id: null, trace_id: traceId };
    next();
    return;
  }
  try {
    const token = header.slice(7);
    // Pin algorithms to HS256 and require an expiration. Without pinning,
    // jsonwebtoken would accept any algorithm including RS/HS confusion attacks.
    // maxAge is a safety net even if exp is set far in the future.
    const decoded = jwt.verify(token, JWT_SECRET, {
      algorithms: ["HS256"],
      maxAge: process.env.JWT_MAX_AGE || "1h",
    }) as { sub?: unknown };
    if (typeof decoded.sub !== "string" || decoded.sub.length === 0) {
      (req as any).auth = { authenticated: false, actor_id: null, trace_id: traceId };
      next();
      return;
    }
    (req as any).auth = {
      authenticated: true,
      actor_id: decoded.sub,
      trace_id: traceId,
    };
  } catch {
    (req as any).auth = { authenticated: false, actor_id: null, trace_id: traceId };
  }
  next();
}

export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const auth: AuthContext = (req as any).auth;
  if (!auth || !auth.authenticated) {
    res.status(401).json({ error: { code: "UNAUTHORIZED", message: "Authentication required" } });
    return;
  }
  next();
}
