// Generated by MarrowScript compiler. DO NOT EDIT.
// Implements spec/10 Â§3 (Logging Schema)

import { v4 as uuid } from "uuid";

export type LogLevel = "debug" | "info" | "warn" | "error" | "fatal";
export type LogStatus = "success" | "failure" | "timeout" | "rejected";

export interface LogEntry {
  timestamp: string;
  level: LogLevel;
  service: string;
  trace_id: string;
  span_id: string;
  event: string;
  duration_ms?: number;
  status: LogStatus;
  entity_id?: string;
  actor_id?: string | null;
  error_code?: string | null;
  metadata?: Record<string, unknown>;
  // ── Cognition Layer Phase 6 — optional structured fields ────────────────
  // These travel inside metadata for backward compat, but are also surfaced
  // at the top level so log search by model / cost / cache_hit is index-friendly.
  model?: string;
  provider?: string;
  prompt_tokens?: number;
  completion_tokens?: number;
  cost_usd?: number;
  cache_hit?: boolean;
  confidence?: number;
}

class Logger {
  private service: string;

  constructor(service: string) {
    this.service = service;
  }

  emit(entry: Omit<LogEntry, "timestamp" | "service" | "span_id">): void {
    const full: LogEntry = {
      timestamp: new Date().toISOString(),
      service: this.service,
      span_id: uuid(),
      ...entry,
    };
    // In production: send to log aggregator. In dev: console.
    const fn = entry.level === "error" || entry.level === "fatal" ? console.error : console.log;
    fn(JSON.stringify(full));
  }

  info(event: string, fields: Partial<LogEntry> = {}): void {
    this.emit({ level: "info", event, status: "success", trace_id: fields.trace_id || "", ...fields });
  }

  warn(event: string, fields: Partial<LogEntry> = {}): void {
    this.emit({ level: "warn", event, status: "rejected", trace_id: fields.trace_id || "", ...fields });
  }

  error(event: string, fields: Partial<LogEntry> = {}): void {
    this.emit({ level: "error", event, status: "failure", trace_id: fields.trace_id || "", ...fields });
  }

  debug(event: string, fields: Partial<LogEntry> = {}): void {
    if (process.env.LOG_LEVEL === "debug") {
      this.emit({ level: "debug", event, status: "success", trace_id: fields.trace_id || "", ...fields });
    }
  }
}

export function createLogger(service: string): Logger {
  return new Logger(service);
}

export const logger = createLogger("SimpleShop");
