// Generated by MarrowScript compiler. DO NOT EDIT.
// Phase 21 — cost budget runtime.
//
// Public API:
//   assertWithinBudget(scope, action, ctx)     — throws if any matching budget would exceed
//   chargeBudget(scope, action, ctx, charge)   — atomically increment the counter
//   getBudgetState(tenant_id?)                 — admin read
//
// scope:  { tenant_id, user_id }   — runtime supplies these from the auth context
// action: capability name (e.g. "forge_artifact") for per_feature matching
// charge: { calls?, tokens?, cost_usd? }       — observed usage

import { randomUUID } from "crypto";
import { query } from "../db";
import { logger } from "../logger";
import { counter } from "../metrics";

export class BudgetExceededError extends Error {
  readonly code: string;
  readonly observed: number;
  readonly cap: number;
  readonly budget_id: string;
  constructor(budgetId: string, code: string, observed: number, cap: number) {
    super(`budget '${budgetId}' exceeded: ${observed} > ${cap}`);
    this.name = "BudgetExceededError";
    this.code = code;
    this.observed = observed;
    this.cap = cap;
    this.budget_id = budgetId;
  }
}

export class BudgetThrottleError extends Error {
  readonly retry_after_ms: number;
  readonly budget_id: string;
  constructor(budgetId: string, retryAfterMs: number) {
    super(`budget '${budgetId}' throttled — retry after ${retryAfterMs}ms`);
    this.name = "BudgetThrottleError";
    this.retry_after_ms = retryAfterMs;
    this.budget_id = budgetId;
  }
}

export interface BudgetScope {
  /** Tenant id when the request is multi-tenant. */
  tenant_id?: string | null;
  /** User id from the auth context. */
  user_id?: string | null;
}

export interface BudgetCharge {
  calls?: number;
  tokens?: number;
  cost_usd?: number;
}

export interface BudgetSpec {
  id: string;
  policy: string;
  scope: "per_tenant" | "per_user" | "per_feature";
  feature: string | null;
  window_ms: number;
  cap_usd: number | null;
  cap_tokens: number | null;
  cap_calls: number | null;
  action: "error" | "throttle";
  retry_after_ms: number | null;
  error_code: string | null;
}

export const BUDGETS: BudgetSpec[] = [
  {"id":"forge_policy:per_tenant::1d:0","policy":"forge_policy","scope":"per_tenant","feature":null,"window_ms":86400000,"cap_usd":null,"cap_tokens":500000,"cap_calls":null,"action":"error","retry_after_ms":null,"error_code":"DEEPSEEK_DAILY_LIMIT"},
];

/** Choose the scope_value for a budget. */
function scopeValue(b: BudgetSpec, scope: BudgetScope, action: string): string | null {
  if (b.scope === "per_tenant") return scope.tenant_id ?? null;
  if (b.scope === "per_user") return scope.user_id ?? null;
  // per_feature: only matches when the action equals the declared feature.
  return b.feature && action === b.feature ? b.feature : null;
}

/** Round a Date down to the nearest window_ms boundary. */
function windowStart(now: Date, windowMs: number): Date {
  const t = now.getTime();
  return new Date(t - (t % windowMs));
}

/**
 * Decide whether a candidate charge would exceed any matching budget.
 * Returns { ok: true } when within all caps; { ok: false, ... } on first
 * matching breach. The runtime applies the breach's action.
 */
export interface BudgetDecision {
  ok: boolean;
  budget_id?: string;
  cap_kind?: "usd" | "tokens" | "calls";
  observed?: number;
  cap?: number;
  action?: "error" | "throttle";
  retry_after_ms?: number | null;
  error_code?: string | null;
}

/**
 * Read the current bucket value for a budget under a scope value.
 * Returns 0 when the bucket doesn't exist yet.
 */
async function readCounter(budgetId: string, scopeVal: string, ws: Date): Promise<{ calls: number; tokens: number; cost_usd_micros: number }> {
  const rows = await query<{ calls: string | number; tokens: string | number; cost_usd_micros: string | number }>(
    `SELECT calls, tokens, cost_usd_micros FROM budget_counters WHERE budget_id = $1 AND scope_value = $2 AND window_start = $3`,
    [budgetId, scopeVal, ws.toISOString()],
  );
  if (rows.length === 0) return { calls: 0, tokens: 0, cost_usd_micros: 0 };
  return {
    calls: Number(rows[0].calls),
    tokens: Number(rows[0].tokens),
    cost_usd_micros: Number(rows[0].cost_usd_micros),
  };
}

/**
 * Atomically increment the bucket for a budget under a scope value. Uses
 * `INSERT ... ON CONFLICT` so the bucket is created on first write and
 * incremented on subsequent writes — both atomic in PG.
 */
async function incrementCounter(budgetId: string, scopeVal: string, ws: Date, charge: BudgetCharge): Promise<void> {
  const calls = charge.calls ?? 0;
  const tokens = charge.tokens ?? 0;
  const micros = Math.round((charge.cost_usd ?? 0) * 1_000_000);
  await query(
    `INSERT INTO budget_counters (budget_id, scope_value, window_start, calls, tokens, cost_usd_micros, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, NOW())
     ON CONFLICT (budget_id, scope_value, window_start) DO UPDATE SET
       calls = budget_counters.calls + EXCLUDED.calls,
       tokens = budget_counters.tokens + EXCLUDED.tokens,
       cost_usd_micros = budget_counters.cost_usd_micros + EXCLUDED.cost_usd_micros,
       updated_at = NOW()`,
    [budgetId, scopeVal, ws.toISOString(), calls, tokens, micros],
  );
}

/**
 * Gate function — call before doing the work. Walks every applicable budget
 * and short-circuits on the first breach. The current charge counts toward
 * the cap (consume-then-charge would let users spend over the cap once;
 * check-then-charge gives the cleaner mental model).
 */
export async function assertWithinBudget(scope: BudgetScope, action: string, charge: BudgetCharge = {}): Promise<void> {
  const now = new Date();
  for (const b of BUDGETS) {
    const sv = scopeValue(b, scope, action);
    if (sv === null) continue; // budget doesn't apply
    const ws = windowStart(now, b.window_ms);
    const cur = await readCounter(b.id, sv, ws);
    let observed = 0;
    let cap = 0;
    let kind: "usd" | "tokens" | "calls" = "calls";
    if (b.cap_calls !== null) {
      observed = cur.calls + (charge.calls ?? 1);  // every gated call counts as 1 by default
      cap = b.cap_calls;
      kind = "calls";
    } else if (b.cap_tokens !== null) {
      observed = cur.tokens + (charge.tokens ?? 0);
      cap = b.cap_tokens;
      kind = "tokens";
    } else if (b.cap_usd !== null) {
      observed = (cur.cost_usd_micros / 1_000_000) + (charge.cost_usd ?? 0);
      cap = b.cap_usd;
      kind = "usd";
    } else {
      continue; // no cap — defensive (type checker T050 should have caught)
    }
    if (observed > cap) {
      counter("budget.exceeded", { budget: b.id, scope: b.scope, action: b.action });
      logger.warn("budget_exceeded", { event: "budget.exceeded", trace_id: "", metadata: { budget_id: b.id, scope_value: sv, observed, cap, kind } });
      // Audit row.
      try {
        await query(
          `INSERT INTO budget_events (id, budget_id, scope_value, event, observed_value, cap_value, actor_id) VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [randomUUID(), b.id, sv, b.action === "throttle" ? "throttled" : "exceeded", Math.round(observed), Math.round(cap), scope.user_id ?? ""],
        );
      } catch { /* audit failures are not fatal */ }
      if (b.action === "throttle") {
        throw new BudgetThrottleError(b.id, b.retry_after_ms ?? 60_000);
      }
      throw new BudgetExceededError(b.id, b.error_code ?? "BUDGET_EXCEEDED", observed, cap);
    }
  }
}

/**
 * Persist the actual usage after the gated work completes. Charges every
 * matching budget — same scope-matching logic as assertWithinBudget. Failures
 * are logged but not fatal: a charge that fails to write should not crash
 * the request, since the work has already been done.
 */
export async function chargeBudget(scope: BudgetScope, action: string, charge: BudgetCharge): Promise<void> {
  const now = new Date();
  for (const b of BUDGETS) {
    const sv = scopeValue(b, scope, action);
    if (sv === null) continue;
    const ws = windowStart(now, b.window_ms);
    try { await incrementCounter(b.id, sv, ws, charge); }
    catch (e) {
      logger.warn("budget_charge_failed", { event: "budget.charge_failed", trace_id: "", metadata: { budget_id: b.id, error: e instanceof Error ? e.message : String(e) } });
    }
  }
  counter("budget.charged", {});
}

/** Admin: read every counter for a tenant. Intended for the admin dashboard. */
export async function getBudgetState(tenantId: string | null): Promise<{ budget_id: string; scope_value: string; window_start: string; calls: number; tokens: number; cost_usd: number }[]> {
  const rows = await query<{ budget_id: string; scope_value: string; window_start: string; calls: string | number; tokens: string | number; cost_usd_micros: string | number }>(
    tenantId
      ? `SELECT budget_id, scope_value, window_start, calls, tokens, cost_usd_micros FROM budget_counters WHERE scope_value = $1 ORDER BY window_start DESC LIMIT 100`
      : `SELECT budget_id, scope_value, window_start, calls, tokens, cost_usd_micros FROM budget_counters ORDER BY window_start DESC LIMIT 100`,
    tenantId ? [tenantId] : [],
  );
  return rows.map(r => ({
    budget_id: r.budget_id,
    scope_value: r.scope_value,
    window_start: String(r.window_start),
    calls: Number(r.calls),
    tokens: Number(r.tokens),
    cost_usd: Number(r.cost_usd_micros) / 1_000_000,
  }));
}

/** Admin: reset a tenant's counters. Audited via budget_events. */
export async function resetBudgetForScope(scopeValue: string, actorId: string): Promise<{ removed: number }> {
  const rows = await query<{ count: string }>(
    `WITH d AS (DELETE FROM budget_counters WHERE scope_value = $1 RETURNING budget_id) SELECT COUNT(*)::text AS count FROM d`,
    [scopeValue],
  );
  const removed = rows.length > 0 ? Number(rows[0].count) : 0;
  await query(
    `INSERT INTO budget_events (id, budget_id, scope_value, event, observed_value, cap_value, actor_id) VALUES ($1, $2, $3, $4, $5, $6, $7)`,
    [randomUUID(), "*", scopeValue, "reset", removed, 0, actorId],
  );
  counter("budget.reset", {});
  return { removed };
}