// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — provider registry.
// One concrete provider instance per declared `model`. Resolved by id.

import type { IModelProvider } from "./types";
import { OpenAICompatProvider } from "./openai_compat";

export interface ModelEntry {
  /** Declared model name (e.g. "TinyClassifier"). */
  name: string;
  /** Provider-specific identifier (the `name:` field of the .marrow `model` decl). */
  modelName: string;
  provider: IModelProvider;
  contextWindow: number;
  maxOutput: number;
  temperature: number;
  topP: number | null;
  stop: string[];
  costClass: "tiny" | "small" | "medium" | "large";
  latencyClass: "fast" | "medium" | "slow";
}

// One entry per model declared in the .marrow source. Sorted by name for determinism.
export const MODELS: Record<string, ModelEntry> = {
  "Medium": {
    name: "Medium",
    modelName: "deepseek/deepseek-v4-flash:free",
    provider: new OpenAICompatProvider("https://openrouter.ai/api/v1"),
    contextWindow: 128000,
    maxOutput: 4096,
    temperature: 0,
    topP: null,
    stop: [],
    costClass: "large",
    latencyClass: "slow",
  },
  "Tiny": {
    name: "Tiny",
    modelName: "mudler/qwen3.6-35b-a3b-uncensored-heretic-apex-gguf/qwen3.6-35b-a3b-uncensored-heretic-apex-i-mini.gguf",
    provider: new OpenAICompatProvider("http://10.0.0.20:1234/v1"),
    contextWindow: 32000,
    maxOutput: 4096,
    temperature: 0,
    topP: null,
    stop: [],
    costClass: "medium",
    latencyClass: "medium",
  },
};

export function getModel(name: string): ModelEntry {
  const e = MODELS[name];
  if (!e) throw new Error(`Unknown model: ${name}`);
  return e;
}

export function listModelNames(): string[] {
  return Object.keys(MODELS).sort();
}
