// Generated by MarrowScript compiler. DO NOT EDIT.
// Endpoint allowlist for openai_compat / http providers.
//
// Default policy: only loopback (127.0.0.0/8, ::1, localhost) and RFC1918
// (10/8, 172.16/12, 192.168/16) are allowed without an explicit env override.
// Set LLM_ENDPOINT_ALLOWLIST=https://api.example.com,http://internal:8080
// to permit additional endpoints. Setting LLM_ALLOW_PUBLIC_ENDPOINTS=1
// disables the host filter entirely (production-only opt-in).

function isLoopback(host: string): boolean {
  const h = host.toLowerCase();
  if (h === "localhost" || h === "::1" || h === "::") return true;
  if (h.startsWith("127.")) return true;
  return false;
}

function isRfc1918(host: string): boolean {
  const m = host.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
  if (!m) return false;
  const a = Number(m[1]), b = Number(m[2]);
  if (a === 10) return true;
  if (a === 172 && b >= 16 && b <= 31) return true;
  if (a === 192 && b === 168) return true;
  return false;
}

export function assertEndpointAllowed(endpoint: string): void {
  if (process.env.LLM_ALLOW_PUBLIC_ENDPOINTS === "1") return;
  let url: URL;
  try { url = new URL(endpoint); } catch { throw new Error(`Invalid endpoint URL: ${endpoint}`); }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error(`Endpoint must use http(s): ${endpoint}`);
  }
  const allow = (process.env.LLM_ENDPOINT_ALLOWLIST || "").split(",").map(s => s.trim()).filter(Boolean);
  for (const a of allow) {
    if (endpoint.startsWith(a)) return;
  }
  if (isLoopback(url.hostname) || isRfc1918(url.hostname)) return;
  throw new Error(
    `Endpoint ${endpoint} is not in LLM_ENDPOINT_ALLOWLIST and is not a private host. ` +
    `Set LLM_ENDPOINT_ALLOWLIST=<comma-separated prefixes> or LLM_ALLOW_PUBLIC_ENDPOINTS=1 to permit.`
  );
}
