// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — provider interface.
//
// All provider adapters implement IModelProvider. The cognition runtime
// (src/cognition/prompts.ts) talks to this interface only — never to a
// concrete provider — so swapping local Ollama for vLLM is a config change.

export interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  /** Phase 15: when role="assistant" and the model invoked tools, */
  /** these are the tool calls. The runtime executes each one and */
  /** appends a follow-up role:"tool" message with the result. */
  tool_calls?: ChatToolCall[];
  /** Phase 15: when role="tool", which call this message answers. */
  tool_call_id?: string;
  /** Phase 15: when role="tool", the name of the tool. Some providers */
  /** require this on the result message. */
  name?: string;
}

/** Phase 15: a single tool call returned by the model. */
export interface ChatToolCall {
  /** Provider-supplied call id; the runtime echoes it back on the result. */
  id: string;
  /** Tool name. Must match a declared capability. */
  name: string;
  /** Raw JSON arguments string from the model. The runtime parses + validates. */
  arguments: string;
}

/** Phase 15: tool spec sent in the chat request. */
export interface ChatToolSpec {
  /** Capability name; the runtime uses this to dispatch via runCognition. */
  name: string;
  /** Short human-readable description shown to the model. */
  description: string;
  /** JSON Schema for the tool's input arguments. Compile-time generated */
  /** from the capability's declared parameter list. */
  parameters: { type: "object"; properties: Record<string, unknown>; required?: string[] };
}

export interface ChatRequest {
  /** Provider-specific model identifier (e.g. "qwen2.5-coder:1.5b"). */
  model: string;
  messages: ChatMessage[];
  temperature?: number;
  top_p?: number;
  max_output?: number;
  stop?: string[];
  /** When set, the runtime expects strict JSON output. Adapters may pass through to a `format: "json"` field if the provider supports it. */
  json?: boolean;
  /** Phase 15: closed list of tools the model may invoke. Adapters that */
  /** support function-calling forward this; others ignore it (the runtime */
  /** treats a no-op response as a normal content reply). */
  tools?: ChatToolSpec[];
  /** Phase 15: "auto" | "required" | "none". Default is auto. */
  tool_choice?: "auto" | "required" | "none";
}

export interface ChatUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
}

export interface ChatResponse {
  content: string;
  usage: ChatUsage;
  /** Optional confidence in [0, 1]. Providers populate this from logprobs
   * (or vendor-specific metadata) when available; null otherwise. The
   * cognition runtime uses it for `router.on_low_confidence` decisions. */
  confidence?: number | null;
  /** Phase 15: when the model invoked tools, the parsed list. The */
  /** cognition runtime executes each call and re-prompts. Empty / undefined */
  /** means "this is the final answer; trust .content". */
  tool_calls?: ChatToolCall[];
  /** Raw provider response — for tracing / debugging only, never inspected by the cognition layer. */
  raw?: unknown;
}

export interface IModelProvider {
  /** Name that appears in traces and metrics. */
  readonly name: string;
  /** One round trip. Honors AbortSignal so the per-prompt `timeout:` works. */
  chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse>;
  /** Best-effort token count. Used only for budget gauges, never as a security boundary. */
  countTokens(text: string): number;
}

/**
 * Conservative tokenizer. 4 chars/token is the rule of thumb for English
 * across Llama / Qwen / Phi / Gemma families. Off by ~20% in either
 * direction; that's fine for budget gauges, never for billing.
 */
export function approxTokens(text: string): number {
  if (!text) return 0;
  return Math.ceil(text.length / 4);
}
