// Generated by MarrowScript compiler. DO NOT EDIT.
// Saga runtime â€” implements flow declarations with backward compensation.
//
// On step failure, executes compensations for ALL completed steps in reverse order.

import { logger } from "./logger";
import { counter } from "./metrics";

export interface FlowStep {
  name: string;
  action: (ctx: any) => Promise<void>;
  compensation: ((ctx: any) => Promise<void>) | null;
}

export interface FlowResult {
  ok: boolean;
  failed_step?: string;
  compensated: string[];
  error?: string;
}

export async function executeFlow(name: string, steps: FlowStep[], ctx: any): Promise<FlowResult> {
  const completed: { step: string; compensation: ((c: any) => Promise<void>) | null }[] = [];

  for (const step of steps) {
    try {
      logger.info("flow_step_started", { event: name + "." + step.name });
      await step.action(ctx);
      completed.push({ step: step.name, compensation: step.compensation });
      counter("flow.step_completed", { flow: name, step: step.name });
    } catch (e: any) {
      logger.error("flow_step_failed", { event: name + "." + step.name, metadata: { error: e.message } });
      counter("flow.step_failed", { flow: name, step: step.name });

      // Backward compensation in reverse order
      const compensated: string[] = [];
      for (const c of [...completed].reverse()) {
        if (!c.compensation) continue;
        try {
          await c.compensation(ctx);
          compensated.push(c.step);
          logger.info("flow_compensated", { event: name + "." + c.step });
        } catch (compErr: any) {
          logger.error("flow_compensation_failed", { event: name + "." + c.step, metadata: { error: compErr.message } });
          // Continue with other compensations even if one fails
        }
      }

      return { ok: false, failed_step: step.name, compensated, error: e.message };
    }
  }

  counter("flow.completed", { flow: name });
  return { ok: true, compensated: [] };
}

// Flow: execute_trade
// ctx must contain: { req, res, auth, client? } for transactional flows
export async function execute_execute_trade(ctx: { req: any; res: any; auth: any; client?: any }): Promise<FlowResult> {
  const steps: FlowStep[] = [
    {
      name: "validate",
      action: async (ctx) => {
        // Calls capability: create_trade(offer.from, offer.to, offer.items)
        const response = await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/create-trade`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify(ctx.req.body),
        });
        if (!response.ok) throw new Error(`Step validate failed: ${await response.text()}`);
        ctx.validate_result = await response.json();
      },
      compensation: async (ctx) => {
        // Compensates: cancel_trade(offer)
        await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/cancel-trade`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify({ ...ctx.req.body, _compensating: true }),
        });
      },
    },
    {
      name: "lock_items",
      action: async (ctx) => {
        // Calls capability: reserve_items(offer.items)
        const response = await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/reserve-items`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify(ctx.req.body),
        });
        if (!response.ok) throw new Error(`Step lock_items failed: ${await response.text()}`);
        ctx.lock_items_result = await response.json();
      },
      compensation: async (ctx) => {
        // Compensates: release_items(offer.items)
        await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/release-items`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify({ ...ctx.req.body, _compensating: true }),
        });
      },
    },
    {
      name: "transfer",
      action: async (ctx) => {
        // Calls capability: accept_trade(offer, offer.to)
        const response = await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/accept-trade`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify(ctx.req.body),
        });
        if (!response.ok) throw new Error(`Step transfer failed: ${await response.text()}`);
        ctx.transfer_result = await response.json();
      },
      compensation: async (ctx) => {
        // Compensates: revert_transfer(offer)
        await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/revert-transfer`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify({ ...ctx.req.body, _compensating: true }),
        });
      },
    },
    {
      name: "notify",
      action: async (ctx) => {
        // Calls capability: emit_trade_complete(offer)
        const response = await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/emit-trade-complete`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify(ctx.req.body),
        });
        if (!response.ok) throw new Error(`Step notify failed: ${await response.text()}`);
        ctx.notify_result = await response.json();
      },
      compensation: async (ctx) => {
        // Compensates: emit_trade_reverted(offer)
        await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/emit-trade-reverted`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
          body: JSON.stringify({ ...ctx.req.body, _compensating: true }),
        });
      },
    },
  ];
  return executeFlow("execute_trade", steps, ctx);
}
