// Generated by MarrowScript compiler. DO NOT EDIT.
// Implements spec/10 Â§5 (Health Checks)

import { Router, Request, Response } from "express";
import { pool } from "./db";
import { dump as dumpMetrics } from "./metrics";

export const healthRouter = Router();

// Liveness â€” is the process running?
healthRouter.get("/live", (_req: Request, res: Response) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// Readiness â€” can the service accept requests?
healthRouter.get("/ready", async (_req: Request, res: Response) => {
  const checks: Record<string, { ok: boolean; message?: string }> = {};

  // Postgres
  try {
    await pool.query("SELECT 1");
    checks.postgres = { ok: true };
  } catch (e: any) {
    checks.postgres = { ok: false, message: e.message };
  }

  const allOk = Object.values(checks).every(c => c.ok);
  res.status(allOk ? 200 : 503).json({
    status: allOk ? "ok" : "degraded",
    checks,
    timestamp: new Date().toISOString(),
  });
});

// Startup â€” has initialization completed?
healthRouter.get("/startup", (_req: Request, res: Response) => {
  res.json({ status: "ok", uptime: process.uptime() });
});

// Prometheus-style metrics — restricted to internal callers
function isInternalMetricsRequest(req: Request): boolean {
  const expected = process.env.METRICS_TOKEN || "";
  if (expected) {
    const header = req.headers.authorization || "";
    if (header.startsWith("Bearer ") && header.slice(7) === expected) return true;
  }
  const ip = (req.ip || "").replace(/^::ffff:/, "");
  if (ip === "127.0.0.1" || ip === "::1") return true;
  if (ip.startsWith("10.") || ip.startsWith("192.168.")) return true;
  // RFC1918 172.16.0.0/12
  const m = ip.match(/^172\.(\d{1,3})\./);
  if (m && +m[1] >= 16 && +m[1] <= 31) return true;
  return false;
}
healthRouter.get("/metrics", (req: Request, res: Response) => {
  if (!isInternalMetricsRequest(req)) {
    res.status(403).json({ error: { code: "FORBIDDEN", message: "Metrics restricted to internal callers" } });
    return;
  }
  res.type("text/plain").send(dumpMetrics());
});
