// Generated by MarrowScript compiler.
// Seed script for: InventoryPlatform v1.0.0
// Run: npx ts-node src/seed.ts

import { query, pool } from "./db";
import { v4 as uuid } from "uuid";

async function main(): Promise<void> {
  console.log("Seeding InventoryPlatform...");

  // Seed Player
  console.log("  Seeding players...");
  await query(
    `INSERT INTO players (id, username, email, password_hash, score, level, state, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), "sample_username_1", "sample_email_1", "sample_password_hash_1", 1, 1, "sample_state_1", new Date().toISOString(), new Date().toISOString()]
  );
  await query(
    `INSERT INTO players (id, username, email, password_hash, score, level, state, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), "sample_username_2", "sample_email_2", "sample_password_hash_2", 2, 2, "sample_state_2", new Date().toISOString(), new Date().toISOString()]
  );
  await query(
    `INSERT INTO players (id, username, email, password_hash, score, level, state, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), "sample_username_3", "sample_email_3", "sample_password_hash_3", 3, 3, "sample_state_3", new Date().toISOString(), new Date().toISOString()]
  );

  // Seed Item
  console.log("  Seeding items...");
  await query(
    `INSERT INTO items (id, name, quantity, rarity, tradeable, owner_id, state, metadata, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT DO NOTHING`,
    [uuid(), "sample_name_1", 1, "sample_rarity_1", true, uuid(), "sample_state_1", JSON.stringify({}), new Date().toISOString(), new Date().toISOString()]
  );
  await query(
    `INSERT INTO items (id, name, quantity, rarity, tradeable, owner_id, state, metadata, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT DO NOTHING`,
    [uuid(), "sample_name_2", 2, "sample_rarity_2", false, uuid(), "sample_state_2", JSON.stringify({}), new Date().toISOString(), new Date().toISOString()]
  );
  await query(
    `INSERT INTO items (id, name, quantity, rarity, tradeable, owner_id, state, metadata, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT DO NOTHING`,
    [uuid(), "sample_name_3", 3, "sample_rarity_3", true, uuid(), "sample_state_3", JSON.stringify({}), new Date().toISOString(), new Date().toISOString()]
  );

  // Seed Player
  console.log("  Seeding players...");
  await query(
    `INSERT INTO players (id, created_at, updated_at, username, email, score, level, inventory) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), "sample_username_1", "sample_email_1", 1, 1, JSON.stringify([])]
  );
  await query(
    `INSERT INTO players (id, created_at, updated_at, username, email, score, level, inventory) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), "sample_username_2", "sample_email_2", 2, 2, JSON.stringify([])]
  );
  await query(
    `INSERT INTO players (id, created_at, updated_at, username, email, score, level, inventory) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), "sample_username_3", "sample_email_3", 3, 3, JSON.stringify([])]
  );

  // Seed Item
  console.log("  Seeding items...");
  await query(
    `INSERT INTO items (id, created_at, updated_at, name, quantity, rarity, tradeable, owner_id, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), "sample_name_1", 1, "sample_rarity_1", true, uuid(), JSON.stringify({})]
  );
  await query(
    `INSERT INTO items (id, created_at, updated_at, name, quantity, rarity, tradeable, owner_id, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), "sample_name_2", 2, "sample_rarity_2", false, uuid(), JSON.stringify({})]
  );
  await query(
    `INSERT INTO items (id, created_at, updated_at, name, quantity, rarity, tradeable, owner_id, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), "sample_name_3", 3, "sample_rarity_3", true, uuid(), JSON.stringify({})]
  );

  // Seed TradeOffer
  console.log("  Seeding trade_offers...");
  await query(
    `INSERT INTO trade_offers (id, created_at, updated_at, from_player, to_player, offered_items, requested_items, status, expires_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), uuid(), uuid(), JSON.stringify([]), JSON.stringify([]), "sample_status_1", new Date().toISOString()]
  );
  await query(
    `INSERT INTO trade_offers (id, created_at, updated_at, from_player, to_player, offered_items, requested_items, status, expires_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), uuid(), uuid(), JSON.stringify([]), JSON.stringify([]), "sample_status_2", new Date().toISOString()]
  );
  await query(
    `INSERT INTO trade_offers (id, created_at, updated_at, from_player, to_player, offered_items, requested_items, status, expires_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING`,
    [uuid(), new Date().toISOString(), new Date().toISOString(), uuid(), uuid(), JSON.stringify([]), JSON.stringify([]), "sample_status_3", new Date().toISOString()]
  );

  console.log("Seed complete.");
}

main()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(() => pool.end());
