// Generated by MarrowScript compiler. DO NOT EDIT.
// Regression tests derived from capability declarations.
// Run: npx ts-node src/tests.ts

import * as http from "http";

const BASE_URL = process.env.TEST_BASE_URL || "http://localhost:3000";
const AUTH_TOKEN = process.env.TEST_AUTH_TOKEN || "";

let passed = 0;
let failed = 0;

async function request(method: string, path: string, body?: any): Promise<{ status: number; data: any }> {
  const url = new URL(path, BASE_URL);
  const res = await fetch(url.toString(), {
    method,
    headers: {
      "Content-Type": "application/json",
      ...(AUTH_TOKEN ? { "Authorization": `Bearer ${AUTH_TOKEN}` } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  return { status: res.status, data };
}

async function test(name: string, fn: () => Promise<void>): Promise<void> {
  try {
    await fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (e: any) {
    console.log(`  ✗ ${name}: ${e.message}`);
    failed++;
  }
}

function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(message);
}

(async () => {
// ─── PlayerService Tests ─────────────────────────────────────────────────────

console.log("\nPlayerService — CRUD");

let __player_id: string;

await test("POST /players — creates entity", async () => {
  const { status, data } = await request("POST", "/players", {"username":"test_value","email":"test_value","score":1,"level":1,"inventory":[]});
  assert(status === 201, `Expected 201, got ${status}: ${JSON.stringify(data)}`);
  assert(data.id, "Response must have id");
  __player_id = data.id;
});

await test("GET /players/:id — reads entity", async () => {
  const { status, data } = await request("GET", `/players/${__player_id}`);
  assert(status === 200, `Expected 200, got ${status}`);
  assert(data.id === __player_id, "ID must match");
});

await test("GET /players — lists entities", async () => {
  const { status, data } = await request("GET", "/players");
  assert(status === 200, `Expected 200, got ${status}`);
  assert(Array.isArray(data.items), "Response must have items array");
  assert(typeof data.total === "number", "Response must have total");
});

await test("GET /players — rejects unauthenticated", async () => {
  const res = await fetch(`${BASE_URL}/players`);
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

await test("POST /players/create-trade — capability executes", async () => {
  const { status, data } = await request("POST", "/players/create-trade", {
    player_id: __player_id,
  });
  // Capability may return 200 (success) or 422 (precondition failed) — both are valid
  assert([200, 422].includes(status), `Expected 200 or 422, got ${status}: ${JSON.stringify(data)}`);
});

await test("POST /players/create-trade — returns 401 without auth", async () => {
  const res = await fetch(`${BASE_URL}/players/create-trade`, { method: "POST" });
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

await test("POST /players/accept-trade — capability executes", async () => {
  const { status, data } = await request("POST", "/players/accept-trade", {
    player_id: __player_id,
  });
  // Capability may return 200 (success) or 422 (precondition failed) — both are valid
  assert([200, 422].includes(status), `Expected 200 or 422, got ${status}: ${JSON.stringify(data)}`);
});

await test("POST /players/accept-trade — returns 401 without auth", async () => {
  const res = await fetch(`${BASE_URL}/players/accept-trade`, { method: "POST" });
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

await test("POST /players/award-xp — capability executes", async () => {
  const { status, data } = await request("POST", "/players/award-xp", {
    player_id: __player_id,
  });
  // Capability may return 200 (success) or 422 (precondition failed) — both are valid
  assert([200, 422].includes(status), `Expected 200 or 422, got ${status}: ${JSON.stringify(data)}`);
});

await test("POST /players/award-xp — returns 401 without auth", async () => {
  const res = await fetch(`${BASE_URL}/players/award-xp`, { method: "POST" });
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

await test("POST /players/consume-item — capability executes", async () => {
  const { status, data } = await request("POST", "/players/consume-item", {
    player_id: __player_id,
  });
  // Capability may return 200 (success) or 422 (precondition failed) — both are valid
  assert([200, 422].includes(status), `Expected 200 or 422, got ${status}: ${JSON.stringify(data)}`);
});

await test("POST /players/consume-item — returns 401 without auth", async () => {
  const res = await fetch(`${BASE_URL}/players/consume-item`, { method: "POST" });
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

// State machine: Player
await test("PUT /players/:id — rejects invalid state transition", async () => {
  const { status, data } = await request("PUT", `/players/${__player_id}`, {
    state: "__invalid_state__",
  });
  assert(status === 422, `Expected 422 for invalid transition, got ${status}`);
  assert(data.error?.code === "INVALID_TRANSITION", "Error code must be INVALID_TRANSITION");
});

await test("DELETE /players/:id — deletes entity", async () => {
  const { status } = await request("DELETE", `/players/${__player_id}`);
  assert(status === 204, `Expected 204, got ${status}`);
});

await test("GET /players/:id — returns 404 after delete", async () => {
  const { status } = await request("GET", `/players/${__player_id}`);
  assert(status === 404, `Expected 404, got ${status}`);
});

// ─── ItemService Tests ─────────────────────────────────────────────────────

console.log("\nItemService — CRUD");

let __item_id: string;

await test("POST /items — creates entity", async () => {
  const { status, data } = await request("POST", "/items", {"name":"test_value","quantity":1,"rarity":"test_value","tradeable":true,"owner_id":"00000000-0000-0000-0000-000000000001","metadata":{}});
  assert(status === 201, `Expected 201, got ${status}: ${JSON.stringify(data)}`);
  assert(data.id, "Response must have id");
  __item_id = data.id;
});

await test("GET /items/:id — reads entity", async () => {
  const { status, data } = await request("GET", `/items/${__item_id}`);
  assert(status === 200, `Expected 200, got ${status}`);
  assert(data.id === __item_id, "ID must match");
});

await test("GET /items — lists entities", async () => {
  const { status, data } = await request("GET", "/items");
  assert(status === 200, `Expected 200, got ${status}`);
  assert(Array.isArray(data.items), "Response must have items array");
  assert(typeof data.total === "number", "Response must have total");
});

await test("GET /items — rejects unauthenticated", async () => {
  const res = await fetch(`${BASE_URL}/items`);
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

await test("POST /items/consume-item — capability executes", async () => {
  const { status, data } = await request("POST", "/items/consume-item", {
    item_id: __item_id,
  });
  // Capability may return 200 (success) or 422 (precondition failed) — both are valid
  assert([200, 422].includes(status), `Expected 200 or 422, got ${status}: ${JSON.stringify(data)}`);
});

await test("POST /items/consume-item — returns 401 without auth", async () => {
  const res = await fetch(`${BASE_URL}/items/consume-item`, { method: "POST" });
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

// State machine: Item
await test("PUT /items/:id — rejects invalid state transition", async () => {
  const { status, data } = await request("PUT", `/items/${__item_id}`, {
    state: "__invalid_state__",
  });
  assert(status === 422, `Expected 422 for invalid transition, got ${status}`);
  assert(data.error?.code === "INVALID_TRANSITION", "Error code must be INVALID_TRANSITION");
});

await test("DELETE /items/:id — deletes entity", async () => {
  const { status } = await request("DELETE", `/items/${__item_id}`);
  assert(status === 204, `Expected 204, got ${status}`);
});

await test("GET /items/:id — returns 404 after delete", async () => {
  const { status } = await request("GET", `/items/${__item_id}`);
  assert(status === 404, `Expected 404, got ${status}`);
});

// ─── TradeOfferService Tests ─────────────────────────────────────────────────────

console.log("\nTradeOfferService — CRUD");

let __trade_offer_id: string;

await test("POST /trade_offers — creates entity", async () => {
  const { status, data } = await request("POST", "/trade_offers", {"from_player":"00000000-0000-0000-0000-000000000001","to_player":"00000000-0000-0000-0000-000000000001","offered_items":[],"requested_items":[],"status":"test_value","expires_at":"2024-01-01T00:00:00.000Z"});
  assert(status === 201, `Expected 201, got ${status}: ${JSON.stringify(data)}`);
  assert(data.id, "Response must have id");
  __trade_offer_id = data.id;
});

await test("GET /trade_offers/:id — reads entity", async () => {
  const { status, data } = await request("GET", `/trade_offers/${__trade_offer_id}`);
  assert(status === 200, `Expected 200, got ${status}`);
  assert(data.id === __trade_offer_id, "ID must match");
});

await test("GET /trade_offers — lists entities", async () => {
  const { status, data } = await request("GET", "/trade_offers");
  assert(status === 200, `Expected 200, got ${status}`);
  assert(Array.isArray(data.items), "Response must have items array");
  assert(typeof data.total === "number", "Response must have total");
});

await test("GET /trade_offers — rejects unauthenticated", async () => {
  const res = await fetch(`${BASE_URL}/trade_offers`);
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

await test("POST /trade_offers/accept-trade — capability executes", async () => {
  const { status, data } = await request("POST", "/trade_offers/accept-trade", {
    trade_offer_id: __trade_offer_id,
  });
  // Capability may return 200 (success) or 422 (precondition failed) — both are valid
  assert([200, 422].includes(status), `Expected 200 or 422, got ${status}: ${JSON.stringify(data)}`);
});

await test("POST /trade_offers/accept-trade — returns 401 without auth", async () => {
  const res = await fetch(`${BASE_URL}/trade_offers/accept-trade`, { method: "POST" });
  assert(res.status === 401, `Expected 401, got ${res.status}`);
});

// State machine: TradeOffer
await test("PUT /trade_offers/:id — rejects invalid state transition", async () => {
  const { status, data } = await request("PUT", `/trade_offers/${__trade_offer_id}`, {
    state: "__invalid_state__",
  });
  assert(status === 422, `Expected 422 for invalid transition, got ${status}`);
  assert(data.error?.code === "INVALID_TRANSITION", "Error code must be INVALID_TRANSITION");
});

await test("DELETE /trade_offers/:id — deletes entity", async () => {
  const { status } = await request("DELETE", `/trade_offers/${__trade_offer_id}`);
  assert(status === 204, `Expected 204, got ${status}`);
});

await test("GET /trade_offers/:id — returns 404 after delete", async () => {
  const { status } = await request("GET", `/trade_offers/${__trade_offer_id}`);
  assert(status === 404, `Expected 404, got ${status}`);
});

console.log(`\n════════════════════════════════════════`);
console.log(`Results: ${passed} passed, ${failed} failed`);
console.log("═".repeat(40));
if (failed > 0) process.exit(1);
})().catch(e => { console.error(e); process.exit(1); });