/**
 * MarrowScript Cognition Emitter (LLM Harness, Phase 2)
 *
 * Compiles `model`, `prompt`, `router`, and `cognition:`-modified capabilities
 * from the IR into deterministic runtime modules under src/cognition/.
 *
 * Generated tree:
 *   src/cognition/router.ts        — deterministic decision tree per declared router
 *   src/cognition/prompts.ts       — typed callers, one async fn per prompt
 *   src/cognition/primitives.ts    — closed catalog of cognition primitives
 *   src/cognition/index.ts         — public entry point: registry + ctx builder
 *
 * Design notes:
 *   - Every prompt body is read from the existing extension_point mechanism
 *     (src/extensions.ts). Users author the prompt text once and it survives
 *     recompilation via the sentinel-bracketed regions.
 *   - Validation reuses the Zod schemas already generated by emit_zod.ts.
 *   - Retry / timeout / on_invalid actions are compiled in-line; the runtime
 *     never surprises the model with unbounded recursion.
 *   - Audit hooks call into src/logger and src/metrics — both already in the
 *     output tree thanks to emit_maintenance.ts.
 *
 * Determinism: deterministic ordering across IRPrompt[], IRRouter[],
 * IRCogModel[]. No Date.now() / Math.random() in emitted code.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";
import { CATALOG, lookupCognition } from "./cognition_catalog";
import { anyPromptUsesCache } from "./emit_cache";
import { memoryNeeded } from "./emit_memory";
import { emitOutputParser } from "./emit_output_parser";

// ─── Public entry ────────────────────────────────────────────────────────────

export function emitCognitionFiles(system: IR.IRSystem): EmittedFile[] {
  const hasModels = system.models.length > 0;
  const hasPrompts = system.prompts.length > 0;
  const hasRouters = system.routers.length > 0;
  const usedCognition = collectUsedCognitionInternal(system);

  // Emit nothing if the system has no cognition surface. This keeps existing
  // non-cognition projects unchanged.
  if (!hasModels && !hasPrompts && !hasRouters && usedCognition.size === 0) return [];

  const files: EmittedFile[] = [];

  if (hasRouters) {
    files.push({
      path: "src/cognition/router.ts",
      content: emitRouterFile(system),
      language: "typescript",
      source_module: "cognition",
    });
  }

  if (hasPrompts) {
    files.push({
      path: "src/cognition/prompts.ts",
      content: emitPromptsFile(system),
      language: "typescript",
      source_module: "cognition",
    });
  }

  if (usedCognition.size > 0) {
    files.push({
      path: "src/cognition/primitives.ts",
      content: emitPrimitivesFile(usedCognition),
      language: "typescript",
      source_module: "cognition",
    });
  }

  // Always emit the index when any cognition surface exists — gives the
  // application a single import point regardless of which subset is in use.
  files.push({
    path: "src/cognition/index.ts",
    content: emitIndexFile(system, usedCognition, hasRouters, hasPrompts),
    language: "typescript",
    source_module: "cognition",
  });

  // Structured output parser (Phase 23) — robust JSON extraction + Zod validation.
  const outputParser = emitOutputParser(system);
  if (outputParser) files.push(outputParser);

  return files;
}

function collectUsedCognitionInternal(system: IR.IRSystem): Set<string> {
  const used = new Set<string>();
  for (const mod of system.modules) {
    for (const iface of mod.interfaces) {
      for (const method of iface.methods) {
        if (method.cognition) used.add(method.cognition.catalog_name);
      }
    }
  }
  // Phase 15: tool capabilities pull their primitive into the registry too.
  // Cognition-only capabilities (no entity-typed param) don't show up in
  // modules at all, so without this their primitive would be missing from
  // src/cognition/primitives.ts and runCognition() would fail at runtime.
  for (const t of system.tool_capabilities) {
    used.add(t.cognition_primitive);
  }
  return used;
}

// ─── Phase 15: tool-call infrastructure ──────────────────────────────────────
//
// A tool is a cognition-bearing capability listed in some prompt's `tools:`.
// At runtime, when the model returns tool_calls in its response, the cognition
// emitter dispatches each call through runCognition using the capability's
// `cognition: <primitive> using { ... }` bindings. The translation is:
//
//   capability search_docs(query: string, max: uint) {
//     cognition: vector_retrieve using { task: query, k: max }
//   }
//
//   model emits: { name: "search_docs", arguments: '{"query":"x","max":5}' }
//   runtime dispatches: runCognition("vector_retrieve", { task: "x", k: 5 })
//
// The model never sees the catalog primitive — it picks tools by capability
// name, which is type-checked at compile time (T023 + T029).

interface ToolCapability {
  name: string;
  params: IR.IRField[];
  cogPrimitive: string;
  bindings: { param: string; value: string }[];
  returnType: string;
}

/**
 * For every cognition-bearing capability referenced by any prompt's
 * allowed_tools, return a typed descriptor. Lowering populates
 * `system.tool_capabilities` directly from the AST so cognition-only
 * capabilities (which don't appear in the lowered module tree) are
 * available here.
 */
function collectToolCapabilities(system: IR.IRSystem): Map<string, ToolCapability> {
  const out = new Map<string, ToolCapability>();
  for (const t of system.tool_capabilities) {
    out.set(t.name, {
      name: t.name,
      params: t.params,
      cogPrimitive: t.cognition_primitive,
      bindings: t.bindings,
      returnType: t.return_type,
    });
  }
  return out;
}

/**
 * Convert a MarrowScript IR type expression to a JSON Schema fragment.
 * Coverage matches what the cognition runtime can reasonably accept from
 * the model: primitives, list<T>, optional<T>, and entity refs (treated as
 * opaque object). Unknown shapes degrade to {} — accept anything — so the
 * model can pass entity ids as plain strings without the validator
 * rejecting valid input.
 */
function irTypeToJsonSchema(typeStr: string): Record<string, unknown> {
  const t = typeStr.trim();
  switch (t) {
    case "string": return { type: "string" };
    case "uuid":   return { type: "string", format: "uuid" };
    case "int":    return { type: "integer" };
    case "uint":   return { type: "integer", minimum: 0 };
    case "float":  return { type: "number" };
    case "bool":   return { type: "boolean" };
    case "json":   return {}; // accept anything
    case "timestamp": return { type: "string", format: "date-time" };
    case "bytes":  return { type: "string", contentEncoding: "base64" };
  }
  const listMatch = t.match(/^list<(.+)>$/);
  if (listMatch) return { type: "array", items: irTypeToJsonSchema(listMatch[1]) };
  const setMatch = t.match(/^set<(.+)>$/);
  if (setMatch) return { type: "array", items: irTypeToJsonSchema(setMatch[1]), uniqueItems: true };
  const optMatch = t.match(/^optional<(.+)>$/);
  if (optMatch) return irTypeToJsonSchema(optMatch[1]);
  // Entity ref or unknown — accept any object so the model can pass an id
  // or a structured payload either way.
  return {};
}

/**
 * Build the JSON-Schema parameters object for one tool capability. Required
 * fields are all parameters whose IR type isn't optional<T>.
 */
function buildToolParameters(cap: ToolCapability): {
  type: "object";
  properties: Record<string, unknown>;
  required: string[];
} {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  for (const p of cap.params) {
    properties[p.name] = irTypeToJsonSchema(p.type);
    if (!p.type.startsWith("optional<") && !p.nullable) required.push(p.name);
  }
  return { type: "object", properties, required };
}

/**
 * Generate IR system extension_point names that prompt bodies reference
 * via `template: "extension_point:NAME"`. Used by emit_full to ensure the
 * referenced extension_point has been declared (the type checker already
 * enforces this at compile time, but we sanity-check before stub generation).
 */
export function collectPromptTemplateExtensionPoints(system: IR.IRSystem): Set<string> {
  const result = new Set<string>();
  for (const p of system.prompts) {
    if (p.template.startsWith("extension_point:")) {
      result.add(p.template.slice("extension_point:".length));
    }
    if (p.validate.kind === "custom") {
      result.add(p.validate.extension_point);
    }
  }
  return result;
}

// ─── src/cognition/router.ts ────────────────────────────────────────────────

function emitRouterFile(system: IR.IRSystem): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 2 — deterministic routing decision trees.");
  lines.push("//");
  lines.push("// Each router is a closed list of tiers, evaluated in declaration order");
  lines.push("// against the routing key. The last tier is the default. There is no");
  lines.push("// dynamic dispatch — the same input always selects the same tier.");
  lines.push("");
  lines.push("import { getModel, type ModelEntry } from \"../providers\";");
  lines.push("");
  lines.push("export interface RouteChoice {");
  lines.push("  /** Declared model name. */");
  lines.push("  model_id: string;");
  lines.push("  /** The tier whose threshold matched. */");
  lines.push("  tier: string;");
  lines.push("  /** Resolved model entry — convenience for prompt callers. */");
  lines.push("  model: ModelEntry;");
  lines.push("}");
  lines.push("");
  lines.push("export interface CompiledRouter {");
  lines.push("  name: string;");
  lines.push("  /** Pick a tier given the routing input. */");
  lines.push("  route(input: unknown): RouteChoice;");
  lines.push("  /** Move up one tier. Returns null if currentTier is the top. */");
  lines.push("  escalate(currentTier: string): RouteChoice | null;");
  lines.push("  /** Optional fallback model when on_low_confidence: escalate exhausts tiers. */");
  lines.push("  fallback(): RouteChoice | null;");
  lines.push("}");
  lines.push("");
  lines.push("/** Pull a numeric value off `input` using a dotted path. Returns NaN on miss. */");
  lines.push("function pickByPath(input: unknown, path: string[]): number {");
  lines.push("  let cur: any = input;");
  lines.push("  for (const k of path) {");
  lines.push("    if (cur === null || cur === undefined) return NaN;");
  lines.push("    cur = cur[k];");
  lines.push("  }");
  lines.push("  if (typeof cur === \"number\") return cur;");
  lines.push("  if (typeof cur === \"string\") return Number(cur);");
  lines.push("  if (Array.isArray(cur)) return cur.length;");
  lines.push("  if (cur && typeof cur === \"object\") return Object.keys(cur).length;");
  lines.push("  return NaN;");
  lines.push("}");
  lines.push("");

  // Emit one CompiledRouter per declared router. Sort by name for determinism.
  const sortedRouters = [...system.routers].sort((a, b) => a.name.localeCompare(b.name));
  for (const r of sortedRouters) {
    emitRouterImpl(r, lines);
  }

  // Registry — sorted, fixed-shape Record literal.
  lines.push("export const ROUTERS: Record<string, CompiledRouter> = {");
  for (const r of sortedRouters) {
    lines.push(`  ${JSON.stringify(r.name)}: ROUTER_${routerIdent(r.name)},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("export function getRouter(name: string): CompiledRouter {");
  lines.push("  const r = ROUTERS[name];");
  lines.push("  if (!r) throw new Error(`Unknown router: ${name}`);");
  lines.push("  return r;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function emitRouterImpl(r: IR.IRRouter, lines: string[]): void {
  // Translate the serialized by_expr into a path-pick at runtime. We support
  // the common case of `input.<field>.<...>`; anything else falls back to
  // pickByPath on the whole expression as a single-element path.
  const path = parseByExpr(r.by_expr);
  const pathExpr = JSON.stringify(path);

  lines.push(`// Router: ${r.name}`);
  lines.push(`// by: ${r.by_expr}`);
  lines.push(`const ROUTER_${routerIdent(r.name)}: CompiledRouter = {`);
  lines.push(`  name: ${JSON.stringify(r.name)},`);
  lines.push(`  route(input: unknown): RouteChoice {`);
  lines.push(`    const value = pickByPath(input, ${pathExpr});`);
  for (let i = 0; i < r.tiers.length; i++) {
    const t = r.tiers[i];
    if (t.max === null) {
      // Default tier — last in the chain by checker invariant.
      lines.push(`    {`);
      lines.push(`      const m = getModel(${JSON.stringify(t.model_ref)});`);
      lines.push(`      return { model_id: ${JSON.stringify(t.model_ref)}, tier: ${JSON.stringify(t.name)}, model: m };`);
      lines.push(`    }`);
    } else {
      lines.push(`    if (!Number.isNaN(value) && value <= ${t.max}) {`);
      lines.push(`      const m = getModel(${JSON.stringify(t.model_ref)});`);
      lines.push(`      return { model_id: ${JSON.stringify(t.model_ref)}, tier: ${JSON.stringify(t.name)}, model: m };`);
      lines.push(`    }`);
    }
  }
  lines.push(`  },`);
  // escalate(currentTier): walk to the tier *after* currentTier.
  lines.push(`  escalate(currentTier: string): RouteChoice | null {`);
  lines.push(`    const order: { name: string; modelRef: string }[] = [`);
  for (const t of r.tiers) {
    lines.push(`      { name: ${JSON.stringify(t.name)}, modelRef: ${JSON.stringify(t.model_ref)} },`);
  }
  lines.push(`    ];`);
  lines.push(`    const idx = order.findIndex(t => t.name === currentTier);`);
  lines.push(`    if (idx < 0 || idx >= order.length - 1) return null;`);
  lines.push(`    const next = order[idx + 1];`);
  lines.push(`    return { model_id: next.modelRef, tier: next.name, model: getModel(next.modelRef) };`);
  lines.push(`  },`);
  lines.push(`  fallback(): RouteChoice | null {`);
  if (r.fallback_model_ref) {
    lines.push(`    return { model_id: ${JSON.stringify(r.fallback_model_ref)}, tier: "fallback", model: getModel(${JSON.stringify(r.fallback_model_ref)}) };`);
  } else {
    lines.push(`    return null;`);
  }
  lines.push(`  },`);
  lines.push(`};`);
  lines.push(``);
}

function parseByExpr(expr: string): string[] {
  // serializeExpr in lowering wraps things like `input.complexity` as
  // "input.complexity"; for nested binops or calls, this emits a single
  // synthetic path. This is sufficient for the documented router pattern;
  // more elaborate routing keys can be wrapped in an extension_point.
  //
  // The router's `route(input)` parameter IS the input object, so a leading
  // `input.` segment must be dropped from the path. Without this strip the
  // generated path becomes ["input","field"] and pickByPath always misses.
  const trimmed = expr.replace(/^\(+|\)+$/g, "").trim();
  if (/^[a-zA-Z_][a-zA-Z0-9_.]*$/.test(trimmed)) {
    const parts = trimmed.split(".");
    if (parts[0] === "input" && parts.length > 1) return parts.slice(1);
    return parts;
  }
  return [trimmed];
}

function routerIdent(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

// ─── src/cognition/prompts.ts ────────────────────────────────────────────────

function emitPromptsFile(system: IR.IRSystem): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 2 — typed prompt callers.");
  lines.push("//");
  lines.push("// One async function per declared `prompt`. Each function:");
  lines.push("//   1. validates input via the prompt's Zod schema (reusing src/schemas.ts)");
  lines.push("//   2. resolves the model from a static model_ref OR a router");
  lines.push("//   3. loads the template body from src/extensions.ts (extension_point)");
  lines.push("//   4. dispatches the call through the provider adapter");
  lines.push("//   5. validates the response per prompt.validate (none / schema_only /");
  lines.push("//      ast_compiles / custom)");
  lines.push("//   6. handles on_invalid: fail / retry / retry_with_repair_prompt /");
  lines.push("//      escalate within the prompt's retry budget");
  lines.push("//   7. emits a span via the cognition_traces logger");
  lines.push("//   8. returns the typed result");
  lines.push("");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter, histogram } from \"../metrics\";");
  lines.push("import { getModel, type ModelEntry } from \"../providers\";");
  lines.push("import { newBudget, budgetEnforced, type BudgetTracker, BudgetExceededError } from \"./budget\";");
  // Phase 5: validation runtime — always present when prompts exist.
  lines.push("import { validateSchemaOnly, validateAstCompiles, validateCustom, type ValidationReport } from \"./validate\";");
  // Phase 6: cognition span writer — always present when prompts exist.
  lines.push("import { writeSpan } from \"./traces\";");
  // Phase 5: repair functions — only when at least one prompt uses retry_with_repair_prompt.
  const repairActive = system.prompts.some(p => p.on_invalid === "retry_with_repair_prompt");
  if (repairActive) {
    lines.push("import { REPAIRS } from \"./repair\";");
  }
  // The cache import is conditional — only when at least one prompt uses cache:
  // (otherwise the file isn't emitted and the import would dangle).
  const cacheActive = anyPromptUsesCache(system);
  if (cacheActive) {
    lines.push("import { cache, deriveKey } from \"./cache\";");
  }
  lines.push("import { createHash } from \"crypto\";");

  if (system.routers.length > 0) {
    lines.push("import { getRouter, type CompiledRouter, type RouteChoice } from \"./router\";");
  }
  lines.push("");
  lines.push("// Extension-point templates — bodies live in src/extensions.ts and are");
  lines.push("// preserved across recompilation. We refer to them by name to keep the");
  lines.push("// compiled file decoupled from prompt wording.");
  // Emit a typed contract for each extension_point template. Each is just a
  // lazy require so the absence of src/extensions.ts (legitimate when the
  // user has no other extension_points) isn't fatal at startup.
  const referencedExtensions = collectPromptTemplateExtensionPoints(system);
  if (referencedExtensions.size > 0) {
    lines.push("function loadExtension(name: string): (...args: unknown[]) => unknown {");
    lines.push("  // Late-bind so module load order doesn't matter.");
    lines.push("  // eslint-disable-next-line @typescript-eslint/no-require-imports");
    lines.push("  const ext = require(\"../extensions\") as Record<string, (...args: unknown[]) => unknown>;");
    lines.push("  const fn = ext[name];");
    lines.push("  if (typeof fn !== \"function\") {");
    lines.push("    throw new Error(`Extension point not implemented: ${name}. ` +");
    lines.push("      `Open src/extensions.ts and fill in the body between the sentinel comments.`);");
    lines.push("  }");
    lines.push("  return fn;");
    lines.push("}");
    lines.push("");
  }

  lines.push("export interface PromptCtx {");
  lines.push("  trace_id: string;");
  lines.push("  /** Optional abort signal — wired to the prompt's `timeout:`. */");
  lines.push("  signal?: AbortSignal;");
  lines.push("  /** Optional budget tracker. When omitted, the prompt creates a fresh one,");
  lines.push("   *  which means budgets only span this single prompt call.");
  lines.push("   *  Pass a shared tracker for trace-level enforcement. */");
  lines.push("  budget?: BudgetTracker;");
  lines.push("}");
  lines.push("");

  // Validation helper. Reuses the existing src/schemas.ts when possible.
  // We emit a small leniency: if the model returns JSON for an enum/string
  // shape, accept both.
  //
  // Six expected modes:
  //   - "string"  the model returned plain text or a fenced code block
  //   - "json"    the model returned a JSON value (parsed via JSON.parse)
  //   - "unknown" try JSON, fall back to raw string
  //   - "file"    the model returned a single { path, content, kind? } record
  //   - "files"   the model returned an array of File records (Phase 14)
  //   - "fenced_string" same as "string" but kept distinct for tracing
  lines.push("function parseModelOutput(raw: string, expected: \"string\" | \"json\" | \"unknown\" | \"file\" | \"files\"): unknown {");
  lines.push("  if (expected === \"string\") {");
  lines.push("    // For string outputs (typically code or markdown), strip surrounding");
  lines.push("    // markdown fences if present so the consumer gets just the inner");
  lines.push("    // content. Most models wrap their output in ```typescript ... ``` or");
  lines.push("    // ```ts or just ``` — we handle all three. If multiple fences are");
  lines.push("    // present, we pick the largest typescript-tagged one (or the largest");
  lines.push("    // untagged fallback). If no fence at all, return raw unchanged.");
  lines.push("    return extractLargestFencedBlock(raw);");
  lines.push("  }");
  lines.push("  if (expected === \"unknown\") {");
  lines.push("    try { return JSON.parse(raw); } catch { return raw; }");
  lines.push("  }");
  lines.push("  if (expected === \"file\" || expected === \"files\") {");
  lines.push("    // Multi-file output. The model should return JSON: a single");
  lines.push("    // { path, content, kind? } record for `file`, or an array for");
  lines.push("    // `files`. We strip a code fence first since models often wrap");
  lines.push("    // structured output in ```json ... ```. If parsing fails entirely,");
  lines.push("    // fall back to a single-file synthesis where the whole raw output");
  lines.push("    // is the content and `path` is empty — the validator will reject");
  lines.push("    // this and trigger repair, so we surface the issue without crashing.");
  lines.push("    const cleaned = raw.replace(/^```[a-zA-Z]*\\n?/, \"\").replace(/```\\s*$/, \"\").trim();");
  lines.push("    let parsed: unknown;");
  lines.push("    try { parsed = JSON.parse(cleaned); }");
  lines.push("    catch { return expected === \"files\" ? [{ path: \"\", content: raw }] : { path: \"\", content: raw }; }");
  lines.push("    if (expected === \"files\") {");
  lines.push("      // Accept a bare array, OR an object with a top-level `files` field");
  lines.push("      // (a common model framing — \"here are the files: { files: [...] }\").");
  lines.push("      if (Array.isArray(parsed)) return parsed;");
  lines.push("      if (parsed && typeof parsed === \"object\" && Array.isArray((parsed as { files?: unknown }).files)) {");
  lines.push("        return (parsed as { files: unknown[] }).files;");
  lines.push("      }");
  lines.push("      // Last resort: single-record-into-list promotion.");
  lines.push("      if (parsed && typeof parsed === \"object\" && \"path\" in (parsed as object)) return [parsed];");
  lines.push("      return [{ path: \"\", content: String(parsed) }];");
  lines.push("    }");
  lines.push("    // expected === \"file\"");
  lines.push("    if (Array.isArray(parsed) && parsed.length > 0) return parsed[0];");
  lines.push("    return parsed;");
  lines.push("  }");
  lines.push("  // expected === json");
  lines.push("  // Strip a markdown code fence if the model wrapped its JSON in ```json ... ```.");
  lines.push("  const cleaned = raw.replace(/^```[a-zA-Z]*\\n?/, \"\").replace(/```\\s*$/, \"\").trim();");
  lines.push("  return JSON.parse(cleaned);");
  lines.push("}");
  lines.push("");
  // Helper: extract the largest fenced block from a model response so the
  // user sees only the artifact, not the model's preamble. Falls back to the
  // raw input if no fenced block is found.
  lines.push("function extractLargestFencedBlock(raw: string): string {");
  lines.push("  const fenceRe = /```([a-zA-Z]*)\\s*\\n([\\s\\S]*?)\\n```/g;");
  lines.push("  const tsFences: string[] = [];");
  lines.push("  const untaggedFences: string[] = [];");
  lines.push("  let m: RegExpExecArray | null;");
  lines.push("  while ((m = fenceRe.exec(raw)) !== null) {");
  lines.push("    const lang = (m[1] || \"\").toLowerCase();");
  lines.push("    const body = m[2];");
  lines.push("    if (lang === \"typescript\" || lang === \"ts\" || lang === \"tsx\" || lang === \"javascript\" || lang === \"js\") {");
  lines.push("      tsFences.push(body);");
  lines.push("    } else if (lang === \"\") {");
  lines.push("      untaggedFences.push(body);");
  lines.push("    } else {");
  lines.push("      // Other languages (markdown, python, etc.) — keep them in untagged");
  lines.push("      // pool as a fallback so the validator at least sees something.");
  lines.push("      untaggedFences.push(body);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  const pool = tsFences.length > 0 ? tsFences : untaggedFences;");
  lines.push("  if (pool.length === 0) return raw;");
  lines.push("  let best = pool[0];");
  lines.push("  for (let i = 1; i < pool.length; i++) {");
  lines.push("    if (pool[i].length > best.length) best = pool[i];");
  lines.push("  }");
  lines.push("  return best;");
  lines.push("}");
  lines.push("");

  // ── Phase 15: tool dispatch infrastructure ────────────────────────────────
  // Emit __TOOL_SPECS (the JSON-Schema-typed list shown to the model) and
  // __TOOL_DISPATCH (the per-tool runtime invoker) only when at least one
  // prompt declares allowed_tools. The dispatcher routes every tool call
  // through runCognition with the capability's `using { ... }` bindings —
  // the model never sees catalog primitive names.
  const toolCaps = collectToolCapabilities(system);
  const anyPromptHasTools = system.prompts.some(p => p.allowed_tools.length > 0);
  if (anyPromptHasTools && toolCaps.size > 0) {
    // We need runCognition to dispatch tool calls. Late-bind via require()
    // so tools.ts (this file) doesn't take a hard import-cycle dependency
    // on cognition/index.ts which imports prompts.ts back.
    lines.push("// Phase 15: tool-call dispatch. The model invokes tools by capability");
    lines.push("// name; the runtime translates each call into a runCognition() invocation");
    lines.push("// using the capability's `cognition: ... using { ... }` bindings.");
    lines.push("//");
    lines.push("// Determinism note: __TOOL_SPECS is emitted in alphabetical order so");
    lines.push("// the same set of tools always presents the model with the same JSON");
    lines.push("// schema in the same field order. Tool calls themselves are bounded");
    lines.push("// by LLM_TOOL_CALL_MAX (default 5).");
    lines.push("import type { ChatMessage, ChatToolCall, ChatToolSpec, ChatRequest, ChatResponse, IModelProvider } from \"../providers/types\";");
    lines.push("");
    lines.push("function loadRunCognition(): (name: string, args: Record<string, unknown>) => Promise<unknown> {");
    lines.push("  // Late-bind to avoid an import cycle (cognition/index → prompts → cognition).");
    lines.push("  // eslint-disable-next-line @typescript-eslint/no-require-imports");
    lines.push("  const cog = require(\"./index\") as { runCognition?: (name: string, args: Record<string, unknown>) => Promise<unknown> };");
    lines.push("  if (typeof cog.runCognition !== \"function\") {");
    lines.push("    throw new Error(\"runCognition is not available — tools require at least one cognition primitive in the system\");");
    lines.push("  }");
    lines.push("  return cog.runCognition;");
    lines.push("}");
    lines.push("");
    // __TOOL_SPECS — emit one ChatToolSpec per tool capability, sorted by name.
    lines.push("const __TOOL_SPECS: Record<string, ChatToolSpec> = {");
    const sortedTools = [...toolCaps.values()].sort((a, b) => a.name.localeCompare(b.name));
    for (const cap of sortedTools) {
      const params = buildToolParameters(cap);
      // Description: "Tool: <name>. Returns <retType>. Cognition primitive: <catalog>."
      // Concise enough to fit in any context window; the model can read it
      // as a hint without us pushing arbitrary user prose into the prompt.
      const desc = `Tool: ${cap.name}. Returns ${cap.returnType}. Backed by cognition primitive: ${cap.cogPrimitive}.`;
      lines.push(`  ${JSON.stringify(cap.name)}: {`);
      lines.push(`    name: ${JSON.stringify(cap.name)},`);
      lines.push(`    description: ${JSON.stringify(desc)},`);
      lines.push(`    parameters: ${JSON.stringify(params)},`);
      lines.push(`  },`);
    }
    lines.push("};");
    lines.push("");
    // __TOOL_DISPATCH — given (name, parsed-args), invoke the right cognition primitive.
    lines.push("const __TOOL_DISPATCH: Record<string, (args: Record<string, unknown>) => Promise<unknown>> = {");
    for (const cap of sortedTools) {
      lines.push(`  ${JSON.stringify(cap.name)}: async (args) => {`);
      // Translate the capability's bindings into a literal mapped-args object.
      // The binding's `value` is a serialized expression like `r.description`
      // or `<paramName>` or a literal like `8`. For tool dispatch we treat
      // bare param names as keys into the args object; everything else is a
      // best-effort literal. This keeps dispatch deterministic and predictable.
      const mapped = cap.bindings.map(b => {
        const v = b.value.trim();
        // Bare param reference: just look it up in args.
        if (cap.params.some(p => p.name === v)) {
          return `${b.param}: args[${JSON.stringify(v)}]`;
        }
        // Numeric literal.
        if (/^-?\d+(\.\d+)?$/.test(v)) {
          return `${b.param}: ${v}`;
        }
        // String literal (already quoted).
        if (/^".*"$/.test(v)) {
          return `${b.param}: ${v}`;
        }
        // Anything else: pass the args object through and hope the primitive
        // handles it. Should be rare since tool capabilities tend to be
        // shallow wrappers around a primitive.
        return `${b.param}: ${JSON.stringify(v)}`;
      });
      lines.push(`    return loadRunCognition()(${JSON.stringify(cap.cogPrimitive)}, { ${mapped.join(", ")} });`);
      lines.push(`  },`);
    }
    lines.push("};");
    lines.push("");
    // ── Tool-call loop helper. Wraps a chat() call so that whenever the
    // model returns tool_calls, we execute them and re-prompt. Bounded by
    // LLM_TOOL_CALL_MAX (default 5).
    lines.push("/**");
    lines.push(" * Phase 15: bounded tool-call loop. Repeatedly calls the provider, dispatches");
    lines.push(" * any tool_calls in the response, and re-prompts with the tool results");
    lines.push(" * appended as role:\"tool\" messages. Returns the first response without");
    lines.push(" * tool_calls (the model's final answer).");
    lines.push(" *");
    lines.push(" * The cap is enforced runtime-side. If the model keeps invoking tools past");
    lines.push(" * the cap, we throw ToolCallBudgetExceeded. The exception type is recoverable");
    lines.push(" * via the normal on_invalid: retry path; the validator will see whatever the");
    lines.push(" * model managed to emit before exhausting the budget.");
    lines.push(" */");
    lines.push("class ToolCallBudgetExceeded extends Error {");
    lines.push("  constructor(public limit: number, public observed: number) {");
    lines.push("    super(`tool-call budget exceeded: ${observed} > ${limit}`);");
    lines.push("    this.name = \"ToolCallBudgetExceeded\";");
    lines.push("  }");
    lines.push("}");
    lines.push("");
    lines.push("async function __chatWithTools(");
    lines.push("  provider: IModelProvider,");
    lines.push("  baseReq: ChatRequest,");
    lines.push("  signal: AbortSignal | undefined,");
    lines.push("  promptName: string,");
    lines.push("  trace_id: string,");
    lines.push("  modelName: string,");
    lines.push("  providerName: string,");
    lines.push("): Promise<ChatResponse> {");
    lines.push("  const max = parseInt(process.env.LLM_TOOL_CALL_MAX || \"5\", 10);");
    lines.push("  const limit = Number.isFinite(max) && max > 0 ? max : 5;");
    lines.push("  const messages: ChatMessage[] = [...baseReq.messages];");
    lines.push("  let toolCallCount = 0;");
    lines.push("  // Loop bound: limit + 1 lets us see the final response after the last tool call.");
    lines.push("  for (let i = 0; i <= limit; i++) {");
    lines.push("    const resp = await provider.chat({ ...baseReq, messages }, signal);");
    lines.push("    const toolCalls = resp.tool_calls;");
    lines.push("    if (!Array.isArray(toolCalls) || toolCalls.length === 0) {");
    lines.push("      // No tool calls — final answer.");
    lines.push("      return resp;");
    lines.push("    }");
    lines.push("    if (toolCallCount + toolCalls.length > limit) {");
    lines.push("      counter(\"cognition.tool_call_budget_exceeded\", { prompt: promptName, model: modelName });");
    lines.push("      throw new ToolCallBudgetExceeded(limit, toolCallCount + toolCalls.length);");
    lines.push("    }");
    lines.push("    // Append the assistant's tool_calls message so providers that need");
    lines.push("    // explicit history (OpenAI does) see the full conversation.");
    lines.push("    messages.push({ role: \"assistant\", content: resp.content || \"\", tool_calls: toolCalls });");
    lines.push("    // Dispatch every tool call sequentially. Order is deterministic — the");
    lines.push("    // provider returned them in some order, we honor it. Errors become tool");
    lines.push("    // results so the model can recover (e.g. retry with a corrected arg).");
    lines.push("    for (const tc of toolCalls) {");
    lines.push("      toolCallCount++;");
    lines.push("      let args: Record<string, unknown> = {};");
    lines.push("      try { args = JSON.parse(tc.arguments) as Record<string, unknown>; }");
    lines.push("      catch { args = {}; }");
    lines.push("      // Closed list — model can't invoke a tool the prompt didn't allow.");
    lines.push("      const fn = __TOOL_DISPATCH[tc.name];");
    lines.push("      const __toolStart = Date.now();");
    lines.push("      let result: unknown;");
    lines.push("      let status: \"ok\" | \"failed\" = \"ok\";");
    lines.push("      let errMsg: string | undefined = undefined;");
    lines.push("      if (!fn) {");
    lines.push("        result = { error: `unknown tool: ${tc.name}` };");
    lines.push("        status = \"failed\";");
    lines.push("        errMsg = `unknown tool: ${tc.name}`;");
    lines.push("      } else {");
    lines.push("        try { result = await fn(args); }");
    lines.push("        catch (e) {");
    lines.push("          const m = e instanceof Error ? e.message : String(e);");
    lines.push("          result = { error: m.slice(0, 256) };");
    lines.push("          status = \"failed\";");
    lines.push("          errMsg = m;");
    lines.push("        }");
    lines.push("      }");
    lines.push("      counter(\"cognition.tool_calls\", { prompt: promptName, tool: tc.name, status });");
    lines.push("      // Phase 15: child span per tool call. Args are recorded redacted-by-default");
    lines.push("      // (we pass `input: args` and the tracer handles redaction at write time).");
    lines.push("      await writeSpan({");
    lines.push("        trace_id,");
    lines.push("        workflow: promptName,");
    lines.push("        step: `tool:${tc.name}`,");
    lines.push("        kind: \"tool_call\",");
    lines.push("        prompt: promptName,");
    lines.push("        model: modelName,");
    lines.push("        provider: providerName,");
    lines.push("        input: args,");
    lines.push("        output: result,");
    lines.push("        latency_ms: Date.now() - __toolStart,");
    lines.push("        status: status === \"ok\" ? \"ok\" : \"failed\",");
    lines.push("        error_code: status === \"failed\" ? \"TOOL_FAILED\" : undefined,");
    lines.push("        metadata: { tool: tc.name, call_id: tc.id, error: errMsg?.slice(0, 256) },");
    lines.push("      });");
    lines.push("      messages.push({");
    lines.push("        role: \"tool\",");
    lines.push("        content: JSON.stringify(result),");
    lines.push("        tool_call_id: tc.id,");
    lines.push("        name: tc.name,");
    lines.push("      });");
    lines.push("    }");
    lines.push("  }");
    lines.push("  // Bound exceeded without a tool-free response — surface as an error.");
    lines.push("  counter(\"cognition.tool_call_budget_exceeded\", { prompt: promptName, model: modelName });");
    lines.push("  throw new ToolCallBudgetExceeded(limit, toolCallCount);");
    lines.push("}");
    lines.push("");
  }

  // Sort prompts by name for determinism.
  const sortedPrompts = [...system.prompts].sort((a, b) => a.name.localeCompare(b.name));
  for (const p of sortedPrompts) {
    emitPromptCaller(p, lines, system);
  }

  // Registry. The cognition primitives find prompts by name, so we expose
  // a Map<name, async fn>.
  lines.push("export type PromptFn = (input: Record<string, unknown>, ctx: PromptCtx) => Promise<unknown>;");
  lines.push("");
  lines.push("export const PROMPTS: Record<string, PromptFn> = {");
  for (const p of sortedPrompts) {
    lines.push(`  ${JSON.stringify(p.name)}: prompt_${promptIdent(p.name)},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("export function getPrompt(name: string): PromptFn {");
  lines.push("  const fn = PROMPTS[name];");
  lines.push("  if (!fn) throw new Error(`Unknown prompt: ${name}`);");
  lines.push("  return fn;");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Find the first prompt that looks like a summariser by convention:");
  lines.push(" * any prompt whose name contains \"summar\". Used by the");
  lines.push(" * compress_context cognition primitive when the user has not specified");
  lines.push(" * an explicit summariser.");
  lines.push(" */");
  lines.push("export function findSummarizer(): PromptFn | null {");
  lines.push("  for (const name of Object.keys(PROMPTS).sort()) {");
  lines.push("    if (/summar/i.test(name)) return PROMPTS[name];");
  lines.push("  }");
  lines.push("  return null;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function emitPromptCaller(p: IR.IRPrompt, lines: string[], system: IR.IRSystem): void {
  const ident = promptIdent(p.name);
  const isExtTemplate = p.template.startsWith("extension_point:");
  const extName = isExtTemplate ? p.template.slice("extension_point:".length) : null;
  // Phase 14: dispatch on the prompt's declared output_type so File and
  // list<File> shapes get parsed differently. The output_type string is the
  // serialized TypeExpr from lowering — "File", "list<File>", "string",
  // "json", or anything else (treated as unknown).
  const expected: "string" | "json" | "unknown" | "file" | "files" =
    p.output_type === "string" ? "string" :
    p.output_type === "File" ? "file" :
    /^list<\s*File\s*>$/.test(p.output_type) ? "files" :
    p.validate.kind === "schema_only" ? "json" : "unknown";

  lines.push(`// Prompt: ${p.name}`);
  lines.push(`// model: ${p.model_ref ?? "router:" + p.router_ref}`);
  lines.push(`// validate: ${p.validate.kind} | on_invalid: ${p.on_invalid} | timeout: ${p.timeout_ms}ms`);
  lines.push(`async function prompt_${ident}(input: Record<string, unknown>, ctx: PromptCtx): Promise<unknown> {`);
  lines.push(`  const __start = Date.now();`);

  // Resolve model entry — static model_ref takes precedence; otherwise call
  // the router with the input.
  if (p.model_ref) {
    lines.push(`  const __model: ModelEntry = getModel(${JSON.stringify(p.model_ref)});`);
    lines.push(`  const __tier = "fixed";`);
  } else if (p.router_ref) {
    lines.push(`  const __router: CompiledRouter = getRouter(${JSON.stringify(p.router_ref)});`);
    lines.push(`  const __routeChoice: RouteChoice = __router.route(input);`);
    lines.push(`  let __model: ModelEntry = __routeChoice.model;`);
    lines.push(`  let __tier: string = __routeChoice.tier;`);
  } else {
    // Type checker T022 already prevents this, but guard anyway.
    lines.push(`  throw new Error(${JSON.stringify(`Prompt ${p.name} has no model or router (this should have been caught at compile time)`)});`);
  }

  // Build messages from the extension_point template.
  if (extName) {
    lines.push(`  const __template = loadExtension(${JSON.stringify(extName)});`);
    lines.push(`  const __rendered = String(__template(...Object.values(input)));`);
  } else {
    // Inline template — used as-is.
    lines.push(`  const __rendered = ${JSON.stringify(p.template)};`);
  }
  lines.push(`  const __messages = [{ role: "user" as const, content: __rendered }];`);

  // ── Phase 3: cache lookup (only when prompt declares cache:) ──────────────
  if (p.cache !== null) {
    // Template hash so prompt rewordings invalidate cache entries automatically.
    lines.push(`  const __templateHash = createHash("sha256").update(__rendered).digest("hex").slice(0, 16);`);
    // Default key: deriveKey over (prompt, model, template, output, input).
    // If user supplied a `key:` expression we still combine it with the model
    // identity so two different models don't collide on the same key.
    if (p.cache.key_expr) {
      // The user-supplied key expression is computed against `input`. Unsafe
      // expressions (e.g. references the runtime can't resolve) fall back to
      // canonical(input).
      lines.push(`  const __userKey = (() => {`);
      lines.push(`    try { return String(${rewriteKeyExpr(p.cache.key_expr)}); }`);
      lines.push(`    catch { return ""; }`);
      lines.push(`  })();`);
      lines.push(`  const __cacheKey = deriveKey({`);
      lines.push(`    prompt_name: ${JSON.stringify(p.name)},`);
      lines.push(`    model_id: __model.name,`);
      lines.push(`    template_hash: __templateHash + ":" + __userKey,`);
      lines.push(`    output_type: ${JSON.stringify(expected)},`);
      lines.push(`    input,`);
      lines.push(`  });`);
    } else {
      lines.push(`  const __cacheKey = deriveKey({`);
      lines.push(`    prompt_name: ${JSON.stringify(p.name)},`);
      lines.push(`    model_id: __model.name,`);
      lines.push(`    template_hash: __templateHash,`);
      lines.push(`    output_type: ${JSON.stringify(expected)},`);
      lines.push(`    input,`);
      lines.push(`  });`);
    }
    lines.push(`  const __hit = await cache.get(__cacheKey);`);
    lines.push(`  if (__hit) {`);
    lines.push(`    logger.info("cognition_prompt_cache_hit", {`);
    lines.push(`      event: ${JSON.stringify(p.name)},`);
    lines.push(`      status: "success",`);
    lines.push(`      duration_ms: 0,`);
    lines.push(`      trace_id: ctx.trace_id,`);
    lines.push(`      metadata: { model: __model.name, cache_hit: true }`);
    lines.push(`    });`);
    // Phase 6: emit a span for the cache hit so traces show the short-circuit.
    lines.push(`    await writeSpan({`);
    lines.push(`      trace_id: ctx.trace_id,`);
    lines.push(`      workflow: ${JSON.stringify(p.name)},`);
    lines.push(`      step: "cache_lookup",`);
    lines.push(`      kind: "cache_hit",`);
    lines.push(`      prompt: ${JSON.stringify(p.name)},`);
    lines.push(`      model: __model.name,`);
    lines.push(`      provider: __model.provider.name,`);
    lines.push(`      input,`);
    lines.push(`      output: __hit.value,`);
    lines.push(`      prompt_tokens: __hit.prompt_tokens ?? undefined,`);
    lines.push(`      completion_tokens: __hit.completion_tokens ?? undefined,`);
    lines.push(`      latency_ms: 0,`);
    lines.push(`      cache_hit: true,`);
    lines.push(`      status: "cache_hit",`);
    lines.push(`    });`);
    lines.push(`    return __hit.value;`);
    lines.push(`  }`);
  }

  // ── Phase 3: budget tracker ───────────────────────────────────────────────
  // The caller may pass a shared tracker (per-trace enforcement) or omit it.
  // When omitted, we create a single-call tracker so token / cost gauges
  // still fire, but enforcement is local to this call.
  lines.push(`  const __budget: BudgetTracker = ctx.budget ?? newBudget(ctx.trace_id);`);
  // Estimate prompt tokens up-front so the budget can refuse a doomed call.
  // Rough estimate via the provider's countTokens (approxTokens = chars/4).
  lines.push(`  const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);`);

  // Retry loop. Bounded by retry.max_attempts; on_invalid drives recovery.
  const maxAttempts = p.retry?.max_attempts ?? 1;
  const intervalMs = p.retry?.interval_ms ?? 0;
  const backoff = p.retry?.backoff ?? "fixed";
  lines.push(`  const __maxAttempts = ${maxAttempts};`);
  lines.push(`  let __lastError: unknown = null;`);
  lines.push(`  for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {`);
  lines.push(`    const __controller = new AbortController();`);
  lines.push(`    const __timer = setTimeout(() => __controller.abort(), ${p.timeout_ms});`);
  lines.push(`    if (ctx.signal) ctx.signal.addEventListener("abort", () => __controller.abort());`);
  lines.push(`    try {`);
  lines.push(`      counter("cognition.prompt_calls", { prompt: ${JSON.stringify(p.name)}, model: __model.name });`);
  lines.push(`      // Budget gate — refuse if this attempt would push the trace over either ceiling.`);
  lines.push(`      __budget.assertCanSpend(__estimatedTokens, __model.costClass);`);
  // Phase 15: when this prompt declares tools, route the chat call through
  // the bounded tool-call loop. Otherwise call provider.chat() directly.
  if (p.allowed_tools.length > 0) {
    // Build the per-prompt tool-spec list. Sorted alphabetically for the
    // same determinism reason __TOOL_SPECS itself is.
    const sorted = [...p.allowed_tools].sort();
    const toolList = sorted.map(t => `__TOOL_SPECS[${JSON.stringify(t)}]`).join(", ");
    lines.push(`      const __resp = await __chatWithTools(`);
    lines.push(`        __model.provider,`);
    lines.push(`        {`);
    lines.push(`          model: __model.modelName,`);
    lines.push(`          messages: __messages,`);
    lines.push(`          temperature: __model.temperature,`);
    lines.push(`          top_p: __model.topP ?? undefined,`);
    lines.push(`          max_output: __model.maxOutput,`);
    lines.push(`          stop: __model.stop,`);
    // tools + json: cannot both be set; provider adapter handles this.
    lines.push(`          tools: [${toolList}].filter(x => x !== undefined),`);
    lines.push(`          tool_choice: "auto",`);
    lines.push(`          json: ${expected === "json" || expected === "file" || expected === "files" ? "true" : "false"},`);
    lines.push(`        },`);
    lines.push(`        __controller.signal,`);
    lines.push(`        ${JSON.stringify(p.name)},`);
    lines.push(`        ctx.trace_id,`);
    lines.push(`        __model.name,`);
    lines.push(`        __model.provider.name,`);
    lines.push(`      );`);
  } else {
    lines.push(`      const __resp = await __model.provider.chat({`);
    lines.push(`        model: __model.modelName,`);
    lines.push(`        messages: __messages,`);
    lines.push(`        temperature: __model.temperature,`);
    lines.push(`        top_p: __model.topP ?? undefined,`);
    lines.push(`        max_output: __model.maxOutput,`);
    lines.push(`        stop: __model.stop,`);
    // File / files outputs are JSON-shaped, so request JSON mode from the
    // provider when supported. Falls back gracefully on providers that don't
    // honour the flag.
    lines.push(`        json: ${expected === "json" || expected === "file" || expected === "files" ? "true" : "false"},`);
    lines.push(`      }, __controller.signal);`);
  }
  lines.push(`      clearTimeout(__timer);`);
  lines.push(`      const __value = parseModelOutput(__resp.content, ${JSON.stringify(expected)});`);

  // Phase 7: low-confidence check (only when prompt routes through a router).
  // The router's confidence_threshold + on_low_confidence determines whether
  // a confidence below threshold is treated as a validation failure (which
  // routes through on_invalid: escalate / retry / fail).
  if (p.router_ref) {
    const router = system.routers.find(r => r.name === p.router_ref);
    const threshold = router?.confidence_threshold ?? 0;
    const onLow = router?.on_low_confidence ?? "fail";
    if (threshold > 0) {
      lines.push(`      // Phase 7: low-confidence check (router=${p.router_ref}, threshold=${threshold}, on_low_confidence=${onLow})`);
      lines.push(`      const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;`);
      lines.push(`      if (__confidence !== null && __confidence < ${threshold}) {`);
      lines.push(`        counter("cognition.low_confidence", { prompt: ${JSON.stringify(p.name)}, model: __model.name });`);
      // Phase 7: dedicated low_confidence span — emit before we throw so the
      // trace record explicitly distinguishes a low-confidence rejection
      // from a generic validation failure. The downstream catch branch will
      // also emit its standard validate / provider_error span; the two
      // together preserve causality (low_confidence → on_invalid path).
      lines.push(`        await writeSpan({`);
      lines.push(`          trace_id: ctx.trace_id,`);
      lines.push(`          workflow: ${JSON.stringify(p.name)},`);
      lines.push(`          step: "low_confidence",`);
      lines.push(`          kind: "low_confidence",`);
      lines.push(`          prompt: ${JSON.stringify(p.name)},`);
      lines.push(`          model: __model.name,`);
      lines.push(`          provider: __model.provider.name,`);
      lines.push(`          input,`);
      lines.push(`          output: __value,`);
      lines.push(`          confidence: __confidence,`);
      lines.push(`          prompt_tokens: __resp.usage.prompt_tokens ?? undefined,`);
      lines.push(`          completion_tokens: __resp.usage.completion_tokens ?? undefined,`);
      lines.push(`          latency_ms: Date.now() - __start,`);
      lines.push(`          status: "low_confidence",`);
      lines.push(`          metadata: { threshold: ${threshold}, on_low_confidence: ${JSON.stringify(onLow)}, attempt: __attempt, tier: __tier },`);
      lines.push(`        });`);
      lines.push(`        const __lcErr = new Error("low confidence: " + __confidence.toFixed(3) + " < ${threshold}");`);
      lines.push(`        (__lcErr as Error & { __validationIssues?: string[]; __badOutput?: unknown; __lowConfidence?: number }).__validationIssues = ["confidence " + __confidence.toFixed(3) + " < ${threshold}"];`);
      lines.push(`        (__lcErr as Error & { __validationIssues?: string[]; __badOutput?: unknown; __lowConfidence?: number }).__badOutput = __value;`);
      lines.push(`        (__lcErr as Error & { __validationIssues?: string[]; __badOutput?: unknown; __lowConfidence?: number }).__lowConfidence = __confidence;`);
      lines.push(`        throw __lcErr;`);
      lines.push(`      }`);
    } else {
      lines.push(`      const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;`);
    }
  } else {
    lines.push(`      const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;`);
  }

  // Phase 5: structured validation. Each branch ends with __report being set
  // to a ValidationReport; `if (!__report.ok) throw` triggers the recovery
  // path via the existing on_invalid handling.
  switch (p.validate.kind) {
    case "none":
      lines.push(`      // validate: none — accept any parsed value`);
      lines.push(`      const __report: ValidationReport = { ok: true, issues: [] };`);
      break;
    case "schema_only":
      lines.push(`      // validate: schema_only — structural check against ${p.output_type}`);
      lines.push(`      const __report: ValidationReport = validateSchemaOnly(__value, ${JSON.stringify(p.output_type)});`);
      break;
    case "ast_compiles":
      lines.push(`      // validate: ast_compiles — best-effort tsc parse against the model output`);
      lines.push(`      const __report: ValidationReport = await validateAstCompiles(__value);`);
      break;
    case "custom":
      lines.push(`      // validate: custom — delegate to ${p.validate.extension_point}`);
      lines.push(`      const __validatorFn = loadExtension(${JSON.stringify(p.validate.extension_point)});`);
      lines.push(`      const __report: ValidationReport = validateCustom(__value, __validatorFn);`);
      break;
  }
  lines.push(`      if (!__report.ok) {`);
  lines.push(`        const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));`);
  lines.push(`        (__vErr as Error & { __validationIssues?: string[]; __badOutput?: unknown }).__validationIssues = __report.issues;`);
  lines.push(`        (__vErr as Error & { __validationIssues?: string[]; __badOutput?: unknown }).__badOutput = __value;`);
  lines.push(`        throw __vErr;`);
  lines.push(`      }`);

  lines.push(`      const __elapsed = Date.now() - __start;`);
  lines.push(`      // Phase 3: actual usage — refund the over-estimate, charge the truth.`);
  lines.push(`      const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);`);
  lines.push(`      // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.`);
  lines.push(`      __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);`);
  if (p.cache !== null) {
    lines.push(`      // Phase 3: write to cache.`);
    lines.push(`      try {`);
    lines.push(`        await cache.put(__cacheKey, ${JSON.stringify(p.name)}, __model.name, __value, ${p.cache.ttl_ms}, {`);
    lines.push(`          prompt_tokens: __resp.usage.prompt_tokens,`);
    lines.push(`          completion_tokens: __resp.usage.completion_tokens,`);
    lines.push(`        });`);
    lines.push(`      } catch (__cacheErr) {`);
    lines.push(`        // Cache write failures are not fatal — log and continue.`);
    lines.push(`        logger.warn("prompt_cache_write_failed", { event: ${JSON.stringify(p.name)}, status: "rejected", trace_id: ctx.trace_id });`);
    lines.push(`      }`);
  }
  lines.push(`      histogram("cognition.prompt_latency_ms", __elapsed, { prompt: ${JSON.stringify(p.name)}, model: __model.name });`);
  lines.push(`      logger.info("cognition_prompt_ok", {`);
  lines.push(`        event: ${JSON.stringify(p.name)},`);
  lines.push(`        status: "success",`);
  lines.push(`        duration_ms: __elapsed,`);
  lines.push(`        trace_id: ctx.trace_id,`);
  lines.push(`        metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }`);
  lines.push(`      });`);
  // Phase 6: success span. Carries usage + tier so cost / latency dashboards
  // have what they need without joining against logs.
  lines.push(`      await writeSpan({`);
  lines.push(`        trace_id: ctx.trace_id,`);
  lines.push(`        workflow: ${JSON.stringify(p.name)},`);
  lines.push(`        step: "chat",`);
  lines.push(`        kind: "prompt_call",`);
  lines.push(`        prompt: ${JSON.stringify(p.name)},`);
  lines.push(`        model: __model.name,`);
  lines.push(`        provider: __model.provider.name,`);
  lines.push(`        input,`);
  lines.push(`        output: __value,`);
  lines.push(`        validate_result: "ok",`);
  lines.push(`        confidence: __confidence ?? undefined,`);
  lines.push(`        prompt_tokens: __resp.usage.prompt_tokens ?? undefined,`);
  lines.push(`        completion_tokens: __resp.usage.completion_tokens ?? undefined,`);
  lines.push(`        latency_ms: __elapsed,`);
  lines.push(`        cache_hit: false,`);
  lines.push(`        status: "ok",`);
  lines.push(`        metadata: { attempt: __attempt, tier: __tier },`);
  lines.push(`      });`);
  lines.push(`      return __value;`);

  lines.push(`    } catch (__err: unknown) {`);
  lines.push(`      clearTimeout(__timer);`);
  lines.push(`      __lastError = __err;`);
  lines.push(`      // Budget exceptions are terminal — no retry, no escalate, just bubble.`);
  lines.push(`      if (__err instanceof BudgetExceededError) {`);
  lines.push(`        logger.error("cognition_budget_exceeded", {`);
  lines.push(`          event: ${JSON.stringify(p.name)},`);
  lines.push(`          status: "rejected",`);
  lines.push(`          trace_id: ctx.trace_id,`);
  lines.push(`          error_code: "BUDGET_EXCEEDED",`);
  lines.push(`          metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }`);
  lines.push(`        });`);
  // Phase 6: budget-exceeded span. The provider was never called so output is null.
  lines.push(`        await writeSpan({`);
  lines.push(`          trace_id: ctx.trace_id,`);
  lines.push(`          workflow: ${JSON.stringify(p.name)},`);
  lines.push(`          step: "budget",`);
  lines.push(`          kind: "budget_exceeded",`);
  lines.push(`          prompt: ${JSON.stringify(p.name)},`);
  lines.push(`          model: __model.name,`);
  lines.push(`          provider: __model.provider.name,`);
  lines.push(`          input,`);
  lines.push(`          latency_ms: Date.now() - __start,`);
  lines.push(`          status: "budget_exceeded",`);
  lines.push(`          error_code: "BUDGET_EXCEEDED",`);
  lines.push(`          metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },`);
  lines.push(`        });`);
  lines.push(`        throw __err;`);
  lines.push(`      }`);
  lines.push(`      counter("cognition.prompt_failed", { prompt: ${JSON.stringify(p.name)}, model: __model.name });`);
  lines.push(`      const __msg = __err instanceof Error ? __err.message : String(__err);`);
  lines.push(`      logger.warn("cognition_prompt_failed", {`);
  lines.push(`        event: ${JSON.stringify(p.name)},`);
  lines.push(`        status: "rejected",`);
  lines.push(`        trace_id: ctx.trace_id,`);
  lines.push(`        metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }`);
  lines.push(`      });`);
  // Phase 6: generic failure / validation failure span. Distinguishes the two
  // by inspecting the error's __validationIssues marker set in Phase 5.
  // Phase 7: when __lowConfidence is set, the dedicated low_confidence span
  // was already written above; skip the generic emit so traces aren't doubled.
  lines.push(`      {`);
  lines.push(`        const __issues = (__err as Error & { __validationIssues?: string[] }).__validationIssues;`);
  lines.push(`        const __isValidate = Array.isArray(__issues);`);
  lines.push(`        const __isLowConf = typeof (__err as Error & { __lowConfidence?: number }).__lowConfidence === "number";`);
  lines.push(`        const __badOut = (__err as Error & { __badOutput?: unknown }).__badOutput;`);
  lines.push(`        if (!__isLowConf) {`);
  lines.push(`          await writeSpan({`);
  lines.push(`            trace_id: ctx.trace_id,`);
  lines.push(`            workflow: ${JSON.stringify(p.name)},`);
  lines.push(`            step: __isValidate ? "validate" : "chat",`);
  lines.push(`            kind: __isValidate ? "validate" : "prompt_call",`);
  lines.push(`            prompt: ${JSON.stringify(p.name)},`);
  lines.push(`            model: __model.name,`);
  lines.push(`            provider: __model.provider.name,`);
  lines.push(`            input,`);
  lines.push(`            output: __isValidate ? __badOut : undefined,`);
  lines.push(`            validate_result: __isValidate ? "failed" : undefined,`);
  lines.push(`            latency_ms: Date.now() - __start,`);
  lines.push(`            status: __isValidate ? "validate_failed" : "provider_error",`);
  lines.push(`            error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",`);
  lines.push(`            metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },`);
  lines.push(`          });`);
  lines.push(`        }`);
  lines.push(`      }`);

  // on_invalid behavior. Each branch is bounded.
  switch (p.on_invalid) {
    case "fail":
      lines.push(`      // on_invalid: fail — bubble immediately`);
      lines.push(`      throw __err;`);
      break;
    case "retry":
      lines.push(`      // on_invalid: retry — fall through to next attempt`);
      break;
    case "retry_with_repair_prompt":
      lines.push(`      // on_invalid: retry_with_repair_prompt — single-shot repair via the same model`);
      lines.push(`      {`);
      lines.push(`        const __issues = (__err as Error & { __validationIssues?: string[] }).__validationIssues ?? [];`);
      lines.push(`        if (__issues.length === 0) {`);
      lines.push(`          // Non-validation error — fall through to a normal retry.`);
      lines.push(`        } else {`);
      lines.push(`          const __repairFn = REPAIRS[${JSON.stringify(p.name)}];`);
      lines.push(`          if (__repairFn) {`);
      lines.push(`            const __repair = await __repairFn({`);
      lines.push(`              original_input: input,`);
      lines.push(`              bad_output: __err && (__err as Error & { __badOutput?: unknown }).__badOutput,`);
      lines.push(`              issues: __issues,`);
      lines.push(`            }, { trace_id: ctx.trace_id, signal: ctx.signal });`);
      lines.push(`            if (__repair.ok && __repair.value !== null) {`);
      lines.push(`              try {`);
      lines.push(`                const __repaired = parseModelOutput(String(__repair.value), ${JSON.stringify(expected)});`);
      lines.push(`                // Re-validate the repaired output. We only accept it if it passes.`);
      lines.push(`                const __reReport: ValidationReport = ${
        p.validate.kind === "schema_only"
          ? `validateSchemaOnly(__repaired, ${JSON.stringify(p.output_type)})`
          : p.validate.kind === "ast_compiles"
            ? `await validateAstCompiles(__repaired)`
            : p.validate.kind === "custom"
              ? `validateCustom(__repaired, loadExtension(${JSON.stringify(p.validate.extension_point)}))`
              : `{ ok: true, issues: [] }`
      };`);
      lines.push(`                if (__reReport.ok) {`);
      lines.push(`                  __budget.charge(__repair.tokens_used || 0, __model.costClass);`);
      lines.push(`                  counter("cognition.repair.accepted", { prompt: ${JSON.stringify(p.name)} });`);
      lines.push(`                  logger.info("cognition_repair_accepted", { event: ${JSON.stringify(p.name)}, status: "success", trace_id: ctx.trace_id });`);
      // Phase 6: repair span — accepted.
      lines.push(`                  await writeSpan({`);
      lines.push(`                    trace_id: ctx.trace_id,`);
      lines.push(`                    workflow: ${JSON.stringify(p.name)},`);
      lines.push(`                    step: "repair",`);
      lines.push(`                    kind: "repair",`);
      lines.push(`                    prompt: ${JSON.stringify(p.name)},`);
      lines.push(`                    model: __model.name,`);
      lines.push(`                    provider: __model.provider.name,`);
      lines.push(`                    input,`);
      lines.push(`                    output: __repaired,`);
      lines.push(`                    validate_result: "ok",`);
      lines.push(`                    completion_tokens: __repair.tokens_used || undefined,`);
      lines.push(`                    latency_ms: Date.now() - __start,`);
      lines.push(`                    status: "repair_accepted",`);
      lines.push(`                    metadata: { issues_count: __issues.length, attempt: __attempt },`);
      lines.push(`                  });`);
      lines.push(`                  return __repaired;`);
      lines.push(`                }`);
      lines.push(`                counter("cognition.repair.rejected", { prompt: ${JSON.stringify(p.name)} });`);
      // Phase 6: repair span — rejected (output failed re-validation).
      lines.push(`                await writeSpan({`);
      lines.push(`                  trace_id: ctx.trace_id,`);
      lines.push(`                  workflow: ${JSON.stringify(p.name)},`);
      lines.push(`                  step: "repair",`);
      lines.push(`                  kind: "repair",`);
      lines.push(`                  prompt: ${JSON.stringify(p.name)},`);
      lines.push(`                  model: __model.name,`);
      lines.push(`                  provider: __model.provider.name,`);
      lines.push(`                  input,`);
      lines.push(`                  output: __repaired,`);
      lines.push(`                  validate_result: "failed",`);
      lines.push(`                  completion_tokens: __repair.tokens_used || undefined,`);
      lines.push(`                  latency_ms: Date.now() - __start,`);
      lines.push(`                  status: "repair_rejected",`);
      lines.push(`                  metadata: { issues_count: __issues.length, re_issues: __reReport.issues.slice(0, 5) },`);
      lines.push(`                });`);
      lines.push(`              } catch (__parseErr) {`);
      lines.push(`                counter("cognition.repair.unparseable", { prompt: ${JSON.stringify(p.name)} });`);
      lines.push(`              }`);
      lines.push(`            }`);
      lines.push(`          }`);
      lines.push(`        }`);
      lines.push(`        // Repair failed (or no repair available) — fall through to next attempt.`);
      lines.push(`      }`);
      break;
    case "escalate":
      // Escalate one tier when we have a router; otherwise re-raise.
      if (p.router_ref) {
        lines.push(`      // on_invalid: escalate — bump tier`);
        lines.push(`      const __next = __router.escalate(__tier);`);
        lines.push(`      if (!__next) throw __err;`);
        // Phase 6: escalate span — captures the tier transition.
        lines.push(`      await writeSpan({`);
        lines.push(`        trace_id: ctx.trace_id,`);
        lines.push(`        workflow: ${JSON.stringify(p.name)},`);
        lines.push(`        step: "escalate",`);
        lines.push(`        kind: "escalate",`);
        lines.push(`        prompt: ${JSON.stringify(p.name)},`);
        lines.push(`        model: __next.model.name,`);
        lines.push(`        provider: __next.model.provider.name,`);
        lines.push(`        latency_ms: Date.now() - __start,`);
        lines.push(`        status: "escalated",`);
        lines.push(`        metadata: { from_tier: __tier, to_tier: __next.tier, attempt: __attempt },`);
        lines.push(`      });`);
        lines.push(`      __model = __next.model;`);
        lines.push(`      __tier = __next.tier;`);
      } else {
        lines.push(`      // on_invalid: escalate — no router, cannot escalate; re-raise`);
        lines.push(`      throw __err;`);
      }
      break;
  }

  // Backoff between attempts. Uses ms wait — works in tests via jest fake timers.
  if (intervalMs > 0 && maxAttempts > 1) {
    if (backoff === "exponential") {
      lines.push(`      if (__attempt < __maxAttempts) await new Promise(r => setTimeout(r, ${intervalMs} * Math.pow(2, __attempt - 1)));`);
    } else if (backoff === "linear") {
      lines.push(`      if (__attempt < __maxAttempts) await new Promise(r => setTimeout(r, ${intervalMs} * __attempt));`);
    } else {
      lines.push(`      if (__attempt < __maxAttempts) await new Promise(r => setTimeout(r, ${intervalMs}));`);
    }
  }
  lines.push(`    }`);
  lines.push(`  }`);
  // Phase 7+: last-chance fallback escalation. When the prompt is router-
  // bound AND the router has a `fallback` model that's distinct from the
  // current tier (or the call has only used the easy tier so far), give
  // the request one final shot on the fallback model with a fresh repair
  // budget. This is the "local model tried hard and failed; now hand it
  // off to the cloud model" pattern. Without this, prompts with low-quality
  // local outputs simply throw — even when a stronger model would succeed.
  if (p.router_ref) {
    lines.push(`  // Last-chance fallback escalation: local model exhausted retries.`);
    lines.push(`  //   1. Find the router's fallback model.`);
    lines.push(`  //   2. If it's distinct from the model that just failed, retry once`);
    lines.push(`  //      with the fallback model + a fresh repair attempt budget.`);
    lines.push(`  //   3. Emit a span tagged escalate / fallback so traces show the swap.`);
    lines.push(`  {`);
    lines.push(`    const __fb = __router.fallback();`);
    lines.push(`    // Only swap if the fallback differs from the model that just failed.`);
    lines.push(`    // Compare by name since the router never exposes a stable id at runtime.`);
    lines.push(`    if (__fb && __fb.model.name !== __model.name) {`);
    lines.push(`      counter("cognition.fallback.attempted", { prompt: ${JSON.stringify(p.name)}, from_model: __model.name, to_model: __fb.model.name });`);
    lines.push(`      logger.info("cognition_fallback_attempt", { event: ${JSON.stringify(p.name)}, status: "success", trace_id: ctx.trace_id, metadata: { from_model: __model.name, to_model: __fb.model.name, after_attempts: __maxAttempts } });`);
    lines.push(`      await writeSpan({`);
    lines.push(`        trace_id: ctx.trace_id,`);
    lines.push(`        workflow: ${JSON.stringify(p.name)},`);
    lines.push(`        step: "fallback",`);
    lines.push(`        kind: "escalate",`);
    lines.push(`        prompt: ${JSON.stringify(p.name)},`);
    lines.push(`        model: __fb.model.name,`);
    lines.push(`        provider: __fb.model.provider.name,`);
    lines.push(`        latency_ms: Date.now() - __start,`);
    lines.push(`        status: "escalated",`);
    lines.push(`        metadata: { from_tier: __tier, to_tier: "fallback", from_model: __model.name, to_model: __fb.model.name, exhausted_attempts: __maxAttempts },`);
    lines.push(`      });`);
    lines.push(`      // Swap to the fallback model and run one bounded attempt.`);
    lines.push(`      const __fbModel = __fb.model;`);
    lines.push(`      const __fbController = new AbortController();`);
    lines.push(`      const __fbTimer = setTimeout(() => __fbController.abort(), ${p.timeout_ms});`);
    lines.push(`      if (ctx.signal) ctx.signal.addEventListener("abort", () => __fbController.abort());`);
    lines.push(`      try {`);
    lines.push(`        const __fbEstimatedTokens = __fbModel.provider.countTokens(__rendered) + (__fbModel.maxOutput || 256);`);
    lines.push(`        __budget.assertCanSpend(__fbEstimatedTokens, __fbModel.costClass);`);
    lines.push(`        const __fbResp = await __fbModel.provider.chat({`);
    lines.push(`          messages: [{ role: "user", content: __rendered }],`);
    lines.push(`          model: __fbModel.modelName,`);
    lines.push(`          temperature: __fbModel.temperature,`);
    lines.push(`          max_output: __fbModel.maxOutput,`);
    lines.push(`        }, __fbController.signal);`);
    lines.push(`        clearTimeout(__fbTimer);`);
    lines.push(`        const __fbValue = parseModelOutput(__fbResp.content, ${JSON.stringify(expected)});`);
    // Re-validate using the same validator the prompt declared.
    const validatorCall = (() => {
      switch (p.validate.kind) {
        case "schema_only":
          return `validateSchemaOnly(__fbValue, ${JSON.stringify(p.output_type)})`;
        case "ast_compiles":
          return `await validateAstCompiles(__fbValue)`;
        case "custom":
          return `validateCustom(__fbValue, loadExtension(${JSON.stringify((p.validate as { extension_point: string }).extension_point)}))`;
        default:
          return `{ ok: true, issues: [] }`;
      }
    })();
    lines.push(`        const __fbReport: ValidationReport = ${validatorCall};`);
    lines.push(`        const __fbTokensUsed = (__fbResp.usage?.completion_tokens ?? 0) + (__fbResp.usage?.prompt_tokens ?? 0);`);
    lines.push(`        if (__fbReport.ok) {`);
    lines.push(`          __budget.charge(__fbTokensUsed || __fbEstimatedTokens, __fbModel.costClass);`);
    lines.push(`          counter("cognition.fallback.accepted", { prompt: ${JSON.stringify(p.name)}, model: __fbModel.name });`);
    lines.push(`          await writeSpan({`);
    lines.push(`            trace_id: ctx.trace_id,`);
    lines.push(`            workflow: ${JSON.stringify(p.name)},`);
    lines.push(`            step: "fallback_call",`);
    lines.push(`            kind: "prompt_call",`);
    lines.push(`            prompt: ${JSON.stringify(p.name)},`);
    lines.push(`            model: __fbModel.name,`);
    lines.push(`            provider: __fbModel.provider.name,`);
    lines.push(`            input,`);
    lines.push(`            output: __fbValue,`);
    lines.push(`            validate_result: "ok",`);
    lines.push(`            prompt_tokens: __fbResp.usage?.prompt_tokens,`);
    lines.push(`            completion_tokens: __fbResp.usage?.completion_tokens,`);
    lines.push(`            latency_ms: Date.now() - __start,`);
    lines.push(`            status: "ok",`);
    lines.push(`            metadata: { fallback: true, from_model: __model.name },`);
    lines.push(`          });`);
    lines.push(`          return __fbValue;`);
    lines.push(`        }`);
    lines.push(`        // Fallback also failed validation — record and re-throw the original.`);
    lines.push(`        counter("cognition.fallback.rejected", { prompt: ${JSON.stringify(p.name)}, model: __fbModel.name });`);
    lines.push(`        await writeSpan({`);
    lines.push(`          trace_id: ctx.trace_id,`);
    lines.push(`          workflow: ${JSON.stringify(p.name)},`);
    lines.push(`          step: "fallback_call",`);
    lines.push(`          kind: "validate",`);
    lines.push(`          prompt: ${JSON.stringify(p.name)},`);
    lines.push(`          model: __fbModel.name,`);
    lines.push(`          provider: __fbModel.provider.name,`);
    lines.push(`          input,`);
    lines.push(`          output: __fbValue,`);
    lines.push(`          validate_result: "failed",`);
    lines.push(`          latency_ms: Date.now() - __start,`);
    lines.push(`          status: "validate_failed",`);
    lines.push(`          metadata: { fallback: true, issues: __fbReport.issues.slice(0, 5) },`);
    lines.push(`        });`);
    lines.push(`      } catch (__fbErr) {`);
    lines.push(`        clearTimeout(__fbTimer);`);
    lines.push(`        // Fallback model errored. Log + fall through to throw the original.`);
    lines.push(`        const __fbMsg = __fbErr instanceof Error ? __fbErr.message : String(__fbErr);`);
    lines.push(`        logger.warn("cognition_fallback_failed", { event: ${JSON.stringify(p.name)}, status: "failure", trace_id: ctx.trace_id, metadata: { error: __fbMsg.slice(0, 256) } });`);
    lines.push(`        counter("cognition.fallback.error", { prompt: ${JSON.stringify(p.name)} });`);
    lines.push(`      }`);
    lines.push(`    }`);
    lines.push(`  }`);
  }
  lines.push(`  throw __lastError ?? new Error(${JSON.stringify(`Prompt ${p.name} failed after retries`)});`);
  lines.push(`}`);
  lines.push("");
}

function promptIdent(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

/**
 * Translate a serialized cache `key:` expression from the IR into a JS
 * expression that can run inside the prompt body. Supports a deliberately
 * narrow surface so users can't smuggle arbitrary code through the key.
 *
 *   hash(field)      → createHash("sha256").update(String(input.field ?? "")).digest("hex").slice(0, 16)
 *   field            → String(input.field ?? "")
 *   field.subfield   → String((input.field ?? {}).subfield ?? "")
 *
 * Anything else falls back to `canonical(input)` — i.e. the default key
 * derivation, so an unknown expression silently degrades rather than
 * exploding.
 */
function rewriteKeyExpr(expr: string): string {
  // Strip outer parens that wrap the whole expression but keep call parens.
  // We trim only matched outer pairs to avoid eating call syntax: `(x)` is OK
  // to unwrap but `hash(x)` must stay intact.
  let trimmed = expr.trim();
  while (trimmed.startsWith("(") && trimmed.endsWith(")") && balancedAtRoot(trimmed)) {
    trimmed = trimmed.slice(1, -1).trim();
  }
  // hash(<path>)
  const hashMatch = trimmed.match(/^hash\(\s*([a-zA-Z_][a-zA-Z0-9_.]*)\s*\)$/);
  if (hashMatch) {
    const path = hashMatch[1].split(".");
    const access = path.length === 1
      ? `input[${JSON.stringify(path[0])}]`
      : path.map((p, i) => i === 0 ? `(input[${JSON.stringify(p)}] as Record<string, unknown>)` : `[${JSON.stringify(p)}]`).join("");
    return `createHash("sha256").update(String(${access} ?? "")).digest("hex").slice(0, 16)`;
  }
  // dotted path → string of the value
  if (/^[a-zA-Z_][a-zA-Z0-9_.]*$/.test(trimmed)) {
    const path = trimmed.split(".");
    if (path.length === 1) return `String(input[${JSON.stringify(path[0])}] ?? "")`;
    let acc = `input[${JSON.stringify(path[0])}]`;
    for (let i = 1; i < path.length; i++) acc = `(${acc} as Record<string, unknown>)?.[${JSON.stringify(path[i])}]`;
    return `String(${acc} ?? "")`;
  }
  // Unknown shape — degrade to default key by returning empty string.
  return `""`;
}

/**
 * Returns true iff the leading `(` at offset 0 is closed by the trailing `)`
 * at offset s.length-1 — i.e. the parens are a single outer wrapper around
 * the whole expression rather than a function call. Used by rewriteKeyExpr
 * to safely peel parenthesised wrappers without eating call syntax.
 */
function balancedAtRoot(s: string): boolean {
  let depth = 0;
  for (let i = 0; i < s.length; i++) {
    if (s[i] === "(") depth++;
    else if (s[i] === ")") {
      depth--;
      if (depth === 0 && i !== s.length - 1) return false;
    }
  }
  return depth === 0;
}

// ─── src/cognition/primitives.ts ────────────────────────────────────────────

function emitPrimitivesFile(used: Set<string>): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition primitives — closed catalog implementations.");
  lines.push("// Only the primitives referenced by capabilities in the system are emitted.");
  lines.push("");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("import { getPrompt, type PromptFn, findSummarizer } from \"./prompts\";");
  lines.push("import { getRouter, type CompiledRouter } from \"./router\";");
  lines.push("");

  // Build the CognitionCtx that the catalog emit functions reference.
  // The interface always declares `memory.getIndex()`; the caller (buildCtx)
  // wires it to the real index when memory is needed, or returns null when not.
  lines.push("export interface CognitionCtx {");
  lines.push("  trace_id: string;");
  lines.push("  signal?: AbortSignal;");
  lines.push("  prompts: {");
  lines.push("    get(name: string): PromptFn | null;");
  lines.push("    findSummarizer(): PromptFn | null;");
  lines.push("  };");
  lines.push("  routers: {");
  lines.push("    get(name: string): CompiledRouter | null;");
  lines.push("  };");
  // Memory slot — exposes the semantic index when the system uses memory
  // primitives. Primitives that need an index but receive a null one fall
  // back to the empty-slice behaviour from the catalog.
  lines.push("  memory: {");
  lines.push("    /** Returns the singleton SemanticIndex, or null when memory is not configured. */");
  lines.push("    getIndex(): { walk(task: string, hopDepth: number, maxFiles: number, repo_filter?: string | string[]): { files: string[]; symbols: string[]; target_symbol: string }; symbolsByFile(file: string): unknown[]; importsOf(file: string): string[]; refresh(): Promise<void>; } | null;");
  lines.push("  };");
  lines.push("  logger: typeof logger;");
  lines.push("  metrics: { counter: typeof counter };");
  lines.push("}");
  lines.push("");

  // Primitives we emit are the intersection of `used` and the catalog. The
  // type checker (T028) has already confirmed every entry is valid.
  const sortedNames = [...used].sort();
  for (const name of sortedNames) {
    const spec = lookupCognition(name);
    if (!spec) {
      // Should never happen — guarded by T028.
      lines.push(`// SKIPPED unknown primitive: ${name}`);
      continue;
    }
    lines.push(`// ${spec.name} (${spec.category}, cost=${spec.cost}, callsModel=${spec.callsModel})`);
    lines.push(`// ${spec.description.split("\n")[0].slice(0, 200)}`);
    lines.push(spec.emit());
    lines.push("");
  }

  // Dispatch table.
  lines.push("export type CognitionPrimitive = (args: Record<string, unknown>, ctx: CognitionCtx) => Promise<unknown>;");
  lines.push("");
  lines.push("export const PRIMITIVES: Record<string, CognitionPrimitive> = {");
  for (const name of sortedNames) {
    lines.push(`  ${JSON.stringify(name)}: ${name},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("export function callCognition(name: string, args: Record<string, unknown>, ctx: CognitionCtx): Promise<unknown> {");
  lines.push("  const fn = PRIMITIVES[name];");
  lines.push("  if (!fn) throw new Error(`Unknown cognition primitive: ${name}`);");
  lines.push("  return fn(args, ctx);");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

// ─── src/cognition/index.ts ─────────────────────────────────────────────────

function emitIndexFile(
  system: IR.IRSystem,
  used: Set<string>,
  hasRouters: boolean,
  hasPrompts: boolean,
): string {
  const memoryActive = memoryNeeded(system);
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 2 — public entry.");
  lines.push("//");
  lines.push("// Application code imports `getCognition` to get a CognitionCtx wired");
  lines.push("// to all declared models, prompts, routers, and primitives.");
  lines.push("");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("import { listModelNames, getModel } from \"../providers\";");
  if (hasPrompts) {
    lines.push("import { PROMPTS, getPrompt, findSummarizer } from \"./prompts\";");
  }
  if (hasRouters) {
    lines.push("import { ROUTERS, getRouter } from \"./router\";");
  }
  if (used.size > 0) {
    lines.push("import { PRIMITIVES, callCognition, type CognitionCtx, type CognitionPrimitive } from \"./primitives\";");
  }
  if (memoryActive) {
    lines.push("import { getIndex as __getMemoryIndex } from \"../memory\";");
  }
  lines.push("");
  lines.push("import { randomUUID } from \"crypto\";");
  lines.push("");
  lines.push("export function newTraceId(): string { return randomUUID(); }");
  lines.push("");

  // Build a CognitionCtx using the registries.
  if (used.size > 0) {
    lines.push("export function buildCtx(trace_id?: string, signal?: AbortSignal): CognitionCtx {");
    lines.push("  return {");
    lines.push("    trace_id: trace_id ?? newTraceId(),");
    lines.push("    signal,");
    lines.push("    prompts: {");
    if (hasPrompts) {
      lines.push("      get(name: string) { return PROMPTS[name] ?? null; },");
      lines.push("      findSummarizer,");
    } else {
      lines.push("      get() { return null; },");
      lines.push("      findSummarizer() { return null; },");
    }
    lines.push("    },");
    lines.push("    routers: {");
    if (hasRouters) {
      lines.push("      get(name: string) { return ROUTERS[name] ?? null; },");
    } else {
      lines.push("      get() { return null; },");
    }
    lines.push("    },");
    lines.push("    memory: {");
    if (memoryActive) {
      lines.push("      getIndex() { return __getMemoryIndex(); },");
    } else {
      lines.push("      getIndex() { return null; },");
    }
    lines.push("    },");
    lines.push("    logger,");
    lines.push("    metrics: { counter },");
    lines.push("  };");
    lines.push("}");
    lines.push("");
  }

  // Re-exports — give the application a single entry point.
  if (hasPrompts) lines.push("export { PROMPTS, getPrompt, findSummarizer };");
  if (hasRouters) lines.push("export { ROUTERS, getRouter };");
  if (used.size > 0) lines.push("export { PRIMITIVES, callCognition };");
  lines.push("export { listModelNames, getModel };");
  lines.push("");

  // Convenience helpers — make it trivial to call a prompt or primitive
  // without building the context manually.
  if (hasPrompts) {
    lines.push("export async function callPrompt(name: string, input: Record<string, unknown>): Promise<unknown> {");
    lines.push("  const fn = getPrompt(name);");
    lines.push("  return fn(input, { trace_id: newTraceId() });");
    lines.push("}");
    lines.push("");
  }
  if (used.size > 0) {
    lines.push("export async function runCognition(name: string, args: Record<string, unknown>): Promise<unknown> {");
    lines.push("  return callCognition(name, args, buildCtx());");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}
