/**
 * MarrowScript Cost Budget Emitter (LLM Harness, Phase 21)
 *
 * Generates the persistence + runtime gate for multi-tenant cost budgets:
 *
 *   migrations/budget_counters.sql  — sliding-window counter tables + admin views
 *   src/policy/budgets.ts           — assertWithinBudget + chargeBudget helpers
 *   src/routes/admin_budgets.ts     — GET /admin/budgets/:tenant + POST reset
 *
 * Files are only emitted when at least one cost_budget is declared in any
 * policy. Systems without budgets stay completely free of this layer.
 *
 * Determinism: budget IDs are stable (lowering serialises them in declaration
 * order with a deterministic suffix). The emitter walks them in sorted order.
 * No Date.now() / Math.random() in the emitter itself.
 *
 * Gate model: every prompt body and capability runner calls
 * `await assertWithinBudget(scope, action, ctx)` before doing real work. The
 * helper looks up matching budgets, checks the per-window counter, and either
 * returns silently (within cap), throws BudgetExceededError (action=error),
 * or throws BudgetThrottleError with a Retry-After hint (action=throttle).
 * After the work completes, `chargeBudget(scope, action, { tokens, cost_usd })`
 * increments the counter so the next call sees an updated value.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function budgetsNeeded(system: IR.IRSystem): boolean {
  return Array.isArray(system.cost_budgets) && system.cost_budgets.length > 0;
}

export function emitBudgetFiles(system: IR.IRSystem): EmittedFile[] {
  if (!budgetsNeeded(system)) return [];
  const files: EmittedFile[] = [];

  files.push({
    path: "migrations/budget_counters.sql",
    content: emitMigration(),
    language: "sql",
    source_module: "budget",
  });

  files.push({
    path: "src/policy/budgets.ts",
    content: emitBudgetRuntime(system),
    language: "typescript",
    source_module: "budget",
  });

  files.push({
    path: "src/routes/admin_budgets.ts",
    content: emitAdminRoute(),
    language: "typescript",
    source_module: "budget",
  });

  return files;
}

// ─── Migration ──────────────────────────────────────────────────────────────

function emitMigration(): string {
  return [
    "-- Generated by MarrowScript compiler. DO NOT EDIT.",
    "-- Phase 21 — sliding-window cost budget counters.",
    "",
    "-- Counters are bucketed per (budget_id, scope_value, window_start). A budget",
    "-- with window=1h gets one row per hour per scope value. Sliding-window",
    "-- enforcement sums the current window + the previous bucket weighted by",
    "-- elapsed time. Resets to a new bucket happen via INSERT ... ON CONFLICT,",
    "-- which is atomic in PG and avoids a read-modify-write race.",
    "",
    "CREATE TABLE IF NOT EXISTS budget_counters (",
    "  budget_id VARCHAR(256) NOT NULL,",
    "  scope_value VARCHAR(256) NOT NULL,  -- tenant_id, user_id, or feature name",
    "  window_start TIMESTAMPTZ NOT NULL,",
    "  calls BIGINT NOT NULL DEFAULT 0,",
    "  tokens BIGINT NOT NULL DEFAULT 0,",
    "  cost_usd_micros BIGINT NOT NULL DEFAULT 0,  -- USD * 1e6 to avoid float drift",
    "  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),",
    "  PRIMARY KEY (budget_id, scope_value, window_start)",
    ");",
    "",
    "CREATE INDEX IF NOT EXISTS idx_budget_counters_scope ON budget_counters(scope_value, window_start DESC);",
    "CREATE INDEX IF NOT EXISTS idx_budget_counters_window ON budget_counters(window_start);",
    "",
    "-- Audit: every charge that pushes a counter past its cap.",
    "CREATE TABLE IF NOT EXISTS budget_events (",
    "  id UUID PRIMARY KEY,",
    "  budget_id VARCHAR(256) NOT NULL,",
    "  scope_value VARCHAR(256) NOT NULL,",
    "  event VARCHAR(32) NOT NULL,  -- exceeded | throttled | reset",
    "  observed_value BIGINT NOT NULL,",
    "  cap_value BIGINT NOT NULL,",
    "  actor_id VARCHAR(128),",
    "  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()",
    ");",
    "",
    "CREATE INDEX IF NOT EXISTS idx_budget_events_scope ON budget_events(scope_value, occurred_at DESC);",
    "CREATE INDEX IF NOT EXISTS idx_budget_events_budget ON budget_events(budget_id, occurred_at DESC);",
    "",
  ].join("\n");
}

// ─── Runtime ────────────────────────────────────────────────────────────────

function emitBudgetRuntime(system: IR.IRSystem): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Phase 21 — cost budget runtime.");
  lines.push("//");
  lines.push("// Public API:");
  lines.push("//   assertWithinBudget(scope, action, ctx)     — throws if any matching budget would exceed");
  lines.push("//   chargeBudget(scope, action, ctx, charge)   — atomically increment the counter");
  lines.push("//   getBudgetState(tenant_id?)                 — admin read");
  lines.push("//");
  lines.push("// scope:  { tenant_id, user_id }   — runtime supplies these from the auth context");
  lines.push("// action: capability name (e.g. \"forge_artifact\") for per_feature matching");
  lines.push("// charge: { calls?, tokens?, cost_usd? }       — observed usage");
  lines.push("");
  lines.push("import { randomUUID } from \"crypto\";");
  lines.push("import { query } from \"../db\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("");
  lines.push("export class BudgetExceededError extends Error {");
  lines.push("  readonly code: string;");
  lines.push("  readonly observed: number;");
  lines.push("  readonly cap: number;");
  lines.push("  readonly budget_id: string;");
  lines.push("  constructor(budgetId: string, code: string, observed: number, cap: number) {");
  lines.push("    super(`budget '${budgetId}' exceeded: ${observed} > ${cap}`);");
  lines.push("    this.name = \"BudgetExceededError\";");
  lines.push("    this.code = code;");
  lines.push("    this.observed = observed;");
  lines.push("    this.cap = cap;");
  lines.push("    this.budget_id = budgetId;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export class BudgetThrottleError extends Error {");
  lines.push("  readonly retry_after_ms: number;");
  lines.push("  readonly budget_id: string;");
  lines.push("  constructor(budgetId: string, retryAfterMs: number) {");
  lines.push("    super(`budget '${budgetId}' throttled — retry after ${retryAfterMs}ms`);");
  lines.push("    this.name = \"BudgetThrottleError\";");
  lines.push("    this.retry_after_ms = retryAfterMs;");
  lines.push("    this.budget_id = budgetId;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export interface BudgetScope {");
  lines.push("  /** Tenant id when the request is multi-tenant. */");
  lines.push("  tenant_id?: string | null;");
  lines.push("  /** User id from the auth context. */");
  lines.push("  user_id?: string | null;");
  lines.push("}");
  lines.push("");
  lines.push("export interface BudgetCharge {");
  lines.push("  calls?: number;");
  lines.push("  tokens?: number;");
  lines.push("  cost_usd?: number;");
  lines.push("}");
  lines.push("");
  lines.push("export interface BudgetSpec {");
  lines.push("  id: string;");
  lines.push("  policy: string;");
  lines.push("  scope: \"per_tenant\" | \"per_user\" | \"per_feature\";");
  lines.push("  feature: string | null;");
  lines.push("  window_ms: number;");
  lines.push("  cap_usd: number | null;");
  lines.push("  cap_tokens: number | null;");
  lines.push("  cap_calls: number | null;");
  lines.push("  action: \"error\" | \"throttle\";");
  lines.push("  retry_after_ms: number | null;");
  lines.push("  error_code: string | null;");
  lines.push("}");
  lines.push("");

  // Embed the budget specs as a static literal so the runtime doesn't need
  // a separate config file. Sorted by id for deterministic output.
  const sorted = [...system.cost_budgets].sort((a, b) => a.id.localeCompare(b.id));
  lines.push("export const BUDGETS: BudgetSpec[] = [");
  for (const b of sorted) {
    lines.push(`  ${JSON.stringify(b)},`);
  }
  lines.push("];");
  lines.push("");

  // Helpers.
  lines.push("/** Choose the scope_value for a budget. */");
  lines.push("function scopeValue(b: BudgetSpec, scope: BudgetScope, action: string): string | null {");
  lines.push("  if (b.scope === \"per_tenant\") return scope.tenant_id ?? null;");
  lines.push("  if (b.scope === \"per_user\") return scope.user_id ?? null;");
  lines.push("  // per_feature: only matches when the action equals the declared feature.");
  lines.push("  return b.feature && action === b.feature ? b.feature : null;");
  lines.push("}");
  lines.push("");
  lines.push("/** Round a Date down to the nearest window_ms boundary. */");
  lines.push("function windowStart(now: Date, windowMs: number): Date {");
  lines.push("  const t = now.getTime();");
  lines.push("  return new Date(t - (t % windowMs));");
  lines.push("}");
  lines.push("");
  // Decision logic — pure function so it's easy to test.
  lines.push("/**");
  lines.push(" * Decide whether a candidate charge would exceed any matching budget.");
  lines.push(" * Returns { ok: true } when within all caps; { ok: false, ... } on first");
  lines.push(" * matching breach. The runtime applies the breach's action.");
  lines.push(" */");
  lines.push("export interface BudgetDecision {");
  lines.push("  ok: boolean;");
  lines.push("  budget_id?: string;");
  lines.push("  cap_kind?: \"usd\" | \"tokens\" | \"calls\";");
  lines.push("  observed?: number;");
  lines.push("  cap?: number;");
  lines.push("  action?: \"error\" | \"throttle\";");
  lines.push("  retry_after_ms?: number | null;");
  lines.push("  error_code?: string | null;");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Read the current bucket value for a budget under a scope value.");
  lines.push(" * Returns 0 when the bucket doesn't exist yet.");
  lines.push(" */");
  lines.push("async function readCounter(budgetId: string, scopeVal: string, ws: Date): Promise<{ calls: number; tokens: number; cost_usd_micros: number }> {");
  lines.push("  const rows = await query<{ calls: string | number; tokens: string | number; cost_usd_micros: string | number }>(");
  lines.push("    `SELECT calls, tokens, cost_usd_micros FROM budget_counters WHERE budget_id = $1 AND scope_value = $2 AND window_start = $3`,");
  lines.push("    [budgetId, scopeVal, ws.toISOString()],");
  lines.push("  );");
  lines.push("  if (rows.length === 0) return { calls: 0, tokens: 0, cost_usd_micros: 0 };");
  lines.push("  return {");
  lines.push("    calls: Number(rows[0].calls),");
  lines.push("    tokens: Number(rows[0].tokens),");
  lines.push("    cost_usd_micros: Number(rows[0].cost_usd_micros),");
  lines.push("  };");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Atomically increment the bucket for a budget under a scope value. Uses");
  lines.push(" * `INSERT ... ON CONFLICT` so the bucket is created on first write and");
  lines.push(" * incremented on subsequent writes — both atomic in PG.");
  lines.push(" */");
  lines.push("async function incrementCounter(budgetId: string, scopeVal: string, ws: Date, charge: BudgetCharge): Promise<void> {");
  lines.push("  const calls = charge.calls ?? 0;");
  lines.push("  const tokens = charge.tokens ?? 0;");
  lines.push("  const micros = Math.round((charge.cost_usd ?? 0) * 1_000_000);");
  lines.push("  await query(");
  lines.push("    `INSERT INTO budget_counters (budget_id, scope_value, window_start, calls, tokens, cost_usd_micros, updated_at)");
  lines.push("     VALUES ($1, $2, $3, $4, $5, $6, NOW())");
  lines.push("     ON CONFLICT (budget_id, scope_value, window_start) DO UPDATE SET");
  lines.push("       calls = budget_counters.calls + EXCLUDED.calls,");
  lines.push("       tokens = budget_counters.tokens + EXCLUDED.tokens,");
  lines.push("       cost_usd_micros = budget_counters.cost_usd_micros + EXCLUDED.cost_usd_micros,");
  lines.push("       updated_at = NOW()`,");
  lines.push("    [budgetId, scopeVal, ws.toISOString(), calls, tokens, micros],");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Gate function — call before doing the work. Walks every applicable budget");
  lines.push(" * and short-circuits on the first breach. The current charge counts toward");
  lines.push(" * the cap (consume-then-charge would let users spend over the cap once;");
  lines.push(" * check-then-charge gives the cleaner mental model).");
  lines.push(" */");
  lines.push("export async function assertWithinBudget(scope: BudgetScope, action: string, charge: BudgetCharge = {}): Promise<void> {");
  lines.push("  const now = new Date();");
  lines.push("  for (const b of BUDGETS) {");
  lines.push("    const sv = scopeValue(b, scope, action);");
  lines.push("    if (sv === null) continue; // budget doesn't apply");
  lines.push("    const ws = windowStart(now, b.window_ms);");
  lines.push("    const cur = await readCounter(b.id, sv, ws);");
  lines.push("    let observed = 0;");
  lines.push("    let cap = 0;");
  lines.push("    let kind: \"usd\" | \"tokens\" | \"calls\" = \"calls\";");
  lines.push("    if (b.cap_calls !== null) {");
  lines.push("      observed = cur.calls + (charge.calls ?? 1);  // every gated call counts as 1 by default");
  lines.push("      cap = b.cap_calls;");
  lines.push("      kind = \"calls\";");
  lines.push("    } else if (b.cap_tokens !== null) {");
  lines.push("      observed = cur.tokens + (charge.tokens ?? 0);");
  lines.push("      cap = b.cap_tokens;");
  lines.push("      kind = \"tokens\";");
  lines.push("    } else if (b.cap_usd !== null) {");
  lines.push("      observed = (cur.cost_usd_micros / 1_000_000) + (charge.cost_usd ?? 0);");
  lines.push("      cap = b.cap_usd;");
  lines.push("      kind = \"usd\";");
  lines.push("    } else {");
  lines.push("      continue; // no cap — defensive (type checker T050 should have caught)");
  lines.push("    }");
  lines.push("    if (observed > cap) {");
  lines.push("      counter(\"budget.exceeded\", { budget: b.id, scope: b.scope, action: b.action });");
  lines.push("      logger.warn(\"budget_exceeded\", { event: \"budget.exceeded\", trace_id: \"\", metadata: { budget_id: b.id, scope_value: sv, observed, cap, kind } });");
  lines.push("      // Audit row.");
  lines.push("      try {");
  lines.push("        await query(");
  lines.push("          `INSERT INTO budget_events (id, budget_id, scope_value, event, observed_value, cap_value, actor_id) VALUES ($1, $2, $3, $4, $5, $6, $7)`,");
  lines.push("          [randomUUID(), b.id, sv, b.action === \"throttle\" ? \"throttled\" : \"exceeded\", Math.round(observed), Math.round(cap), scope.user_id ?? \"\"],");
  lines.push("        );");
  lines.push("      } catch { /* audit failures are not fatal */ }");
  lines.push("      if (b.action === \"throttle\") {");
  lines.push("        throw new BudgetThrottleError(b.id, b.retry_after_ms ?? 60_000);");
  lines.push("      }");
  lines.push("      throw new BudgetExceededError(b.id, b.error_code ?? \"BUDGET_EXCEEDED\", observed, cap);");
  lines.push("    }");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Persist the actual usage after the gated work completes. Charges every");
  lines.push(" * matching budget — same scope-matching logic as assertWithinBudget. Failures");
  lines.push(" * are logged but not fatal: a charge that fails to write should not crash");
  lines.push(" * the request, since the work has already been done.");
  lines.push(" */");
  lines.push("export async function chargeBudget(scope: BudgetScope, action: string, charge: BudgetCharge): Promise<void> {");
  lines.push("  const now = new Date();");
  lines.push("  for (const b of BUDGETS) {");
  lines.push("    const sv = scopeValue(b, scope, action);");
  lines.push("    if (sv === null) continue;");
  lines.push("    const ws = windowStart(now, b.window_ms);");
  lines.push("    try { await incrementCounter(b.id, sv, ws, charge); }");
  lines.push("    catch (e) {");
  lines.push("      logger.warn(\"budget_charge_failed\", { event: \"budget.charge_failed\", trace_id: \"\", metadata: { budget_id: b.id, error: e instanceof Error ? e.message : String(e) } });");
  lines.push("    }");
  lines.push("  }");
  lines.push("  counter(\"budget.charged\", {});");
  lines.push("}");
  lines.push("");
  lines.push("/** Admin: read every counter for a tenant. Intended for the admin dashboard. */");
  lines.push("export async function getBudgetState(tenantId: string | null): Promise<{ budget_id: string; scope_value: string; window_start: string; calls: number; tokens: number; cost_usd: number }[]> {");
  lines.push("  const rows = await query<{ budget_id: string; scope_value: string; window_start: string; calls: string | number; tokens: string | number; cost_usd_micros: string | number }>(");
  lines.push("    tenantId");
  lines.push("      ? `SELECT budget_id, scope_value, window_start, calls, tokens, cost_usd_micros FROM budget_counters WHERE scope_value = $1 ORDER BY window_start DESC LIMIT 100`");
  lines.push("      : `SELECT budget_id, scope_value, window_start, calls, tokens, cost_usd_micros FROM budget_counters ORDER BY window_start DESC LIMIT 100`,");
  lines.push("    tenantId ? [tenantId] : [],");
  lines.push("  );");
  lines.push("  return rows.map(r => ({");
  lines.push("    budget_id: r.budget_id,");
  lines.push("    scope_value: r.scope_value,");
  lines.push("    window_start: String(r.window_start),");
  lines.push("    calls: Number(r.calls),");
  lines.push("    tokens: Number(r.tokens),");
  lines.push("    cost_usd: Number(r.cost_usd_micros) / 1_000_000,");
  lines.push("  }));");
  lines.push("}");
  lines.push("");
  lines.push("/** Admin: reset a tenant's counters. Audited via budget_events. */");
  lines.push("export async function resetBudgetForScope(scopeValue: string, actorId: string): Promise<{ removed: number }> {");
  lines.push("  const rows = await query<{ count: string }>(");
  lines.push("    `WITH d AS (DELETE FROM budget_counters WHERE scope_value = $1 RETURNING budget_id) SELECT COUNT(*)::text AS count FROM d`,");
  lines.push("    [scopeValue],");
  lines.push("  );");
  lines.push("  const removed = rows.length > 0 ? Number(rows[0].count) : 0;");
  lines.push("  await query(");
  lines.push("    `INSERT INTO budget_events (id, budget_id, scope_value, event, observed_value, cap_value, actor_id) VALUES ($1, $2, $3, $4, $5, $6, $7)`,");
  lines.push("    [randomUUID(), \"*\", scopeValue, \"reset\", removed, 0, actorId],");
  lines.push("  );");
  lines.push("  counter(\"budget.reset\", {});");
  lines.push("  return { removed };");
  lines.push("}");

  return lines.join("\n");
}

// ─── Admin route ────────────────────────────────────────────────────────────

function emitAdminRoute(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Phase 21 — admin routes for budget inspection + reset.");
  lines.push("");
  lines.push("import { Router, Request, Response } from \"express\";");
  lines.push("import { requireAuth, AuthContext } from \"../auth\";");
  lines.push("import { getBudgetState, resetBudgetForScope } from \"../policy/budgets\";");
  lines.push("");
  lines.push("export const adminBudgetsRouter = Router();");
  lines.push("");
  lines.push("// GET /admin/budgets/:tenant_id?  — read counters for one tenant or all");
  lines.push("adminBudgetsRouter.get(\"/:tenant_id?\", requireAuth, async (req: Request, res: Response) => {");
  lines.push("  const tenantId = (req.params as { tenant_id?: string }).tenant_id ?? null;");
  lines.push("  const state = await getBudgetState(tenantId);");
  lines.push("  return res.json({ tenant_id: tenantId, counters: state });");
  lines.push("});");
  lines.push("");
  lines.push("// POST /admin/budgets/:scope_value/reset");
  lines.push("adminBudgetsRouter.post(\"/:scope_value/reset\", requireAuth, async (req: Request, res: Response) => {");
  lines.push("  const auth = (req as Request & { auth?: AuthContext }).auth;");
  lines.push("  const actorId = auth?.actor_id || \"unknown\";");
  lines.push("  const sv = String(req.params.scope_value);");
  lines.push("  const r = await resetBudgetForScope(sv, actorId);");
  lines.push("  return res.json({ ok: true, removed: r.removed });");
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}
