/**
 * MarrowScript Streaming Support (Phase 25)
 *
 * Adds `stream: true` option to prompts. When enabled, the generated prompt
 * caller yields tokens as they arrive from the model instead of waiting for
 * the complete response.
 *
 * Surface syntax:
 *   prompt chat_response(history: list<Message>, input: string) {
 *     model: Medium
 *     template: "extension_point:tmpl_chat"
 *     returns: string
 *     stream: true
 *     timeout: 60s
 *   }
 *
 * Generated caller signature changes from:
 *   async function chat_response(...): Promise<string>
 * To:
 *   async function chat_response(...): AsyncGenerator<string, string, void>
 *   async function chat_response_full(...): Promise<string>  // non-streaming fallback
 *
 * The streaming generator:
 *   1. Opens a streaming connection to the provider
 *   2. Yields each token/chunk as it arrives
 *   3. Accumulates the full response
 *   4. On completion, validates the full response
 *   5. The return value of the generator is the complete validated output
 *
 * SSE endpoint generation:
 *   If the prompt has `stream: true`, the route emitter generates a
 *   Server-Sent Events endpoint at POST /cognition/<prompt_name>/stream
 *   that pipes the generator to the client as SSE messages.
 *
 * Emits: src/cognition/streaming.ts (runtime utilities)
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function emitStreaming(system: IR.IRSystem): EmittedFile | null {
  // Only emit if the system has prompts (streaming infra is always useful)
  if (system.prompts.length === 0) return null;

  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Streaming Runtime (Phase 25) — SSE utilities for streaming prompt responses.");
  lines.push("");
  lines.push("import type { Response } from \"express\";");
  lines.push("");

  // ─── Types ───────────────────────────────────────────────────────────
  lines.push("export interface StreamChunk {");
  lines.push("  /** The token/text delta */");
  lines.push("  delta: string;");
  lines.push("  /** Accumulated text so far */");
  lines.push("  accumulated: string;");
  lines.push("  /** Is this the final chunk? */");
  lines.push("  done: boolean;");
  lines.push("  /** Token index (0-based) */");
  lines.push("  index: number;");
  lines.push("}");
  lines.push("");
  lines.push("export interface StreamOptions {");
  lines.push("  /** Called for each chunk (for logging/metrics) */");
  lines.push("  onChunk?: (chunk: StreamChunk) => void;");
  lines.push("  /** Abort signal */");
  lines.push("  signal?: AbortSignal;");
  lines.push("}");
  lines.push("");

  // ─── SSE Writer ──────────────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Pipe an async generator to an Express response as Server-Sent Events.");
  lines.push(" *");
  lines.push(" * Client usage:");
  lines.push(" *   const es = new EventSource('/cognition/chat/stream');");
  lines.push(" *   es.onmessage = (e) => { const chunk = JSON.parse(e.data); ... }");
  lines.push(" */");
  lines.push("export async function pipeToSSE<T>(");
  lines.push("  generator: AsyncGenerator<StreamChunk, T, void>,");
  lines.push("  res: Response");
  lines.push("): Promise<T> {");
  lines.push("  res.setHeader(\"Content-Type\", \"text/event-stream\");");
  lines.push("  res.setHeader(\"Cache-Control\", \"no-cache\");");
  lines.push("  res.setHeader(\"Connection\", \"keep-alive\");");
  lines.push("  res.setHeader(\"X-Accel-Buffering\", \"no\");");
  lines.push("  res.flushHeaders();");
  lines.push("");
  lines.push("  let result: T;");
  lines.push("  try {");
  lines.push("    while (true) {");
  lines.push("      const { value, done } = await generator.next();");
  lines.push("      if (done) {");
  lines.push("        result = value as T;");
  lines.push("        break;");
  lines.push("      }");
  lines.push("      const chunk = value as StreamChunk;");
  lines.push("      res.write(`data: ${JSON.stringify(chunk)}\\n\\n`);");
  lines.push("      if (chunk.done) break;");
  lines.push("    }");
  lines.push("  } catch (e: any) {");
  lines.push("    res.write(`data: ${JSON.stringify({ error: e.message, done: true })}\\n\\n`);");
  lines.push("    result = undefined as T;");
  lines.push("  }");
  lines.push("");
  lines.push("  res.write(`data: [DONE]\\n\\n`);");
  lines.push("  res.end();");
  lines.push("  return result!;");
  lines.push("}");
  lines.push("");

  // ─── Stream accumulator ──────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Wrap a provider's streaming response into our StreamChunk generator.");
  lines.push(" *");
  lines.push(" * Providers return AsyncIterable<string> (each string is a token delta).");
  lines.push(" * This wraps that into StreamChunk objects with accumulation tracking.");
  lines.push(" */");
  lines.push("export async function* accumulateStream(");
  lines.push("  stream: AsyncIterable<string>,");
  lines.push("  options?: StreamOptions");
  lines.push("): AsyncGenerator<StreamChunk, string, void> {");
  lines.push("  let accumulated = \"\";");
  lines.push("  let index = 0;");
  lines.push("");
  lines.push("  for await (const delta of stream) {");
  lines.push("    if (options?.signal?.aborted) break;");
  lines.push("    accumulated += delta;");
  lines.push("    const chunk: StreamChunk = { delta, accumulated, done: false, index };");
  lines.push("    options?.onChunk?.(chunk);");
  lines.push("    yield chunk;");
  lines.push("    index++;");
  lines.push("  }");
  lines.push("");
  lines.push("  // Final chunk");
  lines.push("  const finalChunk: StreamChunk = { delta: \"\", accumulated, done: true, index };");
  lines.push("  options?.onChunk?.(finalChunk);");
  lines.push("  yield finalChunk;");
  lines.push("");
  lines.push("  return accumulated;");
  lines.push("}");
  lines.push("");

  // ─── Non-streaming collect helper ────────────────────────────────────
  lines.push("/**");
  lines.push(" * Collect a stream into a single string (for internal use / validation).");
  lines.push(" * Use when you need the full response before proceeding.");
  lines.push(" */");
  lines.push("export async function collectStream(");
  lines.push("  stream: AsyncIterable<string>");
  lines.push("): Promise<string> {");
  lines.push("  let result = \"\";");
  lines.push("  for await (const chunk of stream) { result += chunk; }");
  lines.push("  return result;");
  lines.push("}");
  lines.push("");

  // ─── WebSocket streaming (for real-time apps) ────────────────────────
  lines.push("/**");
  lines.push(" * Pipe a stream to a WebSocket connection.");
  lines.push(" * Each chunk is sent as a JSON message.");
  lines.push(" */");
  lines.push("export async function pipeToWebSocket<T>(");
  lines.push("  generator: AsyncGenerator<StreamChunk, T, void>,");
  lines.push("  ws: { send(data: string): void; readyState: number }");
  lines.push("): Promise<T> {");
  lines.push("  const OPEN = 1;");
  lines.push("  let result: T;");
  lines.push("  try {");
  lines.push("    while (true) {");
  lines.push("      const { value, done } = await generator.next();");
  lines.push("      if (done) { result = value as T; break; }");
  lines.push("      if (ws.readyState !== OPEN) break;");
  lines.push("      ws.send(JSON.stringify(value));");
  lines.push("    }");
  lines.push("  } catch (e: any) {");
  lines.push("    if (ws.readyState === OPEN) ws.send(JSON.stringify({ error: e.message, done: true }));");
  lines.push("    result = undefined as T;");
  lines.push("  }");
  lines.push("  return result!;");
  lines.push("}");
  lines.push("");

  return {
    path: "src/cognition/streaming.ts",
    content: lines.join("\n"),
    language: "typescript",
    source_module: "cognition",
  };
}
