/**
 * MarrowScript Zod Schema Emitter
 * Generates Zod v3 validation schemas from an IRSystem.
 */

import * as IR from "./ir";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toPascalCase(s: string): string {
  return s
    .replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^([a-z])/, (_: string, c: string) => c.toUpperCase());
}

function irTypeToZod(irType: string): string {
  if (irType === "string") return "z.string()";
  if (irType === "uint") return "z.number().int().nonnegative()";
  if (irType === "int") return "z.number().int()";
  if (irType === "float") return "z.number()";
  if (irType === "bool") return "z.boolean()";
  if (irType === "timestamp") return "z.string().datetime()";
  if (irType === "uuid") return "z.string().uuid()";
  if (irType === "bytes") return "z.string()";
  if (irType === "json") return "z.unknown()";
  const listMatch = irType.match(/^list<(.+)>$/);
  if (listMatch) return `z.array(${irTypeToZod(listMatch[1])})`;
  const setMatch = irType.match(/^set<(.+)>$/);
  if (setMatch) return `z.array(${irTypeToZod(setMatch[1])})`;
  const optMatch = irType.match(/^optional<(.+)>$/);
  if (optMatch) return `${irTypeToZod(optMatch[1])}.nullable()`;
  return "z.unknown()";
}

function applyConstraints(
  baseZod: string,
  fieldName: string,
  constraints: IR.IRModelConstraint[]
): string {
  let result = baseZod;
  for (const c of constraints) {
    if (c.target !== fieldName) continue;
    if (c.kind === "range") {
      if (c.params.min !== undefined) result += `.min(${c.params.min})`;
      if (c.params.max !== undefined) result += `.max(${c.params.max})`;
    } else if (c.kind === "enum") {
      const vals = c.params.values as string[];
      if (vals && vals.length > 0) {
        result = `z.enum([${vals.map((v) => JSON.stringify(v)).join(", ")}])`;
      }
    }
  }
  return result;
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function emitZodSchemas(system: IR.IRSystem): string {
  const lines: string[] = [];

  lines.push(`// Generated by MarrowScript compiler.`);
  lines.push(`import { z } from "zod";`);
  lines.push("");

  // Model schemas — dedupe by name since the same entity can appear in both
  // an api_service module and its backing data_store module.
  const seenModels = new Set<string>();
  for (const mod of system.modules) {
    for (const model of mod.models) {
      if (seenModels.has(model.name)) continue;
      seenModels.add(model.name);
      const schemaName = toPascalCase(model.name) + "Schema";
      const typeName = toPascalCase(model.name);

      lines.push(`export const ${schemaName} = z.object({`);
      for (const field of model.fields) {
        let zodType = irTypeToZod(field.type);
        zodType = applyConstraints(zodType, field.name, model.constraints);
        if (field.nullable) {
          zodType = zodType + ".nullable()";
        }
        lines.push(`  ${field.name}: ${zodType},`);
      }
      lines.push(`});`);
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
      // Derived schemas for CRUD validation. `omit` drops server-managed fields
      // and `partial` makes every key optional for PUT.
      const hasState = model.fields.some(f => f.name === "state");
      const createPartial = hasState ? ".partial({ state: true })" : "";
      lines.push(`export const ${toPascalCase(model.name)}CreateSchema = ${schemaName}.omit({ id: true, created_at: true, updated_at: true })${createPartial};`);
      lines.push(`export const ${toPascalCase(model.name)}UpdateSchema = ${schemaName}.omit({ id: true, created_at: true, updated_at: true }).partial();`);
      lines.push("");
    }
  }

  // Capability input schemas
  for (const mod of system.modules) {
    for (const iface of mod.interfaces) {
      for (const method of iface.methods) {
        if (method.input.length === 0) continue;
        const modPascal = toPascalCase(mod.name);
        const methodPascal = toPascalCase(method.name);
        const schemaName = `${modPascal}${methodPascal}InputSchema`;

        lines.push(`export const ${schemaName} = z.object({`);
        for (const field of method.input) {
          const zodType = irTypeToZod(field.type);
          lines.push(`  ${field.name}: ${zodType},`);
        }
        lines.push(`});`);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

export function emitZodPackageAdditions(): string {
  return JSON.stringify({ zod: "3.22.4" }, null, 2);
}
