/**
 * MarrowScript Ingest Emitter (LLM Harness, Phase 9 — repository ingestion)
 *
 * Generates a small read-only sandbox runtime at src/cognition/ingest.ts.
 *
 * Purpose:
 *   - Clone arbitrary public (or token-authenticated) Git repos into a
 *     bounded local cache.
 *   - Run safety checks BEFORE the indexer / compressor / generator looks at
 *     the cloned tree.
 *   - Produce a typed report `{ local_path, head_sha, file_count, total_bytes }`
 *     that downstream cognition primitives consume.
 *
 * Why this lives outside the catalog's inline emit():
 *   The catalog primitive `ingest_repository` (added in cognition_catalog.ts
 *   alongside this emitter) is the user-facing handle, but its
 *   implementation is non-trivial — git invocation, sandbox path resolution,
 *   deny-list enforcement, oversize-trip cancellation. Inlining all of that
 *   into the catalog spec's emit() string would be unreadable and hard to
 *   audit. Instead the catalog primitive calls into the helper module this
 *   emitter writes, which keeps the runtime module test-friendly and the
 *   catalog spec a one-liner.
 *
 * Determinism:
 *   - File contents are read deterministically; no Date.now() / Math.random()
 *     in the emitter source.
 *   - Sandbox sub-directory name is sha256(url + "|" + ref).slice(0, 16),
 *     so the same (url, ref) pair always lands in the same path. Re-running
 *     against the same commit short-circuits to a cache check.
 *
 * Safety:
 *   - URLs MUST pass the existing SSRF allowlist (the same one the
 *     openai_compat provider uses) — that opt-in moves into env so users
 *     who're paranoid can keep it locked to specific hosts (typically
 *     `https://github.com`). github.com is allowed by default.
 *   - Symlinks are followed only inside the sandbox; any symlink target
 *     escaping the sandbox root is rejected as `IngestError("escape")`.
 *   - Binary / archive / executable extensions are excluded from the file
 *     count and total-bytes checks have a hard ceiling (default 500MB).
 *   - File-count ceiling (default 50000) is enforced after the clone so
 *     monstrous monorepos fail loudly instead of OOMing the indexer.
 *   - The Git binary is invoked with execFile() (array args, not shell)
 *     and a per-clone timeout. No shell substitution, no command injection
 *     surface.
 *   - Tokens are never written to spans: the sandbox dir name is a
 *     content-addressed hash of (url, ref), not the URL itself, so a token
 *     embedded in a private-repo URL never escapes into trace storage. The
 *     audit logger gets the URL stripped of `x:TOKEN@` userinfo.
 */

import { EmittedFile } from "./emitter";

/**
 * Decide whether the ingest runtime needs to be emitted. Trigger: any
 * capability uses `cognition: ingest_repository`. Consistent with how
 * memoryNeeded() in emit_memory.ts decides on the semantic_slice runtime.
 */
import * as IR from "./ir";

export function ingestNeeded(system: IR.IRSystem): boolean {
  for (const mod of system.modules) {
    for (const iface of mod.interfaces) {
      for (const m of iface.methods) {
        if (m.cognition && m.cognition.catalog_name === "ingest_repository") return true;
      }
    }
  }
  return false;
}

export function emitIngestFiles(system: IR.IRSystem): EmittedFile[] {
  if (!ingestNeeded(system)) return [];

  return [
    {
      path: "src/cognition/ingest.ts",
      content: emitIngestRuntime(),
      language: "typescript",
      source_module: "cognition",
    },
  ];
}

function emitIngestRuntime(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 9 — repository ingestion runtime.");
  lines.push("//");
  lines.push("// Provides ingestRepository(url, ref?) → IngestReport. Used by the");
  lines.push("// `ingest_repository` cognition catalog primitive. Read-only sandbox,");
  lines.push("// size-capped, deny-list-aware, deterministic by (url, ref) key.");
  lines.push("");
  lines.push("import * as fs from \"fs\";");
  lines.push("import * as path from \"path\";");
  lines.push("import { createHash } from \"crypto\";");
  lines.push("import { execFile } from \"child_process\";");
  lines.push("import { promisify } from \"util\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter, histogram } from \"../metrics\";");
  lines.push("");
  lines.push("const execFileAsync = promisify(execFile);");
  lines.push("");
  lines.push("// ── Types ───────────────────────────────────────────────────────────");
  lines.push("");
  lines.push("export interface IngestReport {");
  lines.push("  /** Absolute path to the cloned repo on this host. Read-only. */");
  lines.push("  local_path: string;");
  lines.push("  /** Commit SHA of the cloned ref (full 40-char hex). */");
  lines.push("  head_sha: string;");
  lines.push("  /** Count of regular files inside local_path (after deny-list). */");
  lines.push("  file_count: number;");
  lines.push("  /** Total bytes across counted files. */");
  lines.push("  total_bytes: number;");
  lines.push("  /** The url we cloned from, with tokens stripped. */");
  lines.push("  url_redacted: string;");
  lines.push("  /** The ref we resolved (branch / tag / commit). */");
  lines.push("  ref: string;");
  lines.push("  /** When this report was produced (ms since epoch). */");
  lines.push("  ingested_at: number;");
  lines.push("  /** Hint for the indexer — root-level entry path used as the indexer working dir. */");
  lines.push("  indexer_root: string;");
  lines.push("}");
  lines.push("");
  lines.push("export type IngestErrorKind =");
  lines.push("  | \"oversize\"");
  lines.push("  | \"too_many_files\"");
  lines.push("  | \"denied_extension\"");
  lines.push("  | \"clone_failed\"");
  lines.push("  | \"timeout\"");
  lines.push("  | \"ssrf\"");
  lines.push("  | \"escape\"");
  lines.push("  | \"invalid_url\"");
  lines.push("  | \"git_unavailable\";");
  lines.push("");
  lines.push("export class IngestError extends Error {");
  lines.push("  readonly code = \"INGEST_FAILED\";");
  lines.push("  constructor(public readonly kind: IngestErrorKind, message: string) {");
  lines.push("    super(message);");
  lines.push("    this.name = \"IngestError\";");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // ── Configuration ────────────────────────────────────────────────────────
  lines.push("// ── Configuration ────────────────────────────────────────────────────");
  lines.push("");
  lines.push("/** Default sandbox root. Override with LLM_INGEST_ROOT. */");
  lines.push("const DEFAULT_SANDBOX = path.resolve(process.cwd(), \".forge-cache\", \"ingest\");");
  lines.push("");
  lines.push("/** 500 MB. Override with LLM_INGEST_MAX_BYTES. */");
  lines.push("const DEFAULT_MAX_BYTES = 524288000;");
  lines.push("");
  lines.push("/** 50,000 files. Override with LLM_INGEST_MAX_FILES. */");
  lines.push("const DEFAULT_MAX_FILES = 50000;");
  lines.push("");
  lines.push("/** Per-clone timeout (ms). Override with LLM_INGEST_TIMEOUT_MS. */");
  lines.push("const DEFAULT_TIMEOUT_MS = 120000;");
  lines.push("");
  lines.push("/** Default endpoint allowlist for ingest URLs. github.com is in by");
  lines.push(" *  default; add more via LLM_INGEST_ALLOWLIST=https://github.com,https://gitlab.com");
  lines.push(" *  Set LLM_INGEST_ALLOW_ANY=1 to disable the host check (NOT recommended). */");
  lines.push("const DEFAULT_INGEST_ALLOWLIST = [\"https://github.com\", \"https://gitlab.com\", \"https://codeberg.org\", \"https://bitbucket.org\"];");
  lines.push("");
  lines.push("/** File extensions excluded from file_count + total_bytes accounting and");
  lines.push(" *  hidden from any downstream indexer. Sorted, deterministic. */");
  lines.push("const DENY_EXTENSIONS: readonly string[] = [");
  lines.push("  // archives");
  lines.push("  \".7z\", \".bz2\", \".gz\", \".rar\", \".tar\", \".tgz\", \".xz\", \".zip\",");
  lines.push("  // executables / binaries");
  lines.push("  \".bin\", \".dll\", \".dylib\", \".exe\", \".o\", \".obj\", \".pdb\", \".so\",");
  lines.push("  // compiled bytecode");
  lines.push("  \".class\", \".pyc\", \".pyd\", \".rmeta\", \".rlib\",");
  lines.push("  // disk / vm images");
  lines.push("  \".dmg\", \".img\", \".iso\", \".vdi\", \".vmdk\",");
  lines.push("  // media / fonts");
  lines.push("  \".aac\", \".avi\", \".eot\", \".flac\", \".flv\", \".gif\", \".ico\", \".jpeg\", \".jpg\", \".m4a\", \".m4v\", \".mkv\", \".mov\", \".mp3\", \".mp4\", \".mpeg\", \".mpg\", \".oga\", \".ogg\", \".ogv\", \".opus\", \".otf\", \".png\", \".tiff\", \".ttf\", \".wav\", \".webm\", \".webp\", \".woff\", \".woff2\",");
  lines.push("  // documents & data dumps that aren't useful to a code indexer");
  lines.push("  \".pdf\", \".doc\", \".docx\", \".xls\", \".xlsx\", \".ppt\", \".pptx\",");
  lines.push("  \".sqlite\", \".db\",");
  lines.push("];");
  lines.push("");
  lines.push("function isDeniedFile(p: string): boolean {");
  lines.push("  const ext = path.extname(p).toLowerCase();");
  lines.push("  // Binary search would be overkill — deny list is < 50 entries.");
  lines.push("  return DENY_EXTENSIONS.indexOf(ext) >= 0;");
  lines.push("}");
  lines.push("");
  lines.push("function readEnvNumber(name: string, fallback: number): number {");
  lines.push("  const raw = process.env[name];");
  lines.push("  if (!raw) return fallback;");
  lines.push("  const v = Number(raw);");
  lines.push("  if (!Number.isFinite(v) || v <= 0) return fallback;");
  lines.push("  return v;");
  lines.push("}");
  lines.push("");
  lines.push("function readSandboxRoot(): string {");
  lines.push("  const raw = (process.env.LLM_INGEST_ROOT || \"\").trim();");
  lines.push("  if (!raw) return DEFAULT_SANDBOX;");
  lines.push("  return path.resolve(raw);");
  lines.push("}");
  lines.push("");
  // ── URL handling: redaction + allowlist ──────────────────────────────────
  lines.push("// ── URL handling ────────────────────────────────────────────────────");
  lines.push("");
  lines.push("/** Strip `x:TOKEN@host` userinfo from a URL so secrets don't end up in spans. */");
  lines.push("export function redactUrl(url: string): string {");
  lines.push("  try {");
  lines.push("    const u = new URL(url);");
  lines.push("    if (u.username || u.password) {");
  lines.push("      u.username = \"\";");
  lines.push("      u.password = \"\";");
  lines.push("    }");
  lines.push("    return u.toString();");
  lines.push("  } catch {");
  lines.push("    return \"<invalid url>\";");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("/** Throws IngestError(ssrf) if the URL is not on the allowlist. */");
  lines.push("export function assertIngestAllowed(url: string): void {");
  lines.push("  if (process.env.LLM_INGEST_ALLOW_ANY === \"1\") return;");
  lines.push("  let parsed: URL;");
  lines.push("  try { parsed = new URL(url); } catch { throw new IngestError(\"invalid_url\", `Invalid URL: ${redactUrl(url)}`); }");
  lines.push("  if (parsed.protocol !== \"http:\" && parsed.protocol !== \"https:\") {");
  lines.push("    throw new IngestError(\"ssrf\", `Only http(s):// URLs are accepted (got ${parsed.protocol})`);");
  lines.push("  }");
  lines.push("  const userAllow = (process.env.LLM_INGEST_ALLOWLIST || \"\").split(\",\").map(s => s.trim()).filter(Boolean);");
  lines.push("  const allow = userAllow.length > 0 ? userAllow : DEFAULT_INGEST_ALLOWLIST;");
  lines.push("  for (const a of allow) {");
  lines.push("    if (url.startsWith(a)) return;");
  lines.push("  }");
  lines.push("  throw new IngestError(\"ssrf\", `URL ${redactUrl(url)} is not in LLM_INGEST_ALLOWLIST. Add the host prefix or set LLM_INGEST_ALLOW_ANY=1.`);");
  lines.push("}");
  lines.push("");
  // ── Sandbox path computation ─────────────────────────────────────────────
  lines.push("// ── Sandbox path ────────────────────────────────────────────────────");
  lines.push("");
  lines.push("/** Deterministic sandbox subdir name: sha256(url|ref).slice(0, 16). */");
  lines.push("export function sandboxKey(url: string, ref: string): string {");
  lines.push("  return createHash(\"sha256\").update(redactUrl(url) + \"|\" + ref).digest(\"hex\").slice(0, 16);");
  lines.push("}");
  lines.push("");
  lines.push("function ensureWithinSandbox(target: string, sandboxRoot: string): void {");
  lines.push("  const resolved = path.resolve(target);");
  lines.push("  const root = path.resolve(sandboxRoot);");
  lines.push("  if (resolved !== root && !resolved.startsWith(root + path.sep)) {");
  lines.push("    throw new IngestError(\"escape\", `Path ${resolved} escapes sandbox ${root}`);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // ── Git invocation ───────────────────────────────────────────────────────
  lines.push("// ── Git invocation ──────────────────────────────────────────────────");
  lines.push("");
  lines.push("async function gitVersion(): Promise<string> {");
  lines.push("  try {");
  lines.push("    const { stdout } = await execFileAsync(\"git\", [\"--version\"], { timeout: 5000, windowsHide: true });");
  lines.push("    return stdout.trim();");
  lines.push("  } catch {");
  lines.push("    throw new IngestError(\"git_unavailable\", \"git is not installed or not on PATH\");");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("async function gitCloneShallow(url: string, ref: string, dest: string, timeoutMs: number): Promise<void> {");
  lines.push("  // Args:");
  lines.push("  //   --depth 1            shallow — we only want the working tree, not history");
  lines.push("  //   --filter=blob:limit  cap individual blob size — drops giant binaries");
  lines.push("  //   --single-branch      don't fetch other branches");
  lines.push("  //   --no-tags            skip the tag refs");
  lines.push("  //   --branch <ref>       resolve the ref at clone time so head_sha is stable");
  lines.push("  //                        (only when ref != HEAD; `--branch HEAD` is invalid)");
  lines.push("  //   -c core.autocrlf=false   keep line endings as committed (determinism)");
  lines.push("  //   -c safe.directory=*  permit work in this user-owned dir without git's safe-dir warning");
  lines.push("  const baseArgs: string[] = [");
  lines.push("    \"clone\",");
  lines.push("    \"--depth\", \"1\",");
  lines.push("    \"--filter=blob:limit=10m\",");
  lines.push("    \"--single-branch\",");
  lines.push("    \"--no-tags\",");
  lines.push("    \"-c\", \"core.autocrlf=false\",");
  lines.push("    \"-c\", \"safe.directory=*\",");
  lines.push("  ];");
  lines.push("  // Only pass --branch when the user asked for a specific ref. HEAD is the");
  lines.push("  // remote's default branch; git resolves it implicitly without --branch.");
  lines.push("  const args = ref && ref !== \"HEAD\"");
  lines.push("    ? [...baseArgs, \"--branch\", ref, url, dest]");
  lines.push("    : [...baseArgs, url, dest];");
  lines.push("  try {");
  lines.push("    await execFileAsync(\"git\", args, { timeout: timeoutMs, windowsHide: true, maxBuffer: 1024 * 1024 });");
  lines.push("  } catch (e) {");
  lines.push("    const err = e as Error & { signal?: string; code?: number; killed?: boolean };");
  lines.push("    if (err.killed && err.signal === \"SIGTERM\") {");
  lines.push("      throw new IngestError(\"timeout\", `git clone timed out after ${timeoutMs}ms`);");
  lines.push("    }");
  lines.push("    // Some refs only exist as commit SHAs, not branches. Retry without --branch.");
  lines.push("    // (Fall through to throw if that also fails.)");
  lines.push("    if (ref !== \"HEAD\" && /Remote branch.*not found|fatal: Remote branch/i.test(err.message || \"\")) {");
  lines.push("      try {");
  lines.push("        await execFileAsync(\"git\", [...baseArgs, url, dest], { timeout: timeoutMs, windowsHide: true, maxBuffer: 1024 * 1024 });");
  lines.push("        return;");
  lines.push("      } catch (e2) {");
  lines.push("        const err2 = e2 as Error;");
  lines.push("        throw new IngestError(\"clone_failed\", `git clone failed: ${(err2.message || \"\").slice(0, 256)}`);");
  lines.push("      }");
  lines.push("    }");
  lines.push("    throw new IngestError(\"clone_failed\", `git clone failed: ${(err.message || \"\").slice(0, 256)}`);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("async function gitHeadSha(repoDir: string): Promise<string> {");
  lines.push("  try {");
  lines.push("    const { stdout } = await execFileAsync(\"git\", [\"-C\", repoDir, \"rev-parse\", \"HEAD\"], { timeout: 5000, windowsHide: true });");
  lines.push("    return stdout.trim();");
  lines.push("  } catch {");
  lines.push("    return \"unknown\";");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // ── Tree walking + accounting ────────────────────────────────────────────
  lines.push("// ── Tree walking ────────────────────────────────────────────────────");
  lines.push("");
  lines.push("interface AccountingResult {");
  lines.push("  file_count: number;");
  lines.push("  total_bytes: number;");
  lines.push("  oversize: boolean;");
  lines.push("  too_many_files: boolean;");
  lines.push("}");
  lines.push("");
  lines.push("async function walkAndCount(root: string, sandboxRoot: string, maxFiles: number, maxBytes: number): Promise<AccountingResult> {");
  lines.push("  let file_count = 0;");
  lines.push("  let total_bytes = 0;");
  lines.push("  let oversize = false;");
  lines.push("  let too_many_files = false;");
  lines.push("");
  lines.push("  // Iterative walk with an explicit stack — avoids recursion blowing the");
  lines.push("  // stack on deeply nested monorepos.");
  lines.push("  const stack: string[] = [root];");
  lines.push("  while (stack.length > 0) {");
  lines.push("    const dir = stack.pop()!;");
  lines.push("    let entries: fs.Dirent[];");
  lines.push("    try {");
  lines.push("      entries = await fs.promises.readdir(dir, { withFileTypes: true });");
  lines.push("    } catch {");
  lines.push("      continue;");
  lines.push("    }");
  lines.push("    // Sort for determinism — same tree always walked in same order.");
  lines.push("    entries.sort((a, b) => a.name.localeCompare(b.name));");
  lines.push("    for (const ent of entries) {");
  lines.push("      // Skip the .git database — we want the working tree, not git internals.");
  lines.push("      if (ent.name === \".git\") continue;");
  lines.push("      const full = path.join(dir, ent.name);");
  lines.push("      // Cheap escape check for symlinks: ensureWithinSandbox after stat-resolve.");
  lines.push("      if (ent.isSymbolicLink()) {");
  lines.push("        try {");
  lines.push("          const resolved = await fs.promises.realpath(full);");
  lines.push("          ensureWithinSandbox(resolved, sandboxRoot);");
  lines.push("        } catch {");
  lines.push("          // unreadable / dangling symlink — skip silently, indexer will too");
  lines.push("          continue;");
  lines.push("        }");
  lines.push("      }");
  lines.push("      if (ent.isDirectory()) {");
  lines.push("        stack.push(full);");
  lines.push("        continue;");
  lines.push("      }");
  lines.push("      if (!ent.isFile()) continue;");
  lines.push("      if (isDeniedFile(full)) continue;");
  lines.push("      let size = 0;");
  lines.push("      try {");
  lines.push("        const st = await fs.promises.stat(full);");
  lines.push("        size = st.size;");
  lines.push("      } catch {");
  lines.push("        continue;");
  lines.push("      }");
  lines.push("      file_count += 1;");
  lines.push("      total_bytes += size;");
  lines.push("      if (file_count > maxFiles) { too_many_files = true; break; }");
  lines.push("      if (total_bytes > maxBytes) { oversize = true; break; }");
  lines.push("    }");
  lines.push("    if (oversize || too_many_files) break;");
  lines.push("  }");
  lines.push("");
  lines.push("  return { file_count, total_bytes, oversize, too_many_files };");
  lines.push("}");
  lines.push("");
  // ── Public entry: ingestRepository ───────────────────────────────────────
  lines.push("// ── Public entry ────────────────────────────────────────────────────");
  lines.push("");
  lines.push("export interface IngestOptions {");
  lines.push("  /** Branch / tag / commit-ish. Defaults to HEAD. */");
  lines.push("  ref?: string;");
  lines.push("  /** Override LLM_INGEST_MAX_BYTES for this call. */");
  lines.push("  max_bytes?: number;");
  lines.push("  /** Override LLM_INGEST_MAX_FILES for this call. */");
  lines.push("  max_files?: number;");
  lines.push("  /** Override LLM_INGEST_TIMEOUT_MS for this call. */");
  lines.push("  timeout_ms?: number;");
  lines.push("  /** Force re-clone even when the sandbox dir already exists for this key. */");
  lines.push("  force?: boolean;");
  lines.push("}");
  lines.push("");
  lines.push("export async function ingestRepository(url: string, opts: IngestOptions = {}): Promise<IngestReport> {");
  lines.push("  const ref = (opts.ref || \"HEAD\").trim() || \"HEAD\";");
  lines.push("  assertIngestAllowed(url);");
  lines.push("  await gitVersion();");
  lines.push("");
  lines.push("  const max_bytes = opts.max_bytes ?? readEnvNumber(\"LLM_INGEST_MAX_BYTES\", DEFAULT_MAX_BYTES);");
  lines.push("  const max_files = opts.max_files ?? readEnvNumber(\"LLM_INGEST_MAX_FILES\", DEFAULT_MAX_FILES);");
  lines.push("  const timeout_ms = opts.timeout_ms ?? readEnvNumber(\"LLM_INGEST_TIMEOUT_MS\", DEFAULT_TIMEOUT_MS);");
  lines.push("");
  lines.push("  const root = readSandboxRoot();");
  lines.push("  await fs.promises.mkdir(root, { recursive: true });");
  lines.push("  const key = sandboxKey(url, ref);");
  lines.push("  const dest = path.join(root, key);");
  lines.push("  ensureWithinSandbox(dest, root);");
  lines.push("");
  lines.push("  const t0 = Date.now();");
  lines.push("  const alreadyCloned = fs.existsSync(path.join(dest, \".git\"));");
  lines.push("  if (opts.force && fs.existsSync(dest)) {");
  lines.push("    await fs.promises.rm(dest, { recursive: true, force: true });");
  lines.push("  }");
  lines.push("");
  lines.push("  if (!fs.existsSync(path.join(dest, \".git\"))) {");
  lines.push("    counter(\"cognition.ingest.clone\", { ref });");
  lines.push("    await gitCloneShallow(url, ref, dest, timeout_ms);");
  lines.push("  } else {");
  lines.push("    counter(\"cognition.ingest.cache_hit\", { ref });");
  lines.push("  }");
  lines.push("");
  lines.push("  // Account for size + file count after the clone — the --filter flag");
  lines.push("  // already drops blobs over 10MB, but we still need a hard ceiling on");
  lines.push("  // the total tree before the indexer touches it.");
  lines.push("  const acc = await walkAndCount(dest, root, max_files, max_bytes);");
  lines.push("  if (acc.oversize) {");
  lines.push("    throw new IngestError(\"oversize\", `Repo exceeds ${max_bytes} bytes (counted ${acc.total_bytes}+).`);");
  lines.push("  }");
  lines.push("  if (acc.too_many_files) {");
  lines.push("    throw new IngestError(\"too_many_files\", `Repo exceeds ${max_files} files (counted ${acc.file_count}+).`);");
  lines.push("  }");
  lines.push("");
  lines.push("  const head_sha = await gitHeadSha(dest);");
  lines.push("  const elapsed = Date.now() - t0;");
  lines.push("  histogram(\"cognition.ingest.latency_ms\", elapsed, { ref });");
  lines.push("");
  lines.push("  const report: IngestReport = {");
  lines.push("    local_path: dest,");
  lines.push("    head_sha,");
  lines.push("    file_count: acc.file_count,");
  lines.push("    total_bytes: acc.total_bytes,");
  lines.push("    url_redacted: redactUrl(url),");
  lines.push("    ref,");
  lines.push("    ingested_at: t0,");
  lines.push("    indexer_root: dest,");
  lines.push("  };");
  lines.push("");
  lines.push("  logger.info(\"cognition_ingest_completed\", {");
  lines.push("    event: \"ingest_repository\",");
  lines.push("    status: \"success\",");
  lines.push("    duration_ms: elapsed,");
  lines.push("    metadata: {");
  lines.push("      url: report.url_redacted,");
  lines.push("      ref: report.ref,");
  lines.push("      head_sha: report.head_sha,");
  lines.push("      file_count: report.file_count,");
  lines.push("      total_bytes: report.total_bytes,");
  lines.push("      cached: alreadyCloned,");
  lines.push("    },");
  lines.push("  });");
  lines.push("  return report;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
