/**
 * MarrowScript Cron Jobs Emitter
 * Generates src/cron.ts — scheduled background tasks.
 */

import * as IR from "./ir";

function toPascalCase(s: string): string {
  return s.replace(/(^|[-_\s])(\w)/g, (_, __, c: string) => c.toUpperCase());
}

export function emitCronJobs(system: IR.IRSystem): string {
  const lines: string[] = [];

  // Collect batch capabilities across all api_service modules
  const batchCapabilities: { moduleName: string; capabilityName: string }[] = [];
  for (const mod of system.modules) {
    if (mod.kind === "api_service") {
      for (const iface of mod.interfaces) {
        for (const method of iface.methods) {
          if (method.sync === "batch") {
            batchCapabilities.push({ moduleName: mod.name, capabilityName: method.name });
          }
        }
      }
    }
  }

  lines.push(`// Generated by MarrowScript compiler.`);
  lines.push(`// Cron jobs — scheduled background tasks.`);
  lines.push(`// Uncomment and configure as needed.`);
  lines.push(``);
  lines.push(`import cron from "node-cron";`);
  lines.push(`import { logger } from "./logger";`);
  lines.push(``);
  lines.push(`export function startCronJobs(): void {`);
  lines.push(`  logger.info("cron_started", { event: "startup" });`);

  if (batchCapabilities.length === 0) {
    lines.push(``);
    lines.push(`  // No batch capabilities declared — add cron jobs here.`);
  } else {
    for (const { moduleName, capabilityName } of batchCapabilities) {
      lines.push(``);
      lines.push(`  // ─── ${moduleName}.${capabilityName} ───`);
      lines.push(`  // Runs every hour. Adjust schedule as needed (cron syntax).`);
      lines.push(`  // cron.schedule("0 * * * *", async () => {`);
      lines.push(`  //   try {`);
      lines.push(`  //     logger.info("cron_run", { event: "${moduleName}.${capabilityName}" });`);
      lines.push(`  //     // TODO: implement scheduled logic`);
      lines.push(`  //   } catch (e: any) {`);
      lines.push(`  //     logger.error("cron_error", { event: "${moduleName}.${capabilityName}", metadata: { error: e.message } });`);
      lines.push(`  //   }`);
      lines.push(`  // });`);
    }
  }

  lines.push(`}`);
  lines.push(``);

  // Suppress unused import warning when all jobs are commented out
  // by referencing cron in a way that doesn't execute
  if (batchCapabilities.length > 0) {
    lines.push(`// Keep cron import live — remove this if you uncomment any job above`);
    lines.push(`void (cron as any);`);
    lines.push(``);
  }

  return lines.join("\n");
}
