/**
 * MarrowScript Deploy Target Emitter
 * Generates Dockerfile, k8s manifests, and GitHub Actions CI/CD.
 */

import * as IR from "./ir";

function toSnakeCase(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

export function emitDockerfile(system: IR.IRSystem): string {
  return `# Generated by MarrowScript compiler.
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

FROM node:20-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

# Health check
HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=3 \\
  CMD wget -qO- http://localhost:3000/health/live || exit 1

EXPOSE 3000
USER node
CMD ["node", "dist/index.js"]
`;
}

export function emitDockerignore(): string {
  return `node_modules
dist
.env
*.log
.git
*.marrow
*.marrow.map
`;
}

export function emitK8sDeployment(system: IR.IRSystem): string {
  const name = toSnakeCase(system.name).replace(/_/g, "-");
  return `# Generated by MarrowScript compiler.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    app: ${name}
    version: "${system.version}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${name}:${system.version}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${name}-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${name}-secrets
                  key: jwt-secret
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ${name}-secrets
                  key: redis-url
                  optional: true
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
spec:
  selector:
    app: ${name}
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
`;
}

export function emitGithubActions(system: IR.IRSystem): string {
  const name = toSnakeCase(system.name).replace(/_/g, "-");
  return `# Generated by MarrowScript compiler.
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${toSnakeCase(system.name)}_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Run migrations
        run: npm run migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/${toSnakeCase(system.name)}_test

      - name: Run tests
        run: npx ts-node src/tests.ts
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/${toSnakeCase(system.name)}_test
          JWT_SECRET: test-secret
          TEST_BASE_URL: http://localhost:3000

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${name}:\${{ github.sha }} .
      - name: Tag as latest
        run: docker tag ${name}:\${{ github.sha }} ${name}:latest
`;
}
