/**
 * MarrowScript Prompt Versioning & A/B Testing (Phase 24)
 *
 * Adds version tracking and shadow testing to prompts:
 *
 * Surface syntax:
 *   prompt classify(text: string) {
 *     template: "extension_point:tmpl_classify"
 *     version: 3
 *     shadow: { version: 4, traffic: 10 }   // 10% shadow traffic
 *   }
 *
 * What gets generated:
 *   - Each prompt call records which version was used
 *   - Shadow versions run in parallel on a % of traffic (fire-and-forget)
 *   - Results are stored in cognition_traces with version metadata
 *   - `marrowc compare-versions <prompt>` shows pass rates per version
 *
 * Runtime behavior:
 *   1. Primary call always uses the declared version
 *   2. If shadow is configured, roll a random number
 *   3. If within traffic %, also call the shadow version (non-blocking)
 *   4. Log both results to traces for comparison
 *   5. Return only the primary result to the caller
 *
 * This emits: src/cognition/versioning.ts
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function emitVersioning(system: IR.IRSystem): EmittedFile | null {
  // Only emit if any prompt has version/shadow config
  // For now, emit the runtime infrastructure unconditionally if prompts exist
  if (system.prompts.length === 0) return null;

  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Prompt Versioning & A/B Testing Runtime (Phase 24)");
  lines.push("//");
  lines.push("// Tracks prompt versions, runs shadow experiments, logs results.");
  lines.push("");
  lines.push("import { randomUUID } from \"crypto\";");
  lines.push("");

  // ─── Types ───────────────────────────────────────────────────────────
  lines.push("export interface PromptVersion {");
  lines.push("  /** Version number (from .marrow declaration) */");
  lines.push("  version: number;");
  lines.push("  /** Template identifier (extension_point name) */");
  lines.push("  template: string;");
  lines.push("  /** Is this the primary (active) version? */");
  lines.push("  primary: boolean;");
  lines.push("}");
  lines.push("");
  lines.push("export interface ShadowConfig {");
  lines.push("  /** Shadow version number */");
  lines.push("  version: number;");
  lines.push("  /** Percentage of traffic (0-100) */");
  lines.push("  traffic: number;");
  lines.push("  /** Template for shadow version */");
  lines.push("  template: string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface VersionedResult<T> {");
  lines.push("  /** The primary result (always returned to caller) */");
  lines.push("  data: T;");
  lines.push("  /** Version that produced this result */");
  lines.push("  version: number;");
  lines.push("  /** Execution time in ms */");
  lines.push("  duration_ms: number;");
  lines.push("  /** Whether validation passed */");
  lines.push("  valid: boolean;");
  lines.push("  /** Trace ID for this execution */");
  lines.push("  trace_id: string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface ShadowResult {");
  lines.push("  version: number;");
  lines.push("  duration_ms: number;");
  lines.push("  valid: boolean;");
  lines.push("  trace_id: string;");
  lines.push("  /** Did the shadow produce the same output as primary? */");
  lines.push("  matches_primary: boolean;");
  lines.push("}");
  lines.push("");
  lines.push("export interface VersionComparison {");
  lines.push("  prompt_name: string;");
  lines.push("  primary_version: number;");
  lines.push("  shadow_version: number;");
  lines.push("  /** How many times each version was called */");
  lines.push("  primary_calls: number;");
  lines.push("  shadow_calls: number;");
  lines.push("  /** Pass rates */");
  lines.push("  primary_pass_rate: number;");
  lines.push("  shadow_pass_rate: number;");
  lines.push("  /** Average latency */");
  lines.push("  primary_avg_ms: number;");
  lines.push("  shadow_avg_ms: number;");
  lines.push("  /** How often shadow matched primary output */");
  lines.push("  agreement_rate: number;");
  lines.push("}");
  lines.push("");

  // ─── Version Registry ────────────────────────────────────────────────
  lines.push("/** In-memory version tracking. Persisted to cognition_traces table. */");
  lines.push("class VersionTracker {");
  lines.push("  private results: Map<string, { version: number; valid: boolean; duration_ms: number; output_hash: string }[]> = new Map();");
  lines.push("");
  lines.push("  /** Record a prompt execution result */");
  lines.push("  record(promptName: string, version: number, valid: boolean, duration_ms: number, outputHash: string): void {");
  lines.push("    const key = promptName;");
  lines.push("    if (!this.results.has(key)) this.results.set(key, []);");
  lines.push("    this.results.get(key)!.push({ version, valid, duration_ms, output_hash: outputHash });");
  lines.push("    // Keep last 1000 results per prompt");
  lines.push("    const arr = this.results.get(key)!;");
  lines.push("    if (arr.length > 1000) arr.splice(0, arr.length - 1000);");
  lines.push("  }");
  lines.push("");
  lines.push("  /** Compare two versions of a prompt */");
  lines.push("  compare(promptName: string, versionA: number, versionB: number): VersionComparison {");
  lines.push("    const all = this.results.get(promptName) || [];");
  lines.push("    const aResults = all.filter(r => r.version === versionA);");
  lines.push("    const bResults = all.filter(r => r.version === versionB);");
  lines.push("");
  lines.push("    const aPass = aResults.filter(r => r.valid).length;");
  lines.push("    const bPass = bResults.filter(r => r.valid).length;");
  lines.push("    const aAvg = aResults.length > 0 ? aResults.reduce((s, r) => s + r.duration_ms, 0) / aResults.length : 0;");
  lines.push("    const bAvg = bResults.length > 0 ? bResults.reduce((s, r) => s + r.duration_ms, 0) / bResults.length : 0;");
  lines.push("");
  lines.push("    // Agreement: count how many times both versions produced the same output_hash");
  lines.push("    // (only meaningful when both ran on the same input — shadow mode)");
  lines.push("    let agreements = 0;");
  lines.push("    const bHashes = new Set(bResults.map(r => r.output_hash));");
  lines.push("    for (const r of aResults) { if (bHashes.has(r.output_hash)) agreements++; }");
  lines.push("");
  lines.push("    return {");
  lines.push("      prompt_name: promptName,");
  lines.push("      primary_version: versionA,");
  lines.push("      shadow_version: versionB,");
  lines.push("      primary_calls: aResults.length,");
  lines.push("      shadow_calls: bResults.length,");
  lines.push("      primary_pass_rate: aResults.length > 0 ? aPass / aResults.length : 0,");
  lines.push("      shadow_pass_rate: bResults.length > 0 ? bPass / bResults.length : 0,");
  lines.push("      primary_avg_ms: Math.round(aAvg),");
  lines.push("      shadow_avg_ms: Math.round(bAvg),");
  lines.push("      agreement_rate: aResults.length > 0 ? agreements / aResults.length : 0,");
  lines.push("    };");
  lines.push("  }");
  lines.push("");
  lines.push("  /** Get stats for all tracked prompts */");
  lines.push("  stats(): { prompt: string; versions: number[]; total_calls: number; pass_rate: number }[] {");
  lines.push("    const out: { prompt: string; versions: number[]; total_calls: number; pass_rate: number }[] = [];");
  lines.push("    for (const [prompt, results] of this.results) {");
  lines.push("      const versions = [...new Set(results.map(r => r.version))].sort();");
  lines.push("      const passRate = results.filter(r => r.valid).length / results.length;");
  lines.push("      out.push({ prompt, versions, total_calls: results.length, pass_rate: Math.round(passRate * 100) / 100 });");
  lines.push("    }");
  lines.push("    return out;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("/** Singleton version tracker */");
  lines.push("export const versionTracker = new VersionTracker();");
  lines.push("");

  // ─── Shadow runner ───────────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Decide whether to run a shadow test for this request.");
  lines.push(" * Returns true if the random roll is within the traffic percentage.");
  lines.push(" */");
  lines.push("export function shouldRunShadow(trafficPercent: number): boolean {");
  lines.push("  if (trafficPercent <= 0) return false;");
  lines.push("  if (trafficPercent >= 100) return true;");
  lines.push("  return Math.random() * 100 < trafficPercent;");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Run a shadow version in the background (fire-and-forget).");
  lines.push(" * Does NOT block the primary response. Logs result to tracker.");
  lines.push(" */");
  lines.push("export function runShadow<T>(");
  lines.push("  promptName: string,");
  lines.push("  shadowVersion: number,");
  lines.push("  fn: () => Promise<{ data: T; valid: boolean; duration_ms: number }>");
  lines.push("): void {");
  lines.push("  // Fire-and-forget — never blocks the caller");
  lines.push("  fn().then(result => {");
  lines.push("    const hash = simpleHash(JSON.stringify(result.data));");
  lines.push("    versionTracker.record(promptName, shadowVersion, result.valid, result.duration_ms, hash);");
  lines.push("  }).catch(() => {");
  lines.push("    // Shadow failures are silent — they're experiments, not production");
  lines.push("    versionTracker.record(promptName, shadowVersion, false, 0, \"error\");");
  lines.push("  });");
  lines.push("}");
  lines.push("");

  // ─── Hash helper ─────────────────────────────────────────────────────
  lines.push("/** Simple string hash for output comparison (not cryptographic) */");
  lines.push("function simpleHash(str: string): string {");
  lines.push("  let hash = 0;");
  lines.push("  for (let i = 0; i < str.length; i++) {");
  lines.push("    const ch = str.charCodeAt(i);");
  lines.push("    hash = ((hash << 5) - hash) + ch;");
  lines.push("    hash = hash & hash; // Convert to 32bit integer");
  lines.push("  }");
  lines.push("  return hash.toString(36);");
  lines.push("}");
  lines.push("");

  // ─── HTTP endpoint for comparing versions ────────────────────────────
  lines.push("/**");
  lines.push(" * Express route handler: GET /cognition/versions");
  lines.push(" * Returns version stats and comparisons for all tracked prompts.");
  lines.push(" */");
  lines.push("export function versionStatsHandler(_req: any, res: any): void {");
  lines.push("  res.json({ versions: versionTracker.stats() });");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Express route handler: GET /cognition/versions/compare?prompt=X&a=1&b=2");
  lines.push(" * Returns A/B comparison between two versions.");
  lines.push(" */");
  lines.push("export function versionCompareHandler(req: any, res: any): void {");
  lines.push("  const { prompt, a, b } = req.query;");
  lines.push("  if (!prompt || !a || !b) {");
  lines.push("    res.status(400).json({ error: \"Required: ?prompt=name&a=versionA&b=versionB\" });");
  lines.push("    return;");
  lines.push("  }");
  lines.push("  const comparison = versionTracker.compare(prompt, parseInt(a), parseInt(b));");
  lines.push("  res.json(comparison);");
  lines.push("}");
  lines.push("");

  return {
    path: "src/cognition/versioning.ts",
    content: lines.join("\n"),
    language: "typescript",
    source_module: "cognition",
  };
}
