/**
 * MarrowScript Validation Emitter (LLM Harness, Phase 5)
 *
 * Generates src/cognition/validate.ts. The validation runtime is the small,
 * deterministic layer that decides whether a model's parsed output is
 * acceptable. It exposes one function per validate mode:
 *
 *   validateSchemaOnly(value, output_type)         → ValidationReport
 *   validateAstCompiles(value)                     → Promise<ValidationReport>
 *   validateCustom(value, extension_point_name)    → ValidationReport
 *
 * Each returns a structured `{ ok, issues }` shape so the prompt body can
 * branch on a single boolean and still surface issues to logs / repair prompts.
 *
 * Determinism: the schema-shape derivation is content-only (no Date.now() or
 * Math.random()). The ast_compiles helper uses the user's installed
 * `typescript` module via require(), producing the same diagnostics for the
 * same input.
 *
 * Integration:
 *   - emit_cognition.ts:emitPromptCaller calls these helpers in the
 *     validation step instead of inline comments.
 *   - emit_repair.ts (also Phase 5) emits a repair-prompt scaffolding that
 *     wraps the catalog's `repair_with_diff` primitive.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

/**
 * Whether the system has any prompts at all. The validation runtime is only
 * useful when prompts exist, so we skip emission for non-prompt projects.
 */
export function validateNeeded(system: IR.IRSystem): boolean {
  return system.prompts.length > 0;
}

export function emitValidateFile(system: IR.IRSystem): EmittedFile | null {
  if (!validateNeeded(system)) return null;
  return {
    path: "src/cognition/validate.ts",
    content: emitValidateRuntime(),
    language: "typescript",
    source_module: "cognition",
  };
}

function emitValidateRuntime(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 5 — output validation modes.");
  lines.push("//");
  lines.push("// Three validation modes correspond to the prompt's `validate:` clause:");
  lines.push("//   schema_only   structural / type / shape check against the prompt's");
  lines.push("//                 declared `returns:` type, derived at compile time.");
  lines.push("//   ast_compiles  best-effort: runs the user's installed typescript");
  lines.push("//                 module over the output as if it were a .ts source.");
  lines.push("//   custom:<ext>  delegates to the user's extension_point body.");
  lines.push("//");
  lines.push("// Every mode returns ValidationReport, so on_invalid logic can branch on");
  lines.push("// a single boolean and surface specific issues to repair prompts and logs.");
  lines.push("");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("");
  lines.push("export interface ValidationReport {");
  lines.push("  ok: boolean;");
  lines.push("  /** Concrete issues — used to seed repair prompts. */");
  lines.push("  issues: string[];");
  lines.push("}");
  lines.push("");
  // ─── Helpers ─────────────────────────────────────────────────────────────
  lines.push("/** Strip enum-style declared types like `enum<[\"a\",\"b\"]>` and return the literal set, or null. */");
  lines.push("function parseEnumDecl(declared: string): string[] | null {");
  lines.push("  const m = declared.match(/^enum<\\[(.+)\\]>$/);");
  lines.push("  if (!m) return null;");
  lines.push("  // Split on top-level commas. Items are JSON-quoted strings.");
  lines.push("  const items: string[] = [];");
  lines.push("  let buf = \"\";");
  lines.push("  let depth = 0;");
  lines.push("  for (const ch of m[1]) {");
  lines.push("    if (ch === \"[\" || ch === \"{\" || ch === \"(\") depth++;");
  lines.push("    if (ch === \"]\" || ch === \"}\" || ch === \")\") depth--;");
  lines.push("    if (ch === \",\" && depth === 0) { items.push(buf.trim()); buf = \"\"; }");
  lines.push("    else buf += ch;");
  lines.push("  }");
  lines.push("  if (buf.trim()) items.push(buf.trim());");
  lines.push("  // Each item is a JSON-quoted string.");
  lines.push("  return items.map(s => {");
  lines.push("    try { return JSON.parse(s); }");
  lines.push("    catch { return s.replace(/^[\"']|[\"']$/g, \"\"); }");
  lines.push("  });");
  lines.push("}");
  lines.push("");
  lines.push("/** True when the declared type is a recognised primitive. */");
  lines.push("function declaredPrimitiveCheck(declared: string, value: unknown): string | null {");
  lines.push("  switch (declared) {");
  lines.push("    case \"string\":");
  lines.push("      if (typeof value !== \"string\") return `expected string, got ${typeof value}`;");
  lines.push("      return value.length === 0 ? \"empty string\" : null;");
  lines.push("    case \"int\": case \"uint\": case \"float\":");
  lines.push("      if (typeof value !== \"number\" || !Number.isFinite(value)) return `expected number, got ${typeof value}`;");
  lines.push("      if (declared === \"uint\" && value < 0) return \"expected uint, got negative\";");
  lines.push("      if (declared === \"int\" && !Number.isInteger(value)) return \"expected int, got non-integer\";");
  lines.push("      return null;");
  lines.push("    case \"bool\":");
  lines.push("      return typeof value === \"boolean\" ? null : `expected bool, got ${typeof value}`;");
  lines.push("    case \"json\":");
  lines.push("      return null;");
  lines.push("    default:");
  lines.push("      return null;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // ─── schema_only ─────────────────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Validate a parsed model output against the prompt's declared return type.");
  lines.push(" * `outputType` is the IR-serialised type expression, e.g. \"string\",");
  lines.push(" * \"json\", `enum<[\"a\",\"b\"]>`, \"File\", or `list<File>`. We deliberately keep");
  lines.push(" * the surface narrow: we recognise primitives, list<T>, enum literals,");
  lines.push(" * and the built-in File record. Anything else falls through to a no-op");
  lines.push(" * accept so users can specify rich return shapes via a custom validator.");
  lines.push(" */");
  lines.push("export function validateSchemaOnly(value: unknown, outputType: string): ValidationReport {");
  lines.push("  const issues: string[] = [];");
  lines.push("  // File: { path: string, content: string, kind?: string }");
  lines.push("  if (outputType === \"File\") {");
  lines.push("    fileShapeIssues(value, issues, \"\");");
  lines.push("    return finalize(issues, \"file\");");
  lines.push("  }");
  lines.push("  // list<File>");
  lines.push("  if (/^list<\\s*File\\s*>$/.test(outputType)) {");
  lines.push("    if (!Array.isArray(value)) {");
  lines.push("      issues.push(`expected list<File>, got ${typeof value}`);");
  lines.push("      return finalize(issues, \"files\");");
  lines.push("    }");
  lines.push("    if (value.length === 0) {");
  lines.push("      issues.push(\"expected at least one File, got empty array\");");
  lines.push("      return finalize(issues, \"files\");");
  lines.push("    }");
  lines.push("    // Defensive: reject duplicate paths early — the consumer will fail later anyway.");
  lines.push("    const seen = new Set<string>();");
  lines.push("    for (let i = 0; i < value.length; i++) {");
  lines.push("      fileShapeIssues(value[i], issues, `file[${i}]: `);");
  lines.push("      const f = value[i] as { path?: unknown };");
  lines.push("      if (typeof f?.path === \"string\") {");
  lines.push("        if (seen.has(f.path)) issues.push(`file[${i}]: duplicate path \"${f.path}\"`);");
  lines.push("        seen.add(f.path);");
  lines.push("      }");
  lines.push("    }");
  lines.push("    return finalize(issues, \"files\");");
  lines.push("  }");
  lines.push("  // Enum: literal set of allowed values.");
  lines.push("  const enumValues = parseEnumDecl(outputType);");
  lines.push("  if (enumValues) {");
  lines.push("    if (typeof value !== \"string\") {");
  lines.push("      issues.push(`expected one of [${enumValues.join(\", \")}], got ${typeof value}`);");
  lines.push("    } else if (!enumValues.includes(value)) {");
  lines.push("      issues.push(`value \"${value.slice(0, 64)}\" is not in [${enumValues.join(\", \")}]`);");
  lines.push("    }");
  lines.push("    return finalize(issues, \"enum\");");
  lines.push("  }");
  lines.push("  // list<T>");
  lines.push("  const listMatch = outputType.match(/^list<(.+)>$/);");
  lines.push("  if (listMatch) {");
  lines.push("    if (!Array.isArray(value)) {");
  lines.push("      issues.push(`expected list<${listMatch[1]}>, got ${typeof value}`);");
  lines.push("    } else {");
  lines.push("      const inner = listMatch[1];");
  lines.push("      for (let i = 0; i < value.length; i++) {");
  lines.push("        const issue = declaredPrimitiveCheck(inner, value[i]);");
  lines.push("        if (issue) issues.push(`item[${i}]: ${issue}`);");
  lines.push("      }");
  lines.push("    }");
  lines.push("    return finalize(issues, \"list\");");
  lines.push("  }");
  lines.push("  // Primitive (or json — accepts anything).");
  lines.push("  const issue = declaredPrimitiveCheck(outputType, value);");
  lines.push("  if (issue) issues.push(issue);");
  lines.push("  return finalize(issues, \"primitive\");");
  lines.push("}");
  lines.push("");
  // Helper: validate a single File record's shape.
  lines.push("/** Push issues for a value that should be a File record. Empty string");
  lines.push(" *  prefix is fine for the singular File path; pass `file[N]: ` for list. */");
  lines.push("function fileShapeIssues(value: unknown, issues: string[], prefix: string): void {");
  lines.push("  if (!value || typeof value !== \"object\") {");
  lines.push("    issues.push(`${prefix}expected File record, got ${typeof value}`);");
  lines.push("    return;");
  lines.push("  }");
  lines.push("  const v = value as { path?: unknown; content?: unknown; kind?: unknown };");
  lines.push("  if (typeof v.path !== \"string\" || v.path.length === 0) {");
  lines.push("    issues.push(`${prefix}File.path must be a non-empty string`);");
  lines.push("  } else if (v.path.includes(\"..\") || v.path.startsWith(\"/\") || /^[A-Za-z]:/.test(v.path)) {");
  lines.push("    // Defensive: reject path-traversal and absolute paths so the");
  lines.push("    // generated artifact can be safely written to a sandbox dir.");
  lines.push("    issues.push(`${prefix}File.path must be a relative path without \"..\" segments`);");
  lines.push("  }");
  lines.push("  if (typeof v.content !== \"string\") {");
  lines.push("    issues.push(`${prefix}File.content must be a string`);");
  lines.push("  } else if (v.content.length === 0) {");
  lines.push("    issues.push(`${prefix}File.content is empty`);");
  lines.push("  }");
  lines.push("  if (v.kind !== undefined && typeof v.kind !== \"string\") {");
  lines.push("    issues.push(`${prefix}File.kind must be a string when present`);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("function finalize(issues: string[], kind: string): ValidationReport {");
  lines.push("  if (issues.length > 0) {");
  lines.push("    counter(\"cognition.validate.failed\", { mode: \"schema_only\", kind });");
  lines.push("  } else {");
  lines.push("    counter(\"cognition.validate.passed\", { mode: \"schema_only\", kind });");
  lines.push("  }");
  lines.push("  return { ok: issues.length === 0, issues };");
  lines.push("}");
  lines.push("");
  // ─── ast_compiles ────────────────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Best-effort syntactic + semantic validation of TypeScript code returned");
  lines.push(" * by the model. Loads the user's installed `typescript` module on demand,");
  lines.push(" * runs `createSourceFile` for parse diagnostics, then `createProgram` with");
  lines.push(" * an in-memory compiler host for both syntactic and semantic diagnostics.");
  lines.push(" *");
  lines.push(" * What gets flagged as a failure:");
  lines.push(" *   - any parse error (unbalanced braces, malformed expression, etc.)");
  lines.push(" *   - undeclared names (e.g. `AiderApiConfig` referenced but never declared)");
  lines.push(" *   - imports from packages the model hallucinated (filtered out by default,");
  lines.push(" *     opt-in via LLM_VALIDATE_STRICT_IMPORTS=1 since real code legitimately");
  lines.push(" *     imports from packages tsc can't see in noResolve mode)");
  lines.push(" *   - duplicate identifiers, type-only constructs used as values");
  lines.push(" *");
  lines.push(" * What gets quietly tolerated:");
  lines.push(" *   - missing module declarations (TS2307 'Cannot find module …') —");
  lines.push(" *     unavoidable when the LLM imports a real npm package the validator");
  lines.push(" *     sandbox doesn't know about. The repair prompt still gets the issue");
  lines.push(" *     summary so it can swap to a known-good package if needed.");
  lines.push(" *   - unused-locals / unused-params (TS6133) — too noisy for a one-pass");
  lines.push(" *     model that often emits scaffold code with placeholders.");
  lines.push(" *");
  lines.push(" * If `typescript` isn't installed, returns ok:true with a 'skipped' note.");
  lines.push(" */");
  lines.push("export async function validateAstCompiles(value: unknown): Promise<ValidationReport> {");
  // Phase 14: dispatch on shape. The original contract was "value is the
  // TypeScript source as a string". We extend it so a single File record or
  // a list of File records also works — each File's content is validated
  // independently and issues get aggregated with file path prefixes.
  lines.push("  // Phase 14: File / list<File> dispatch. Single File: validate its");
  lines.push("  // .content. List of Files: validate each, prefix issues by path, OR");
  lines.push("  // together (one bad file fails the whole list).");
  lines.push("  if (Array.isArray(value)) {");
  lines.push("    return validateFileList(value);");
  lines.push("  }");
  lines.push("  if (value && typeof value === \"object\" && \"path\" in (value as object) && \"content\" in (value as object)) {");
  lines.push("    const f = value as { path: string; content: unknown };");
  lines.push("    return validateSingleFile(f);");
  lines.push("  }");
  lines.push("  if (typeof value !== \"string\" || value.trim().length === 0) {");
  lines.push("    counter(\"cognition.validate.failed\", { mode: \"ast_compiles\", kind: \"empty\" });");
  lines.push("    return { ok: false, issues: [\"output must be a non-empty TypeScript string\"] };");
  lines.push("  }");
  lines.push("  return validateTypeScriptString(value);");
  lines.push("}");
  lines.push("");
  // Helper: dispatch a single File record to the underlying TS validator,
  // attaching the file path to any reported issues.
  lines.push("async function validateSingleFile(f: { path: string; content: unknown }): Promise<ValidationReport> {");
  lines.push("  if (typeof f.content !== \"string\" || f.content.trim().length === 0) {");
  lines.push("    counter(\"cognition.validate.failed\", { mode: \"ast_compiles\", kind: \"empty_file\" });");
  lines.push("    return { ok: false, issues: [`${f.path}: content must be a non-empty TypeScript string`] };");
  lines.push("  }");
  lines.push("  const inner = await validateTypeScriptString(f.content);");
  lines.push("  if (inner.ok) return inner;");
  lines.push("  return { ok: false, issues: inner.issues.map(i => `${f.path}: ${i}`) };");
  lines.push("}");
  lines.push("");
  // Helper: validate a list of File records. Each file is validated in
  // isolation; an empty list is its own failure mode (the model produced
  // a valid array shape but no actual files).
  lines.push("async function validateFileList(files: unknown[]): Promise<ValidationReport> {");
  lines.push("  if (files.length === 0) {");
  lines.push("    counter(\"cognition.validate.failed\", { mode: \"ast_compiles\", kind: \"empty_list\" });");
  lines.push("    return { ok: false, issues: [\"file list is empty\"] };");
  lines.push("  }");
  lines.push("  const aggregated: string[] = [];");
  lines.push("  for (let i = 0; i < files.length; i++) {");
  lines.push("    const f = files[i] as { path?: unknown; content?: unknown };");
  lines.push("    if (!f || typeof f !== \"object\" || typeof f.path !== \"string\") {");
  lines.push("      aggregated.push(`file[${i}]: invalid shape; expected { path, content }`);");
  lines.push("      continue;");
  lines.push("    }");
  lines.push("    // Skip non-TypeScript files (markdown, json, yaml). Their content");
  lines.push("    // shape was already checked by validateSchemaOnly; we only run the");
  lines.push("    // TS compiler over .ts/.tsx files. The .kind hint is honored when");
  lines.push("    // present, otherwise we infer from the path extension.");
  lines.push("    const path = f.path;");
  lines.push("    const isTs = /\\.(ts|tsx|cts|mts)$/i.test(path);");
  lines.push("    if (!isTs) continue;");
  lines.push("    const r = await validateSingleFile({ path, content: f.content });");
  lines.push("    if (!r.ok) aggregated.push(...r.issues);");
  lines.push("  }");
  lines.push("  if (aggregated.length > 0) {");
  lines.push("    counter(\"cognition.validate.failed\", { mode: \"ast_compiles\", kind: \"file_list\" });");
  lines.push("  } else {");
  lines.push("    counter(\"cognition.validate.passed\", { mode: \"ast_compiles\", kind: \"file_list\" });");
  lines.push("  }");
  lines.push("  return { ok: aggregated.length === 0, issues: aggregated };");
  lines.push("}");
  lines.push("");
  // The original ast_compiles body, refactored as a helper that operates on
  // a string. Public surface is preserved through the dispatch above.
  lines.push("async function validateTypeScriptString(value: string): Promise<ValidationReport> {");
  lines.push("  // Models often emit multi-file artifacts as one block with `// path:`");
  lines.push("  // headers between sections. tsc parses that as a single source file and");
  lines.push("  // chokes on the file-path comments. Rather than fail the whole call we");
  lines.push("  // pick the LARGEST contiguous section between such headers and validate");
  lines.push("  // just that — the model can return a multi-file plan as long as at least");
  lines.push("  // one section is internally consistent.");
  lines.push("  //");
  lines.push("  // Models also commonly wrap their output in markdown code fences. We");
  lines.push("  // extract the fenced block first when present so the surrounding prose");
  lines.push("  // (which is never valid TS) doesn't drag down the validator. If multiple");
  lines.push("  // fences exist, we pick the largest typescript-tagged one.");
  lines.push("  const candidate = pickLargestTsSection(extractFencedTypeScript(value));");
  lines.push("  let ts: typeof import(\"typescript\") | null = null;");
  lines.push("  try {");
  lines.push("    // eslint-disable-next-line @typescript-eslint/no-require-imports");
  lines.push("    ts = require(\"typescript\") as typeof import(\"typescript\");");
  lines.push("  } catch {");
  lines.push("    counter(\"cognition.validate.skipped\", { mode: \"ast_compiles\" });");
  lines.push("    return { ok: true, issues: [\"typescript module not installed — ast_compiles skipped\"] };");
  lines.push("  }");
  lines.push("");
  lines.push("  const sf = ts.createSourceFile(\"__model_output.ts\", candidate, ts.ScriptTarget.Latest, true);");
  lines.push("  const issues: string[] = [];");
  lines.push("");
  lines.push("  // Parse diagnostics — unrecoverable syntax errors. tsc's API is loose");
  lines.push("  // with naming; cast for the diagnostic array we care about.");
  lines.push("  const parseDiags = (sf as unknown as { parseDiagnostics?: ReadonlyArray<import(\"typescript\").Diagnostic> }).parseDiagnostics ?? [];");
  lines.push("  for (const d of parseDiags) {");
  lines.push("    issues.push(ts.flattenDiagnosticMessageText(d.messageText, \"\\n\"));");
  lines.push("  }");
  lines.push("");
  lines.push("  if (issues.length === 0) {");
  lines.push("    // Run a real program over the source so we get semantic diagnostics");
  lines.push("    // (undeclared names, type-only-as-value, duplicate identifiers, etc.).");
  lines.push("    // We keep noResolve:true so missing-module errors are recoverable; we");
  lines.push("    // filter those out below and only fail on real bugs in the user's code.");
  lines.push("    try {");
  lines.push("      const compilerOptions: import(\"typescript\").CompilerOptions = {");
  lines.push("        target: ts.ScriptTarget.ES2022,");
  lines.push("        module: ts.ModuleKind.CommonJS,");
  lines.push("        strict: false,");
  lines.push("        noResolve: true,");
  lines.push("        skipLibCheck: true,");
  lines.push("        skipDefaultLibCheck: true,");
  lines.push("        noEmit: true,");
  lines.push("        allowJs: true,");
  lines.push("        // Don't trip on incidental noise from one-pass model output:");
  lines.push("        noUnusedLocals: false,");
  lines.push("        noUnusedParameters: false,");
  lines.push("        noImplicitAny: false,");
  lines.push("      };");
  lines.push("      // Synthesise a tiny lib.d.ts so global names like `console`, `Promise`,");
  lines.push("      // `process`, `Map`, `Array`, etc. resolve cleanly. Without this every");
  lines.push("      // builtin reference becomes a TS2304 false positive.");
  lines.push("      const stubLib = [");
  lines.push("        // Common globals as values.");
  lines.push("        \"declare var console: { log(...a: unknown[]): void; warn(...a: unknown[]): void; error(...a: unknown[]): void; info(...a: unknown[]): void; debug(...a: unknown[]): void };\",");
  lines.push("        \"declare var process: { cwd(): string; env: Record<string, string | undefined>; argv: string[]; exit(code?: number): never };\",");
  lines.push("        \"declare var Buffer: { from(s: string, e?: string): { toString(e?: string): string } };\",");
  lines.push("        \"declare var setTimeout: (cb: () => void, ms: number) => unknown;\",");
  lines.push("        \"declare var clearTimeout: (h: unknown) => void;\",");
  lines.push("        \"declare var setInterval: (cb: () => void, ms: number) => unknown;\",");
  lines.push("        \"declare var clearInterval: (h: unknown) => void;\",");
  lines.push("        \"declare var require: (m: string) => unknown;\",");
  lines.push("        \"declare var module: unknown; declare var exports: unknown; declare var __dirname: string; declare var __filename: string;\",");
  lines.push("        \"declare var globalThis: { fetch: (url: string, init?: unknown) => Promise<Response> } & Record<string, unknown>;\",");
  lines.push("        \"declare var Number: { isInteger(v: unknown): boolean; isFinite(v: unknown): boolean; parseFloat(s: string): number; parseInt(s: string, r?: number): number };\",");
  lines.push("        \"declare var Math: { floor(n: number): number; ceil(n: number): number; round(n: number): number; min(...n: number[]): number; max(...n: number[]): number; abs(n: number): number; pow(b: number, e: number): number; random(): number };\",");
  lines.push("        \"declare var JSON: { parse(s: string): unknown; stringify(v: unknown, r?: unknown, s?: unknown): string };\",");
  lines.push("        \"declare var Symbol: { for(s: string): symbol; iterator: symbol };\",");
  lines.push("        // Common types AND values for built-ins that are also referenced as");
  lines.push("        // generic types (e.g. `Map<string, T>`, `Promise<unknown>`). Without");
  lines.push("        // these the validator flags every typed builtin as TS2749/TS2583.");
  lines.push("        \"interface Iterator<T> { next(): { value: T; done: boolean } }\",");
  lines.push("        \"interface Iterable<T> { [Symbol.iterator](): Iterator<T> }\",");
  lines.push("        \"interface ArrayLike<T> { readonly length: number; readonly [n: number]: T }\",");
  lines.push("        \"interface Map<K, V> { get(k: K): V | undefined; set(k: K, v: V): this; has(k: K): boolean; delete(k: K): boolean; clear(): void; size: number; keys(): Iterator<K>; values(): Iterator<V>; entries(): Iterator<[K, V]>; forEach(cb: (v: V, k: K) => void): void }\",");
  lines.push("        \"interface MapConstructor { new <K, V>(entries?: Iterable<[K, V]>): Map<K, V> }\",");
  lines.push("        \"declare var Map: MapConstructor;\",");
  lines.push("        \"interface Set<T> { add(v: T): this; has(v: T): boolean; delete(v: T): boolean; clear(): void; size: number; values(): Iterator<T>; forEach(cb: (v: T) => void): void }\",");
  lines.push("        \"interface SetConstructor { new <T>(values?: Iterable<T>): Set<T> }\",");
  lines.push("        \"declare var Set: SetConstructor;\",");
  lines.push("        \"interface Promise<T> { then<U>(onFulfilled?: (v: T) => U | Promise<U>, onRejected?: (e: unknown) => U | Promise<U>): Promise<U>; catch<U>(onRejected: (e: unknown) => U | Promise<U>): Promise<U>; finally(cb: () => void): Promise<T> }\",");
  lines.push("        \"interface PromiseConstructor { new <T>(executor: (resolve: (v: T) => void, reject: (e: unknown) => void) => void): Promise<T>; all<T>(p: Promise<T>[]): Promise<T[]>; resolve<T>(v: T): Promise<T>; reject(e: unknown): Promise<never> }\",");
  lines.push("        \"declare var Promise: PromiseConstructor;\",");
  lines.push("        \"interface Array<T> { length: number; [n: number]: T; push(...items: T[]): number; pop(): T | undefined; map<U>(cb: (v: T, i: number) => U): U[]; filter(cb: (v: T, i: number) => boolean): T[]; forEach(cb: (v: T, i: number) => void): void; slice(s?: number, e?: number): T[]; join(sep?: string): string; includes(v: T): boolean; find(cb: (v: T) => boolean): T | undefined; indexOf(v: T): number; concat(...items: T[]): T[]; reverse(): T[]; sort(cb?: (a: T, b: T) => number): T[]; some(cb: (v: T) => boolean): boolean; every(cb: (v: T) => boolean): boolean; reduce<U>(cb: (acc: U, v: T) => U, init: U): U; flat<U>(): U[] }\",");
  lines.push("        \"interface ArrayConstructor { new <T>(length: number): T[]; new <T>(...items: T[]): T[]; isArray(v: unknown): boolean; from<T>(v: Iterable<T> | ArrayLike<T>): T[] }\",");
  lines.push("        \"declare var Array: ArrayConstructor;\",");
  lines.push("        \"interface String { length: number; [n: number]: string; charAt(i: number): string; charCodeAt(i: number): number; concat(...s: string[]): string; includes(s: string): boolean; indexOf(s: string): number; lastIndexOf(s: string): number; match(re: unknown): unknown; replace(re: unknown, r: string): string; slice(s?: number, e?: number): string; split(sep?: string | unknown): string[]; substring(s: number, e?: number): string; toLowerCase(): string; toUpperCase(): string; trim(): string; startsWith(s: string): boolean; endsWith(s: string): boolean; repeat(n: number): string; padStart(n: number, p?: string): string; padEnd(n: number, p?: string): string; normalize(): string }\",");
  lines.push("        \"interface StringConstructor { (v: unknown): string; new (v: unknown): String; fromCharCode(...codes: number[]): string }\",");
  lines.push("        \"declare var String: StringConstructor;\",");
  lines.push("        \"interface Date { toISOString(): string; getTime(): number; toString(): string }\",");
  lines.push("        \"interface DateConstructor { new (): Date; new (ms: number): Date; new (s: string): Date; now(): number }\",");
  lines.push("        \"declare var Date: DateConstructor;\",");
  lines.push("        \"interface ObjectConstructor { keys(o: object): string[]; values(o: object): unknown[]; entries(o: object): [string, unknown][]; assign<T>(t: T, ...s: unknown[]): T; freeze<T>(o: T): T; create(proto: object | null, props?: Record<string, unknown>): object }\",");
  lines.push("        \"declare var Object: ObjectConstructor;\",");
  lines.push("        \"interface Error { message: string; stack?: string; name: string }\",");
  lines.push("        \"interface ErrorConstructor { new (m?: string): Error; (m?: string): Error; captureStackTrace?(e: unknown, c?: unknown): void }\",");
  lines.push("        \"declare var Error: ErrorConstructor;\",");
  lines.push("        \"interface RegExp { test(s: string): boolean; exec(s: string): string[] | null; source: string; flags: string }\",");
  lines.push("        \"interface RegExpConstructor { new (p: string, f?: string): RegExp; (p: string, f?: string): RegExp }\",");
  lines.push("        \"declare var RegExp: RegExpConstructor;\",");
  lines.push("        \"type Record<K extends string | number | symbol, V> = { [P in K]: V };\",");
  lines.push("        \"type Partial<T> = { [P in keyof T]?: T[P] };\",");
  lines.push("        \"type Required<T> = { [P in keyof T]-?: T[P] };\",");
  lines.push("        \"type Readonly<T> = { readonly [P in keyof T]: T[P] };\",");
  lines.push("        \"type Pick<T, K extends keyof T> = { [P in K]: T[P] };\",");
  lines.push("        \"type Omit<T, K extends string | number | symbol> = { [P in keyof T as P extends K ? never : P]: T[P] };\",");
  lines.push("        \"type Awaited<T> = T extends Promise<infer U> ? U : T;\",");
  lines.push("        \"type ReturnType<T extends (...a: unknown[]) => unknown> = T extends (...a: unknown[]) => infer R ? R : unknown;\",");
  lines.push("        \"type Parameters<T extends (...a: unknown[]) => unknown> = T extends (...a: infer P) => unknown ? P : never;\",");
  // ── DOM / fetch types — Node 18+ has these as globals. Without them every
  // response.ok / response.json() / response.status access is flagged as
  // TS2339 'Property does not exist on type unknown'.
  lines.push("        \"interface Headers { get(name: string): string | null; has(name: string): boolean; set(name: string, value: string): void; append(name: string, value: string): void; delete(name: string): void }\",");
  lines.push("        \"interface Response { readonly ok: boolean; readonly status: number; readonly statusText: string; readonly headers: Headers; readonly url: string; text(): Promise<string>; json(): Promise<unknown>; arrayBuffer(): Promise<ArrayBuffer>; clone(): Response }\",");
  lines.push("        \"interface RequestInit { method?: string; headers?: Headers | Record<string, string>; body?: string | unknown; signal?: unknown; credentials?: 'omit' | 'include' | 'same-origin'; mode?: 'cors' | 'no-cors' | 'same-origin'; redirect?: 'follow' | 'error' | 'manual' }\",");
  lines.push("        \"declare var fetch: (url: string, init?: RequestInit) => Promise<Response>;\",");
  lines.push("        \"interface ArrayBuffer { readonly byteLength: number; slice(begin: number, end?: number): ArrayBuffer }\",");
  lines.push("        \"declare var ArrayBuffer: { new (length: number): ArrayBuffer };\",");
  // ── Node builtin module declarations. The LLM commonly imports these
  // (fs, path, crypto, child_process, http, https, os, url, events, stream).
  // Ambient module declarations let `import { writeFileSync } from 'fs'`
  // validate without resolving Node's @types/node.
  lines.push("        \"declare module 'fs' { export function readFileSync(p: string, e?: string): string; export function writeFileSync(p: string, d: string | unknown, e?: string | unknown): void; export function existsSync(p: string): boolean; export function mkdirSync(p: string, opts?: { recursive?: boolean }): void; export function readdirSync(p: string): string[]; export function statSync(p: string): { isDirectory(): boolean; isFile(): boolean; size: number }; export function unlinkSync(p: string): void; export const promises: { readFile(p: string, e?: string): Promise<string>; writeFile(p: string, d: string | unknown, e?: string): Promise<void>; mkdir(p: string, opts?: { recursive?: boolean }): Promise<void> } }\",");
  lines.push("        \"declare module 'path' { export function join(...parts: string[]): string; export function resolve(...parts: string[]): string; export function basename(p: string, ext?: string): string; export function dirname(p: string): string; export function extname(p: string): string; export function relative(from: string, to: string): string; export const sep: string; export const delimiter: string }\",");
  lines.push("        \"declare module 'crypto' { export function randomUUID(): string; export function randomBytes(n: number): { toString(e?: string): string }; export function createHash(alg: string): { update(d: string | unknown): { digest(e?: string): string } }; export function createHmac(alg: string, key: string): { update(d: string): { digest(e?: string): string } } }\",");
  lines.push("        \"declare module 'child_process' { export function exec(cmd: string, cb: (err: Error | null, stdout: string, stderr: string) => void): unknown; export function execSync(cmd: string, opts?: { encoding?: string; cwd?: string }): string; export function execFile(cmd: string, args: string[], cb: (err: Error | null, stdout: string, stderr: string) => void): unknown; export function spawn(cmd: string, args: string[], opts?: { cwd?: string }): unknown }\",");
  lines.push("        \"declare module 'http' { export function createServer(handler: (req: unknown, res: unknown) => void): { listen(port: number, cb?: () => void): void; close(cb?: () => void): void }; export function request(opts: unknown, cb: (res: unknown) => void): unknown }\",");
  lines.push("        \"declare module 'https' { export function request(opts: unknown, cb: (res: unknown) => void): unknown; export function get(url: string, cb: (res: unknown) => void): unknown }\",");
  lines.push("        \"declare module 'os' { export function platform(): string; export function arch(): string; export function tmpdir(): string; export function homedir(): string; export function cpus(): unknown[]; export function totalmem(): number; export function freemem(): number }\",");
  lines.push("        \"declare module 'url' { export class URL { constructor(input: string, base?: string); href: string; origin: string; protocol: string; host: string; pathname: string; search: string; searchParams: { get(k: string): string | null; set(k: string, v: string): void } } }\",");
  lines.push("        \"declare module 'events' { export class EventEmitter { on(event: string, cb: (...a: unknown[]) => void): this; off(event: string, cb: (...a: unknown[]) => void): this; emit(event: string, ...a: unknown[]): boolean; once(event: string, cb: (...a: unknown[]) => void): this; removeAllListeners(event?: string): this } }\",");
  lines.push("        \"declare module 'stream' { export class Readable { read(size?: number): unknown; pipe<T>(dest: T): T; on(event: string, cb: (...a: unknown[]) => void): this } export class Writable { write(chunk: unknown): boolean; end(chunk?: unknown): void; on(event: string, cb: (...a: unknown[]) => void): this } }\",");
  lines.push("        \"declare module 'util' { export function promisify<T>(fn: T): T; export function inspect(v: unknown, opts?: unknown): string; export function format(...a: unknown[]): string }\",");
  lines.push("      ].join(\"\\n\");");
  lines.push("      const stubSf = ts.createSourceFile(\"__lib.d.ts\", stubLib, ts.ScriptTarget.ES2022, true);");
  lines.push("      const host: import(\"typescript\").CompilerHost = {");
  lines.push("        fileExists: (p) => p === \"__model_output.ts\" || p === \"__lib.d.ts\",");
  lines.push("        readFile: (p) => p === \"__model_output.ts\" ? candidate : p === \"__lib.d.ts\" ? stubLib : undefined,");
  lines.push("        writeFile: () => {},");
  lines.push("        getSourceFile: (p) => p === \"__model_output.ts\" ? sf : p === \"__lib.d.ts\" ? stubSf : undefined,");
  lines.push("        getDefaultLibFileName: () => \"__lib.d.ts\",");
  lines.push("        useCaseSensitiveFileNames: () => true,");
  lines.push("        getCanonicalFileName: (p) => p,");
  lines.push("        getCurrentDirectory: () => \"\",");
  lines.push("        getNewLine: () => \"\\n\",");
  lines.push("      };");
  lines.push("      const program = ts.createProgram([\"__model_output.ts\", \"__lib.d.ts\"], compilerOptions, host);");
  lines.push("");
  lines.push("      // Pull syntactic + semantic diagnostics. Filter strategy:");
  lines.push("      //   TS2307 (Cannot find module 'X') — missing-module noise, kept as");
  lines.push("      //     a *warning* note but does NOT fail validation. Real npm packages");
  lines.push("      //     will always trip this in noResolve mode.");
  lines.push("      //   TS6133 (declared but never read) — too noisy for one-pass output.");
  lines.push("      //   Everything else — counts as a real bug.");
  lines.push("      const STRICT_IMPORTS = process.env.LLM_VALIDATE_STRICT_IMPORTS === \"1\";");
  lines.push("      const SOFT_CODES = new Set<number>(STRICT_IMPORTS ? [6133] : [2307, 2305, 6133, 2792]);");
  lines.push("      const diags = [");
  lines.push("        ...program.getSyntacticDiagnostics(sf),");
  lines.push("        ...program.getSemanticDiagnostics(sf),");
  lines.push("      ];");
  lines.push("      const softNotes: string[] = [];");
  lines.push("      for (const d of diags) {");
  lines.push("        const msg = ts.flattenDiagnosticMessageText(d.messageText, \"\\n\");");
  lines.push("        const formatted = `TS${d.code}: ${msg}`;");
  lines.push("        if (SOFT_CODES.has(d.code)) {");
  lines.push("          softNotes.push(formatted);");
  lines.push("        } else {");
  lines.push("          issues.push(formatted);");
  lines.push("        }");
  lines.push("      }");
  lines.push("      if (softNotes.length > 0) {");
  lines.push("        logger.info(\"validate_ast_soft_notes\", { event: \"validate\", status: \"success\", metadata: { count: softNotes.length, sample: softNotes.slice(0, 3) } });");
  lines.push("      }");
  lines.push("    } catch (e) {");
  lines.push("      const msg = e instanceof Error ? e.message : String(e);");
  lines.push("      logger.warn(\"validate_ast_compile_failed\", { event: \"validate\", status: \"rejected\", metadata: { error: msg.slice(0, 256) } });");
  lines.push("      issues.push(`validator threw: ${msg.slice(0, 200)}`);");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  if (issues.length > 0) counter(\"cognition.validate.failed\", { mode: \"ast_compiles\", kind: \"diag\" });");
  lines.push("  else counter(\"cognition.validate.passed\", { mode: \"ast_compiles\", kind: \"clean\" });");
  lines.push("  return { ok: issues.length === 0, issues };");
  lines.push("}");
  lines.push("");
  // Helper: tolerate multi-file artifacts by picking the largest contiguous
  // section. Splits on lines that look like file-path headers (// path/to/x.ts,
  // // src/foo.ts, /* === src/bar.ts === */, or `// File: …`).
  lines.push("/**");
  lines.push(" * Pick the largest contiguous TypeScript section out of a multi-file");
  lines.push(" * artifact. Models often emit several files in one fenced block separated");
  lines.push(" * by file-path comments; rather than fail-closed on the first inter-file");
  lines.push(" * comment, we extract the biggest section and validate just that. If the");
  lines.push(" * input has no recognisable headers, the whole string is returned.");
  lines.push(" */");
  lines.push("function pickLargestTsSection(value: string): string {");
  lines.push("  // Match lines that look like a file-path header. Recognises:");
  lines.push("  //   // src/foo.ts");
  lines.push("  //   // path: src/foo.ts");
  lines.push("  //   // File: src/foo.ts");
  lines.push("  //   // === src/foo.ts ===");
  lines.push("  //   /* src/foo.ts */");
  lines.push("  // Anything else is treated as part of the current section.");
  lines.push("  const headerRe = /^\\s*(?:\\/\\/|\\/\\*)\\s*(?:File:|path:|=+)?\\s*[a-zA-Z0-9_\\-./]+\\.(?:ts|tsx|js|jsx|mts|cts)\\s*(?:=+\\s*)?(?:\\*\\/)?\\s*$/;");
  lines.push("  const lines = value.split(/\\r?\\n/);");
  lines.push("  const sections: string[] = [];");
  lines.push("  let current: string[] = [];");
  lines.push("  for (const line of lines) {");
  lines.push("    if (headerRe.test(line)) {");
  lines.push("      if (current.length > 0) sections.push(current.join(\"\\n\"));");
  lines.push("      current = [];");
  lines.push("    } else {");
  lines.push("      current.push(line);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  if (current.length > 0) sections.push(current.join(\"\\n\"));");
  lines.push("  if (sections.length <= 1) return value;");
  lines.push("  // Largest by character count. Stable on ties: first occurrence wins.");
  lines.push("  let best = sections[0];");
  lines.push("  for (let i = 1; i < sections.length; i++) {");
  lines.push("    if (sections[i].length > best.length) best = sections[i];");
  lines.push("  }");
  lines.push("  return best;");
  lines.push("}");
  lines.push("");
  // ── Helper: pull the TS code out of markdown fences ──────────────────────
  lines.push("/**");
  lines.push(" * Extract the largest TypeScript-tagged code fence from a model's response.");
  lines.push(" * Models commonly wrap their output in ```typescript ... ``` (sometimes ```ts");
  lines.push(" * or ```tsx). When that's present, the prose around the fence is never valid");
  lines.push(" * TS — keeping it in the validator would just produce noise. If no fenced");
  lines.push(" * block is found, the entire input is returned (the legacy behaviour).");
  lines.push(" *");
  lines.push(" * Picks the LARGEST fenced block when multiple exist. Untagged ``` fences are");
  lines.push(" * also accepted as a fallback so the validator still works on output that");
  lines.push(" * forgot the language tag.");
  lines.push(" */");
  lines.push("function extractFencedTypeScript(value: string): string {");
  lines.push("  // Match ```<lang?>\\n ... \\n``` blocks. Lang is optional and case-insensitive.");
  lines.push("  // We use a non-greedy `[\\s\\S]*?` so consecutive fences don't merge.");
  lines.push("  const fenceRe = /```([a-zA-Z]*)\\s*\\n([\\s\\S]*?)\\n```/g;");
  lines.push("  const tsFences: string[] = [];");
  lines.push("  const untaggedFences: string[] = [];");
  lines.push("  let m: RegExpExecArray | null;");
  lines.push("  while ((m = fenceRe.exec(value)) !== null) {");
  lines.push("    const lang = (m[1] || \"\").toLowerCase();");
  lines.push("    const body = m[2];");
  lines.push("    if (lang === \"typescript\" || lang === \"ts\" || lang === \"tsx\") {");
  lines.push("      tsFences.push(body);");
  lines.push("    } else if (lang === \"\") {");
  lines.push("      untaggedFences.push(body);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  // Prefer typescript-tagged fences. Fall back to the largest untagged one");
  lines.push("  // since some models drop the language tag. If neither, return the whole");
  lines.push("  // input — the legacy behaviour.");
  lines.push("  const pool = tsFences.length > 0 ? tsFences : untaggedFences;");
  lines.push("  if (pool.length === 0) return value;");
  lines.push("  let best = pool[0];");
  lines.push("  for (let i = 1; i < pool.length; i++) {");
  lines.push("    if (pool[i].length > best.length) best = pool[i];");
  lines.push("  }");
  lines.push("  return best;");
  lines.push("}");
  lines.push("");
  // ─── custom ──────────────────────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Delegate to a user-supplied extension_point. The extension may return");
  lines.push(" * either a `ValidationReport` shape (`{ ok, issues }`) for rich feedback,");
  lines.push(" * or any truthy/falsy value for the simple case. Extension errors are");
  lines.push(" * treated as validation failures so a buggy validator can't silently");
  lines.push(" * accept everything.");
  lines.push(" */");
  lines.push("export function validateCustom(value: unknown, validatorFn: (value: unknown) => unknown): ValidationReport {");
  lines.push("  try {");
  lines.push("    const raw = validatorFn(value);");
  lines.push("    if (raw && typeof raw === \"object\" && \"ok\" in (raw as Record<string, unknown>)) {");
  lines.push("      const r = raw as { ok?: unknown; issues?: unknown };");
  lines.push("      const ok = Boolean(r.ok);");
  lines.push("      const issues = Array.isArray(r.issues) ? (r.issues as unknown[]).map(String) : [];");
  lines.push("      counter(ok ? \"cognition.validate.passed\" : \"cognition.validate.failed\", { mode: \"custom\", kind: \"structured\" });");
  lines.push("      return { ok, issues };");
  lines.push("    }");
  lines.push("    const ok = Boolean(raw);");
  lines.push("    counter(ok ? \"cognition.validate.passed\" : \"cognition.validate.failed\", { mode: \"custom\", kind: \"truthy\" });");
  lines.push("    return { ok, issues: ok ? [] : [\"custom validator rejected output\"] };");
  lines.push("  } catch (e) {");
  lines.push("    const msg = e instanceof Error ? e.message : String(e);");
  lines.push("    counter(\"cognition.validate.failed\", { mode: \"custom\", kind: \"threw\" });");
  lines.push("    return { ok: false, issues: [`custom validator threw: ${msg.slice(0, 200)}`] };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
