/**
 * MarrowScript Seed File Emitter
 * Generates a TypeScript seed script from an IRSystem.
 */

import * as IR from "./ir";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toSnakeCase(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function seedValue(irType: string, fieldName: string, i: number): string {
  if (irType === "string") return `"sample_${fieldName}_${i + 1}"`;
  if (irType === "uint" || irType === "int") return String(i + 1);
  if (irType === "float") return String((i + 1) * 1.5);
  if (irType === "bool") return i % 2 === 0 ? "true" : "false";
  if (irType === "uuid") return "uuid()";
  if (irType === "timestamp") return "new Date().toISOString()";
  if (irType === "bytes") return `"sample_${fieldName}_${i + 1}"`;
  if (irType === "json") return "JSON.stringify({})";
  const listMatch = irType.match(/^list<(.+)>$/);
  if (listMatch) return "JSON.stringify([])";
  const setMatch = irType.match(/^set<(.+)>$/);
  if (setMatch) return "JSON.stringify([])";
  const optMatch = irType.match(/^optional<(.+)>$/);
  if (optMatch) return "null";
  return `"sample_${fieldName}_${i + 1}"`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function emitSeedFile(system: IR.IRSystem): string {
  const lines: string[] = [];

  lines.push(`// Generated by MarrowScript compiler.`);
  lines.push(`// Seed script for: ${system.name} v${system.version}`);
  lines.push(`// Run: npx ts-node src/seed.ts`);
  lines.push("");
  lines.push(`import { query, pool } from "./db";`);
  lines.push(`import { v4 as uuid } from "uuid";`);
  lines.push("");

  const seedModels: { mod: IR.IRModule; model: IR.IRModel }[] = [];
  for (const mod of system.modules) {
    if (mod.kind === "api_service" || mod.kind === "data_store") {
      for (const model of mod.models) {
        seedModels.push({ mod, model });
      }
    }
  }

  lines.push(`async function main(): Promise<void> {`);
  lines.push(`  console.log("Seeding ${system.name}...");`);
  lines.push("");

  for (const { model } of seedModels) {
    const tableName = toSnakeCase(model.name) + "s";
    lines.push(`  // Seed ${model.name}`);
    lines.push(`  console.log("  Seeding ${tableName}...");`);

    for (let i = 0; i < 3; i++) {
      const fieldNames = model.fields.map((f) => f.name);
      const fieldValues = model.fields.map((f) =>
        seedValue(f.type, f.name, i)
      );

      lines.push(`  await query(`);
      lines.push(
        `    \`INSERT INTO ${tableName} (${fieldNames.join(", ")}) VALUES (${fieldNames.map((_, idx) => `$${idx + 1}`).join(", ")}) ON CONFLICT DO NOTHING\`,`
      );
      lines.push(`    [${fieldValues.join(", ")}]`);
      lines.push(`  );`);
    }
    lines.push("");
  }

  lines.push(`  console.log("Seed complete.");`);
  lines.push(`}`);
  lines.push("");
  lines.push(`main()`);
  lines.push(`  .catch((err) => {`);
  lines.push(`    console.error("Seed failed:", err);`);
  lines.push(`    process.exit(1);`);
  lines.push(`  })`);
  lines.push(`  .finally(() => pool.end());`);
  lines.push("");

  return lines.join("\n");
}
