/**
 * MarrowScript Flow Checkpoint Emitter (LLM Harness, Phase 17)
 *
 * Emits the persistence + runtime + HTTP surface for the checkpoint primitive:
 *
 *   migrations/flow_runs.sql          — flow_runs + flow_run_checkpoints tables
 *   src/flows/checkpoints.ts          — state machine + decision helpers
 *   src/routes/flow_runs.ts           — GET /flow_runs/:id + POST /flow_runs/:id/checkpoint/:name
 *
 * Files are only emitted when at least one flow has at least one checkpoint.
 * Flows without checkpoints stay on the legacy synchronous path emitted by
 * emit_extras.ts:emitFlowRuntime.
 *
 * Determinism: the schema and helpers are static. The HTTP routes iterate
 * over flows in declaration order so the route registration is stable.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function checkpointsNeeded(system: IR.IRSystem): boolean {
  return system.flows.some(f => f.steps.some(s => s.checkpoint !== null));
}

export function emitCheckpointFiles(system: IR.IRSystem): EmittedFile[] {
  if (!checkpointsNeeded(system)) return [];
  const files: EmittedFile[] = [];

  files.push({
    path: "migrations/flow_runs.sql",
    content: emitMigration(),
    language: "sql",
    source_module: "checkpoint",
  });

  files.push({
    path: "src/flows/checkpoints.ts",
    content: emitCheckpointRuntime(),
    language: "typescript",
    source_module: "checkpoint",
  });

  files.push({
    path: "src/routes/flow_runs.ts",
    content: emitFlowRunsRoute(system),
    language: "typescript",
    source_module: "checkpoint",
  });

  return files;
}

// ─── Migration ──────────────────────────────────────────────────────────────

function emitMigration(): string {
  return [
    "-- Generated by MarrowScript compiler. DO NOT EDIT.",
    "-- Phase 17 — flow runs + per-checkpoint decisions.",
    "",
    "CREATE TABLE IF NOT EXISTS flow_runs (",
    "  id UUID PRIMARY KEY,",
    "  flow_name VARCHAR(128) NOT NULL,",
    "  state VARCHAR(32) NOT NULL,  -- running | paused | resumed | completed | cancelled | failed",
    "  current_step VARCHAR(128) NOT NULL DEFAULT '',",
    "  current_checkpoint VARCHAR(128) NOT NULL DEFAULT '',",
    "  payload JSONB NOT NULL DEFAULT '{}'::jsonb,",
    "  result JSONB,",
    "  error TEXT,",
    "  trace_id VARCHAR(128) NOT NULL DEFAULT '',",
    "  actor_id VARCHAR(128) NOT NULL DEFAULT '',",
    "  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),",
    "  paused_at TIMESTAMPTZ,",
    "  resumed_at TIMESTAMPTZ,",
    "  finished_at TIMESTAMPTZ",
    ");",
    "",
    "CREATE INDEX IF NOT EXISTS idx_flow_runs_state ON flow_runs(state);",
    "CREATE INDEX IF NOT EXISTS idx_flow_runs_flow ON flow_runs(flow_name);",
    "CREATE INDEX IF NOT EXISTS idx_flow_runs_started ON flow_runs(started_at DESC);",
    "",
    "CREATE TABLE IF NOT EXISTS flow_run_checkpoints (",
    "  id UUID PRIMARY KEY,",
    "  flow_run_id UUID NOT NULL REFERENCES flow_runs(id) ON DELETE CASCADE,",
    "  checkpoint_name VARCHAR(128) NOT NULL,",
    "  payload JSONB NOT NULL DEFAULT '{}'::jsonb,  -- the `shows:` snapshot",
    "  decision VARCHAR(32),  -- approve | reject | edit | regenerate | cancel | NULL while pending",
    "  edited_payload JSONB,  -- only set when decision = 'edit'",
    "  actor_id VARCHAR(128),",
    "  decided_at TIMESTAMPTZ,",
    "  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()",
    ");",
    "",
    "CREATE INDEX IF NOT EXISTS idx_flow_checkpoints_run ON flow_run_checkpoints(flow_run_id);",
    "CREATE INDEX IF NOT EXISTS idx_flow_checkpoints_pending ON flow_run_checkpoints(flow_run_id) WHERE decision IS NULL;",
    "",
  ].join("\n");
}

// ─── Runtime helpers ────────────────────────────────────────────────────────

function emitCheckpointRuntime(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Phase 17 — flow checkpoint runtime.");
  lines.push("//");
  lines.push("// State machine:");
  lines.push("//   running  → paused (await decision) → resumed (continue) → completed");
  lines.push("//                                      → cancelled (decision=reject|cancel)");
  lines.push("//                                      → completed via 'edit' (with edited payload)");
  lines.push("//                                      → resumed via 'regenerate' (re-run step)");
  lines.push("//                                      → cancelled by timeout (on_timeout: cancel)");
  lines.push("//");
  lines.push("// Decisions are delivered via POST /flow_runs/:id/checkpoint/:name; this");
  lines.push("// module exposes an in-process Map<flow_run_id+checkpoint, resolver> so");
  lines.push("// the flow runner's awaitDecision() promise resolves as soon as the HTTP");
  lines.push("// handler calls submitDecision(). Cross-process resume requires polling");
  lines.push("// or pubsub — out of scope for v1.");
  lines.push("");
  lines.push("import { randomUUID } from \"crypto\";");
  lines.push("import { query, queryOne } from \"../db\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("");
  lines.push("export type FlowRunState = \"running\" | \"paused\" | \"resumed\" | \"completed\" | \"cancelled\" | \"failed\";");
  lines.push("export type CheckpointDecision = \"approve\" | \"reject\" | \"edit\" | \"regenerate\" | \"cancel\";");
  lines.push("");
  lines.push("export interface FlowRun {");
  lines.push("  id: string;");
  lines.push("  flow_name: string;");
  lines.push("  state: FlowRunState;");
  lines.push("  current_step: string;");
  lines.push("  current_checkpoint: string;");
  lines.push("  payload: Record<string, unknown>;");
  lines.push("  result: unknown;");
  lines.push("  error: string | null;");
  lines.push("  trace_id: string;");
  lines.push("  actor_id: string;");
  lines.push("  started_at: string;");
  lines.push("  paused_at: string | null;");
  lines.push("  resumed_at: string | null;");
  lines.push("  finished_at: string | null;");
  lines.push("}");
  lines.push("");
  lines.push("export interface CheckpointRecord {");
  lines.push("  id: string;");
  lines.push("  flow_run_id: string;");
  lines.push("  checkpoint_name: string;");
  lines.push("  payload: Record<string, unknown>;");
  lines.push("  decision: CheckpointDecision | null;");
  lines.push("  edited_payload: Record<string, unknown> | null;");
  lines.push("  actor_id: string | null;");
  lines.push("  decided_at: string | null;");
  lines.push("  created_at: string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface DecisionResult {");
  lines.push("  decision: CheckpointDecision;");
  lines.push("  edited_payload: Record<string, unknown> | null;");
  lines.push("  actor_id: string;");
  lines.push("  /** True when the resolver fired via timeout rather than a real submit. */");
  lines.push("  timed_out: boolean;");
  lines.push("}");
  lines.push("");
  // ── In-process resolver registry ─────────────────────────────────────────
  lines.push("// In-process registry: flow_run_id|checkpoint_name → pending resolver.");
  lines.push("// When the HTTP handler accepts a decision, it calls the resolver to");
  lines.push("// unblock the flow runner's awaitDecision() promise. The cleanup is");
  lines.push("// idempotent (delete-on-resolve) so a duplicate decision is a no-op.");
  lines.push("interface PendingDecision {");
  lines.push("  resolve: (d: DecisionResult) => void;");
  lines.push("  timer: ReturnType<typeof setTimeout> | null;");
  lines.push("}");
  lines.push("const __pending: Map<string, PendingDecision> = new Map();");
  lines.push("");
  lines.push("function pendingKey(flowRunId: string, checkpointName: string): string {");
  lines.push("  return flowRunId + \"|\" + checkpointName;");
  lines.push("}");
  lines.push("");
  // ── Public API ────────────────────────────────────────────────────────────
  lines.push("/** Start a flow run row in the running state. */");
  lines.push("export async function startFlowRun(flowName: string, traceId: string, actorId: string, payload: Record<string, unknown> = {}): Promise<FlowRun> {");
  lines.push("  const id = randomUUID();");
  lines.push("  const rows = await query<FlowRun>(");
  lines.push("    `INSERT INTO flow_runs (id, flow_name, state, payload, trace_id, actor_id) VALUES ($1, $2, 'running', $3, $4, $5) RETURNING *`,");
  lines.push("    [id, flowName, JSON.stringify(payload), traceId, actorId],");
  lines.push("  );");
  lines.push("  counter(\"flow.run_started\", { flow: flowName });");
  lines.push("  return rows[0];");
  lines.push("}");
  lines.push("");
  lines.push("/** Pause a flow at a checkpoint and write the `shows:` snapshot. */");
  lines.push("export async function pauseFlowRun(flowRunId: string, stepName: string, checkpointName: string, payload: Record<string, unknown>): Promise<CheckpointRecord> {");
  lines.push("  await query(");
  lines.push("    `UPDATE flow_runs SET state = 'paused', current_step = $2, current_checkpoint = $3, paused_at = NOW() WHERE id = $1`,");
  lines.push("    [flowRunId, stepName, checkpointName],");
  lines.push("  );");
  lines.push("  const cpId = randomUUID();");
  lines.push("  const rows = await query<CheckpointRecord>(");
  lines.push("    `INSERT INTO flow_run_checkpoints (id, flow_run_id, checkpoint_name, payload) VALUES ($1, $2, $3, $4) RETURNING *`,");
  lines.push("    [cpId, flowRunId, checkpointName, JSON.stringify(payload)],");
  lines.push("  );");
  lines.push("  logger.info(\"flow_paused\", { event: \"flow.paused\", trace_id: \"\", metadata: { flow_run_id: flowRunId, checkpoint: checkpointName } });");
  lines.push("  counter(\"flow.paused\", { checkpoint: checkpointName });");
  lines.push("  return rows[0];");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Wait for a decision on a paused checkpoint. Resolves when an HTTP");
  lines.push(" * handler calls submitDecision(), or when timeoutMs elapses (in which");
  lines.push(" * case the result is the on_timeout fallback decision and timed_out=true).");
  lines.push(" */");
  lines.push("export function awaitDecision(flowRunId: string, checkpointName: string, timeoutMs: number | null, onTimeout: \"cancel\" | null): Promise<DecisionResult> {");
  lines.push("  const key = pendingKey(flowRunId, checkpointName);");
  lines.push("  return new Promise<DecisionResult>((resolve) => {");
  lines.push("    let timer: ReturnType<typeof setTimeout> | null = null;");
  lines.push("    if (timeoutMs && timeoutMs > 0) {");
  lines.push("      timer = setTimeout(() => {");
  lines.push("        const entry = __pending.get(key);");
  lines.push("        if (!entry) return; // already resolved");
  lines.push("        __pending.delete(key);");
  lines.push("        counter(\"flow.checkpoint_timeout\", { checkpoint: checkpointName });");
  lines.push("        const decision: CheckpointDecision = onTimeout === \"cancel\" ? \"cancel\" : \"reject\";");
  lines.push("        resolve({ decision, edited_payload: null, actor_id: \"system:timeout\", timed_out: true });");
  lines.push("      }, timeoutMs);");
  lines.push("    }");
  lines.push("    __pending.set(key, { resolve, timer });");
  lines.push("  });");
  lines.push("}");
  lines.push("");
  lines.push("/** Submit a decision from outside the runner (called by HTTP route). */");
  lines.push("export async function submitDecision(flowRunId: string, checkpointName: string, decision: CheckpointDecision, editedPayload: Record<string, unknown> | null, actorId: string): Promise<{ ok: boolean; reason?: string }> {");
  lines.push("  // Persist the decision first; durability over speed.");
  lines.push("  const updated = await query<CheckpointRecord>(");
  lines.push("    `UPDATE flow_run_checkpoints SET decision = $1, edited_payload = $2, actor_id = $3, decided_at = NOW() WHERE flow_run_id = $4 AND checkpoint_name = $5 AND decision IS NULL RETURNING *`,");
  lines.push("    [decision, editedPayload ? JSON.stringify(editedPayload) : null, actorId, flowRunId, checkpointName],");
  lines.push("  );");
  lines.push("  if (updated.length === 0) {");
  lines.push("    return { ok: false, reason: \"no pending checkpoint matches\" };");
  lines.push("  }");
  lines.push("  counter(\"flow.checkpoint_decided\", { checkpoint: checkpointName, decision });");
  lines.push("  // Wake the in-process awaiter, if any. Cross-process awaiters need to poll.");
  lines.push("  const key = pendingKey(flowRunId, checkpointName);");
  lines.push("  const entry = __pending.get(key);");
  lines.push("  if (entry) {");
  lines.push("    if (entry.timer) clearTimeout(entry.timer);");
  lines.push("    __pending.delete(key);");
  lines.push("    entry.resolve({ decision, edited_payload: editedPayload, actor_id: actorId, timed_out: false });");
  lines.push("  }");
  lines.push("  return { ok: true };");
  lines.push("}");
  lines.push("");
  lines.push("export async function markRunCompleted(flowRunId: string, result: unknown): Promise<void> {");
  lines.push("  await query(");
  lines.push("    `UPDATE flow_runs SET state = 'completed', result = $2, finished_at = NOW() WHERE id = $1`,");
  lines.push("    [flowRunId, JSON.stringify(result)],");
  lines.push("  );");
  lines.push("  counter(\"flow.run_completed\", {});");
  lines.push("}");
  lines.push("");
  lines.push("export async function markRunFailed(flowRunId: string, error: string): Promise<void> {");
  lines.push("  await query(");
  lines.push("    `UPDATE flow_runs SET state = 'failed', error = $2, finished_at = NOW() WHERE id = $1`,");
  lines.push("    [flowRunId, error.slice(0, 4096)],");
  lines.push("  );");
  lines.push("  counter(\"flow.run_failed\", {});");
  lines.push("}");
  lines.push("");
  lines.push("export async function markRunCancelled(flowRunId: string, reason: string = \"\"): Promise<void> {");
  lines.push("  await query(");
  lines.push("    `UPDATE flow_runs SET state = 'cancelled', error = $2, finished_at = NOW() WHERE id = $1`,");
  lines.push("    [flowRunId, reason.slice(0, 4096)],");
  lines.push("  );");
  lines.push("  counter(\"flow.run_cancelled\", {});");
  lines.push("}");
  lines.push("");
  lines.push("export async function markRunResumed(flowRunId: string): Promise<void> {");
  lines.push("  await query(");
  lines.push("    `UPDATE flow_runs SET state = 'resumed', resumed_at = NOW() WHERE id = $1`,");
  lines.push("    [flowRunId],");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  lines.push("/** Read a flow run plus its pending checkpoint (if any) for the GET endpoint. */");
  lines.push("export async function getFlowRunWithPending(flowRunId: string): Promise<{ run: FlowRun | null; pending: CheckpointRecord | null }> {");
  lines.push("  const run = await queryOne<FlowRun>(`SELECT * FROM flow_runs WHERE id = $1`, [flowRunId]);");
  lines.push("  if (!run) return { run: null, pending: null };");
  lines.push("  const pending = await queryOne<CheckpointRecord>(");
  lines.push("    `SELECT * FROM flow_run_checkpoints WHERE flow_run_id = $1 AND decision IS NULL ORDER BY created_at DESC LIMIT 1`,");
  lines.push("    [flowRunId],");
  lines.push("  );");
  lines.push("  return { run, pending };");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Snapshot the visible portion of the runner's context per the checkpoint's");
  lines.push(" * `shows:` clause. The runner passes the full ctx in; this helper returns");
  lines.push(" * a slimmed object containing only the requested fields. Missing paths");
  lines.push(" * resolve to undefined; arrays and objects are deep-cloned to avoid the");
  lines.push(" * caller mutating persisted state.");
  lines.push(" */");
  lines.push("export function buildShowsPayload(ctx: Record<string, unknown>, paths: string[]): Record<string, unknown> {");
  lines.push("  const out: Record<string, unknown> = {};");
  lines.push("  for (const path of paths) {");
  lines.push("    const segs = path.split(\".\");");
  lines.push("    let cur: unknown = ctx;");
  lines.push("    for (const s of segs) {");
  lines.push("      if (cur && typeof cur === \"object\" && s in (cur as object)) {");
  lines.push("        cur = (cur as Record<string, unknown>)[s];");
  lines.push("      } else {");
  lines.push("        cur = undefined;");
  lines.push("        break;");
  lines.push("      }");
  lines.push("    }");
  lines.push("    out[path] = deepClone(cur);");
  lines.push("  }");
  lines.push("  return out;");
  lines.push("}");
  lines.push("");
  lines.push("function deepClone(v: unknown): unknown {");
  lines.push("  if (v === null || v === undefined) return v;");
  lines.push("  if (typeof v !== \"object\") return v;");
  lines.push("  return JSON.parse(JSON.stringify(v));");
  lines.push("}");
  return lines.join("\n");
}

// ─── HTTP routes ────────────────────────────────────────────────────────────

function emitFlowRunsRoute(system: IR.IRSystem): string {
  const lines: string[] = [];
  // Build the closed list of (flow_name, checkpoint_name, allow) triples so
  // the route validates the decision against the declared allow list.
  const allowMap: { flow: string; cp: string; allow: string[] }[] = [];
  for (const f of system.flows) {
    for (const s of f.steps) {
      if (s.checkpoint) allowMap.push({ flow: f.name, cp: s.checkpoint.name, allow: s.checkpoint.allow });
    }
  }

  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Phase 17 — flow runs HTTP routes.");
  lines.push("//");
  lines.push("// GET  /flow_runs/:id                              → current state + pending checkpoint");
  lines.push("// POST /flow_runs/:id/checkpoint/:name             → submit a decision");
  lines.push("//");
  lines.push("// Auth: requires the same JWT the rest of the API does. Decisions are");
  lines.push("// validated against the declared allow list per checkpoint — a decision");
  lines.push("// not on the list is rejected with 400.");
  lines.push("");
  lines.push("import { Router, Request, Response } from \"express\";");
  lines.push("import { requireAuth, AuthContext } from \"../auth\";");
  lines.push("import {");
  lines.push("  getFlowRunWithPending,");
  lines.push("  submitDecision,");
  lines.push("  type CheckpointDecision,");
  lines.push("} from \"../flows/checkpoints\";");
  lines.push("");
  // Closed allow map per (flow, checkpoint) — same shape the type checker
  // validated at compile time. Embedded as a literal so the route doesn't
  // need to parse the spec at startup.
  lines.push("const ALLOW: Record<string, string[]> = {");
  for (const a of allowMap) {
    lines.push(`  ${JSON.stringify(a.flow + ":" + a.cp)}: ${JSON.stringify(a.allow)},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("export const flowRunsRouter = Router();");
  lines.push("");
  lines.push("// GET /flow_runs/:id");
  lines.push("flowRunsRouter.get(\"/:id\", requireAuth, async (req: Request, res: Response) => {");
  lines.push("  const id = String(req.params.id);");
  lines.push("  const r = await getFlowRunWithPending(id);");
  lines.push("  if (!r.run) return res.status(404).json({ error: { code: \"NOT_FOUND\", message: \"flow run not found\" } });");
  lines.push("  return res.json({ run: r.run, pending: r.pending });");
  lines.push("});");
  lines.push("");
  lines.push("// POST /flow_runs/:id/checkpoint/:name");
  lines.push("flowRunsRouter.post(\"/:id/checkpoint/:name\", requireAuth, async (req: Request, res: Response) => {");
  lines.push("  const auth = (req as Request & { auth?: AuthContext }).auth;");
  lines.push("  const actorId = auth?.actor_id || \"unknown\";");
  lines.push("  const id = String(req.params.id);");
  lines.push("  const cpName = String(req.params.name);");
  lines.push("  const body = (req.body ?? {}) as { decision?: string; edited_payload?: Record<string, unknown>; flow_name?: string };");
  lines.push("  const decision = String(body.decision || \"\");");
  lines.push("  const flowName = String(body.flow_name || \"\");");
  lines.push("  if (!decision) return res.status(400).json({ error: { code: \"INVALID_DECISION\", message: \"decision is required\" } });");
  lines.push("  // Validate against the declared allow list. The flow_name is required");
  lines.push("  // because the same checkpoint name can exist on different flows.");
  lines.push("  const allowKey = flowName + \":\" + cpName;");
  lines.push("  const allowed = ALLOW[allowKey];");
  lines.push("  if (!allowed) return res.status(400).json({ error: { code: \"UNKNOWN_CHECKPOINT\", message: \"unknown flow/checkpoint pair\" } });");
  lines.push("  if (!allowed.includes(decision)) return res.status(400).json({ error: { code: \"DECISION_NOT_ALLOWED\", message: `decision '${decision}' not in allow list [${allowed.join(\",\")}]` } });");
  lines.push("  const r = await submitDecision(id, cpName, decision as CheckpointDecision, body.edited_payload ?? null, actorId);");
  lines.push("  if (!r.ok) return res.status(409).json({ error: { code: \"NOT_PENDING\", message: r.reason || \"checkpoint not pending\" } });");
  lines.push("  return res.json({ ok: true });");
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}
