/**
 * MarrowScript Prompt Cache Emitter (LLM Harness, Phase 3)
 *
 * Generates two artifacts:
 *   - migrations/prompt_cache.sql  — content-addressed cache table
 *   - src/cognition/cache.ts       — get/put/key helper used by the prompt
 *                                    runtime
 *
 * Determinism: pure code generation. The cache key is derived deterministically
 * from (canonical input JSON | model identity | template hash | output type)
 * so two identical prompt invocations produce identical lookup keys.
 *
 * Integration:
 *   - emit_cognition.ts wraps the provider call with `cache.get(key)` →
 *     `cache.put(key, value, ttl_ms)` only when the IRPrompt declares a
 *     `cache:` block.
 *   - The schema runs alongside the existing migrations (event_outbox.sql,
 *     audit_log.sql, etc.) — emit_full.ts decides when to include it.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

/**
 * True iff at least one prompt declares a `cache:` block. Otherwise we don't
 * emit the migration / runtime — non-cached projects stay clean.
 */
export function anyPromptUsesCache(system: IR.IRSystem): boolean {
  return system.prompts.some(p => p.cache !== null);
}

export function emitCacheFiles(system: IR.IRSystem): EmittedFile[] {
  if (!anyPromptUsesCache(system)) return [];
  return [
    {
      path: "migrations/prompt_cache.sql",
      content: emitCacheSchema(),
      language: "sql",
      source_module: "cognition",
    },
    {
      path: "src/cognition/cache.ts",
      content: emitCacheRuntime(),
      language: "typescript",
      source_module: "cognition",
    },
  ];
}

function emitCacheSchema(): string {
  return `-- MarrowScript: Prompt Cache Schema
-- Generated by MarrowScript compiler. DO NOT EDIT.
--
-- Content-addressed cache for prompt invocations. Entries are keyed by
-- a deterministic hash of (canonical input | model | template | output type).
-- TTL is enforced application-side (the runtime ignores rows with
-- expires_at < now()), and a janitor query can periodically delete expired
-- rows. Foreign keys are intentionally absent: the cache is a side-store.

CREATE TABLE IF NOT EXISTS prompt_cache (
  cache_key       VARCHAR(64) PRIMARY KEY,
  prompt_name     VARCHAR     NOT NULL,
  model_id        VARCHAR     NOT NULL,
  output_value    JSONB       NOT NULL,
  prompt_tokens   INT,
  completion_tokens INT,
  cost_usd        NUMERIC(10,6),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ NOT NULL,
  hits            INT         NOT NULL DEFAULT 0,
  last_hit_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_prompt_cache_expires
  ON prompt_cache (expires_at);

CREATE INDEX IF NOT EXISTS idx_prompt_cache_prompt
  ON prompt_cache (prompt_name, created_at);
`;
}

function emitCacheRuntime(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 3 — prompt cache.");
  lines.push("//");
  lines.push("// Two storage modes, switched by env var LLM_CACHE_MODE:");
  lines.push("//   memory  — in-process Map, useful for tests and single-instance dev (default)");
  lines.push("//   pg      — Postgres-backed, durable across restarts and HA workers");
  lines.push("//");
  lines.push("// Both modes share the same get/put/deriveKey API. The cognition runtime");
  lines.push("// always asks the cache, never the storage backend directly.");
  lines.push("");
  lines.push("import { createHash } from \"crypto\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("");
  lines.push("export interface CacheEntry {");
  lines.push("  value: unknown;");
  lines.push("  prompt_tokens: number | null;");
  lines.push("  completion_tokens: number | null;");
  lines.push("  cost_usd: number | null;");
  lines.push("  cached_at: number; // ms epoch");
  lines.push("  expires_at: number; // ms epoch");
  lines.push("}");
  lines.push("");
  lines.push("export interface PromptCache {");
  lines.push("  get(key: string): Promise<CacheEntry | null>;");
  lines.push("  put(key: string, prompt_name: string, model_id: string, value: unknown, ttl_ms: number, usage: { prompt_tokens?: number; completion_tokens?: number; cost_usd?: number }): Promise<void>;");
  lines.push("}");
  lines.push("");
  // Key derivation. Stable across runs — JSON.stringify with sorted keys.
  lines.push("/**");
  lines.push(" * Canonical-JSON stringify: keys are sorted at every level so two");
  lines.push(" * objects with the same content produce identical strings regardless");
  lines.push(" * of declaration order. Used as the basis for the cache key.");
  lines.push(" */");
  lines.push("function canonical(value: unknown): string {");
  lines.push("  if (value === null || value === undefined) return JSON.stringify(value ?? null);");
  lines.push("  if (typeof value !== \"object\") return JSON.stringify(value);");
  lines.push("  if (Array.isArray(value)) return \"[\" + value.map(canonical).join(\",\") + \"]\";");
  lines.push("  const obj = value as Record<string, unknown>;");
  lines.push("  const keys = Object.keys(obj).sort();");
  lines.push("  return \"{\" + keys.map(k => JSON.stringify(k) + \":\" + canonical(obj[k])).join(\",\") + \"}\";");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Derive a 64-char hex key. The runtime passes the rendered template");
  lines.push(" * as `template_hash` so prompt rewordings invalidate the cache.");
  lines.push(" */");
  lines.push("export function deriveKey(args: {");
  lines.push("  prompt_name: string;");
  lines.push("  model_id: string;");
  lines.push("  template_hash: string;");
  lines.push("  output_type: string;");
  lines.push("  input: unknown;");
  lines.push("}): string {");
  lines.push("  const composite = [");
  lines.push("    args.prompt_name,");
  lines.push("    args.model_id,");
  lines.push("    args.template_hash,");
  lines.push("    args.output_type,");
  lines.push("    canonical(args.input),");
  lines.push("  ].join(\"|\");");
  lines.push("  return createHash(\"sha256\").update(composite).digest(\"hex\");");
  lines.push("}");
  lines.push("");
  // ─── Memory backend ──────────────────────────────────────────────────────
  lines.push("class MemoryCache implements PromptCache {");
  lines.push("  private store = new Map<string, CacheEntry>();");
  lines.push("");
  lines.push("  async get(key: string): Promise<CacheEntry | null> {");
  lines.push("    const e = this.store.get(key);");
  lines.push("    if (!e) return null;");
  lines.push("    if (e.expires_at < Date.now()) {");
  lines.push("      this.store.delete(key);");
  lines.push("      return null;");
  lines.push("    }");
  lines.push("    return e;");
  lines.push("  }");
  lines.push("");
  lines.push("  async put(key: string, _prompt: string, _model: string, value: unknown, ttl_ms: number, usage: { prompt_tokens?: number; completion_tokens?: number; cost_usd?: number }): Promise<void> {");
  lines.push("    const now = Date.now();");
  lines.push("    this.store.set(key, {");
  lines.push("      value,");
  lines.push("      prompt_tokens: usage.prompt_tokens ?? null,");
  lines.push("      completion_tokens: usage.completion_tokens ?? null,");
  lines.push("      cost_usd: usage.cost_usd ?? null,");
  lines.push("      cached_at: now,");
  lines.push("      expires_at: now + ttl_ms,");
  lines.push("    });");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // ─── Postgres backend ────────────────────────────────────────────────────
  lines.push("class PgCache implements PromptCache {");
  lines.push("  async get(key: string): Promise<CacheEntry | null> {");
  lines.push("    // Lazy import — keeps tests that don't exercise PG mode free of pg dependency.");
  lines.push("    // eslint-disable-next-line @typescript-eslint/no-require-imports");
  lines.push("    const { query } = require(\"../db\") as { query: (sql: string, args: unknown[]) => Promise<Record<string, unknown>[]> };");
  lines.push("    const rows = await query(");
  lines.push("      `UPDATE prompt_cache SET hits = hits + 1, last_hit_at = NOW()");
  lines.push("        WHERE cache_key = $1 AND expires_at > NOW() RETURNING *`,");
  lines.push("      [key],");
  lines.push("    );");
  lines.push("    if (rows.length === 0) return null;");
  lines.push("    const r = rows[0] as { output_value: unknown; prompt_tokens: number | null; completion_tokens: number | null; cost_usd: string | null; created_at: Date; expires_at: Date };");
  lines.push("    return {");
  lines.push("      value: r.output_value,");
  lines.push("      prompt_tokens: r.prompt_tokens,");
  lines.push("      completion_tokens: r.completion_tokens,");
  lines.push("      cost_usd: r.cost_usd === null ? null : Number(r.cost_usd),");
  lines.push("      cached_at: new Date(r.created_at).getTime(),");
  lines.push("      expires_at: new Date(r.expires_at).getTime(),");
  lines.push("    };");
  lines.push("  }");
  lines.push("");
  lines.push("  async put(key: string, prompt_name: string, model_id: string, value: unknown, ttl_ms: number, usage: { prompt_tokens?: number; completion_tokens?: number; cost_usd?: number }): Promise<void> {");
  lines.push("    // eslint-disable-next-line @typescript-eslint/no-require-imports");
  lines.push("    const { query } = require(\"../db\") as { query: (sql: string, args: unknown[]) => Promise<unknown> };");
  lines.push("    await query(");
  lines.push("      `INSERT INTO prompt_cache (cache_key, prompt_name, model_id, output_value, prompt_tokens, completion_tokens, cost_usd, expires_at)");
  lines.push("        VALUES ($1, $2, $3, $4, $5, $6, $7, NOW() + ($8 || ' milliseconds')::interval)");
  lines.push("        ON CONFLICT (cache_key) DO UPDATE SET");
  lines.push("          output_value = EXCLUDED.output_value,");
  lines.push("          expires_at = EXCLUDED.expires_at,");
  lines.push("          last_hit_at = NULL,");
  lines.push("          hits = 0`,");
  lines.push("      [key, prompt_name, model_id, JSON.stringify(value), usage.prompt_tokens ?? null, usage.completion_tokens ?? null, usage.cost_usd ?? null, ttl_ms],");
  lines.push("    );");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // ─── Factory + observability wrapper ─────────────────────────────────────
  lines.push("function chooseBackend(): PromptCache {");
  lines.push("  const mode = process.env.LLM_CACHE_MODE || \"memory\";");
  lines.push("  if (mode === \"pg\") return new PgCache();");
  lines.push("  if (mode !== \"memory\") {");
  lines.push("    logger.warn(\"prompt_cache_unknown_mode\", { event: \"cache\", status: \"rejected\", metadata: { mode } });");
  lines.push("  }");
  lines.push("  return new MemoryCache();");
  lines.push("}");
  lines.push("");
  lines.push("const __backend: PromptCache = chooseBackend();");
  lines.push("");
  lines.push("/** Public cache. Counters are emitted on every get/put for hit-rate observability. */");
  lines.push("export const cache: PromptCache = {");
  lines.push("  async get(key: string): Promise<CacheEntry | null> {");
  lines.push("    const e = await __backend.get(key);");
  lines.push("    counter(e ? \"cognition.cache_hit\" : \"cognition.cache_miss\");");
  lines.push("    return e;");
  lines.push("  },");
  lines.push("  async put(key, prompt_name, model_id, value, ttl_ms, usage): Promise<void> {");
  lines.push("    await __backend.put(key, prompt_name, model_id, value, ttl_ms, usage);");
  lines.push("    counter(\"cognition.cache_put\", { prompt: prompt_name });");
  lines.push("  },");
  lines.push("};");
  lines.push("");
  lines.push("/** For tests: clear the in-memory cache. No-op against PG mode. */");
  lines.push("export function __resetMemoryCache(): void {");
  lines.push("  if (__backend instanceof MemoryCache) {");
  lines.push("    // @ts-expect-error — internal field for tests");
  lines.push("    __backend.store.clear();");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
