/**
 * MarrowScript Bounded Agent Loops (Phase 26)
 *
 * Adds a `loop:` primitive to prompts for iterative refinement patterns:
 *
 * Surface syntax:
 *   prompt refine_code(spec: string) {
 *     loop: {
 *       generate(spec) as draft
 *       critique(draft) as feedback
 *       revise(draft, feedback) as final
 *       until: passes(ast_compiles) or max_iterations: 3
 *     }
 *     returns: string
 *     validate: ast_compiles
 *   }
 *
 * What gets generated:
 *   - A bounded iteration loop that calls sub-prompts in sequence
 *   - Each iteration's output is validated against the `until:` condition
 *   - If condition passes, return immediately (short-circuit)
 *   - If max_iterations hit, return the best result so far
 *   - Full tracing of each iteration (duration, pass/fail, version)
 *
 * Common patterns:
 *   1. Generate + Validate: generate until it compiles (retry with feedback)
 *   2. Generate + Critique + Revise: self-improvement loop
 *   3. Decompose + Execute + Aggregate: fan-out then collect
 *   4. Draft + Review + Finalize: human-in-the-loop hybrid
 *
 * Emits: src/cognition/loops.ts (runtime utilities)
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function emitLoops(system: IR.IRSystem): EmittedFile | null {
  if (system.prompts.length === 0) return null;

  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Bounded Agent Loops (Phase 26) — iterative refinement runtime.");
  lines.push("//");
  lines.push("// Patterns: generate-validate, generate-critique-revise, decompose-execute-aggregate");
  lines.push("// All loops are BOUNDED — max_iterations is enforced at compile time.");
  lines.push("");
  lines.push("import { writeSpan } from \"./traces\";");
  lines.push("import { counter, histogram } from \"../metrics\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("");

  // ─── Types ───────────────────────────────────────────────────────────
  lines.push("export interface LoopConfig<T> {");
  lines.push("  /** Human-readable name for tracing */");
  lines.push("  name: string;");
  lines.push("  /** Maximum number of iterations before returning best-so-far */");
  lines.push("  max_iterations: number;");
  lines.push("  /** The step function: takes current state, returns next state */");
  lines.push("  step: (state: LoopState<T>, iteration: number) => Promise<T>;");
  lines.push("  /** Validation: returns true if the output is acceptable */");
  lines.push("  validate: (output: T) => Promise<boolean> | boolean;");
  lines.push("  /** Optional: generate feedback for the next iteration */");
  lines.push("  critique?: (output: T, iteration: number) => Promise<string>;");
  lines.push("  /** Trace ID for the parent span */");
  lines.push("  trace_id: string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface LoopState<T> {");
  lines.push("  /** Current best output */");
  lines.push("  current: T | null;");
  lines.push("  /** Feedback from previous iteration (if critique is provided) */");
  lines.push("  feedback: string | null;");
  lines.push("  /** History of all previous outputs */");
  lines.push("  history: { output: T; valid: boolean; feedback: string | null }[];");
  lines.push("}");
  lines.push("");
  lines.push("export interface LoopResult<T> {");
  lines.push("  /** The final output (best result) */");
  lines.push("  output: T;");
  lines.push("  /** Did validation pass? */");
  lines.push("  valid: boolean;");
  lines.push("  /** How many iterations ran */");
  lines.push("  iterations: number;");
  lines.push("  /** Which iteration produced the returned output */");
  lines.push("  best_iteration: number;");
  lines.push("  /** Total duration across all iterations */");
  lines.push("  total_ms: number;");
  lines.push("  /** Per-iteration details */");
  lines.push("  history: { iteration: number; valid: boolean; duration_ms: number; feedback: string | null }[];");
  lines.push("}");
  lines.push("");

  // ─── Core loop runner ────────────────────────────────────────────────
  lines.push("/**");
  lines.push(" * Run a bounded refinement loop.");
  lines.push(" *");
  lines.push(" * Executes `step()` up to `max_iterations` times. After each step,");
  lines.push(" * calls `validate()`. If valid, returns immediately. If not, optionally");
  lines.push(" * calls `critique()` to generate feedback for the next iteration.");
  lines.push(" *");
  lines.push(" * Always terminates. Never recurses. Fully traced.");
  lines.push(" */");
  lines.push("export async function runLoop<T>(config: LoopConfig<T>): Promise<LoopResult<T>> {");
  lines.push("  const startMs = Date.now();");
  lines.push("  const state: LoopState<T> = { current: null, feedback: null, history: [] };");
  lines.push("  const iterationHistory: LoopResult<T>[\"history\"] = [];");
  lines.push("  let bestOutput: T | null = null;");
  lines.push("  let bestIteration = 0;");
  lines.push("  let bestValid = false;");
  lines.push("");
  lines.push("  for (let i = 0; i < config.max_iterations; i++) {");
  lines.push("    const iterStart = Date.now();");
  lines.push("");
  lines.push("    // Execute step");
  lines.push("    let output: T;");
  lines.push("    try {");
  lines.push("      output = await config.step(state, i);");
  lines.push("    } catch (e: any) {");
  lines.push("      logger.error(\"loop.step_error\", { loop: config.name, iteration: i, error: e.message });");
  lines.push("      iterationHistory.push({ iteration: i, valid: false, duration_ms: Date.now() - iterStart, feedback: e.message });");
  lines.push("      continue;");
  lines.push("    }");
  lines.push("");
  lines.push("    // Validate");
  lines.push("    let valid: boolean;");
  lines.push("    try {");
  lines.push("      valid = await config.validate(output);");
  lines.push("    } catch {");
  lines.push("      valid = false;");
  lines.push("    }");
  lines.push("");
  lines.push("    // Track best");
  lines.push("    if (valid || !bestOutput) {");
  lines.push("      bestOutput = output;");
  lines.push("      bestIteration = i;");
  lines.push("      bestValid = valid;");
  lines.push("    }");
  lines.push("");
  lines.push("    // Generate feedback if needed");
  lines.push("    let feedback: string | null = null;");
  lines.push("    if (!valid && config.critique) {");
  lines.push("      try {");
  lines.push("        feedback = await config.critique(output, i);");
  lines.push("      } catch { feedback = \"Validation failed, please try again.\"; }");
  lines.push("    }");
  lines.push("");
  lines.push("    // Update state");
  lines.push("    state.current = output;");
  lines.push("    state.feedback = feedback;");
  lines.push("    state.history.push({ output, valid, feedback });");
  lines.push("");
  lines.push("    const iterMs = Date.now() - iterStart;");
  lines.push("    iterationHistory.push({ iteration: i, valid, duration_ms: iterMs, feedback });");
  lines.push("");
  lines.push("    // Trace");
  lines.push("    counter(\"cognition.loop.iteration\", { loop: config.name, iteration: String(i), valid: String(valid) });");
  lines.push("    histogram(\"cognition.loop.iteration_ms\", iterMs, { loop: config.name });");
  lines.push("");
  lines.push("    // Short-circuit on success");
  lines.push("    if (valid) {");
  lines.push("      logger.info(\"loop.success\", { loop: config.name, iterations: i + 1, total_ms: Date.now() - startMs });");
  lines.push("      break;");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  const totalMs = Date.now() - startMs;");
  lines.push("");
  lines.push("  // Write summary span");
  lines.push("  await writeSpan({");
  lines.push("    trace_id: config.trace_id,");
  lines.push("    kind: \"loop\",");
  lines.push("    name: config.name,");
  lines.push("    status: bestValid ? \"ok\" : \"exhausted\",");
  lines.push("    duration_ms: totalMs,");
  lines.push("    metadata: {");
  lines.push("      iterations: iterationHistory.length,");
  lines.push("      max_iterations: config.max_iterations,");
  lines.push("      best_iteration: bestIteration,");
  lines.push("      valid: bestValid,");
  lines.push("    },");
  lines.push("  });");
  lines.push("");
  lines.push("  if (!bestValid) {");
  lines.push("    counter(\"cognition.loop.exhausted\", { loop: config.name });");
  lines.push("    logger.warn(\"loop.exhausted\", { loop: config.name, iterations: iterationHistory.length, total_ms: totalMs });");
  lines.push("  }");
  lines.push("");
  lines.push("  return {");
  lines.push("    output: bestOutput as T,");
  lines.push("    valid: bestValid,");
  lines.push("    iterations: iterationHistory.length,");
  lines.push("    best_iteration: bestIteration,");
  lines.push("    total_ms: totalMs,");
  lines.push("    history: iterationHistory,");
  lines.push("  };");
  lines.push("}");
  lines.push("");

  // ─── Convenience: generate-validate loop ─────────────────────────────
  lines.push("/**");
  lines.push(" * Simple generate-until-valid loop.");
  lines.push(" * Calls `generate()` repeatedly until `validate()` passes.");
  lines.push(" */");
  lines.push("export async function generateUntilValid<T>(");
  lines.push("  name: string,");
  lines.push("  generate: (attempt: number, previousFeedback: string | null) => Promise<T>,");
  lines.push("  validate: (output: T) => Promise<boolean> | boolean,");
  lines.push("  options: { max_iterations?: number; trace_id?: string; critique?: (output: T) => Promise<string> } = {}");
  lines.push("): Promise<LoopResult<T>> {");
  lines.push("  return runLoop({");
  lines.push("    name,");
  lines.push("    max_iterations: options.max_iterations || 3,");
  lines.push("    trace_id: options.trace_id || \"loop-\" + Date.now(),");
  lines.push("    step: (state, i) => generate(i, state.feedback),");
  lines.push("    validate,");
  lines.push("    critique: options.critique,");
  lines.push("  });");
  lines.push("}");
  lines.push("");

  // ─── Convenience: generate-critique-revise ───────────────────────────
  lines.push("/**");
  lines.push(" * Generate → Critique → Revise loop.");
  lines.push(" * First iteration generates from scratch. Subsequent iterations revise based on feedback.");
  lines.push(" */");
  lines.push("export async function generateCritiqueRevise<T>(");
  lines.push("  name: string,");
  lines.push("  generate: (spec: string) => Promise<T>,");
  lines.push("  critique: (output: T) => Promise<string>,");
  lines.push("  revise: (output: T, feedback: string) => Promise<T>,");
  lines.push("  validate: (output: T) => Promise<boolean> | boolean,");
  lines.push("  spec: string,");
  lines.push("  options: { max_iterations?: number; trace_id?: string } = {}");
  lines.push("): Promise<LoopResult<T>> {");
  lines.push("  return runLoop({");
  lines.push("    name,");
  lines.push("    max_iterations: options.max_iterations || 3,");
  lines.push("    trace_id: options.trace_id || \"loop-\" + Date.now(),");
  lines.push("    step: async (state, i) => {");
  lines.push("      if (i === 0 || !state.current) return generate(spec);");
  lines.push("      return revise(state.current, state.feedback || \"Please improve.\");");
  lines.push("    },");
  lines.push("    validate,");
  lines.push("    critique,");
  lines.push("  });");
  lines.push("}");
  lines.push("");

  return {
    path: "src/cognition/loops.ts",
    content: lines.join("\n"),
    language: "typescript",
    source_module: "cognition",
  };
}
