/**
 * MarrowScript TypeScript SDK Emitter
 * Generates a typed fetch client SDK from an IRSystem.
 */

import * as IR from "./ir";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toSnakeCase(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function toCamelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase());
}

function toPascalCase(s: string): string {
  const c = toCamelCase(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

function irTypeToTs(irType: string): string {
  if (irType === "string") return "string";
  if (irType === "uint" || irType === "int") return "number";
  if (irType === "float") return "number";
  if (irType === "bool") return "boolean";
  if (irType === "timestamp") return "string";
  if (irType === "uuid") return "string";
  if (irType === "bytes") return "string";
  if (irType === "json") return "unknown";
  const listMatch = irType.match(/^list<(.+)>$/);
  if (listMatch) return irTypeToTs(listMatch[1]) + "[]";
  const setMatch = irType.match(/^set<(.+)>$/);
  if (setMatch) return irTypeToTs(setMatch[1]) + "[]";
  const optMatch = irType.match(/^optional<(.+)>$/);
  if (optMatch) return irTypeToTs(optMatch[1]) + " | null";
  return "unknown";
}

// ─── SDK generator ────────────────────────────────────────────────────────────

export function emitTypescriptSdk(system: IR.IRSystem): string {
  const lines: string[] = [];
  const systemPascal = toPascalCase(system.name.replace(/[^a-zA-Z0-9_]/g, "_"));

  lines.push("// Generated by MarrowScript compiler. Import this file into your frontend.");
  lines.push(`// System: ${system.name} v${system.version}`);
  lines.push("");

  // Collect all models for interface generation
  const allModels: { mod: IR.IRModule; model: IR.IRModel }[] = [];
  for (const mod of system.modules) {
    if (mod.kind === "api_service" && mod.models.length > 0) {
      for (const model of mod.models) {
        allModels.push({ mod, model });
      }
    }
  }

  // Emit TypeScript interfaces
  for (const { model } of allModels) {
    const typeName = toPascalCase(model.name);
    lines.push(`export interface ${typeName} {`);
    for (const field of model.fields) {
      const nullable = field.nullable ? " | null" : "";
      lines.push(`  ${field.name}: ${irTypeToTs(field.type)}${nullable};`);
    }
    lines.push("}");
    lines.push("");
  }

  // Emit client class
  lines.push(`export class ${systemPascal}Client {`);
  lines.push(
    `  constructor(private baseUrl: string, private getToken?: () => string | null) {}`
  );
  lines.push("");

  // Private request helper
  lines.push(
    `  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {`
  );
  lines.push(`    const headers: Record<string, string> = {`);
  lines.push(`      "Content-Type": "application/json",`);
  lines.push(`    };`);
  lines.push(`    if (this.getToken) {`);
  lines.push(`      const token = this.getToken();`);
  lines.push(`      if (token) headers["Authorization"] = "Bearer " + token;`);
  lines.push(`    }`);
  lines.push(`    const res = await fetch(this.baseUrl + path, {`);
  lines.push(`      method,`);
  lines.push(`      headers,`);
  lines.push(`      body: body !== undefined ? JSON.stringify(body) : undefined,`);
  lines.push(`    });`);
  lines.push(`    if (!res.ok) {`);
  lines.push(
    `      const text = await res.text().catch(() => res.statusText);`
  );
  lines.push(`      throw new Error(\`HTTP \${res.status}: \${text}\`);`);
  lines.push(`    }`);
  lines.push(`    if (res.status === 204) return undefined as unknown as T;`);
  lines.push(`    return res.json() as Promise<T>;`);
  lines.push(`  }`);
  lines.push("");

  // Per-entity methods
  for (const { mod, model } of allModels) {
    const entity = toPascalCase(model.name);
    const tableName = toSnakeCase(model.name);
    const basePath = `/${tableName}s`;

    lines.push(`  // ─── ${entity} ───`);
    lines.push("");

    lines.push(
      `  list${entity}(page = 1, pageSize = 50): Promise<{ items: ${entity}[]; total: number; page: number; page_size: number }> {`
    );
    lines.push(
      `    return this.request("GET", \`${basePath}?page=\${page}&page_size=\${pageSize}\`);`
    );
    lines.push(`  }`);
    lines.push("");

    lines.push(`  get${entity}(id: string): Promise<${entity}> {`);
    lines.push(`    return this.request("GET", \`${basePath}/\${id}\`);`);
    lines.push(`  }`);
    lines.push("");

    lines.push(
      `  create${entity}(data: Partial<${entity}>): Promise<${entity}> {`
    );
    lines.push(`    return this.request("POST", "${basePath}", data);`);
    lines.push(`  }`);
    lines.push("");

    lines.push(
      `  update${entity}(id: string, data: Partial<${entity}>): Promise<${entity}> {`
    );
    lines.push(`    return this.request("PUT", \`${basePath}/\${id}\`, data);`);
    lines.push(`  }`);
    lines.push("");

    lines.push(`  delete${entity}(id: string): Promise<void> {`);
    lines.push(`    return this.request("DELETE", \`${basePath}/\${id}\`);`);
    lines.push(`  }`);
    lines.push("");

    // Capability methods
    const crudNames = new Set(["create", "read", "update", "delete", "list"]);
    const allMethods: IR.IRMethod[] = mod.interfaces.flatMap((i) => i.methods);
    const capabilityMethods = allMethods.filter(
      (m) => !crudNames.has(m.name.toLowerCase())
    );

    for (const method of capabilityMethods) {
      const methodCamel = toCamelCase(method.name);
      const dashName = toSnakeCase(method.name).replace(/_/g, "-");
      // Pipeline-bearing capabilities return the typed { ok, action,
      // trace_id, results } shape the route handler emits. Plain
      // capabilities return the simpler { ok, action } shape (still
      // augmented at runtime with `entity` when an entity fetch was used,
      // but we don't surface that in the public SDK type since it's
      // schema-shaped per-capability).
      const isPipeline = !!method.pipeline;
      const returnType = isPipeline
        ? `{ ok: boolean; action: string; trace_id: string | null; results: Record<string, unknown> }`
        : `{ ok: boolean; action: string }`;
      lines.push(
        `  ${methodCamel}(data: Record<string, unknown>): Promise<${returnType}> {`
      );
      lines.push(
        `    return this.request("POST", "${basePath}/${dashName}", data);`
      );
      lines.push(`  }`);
      lines.push("");
    }
  }

  // ─── Cognition traces fetcher (when prompts exist) ─────────────────────────
  // The frontend uses this to render the prompt-by-prompt timeline a forge
  // run produced. The backend redacts @sensitive fields before persistence,
  // so the spans are safe to surface in a UI.
  if (system.prompts.length > 0) {
    lines.push(`  // ─── Cognition traces ───`);
    lines.push("");
    lines.push(`  /** Fetch every span recorded for a trace_id, ordered by start time. */`);
    lines.push(`  getCognitionTrace(trace_id: string): Promise<{ trace_id: string; span_count: number; spans: unknown[] }> {`);
    lines.push(`    return this.request("GET", \`/cognition_traces/\${trace_id}\`);`);
    lines.push(`  }`);
    lines.push("");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export function emitSdkPackageJson(system: IR.IRSystem): string {
  const pkgName = toSnakeCase(system.name).replace(/_/g, "-") + "-sdk";
  return JSON.stringify(
    {
      name: pkgName,
      version: system.version,
      description: `TypeScript SDK for ${system.name} — generated by MarrowScript compiler`,
      main: "client.js",
      types: "client.d.ts",
      scripts: {
        build: "tsc",
      },
      devDependencies: {
        typescript: "5.3.3",
      },
    },
    null,
    2
  );
}
