/**
 * MarrowScript Source Map Emitter
 * Generates a .marrow.map file that maps generated TS line numbers back to .marrow source.
 * Also generates a debug wrapper that intercepts runtime errors and annotates them.
 */

import * as IR from "./ir";

export interface BoneSourceMap {
  version: 1;
  source_hash: string;
  source_file: string;
  mappings: BoneMapping[];
}

export interface BoneMapping {
  generated_file: string;
  generated_line: number;
  bone_line: number;
  bone_column: number;
  description: string;
}

/**
 * Emit a source map JSON file for the compiled system.
 * Maps IR nodes to their approximate .marrow source locations.
 */
export function emitSourceMapFile(system: IR.IRSystem, sourceFile: string): string {
  const mappings: BoneMapping[] = [];

  // Map each module to a rough line estimate
  // (Real line numbers would require storing loc in IR — this is a best-effort approximation)
  let estimatedLine = 1;
  for (const mod of system.modules) {
    mappings.push({
      generated_file: `src/routes/${mod.name.replace(/Service$/, "").toLowerCase()}.ts`,
      generated_line: 1,
      bone_line: estimatedLine,
      bone_column: 1,
      description: `Module: ${mod.name}`,
    });
    estimatedLine += 10;

    for (const iface of mod.interfaces) {
      for (const method of iface.methods) {
        mappings.push({
          generated_file: `src/routes/${mod.name.replace(/Service$/, "").toLowerCase()}.ts`,
          generated_line: estimatedLine,
          bone_line: estimatedLine,
          bone_column: 3,
          description: `Capability: ${method.name}`,
        });
        estimatedLine += 5;
      }
    }
  }

  const map: BoneSourceMap = {
    version: 1,
    source_hash: system.source_hash,
    source_file: sourceFile,
    mappings,
  };

  return JSON.stringify(map, null, 2);
}

/**
 * Emit a debug error handler that annotates runtime errors with .marrow context.
 * Reads the source map at runtime to provide dual-stack traces.
 */
export function emitDebugHandler(system: IR.IRSystem): string {
  return `// Generated by MarrowScript compiler. DO NOT EDIT.
// Runtime error handler with .marrow source annotation.

import * as fs from "fs";
import * as path from "path";

interface BoneMapping {
  generated_file: string;
  generated_line: number;
  bone_line: number;
  bone_column: number;
  description: string;
}

interface BoneSourceMap {
  version: number;
  source_hash: string;
  source_file: string;
  mappings: BoneMapping[];
}

let sourceMap: BoneSourceMap | null = null;

function loadSourceMap(): BoneSourceMap | null {
  if (sourceMap) return sourceMap;
  const mapPath = path.join(__dirname, "..", "${system.name}.marrow.map");
  if (!fs.existsSync(mapPath)) return null;
  try {
    sourceMap = JSON.parse(fs.readFileSync(mapPath, "utf-8"));
    return sourceMap;
  } catch {
    return null;
  }
}

export function annotateBoneError(err: Error, generatedFile: string): string {
  const map = loadSourceMap();
  if (!map) return err.stack || err.message;

  // Extract line number from stack trace
  const lineMatch = err.stack?.match(new RegExp(generatedFile.replace(/[/\\\\]/g, "[/\\\\\\\\]") + ":(\\\\d+)"));
  if (!lineMatch) return err.stack || err.message;

  const generatedLine = parseInt(lineMatch[1], 10);
  const mapping = map.mappings
    .filter(m => m.generated_file.includes(generatedFile) && m.generated_line <= generatedLine)
    .sort((a, b) => b.generated_line - a.generated_line)[0];

  if (!mapping) return err.stack || err.message;

  return [
    \`MarrowScript source: \${map.source_file}:\${mapping.bone_line}:\${mapping.bone_column}\`,
    \`  Context: \${mapping.description}\`,
    \`Generated TS: \${generatedFile}:\${generatedLine}\`,
    \`\`,
    err.stack || err.message,
  ].join("\\n");
}

// Global error handler — annotates unhandled errors with .marrow context
process.on("uncaughtException", (err: Error) => {
  const annotated = annotateBoneError(err, err.stack?.split("\\n")[1]?.match(/\\((.+):\\d+:\\d+\\)/)?.[1] || "");
  console.error("[MarrowScript] Unhandled error:");
  console.error(annotated);
  // process.exit(1); // disabled - errors should not crash the server
});
`;
}
