/**
 * MarrowScript Notification Service Emitter
 * Generates src/notify.ts — fires on event emissions.
 */

import * as IR from "./ir";

function toPascalCase(s: string): string {
  return s.replace(/(^|[-_\s])(\w)/g, (_, __, c: string) => c.toUpperCase());
}

export function emitNotifyService(system: IR.IRSystem): string {
  const lines: string[] = [];

  lines.push(`// Generated by MarrowScript compiler.`);
  lines.push(`// Notification service — fires on event emissions.`);
  lines.push(`// Configure NOTIFY_PROVIDER=resend|sendgrid|log (default: log)`);
  lines.push(`// Set NOTIFY_API_KEY and NOTIFY_FROM_EMAIL in .env`);
  lines.push(``);
  lines.push(`import { SystemEvent } from "./events";`);
  lines.push(``);
  lines.push(`export type NotifyProvider = "resend" | "sendgrid" | "webhook" | "log";`);
  lines.push(``);
  lines.push(`const PROVIDER = (process.env.NOTIFY_PROVIDER || "log") as NotifyProvider;`);
  lines.push(`const API_KEY = process.env.NOTIFY_API_KEY || "";`);
  lines.push(`const FROM_EMAIL = process.env.NOTIFY_FROM_EMAIL || "noreply@example.com";`);
  lines.push(`const WEBHOOK_URL = process.env.NOTIFY_WEBHOOK_URL || "";`);
  lines.push(`const WEBHOOK_SECRET = process.env.NOTIFY_WEBHOOK_SECRET || "";`);
  lines.push(``);
  lines.push(`export interface NotifyMessage {`);
  lines.push(`  to: string;`);
  lines.push(`  subject: string;`);
  lines.push(`  body: string;`);
  lines.push(`}`);
  lines.push(``);
  // HTML-escape helper. Used to render arbitrary event payload data inside an
  // HTML email body without enabling HTML/JS injection in clients that render
  // it. Subject lines are also escaped for consistency.
  lines.push(`function escapeHtml(s: string): string {`);
  lines.push(`  return s`);
  lines.push(`    .replace(/&/g, "&amp;")`);
  lines.push(`    .replace(/</g, "&lt;")`);
  lines.push(`    .replace(/>/g, "&gt;")`);
  lines.push(`    .replace(/"/g, "&quot;")`);
  lines.push(`    .replace(/'/g, "&#39;");`);
  lines.push(`}`);
  lines.push(``);
  // Conservative email validation. Rejects empty input, multiple addresses,
  // and CRLF that would let a caller inject extra headers into the request body
  // sent to Resend / SendGrid.
  lines.push(`const __EMAIL_RE = /^[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}$/;`);
  lines.push(`function isValidEmail(addr: string): boolean {`);
  lines.push(`  if (!addr || addr.length > 254) return false;`);
  lines.push(`  if (/[\\r\\n]/.test(addr)) return false;`);
  lines.push(`  return __EMAIL_RE.test(addr);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function sendEmail(msg: NotifyMessage): Promise<void> {`);
  lines.push(`  if (!isValidEmail(msg.to)) {`);
  lines.push("    throw new Error(`Invalid recipient address: ${msg.to.slice(0, 64)}`);");
  lines.push(`  }`);
  lines.push(`  if (PROVIDER === "log") {`);
  lines.push(`    console.log(\`[notify] \${msg.subject} → \${msg.to}\`);`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`  if (PROVIDER === "resend") {`);
  lines.push(`    const res = await fetch("https://api.resend.com/emails", {`);
  lines.push(`      method: "POST",`);
  lines.push(`      headers: { "Authorization": \`Bearer \${API_KEY}\`, "Content-Type": "application/json" },`);
  lines.push(`      body: JSON.stringify({ from: FROM_EMAIL, to: msg.to, subject: msg.subject, html: msg.body }),`);
  lines.push(`    });`);
  lines.push(`    if (!res.ok) throw new Error(\`Resend error: \${res.status}\`);`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`  if (PROVIDER === "sendgrid") {`);
  lines.push(`    const res = await fetch("https://api.sendgrid.com/v3/mail/send", {`);
  lines.push(`      method: "POST",`);
  lines.push(`      headers: { "Authorization": \`Bearer \${API_KEY}\`, "Content-Type": "application/json" },`);
  lines.push(`      body: JSON.stringify({ personalizations: [{ to: [{ email: msg.to }] }], from: { email: FROM_EMAIL }, subject: msg.subject, content: [{ type: "text/html", value: msg.body }] }),`);
  lines.push(`    });`);
  lines.push(`    if (!res.ok) throw new Error(\`SendGrid error: \${res.status}\`);`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`  if (PROVIDER === "webhook") {`);
  lines.push(`    // Email-style notifications still flow through the webhook so the receiver sees a uniform shape.`);
  lines.push(`    await sendWebhook({ kind: "email", to: msg.to, subject: msg.subject, body: msg.body });`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  // Webhook signing. We use HMAC-SHA256 over the raw body for tamper detection.
  // Receivers verify with the same secret.
  lines.push(`import { createHmac } from "crypto";`);
  lines.push(``);
  lines.push(`function signPayload(body: string): string {`);
  lines.push(`  if (!WEBHOOK_SECRET) return "";`);
  lines.push(`  return createHmac("sha256", WEBHOOK_SECRET).update(body).digest("hex");`);
  lines.push(`}`);
  lines.push(``);
  // Private-host detection. Catches loopback (127/8, ::1, 0.0.0.0), RFC1918
  // (10/8, 172.16/12, 192.168/16), link-local (169.254/16, fe80::/10) and
  // unique-local IPv6 (fc00::/7). DNS hostnames that resolve to private
  // addresses are not blocked here — that requires a DNS lookup and a
  // dual-stack check; we leave that to the deployer's network policy.
  lines.push(`function isPrivateHost(host: string): boolean {`);
  lines.push(`  const h = host.toLowerCase();`);
  lines.push(`  if (h === "localhost" || h === "0.0.0.0" || h === "::" || h === "::1") return true;`);
  lines.push(`  // IPv4 dotted quad`);
  lines.push(`  const m4 = h.match(/^(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})$/);`);
  lines.push(`  if (m4) {`);
  lines.push(`    const a = Number(m4[1]), b = Number(m4[2]);`);
  lines.push(`    if (a === 127) return true;            // loopback`);
  lines.push(`    if (a === 10) return true;             // RFC1918`);
  lines.push(`    if (a === 172 && b >= 16 && b <= 31) return true; // RFC1918`);
  lines.push(`    if (a === 192 && b === 168) return true;          // RFC1918`);
  lines.push(`    if (a === 169 && b === 254) return true;          // link-local / cloud metadata`);
  lines.push(`    if (a === 0) return true;`);
  lines.push(`    return false;`);
  lines.push(`  }`);
  lines.push(`  // IPv6 — strip optional brackets and zone suffix.`);
  lines.push(`  const v6 = h.replace(/^\\[|\\]$/g, "").split("%")[0];`);
  lines.push(`  if (/^fe[89ab][0-9a-f]?:/i.test(v6)) return true; // link-local fe80::/10`);
  lines.push(`  if (/^f[cd][0-9a-f]?:/i.test(v6)) return true;     // unique-local fc00::/7`);
  lines.push(`  return false;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Send a JSON payload to NOTIFY_WEBHOOK_URL.`);
  lines.push(` *`);
  lines.push(` * Headers:`);
  lines.push(` *   Content-Type: application/json`);
  lines.push(` *   X-MarrowScript-Signature: <hex hmac-sha256(body, WEBHOOK_SECRET)>  (only if secret set)`);
  lines.push(` *   X-MarrowScript-Event: <event type>  (set by event handlers)`);
  lines.push(` */`);
  lines.push(`export async function sendWebhook(payload: Record<string, unknown>, eventType?: string): Promise<void> {`);
  lines.push(`  if (PROVIDER === "log") {`);
  lines.push(`    console.log(\`[notify:webhook] \${eventType || payload.kind || "event"}\`, JSON.stringify(payload).slice(0, 200));`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`  if (!WEBHOOK_URL) {`);
  lines.push(`    throw new Error("NOTIFY_WEBHOOK_URL is not configured");`);
  lines.push(`  }`);
  lines.push(`  // Validate URL — only http(s), and reject loopback / RFC1918 /`);
  lines.push(`  // link-local hosts to make this server unusable as an SSRF probe.`);
  lines.push(`  // Set NOTIFY_WEBHOOK_ALLOW_PRIVATE=1 to opt out (e.g. for internal CI`);
  lines.push(`  // setups where the webhook receiver is on the same network).`);
  lines.push(`  let url: URL;`);
  lines.push(`  try { url = new URL(WEBHOOK_URL); }`);
  lines.push(`  catch { throw new Error("Invalid NOTIFY_WEBHOOK_URL"); }`);
  lines.push(`  if (url.protocol !== "https:" && url.protocol !== "http:") {`);
  lines.push(`    throw new Error(\`Webhook URL protocol must be http(s), got \${url.protocol}\`);`);
  lines.push(`  }`);
  lines.push(`  if (process.env.NOTIFY_WEBHOOK_ALLOW_PRIVATE !== "1") {`);
  lines.push(`    if (isPrivateHost(url.hostname)) {`);
  lines.push(`      throw new Error(\`Webhook URL host is loopback / private / link-local: \${url.hostname}. Set NOTIFY_WEBHOOK_ALLOW_PRIVATE=1 to allow.\`);`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`  const body = JSON.stringify(payload);`);
  lines.push(`  const headers: Record<string, string> = { "Content-Type": "application/json" };`);
  lines.push(`  const sig = signPayload(body);`);
  lines.push(`  if (sig) headers["X-MarrowScript-Signature"] = sig;`);
  lines.push(`  if (eventType) headers["X-MarrowScript-Event"] = eventType;`);
  lines.push(`  const res = await fetch(WEBHOOK_URL, { method: "POST", headers, body });`);
  lines.push(`  if (!res.ok) throw new Error(\`Webhook delivery failed: \${res.status}\`);`);
  lines.push(`}`);
  lines.push(``);

  // Per-event handlers — payload is JSON-stringified and HTML-escaped before
  // being placed inside <pre> so payload values like "<script>..." can't break
  // out of the body.
  for (const event of system.events) {
    const eventName = toPascalCase(event.name);
    lines.push(`// Handler for ${eventName}`);
    lines.push(`export async function notify${eventName}(event: SystemEvent, recipientEmail: string): Promise<void> {`);
    lines.push(`  const __payload = escapeHtml(JSON.stringify(event.payload, null, 2));`);
    lines.push(`  await sendEmail({`);
    lines.push(`    to: recipientEmail,`);
    lines.push(`    subject: "${eventName} notification",`);
    lines.push("    body: `<p>Event <strong>${escapeHtml(\"" + eventName + "\")}</strong> occurred.</p><pre>${__payload}</pre>`,");
    lines.push(`  });`);
    lines.push(`}`);
    lines.push(``);
  }

  // registerNotificationHandlers
  lines.push(`export function registerNotificationHandlers(eventBus: any): void {`);
  lines.push(`  // TODO: implement recipient lookup per event type`);
  for (const event of system.events) {
    const eventName = toPascalCase(event.name);
    lines.push(`  // eventBus.subscribe("${eventName}", async (event: SystemEvent) => {`);
    lines.push(`  //   const recipientEmail = await lookupRecipient(event);`);
    lines.push(`  //   await notify${eventName}(event, recipientEmail);`);
    lines.push(`  // });`);
  }
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}
