/**
 * MarrowScript Prisma Schema Emitter
 * Generates a Prisma schema file from the IR.
 *
 * Maps MarrowScript entities, relations, and constraints to Prisma's
 * schema language. Produces a single `schema.prisma` file that can
 * be used with `npx prisma migrate dev` and `npx prisma generate`.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

function toSnakeCase(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function toPascalCase(s: string): string {
  return s.replace(/(^|[-_\s])(\w)/g, (_, __, c: string) => c.toUpperCase());
}

// ─── Type Mapping ─────────────────────────────────────────────────────────────

const PRISMA_TYPE_MAP: Record<string, string> = {
  string: "String",
  uint: "Int",
  int: "Int",
  float: "Float",
  bool: "Boolean",
  timestamp: "DateTime",
  uuid: "String",
  bytes: "Bytes",
  json: "Json",
};

function toPrismaType(irType: string): string {
  if (PRISMA_TYPE_MAP[irType]) return PRISMA_TYPE_MAP[irType];
  const listMatch = irType.match(/^(list|set)<(.+)>$/);
  if (listMatch) return `${toPrismaType(listMatch[2])}[]`;
  const optMatch = irType.match(/^optional<(.+)>$/);
  if (optMatch) return `${toPrismaType(optMatch[1])}?`;
  // Entity reference — will be handled as a relation
  return "String";
}

function toPrismaNativeType(irType: string): string | null {
  switch (irType) {
    case "uuid": return "@db.Uuid";
    case "string": return null; // default is fine
    case "json": return null; // Json maps directly
    case "bytes": return null;
    case "timestamp": return "@db.Timestamptz";
    case "float": return "@db.DoublePrecision";
    // MarrowScript `uint` and `int` map to Prisma `Int`. Prisma rejects
    // `Int @db.BigInt` (BigInt requires the Prisma `BigInt` type), so we use
    // no native type and let Prisma map to the default Postgres `INTEGER`.
    // If a caller needs 64-bit ints they should use the `int` IR type with a
    // future `@db.bigint` annotation — TBD.
    case "uint": return null;
    case "int": return null;
    default: return null;
  }
}

// ─── Prisma Emitter ───────────────────────────────────────────────────────────

export class PrismaEmitter {
  emit(system: IR.IRSystem): EmittedFile[] {
    const files: EmittedFile[] = [];
    files.push({
      path: "prisma/schema.prisma",
      content: this.emitSchema(system),
      language: "typescript", // closest match for syntax highlighting
      source_module: "prisma",
    });
    return files;
  }

  private emitSchema(system: IR.IRSystem): string {
    const lines: string[] = [];

    // Header
    lines.push(`// Generated by MarrowScript compiler. DO NOT EDIT.`);
    lines.push(`// Source: ${system.name} (${system.source_hash})`);
    lines.push(`// Run: npx prisma migrate dev --name init`);
    lines.push(`//      npx prisma generate`);
    lines.push(``);

    // Datasource
    lines.push(`datasource db {`);
    lines.push(`  provider = "postgresql"`);
    lines.push(`  url      = env("DATABASE_URL")`);
    lines.push(`}`);
    lines.push(``);

    // Generator
    lines.push(`generator client {`);
    lines.push(`  provider = "prisma-client-js"`);
    lines.push(`}`);
    lines.push(``);

    // Collect all models across modules, deduplicating by name
    const modelMap = new Map<string, { model: IR.IRModel; mod: IR.IRModule }>();
    const allRelations: IR.IRRelation[] = [];

    for (const mod of system.modules) {
      if (mod.kind === "data_store" || mod.kind === "api_service") {
        for (const model of mod.models) {
          if (!modelMap.has(model.name)) {
            modelMap.set(model.name, { model, mod });
          }
        }
        allRelations.push(...mod.relations);
      }
    }

    // Deduplicate relations by a stable key
    const seenRelations = new Set<string>();
    const uniqueRelations: IR.IRRelation[] = [];
    for (const rel of allRelations) {
      const key = `${rel.from_entity}:${rel.to_entity}:${rel.kind}:${rel.foreign_key}`;
      if (!seenRelations.has(key)) {
        seenRelations.add(key);
        uniqueRelations.push(rel);
      }
    }

    // Build a lookup: entity name → relations where it's the "from" side
    const relationsFrom = new Map<string, IR.IRRelation[]>();
    const relationsTo = new Map<string, IR.IRRelation[]>();
    for (const rel of uniqueRelations) {
      if (!relationsFrom.has(rel.from_entity)) relationsFrom.set(rel.from_entity, []);
      relationsFrom.get(rel.from_entity)!.push(rel);
      if (!relationsTo.has(rel.to_entity)) relationsTo.set(rel.to_entity, []);
      relationsTo.get(rel.to_entity)!.push(rel);
    }

    // Emit each model
    for (const [name, { model, mod }] of modelMap) {
      lines.push(this.emitModel(name, model, mod, relationsFrom.get(name) || [], relationsTo.get(name) || [], modelMap));
      lines.push(``);
    }

    // Emit junction tables for many_to_many
    for (const rel of uniqueRelations) {
      if (rel.kind === "many_to_many" && rel.junction_table) {
        lines.push(this.emitJunctionModel(rel));
        lines.push(``);
      }
    }

    // Emit audit_log and event_outbox models (infrastructure)
    lines.push(this.emitAuditLogModel());
    lines.push(``);
    lines.push(this.emitEventOutboxModel());
    lines.push(``);

    return lines.join("\n");
  }

  private emitModel(
    name: string,
    model: IR.IRModel,
    mod: IR.IRModule,
    relationsFrom: IR.IRRelation[],
    relationsTo: IR.IRRelation[],
    allModels: Map<string, { model: IR.IRModel; mod: IR.IRModule }>
  ): string {
    const lines: string[] = [];
    const tableName = toSnakeCase(name) + "s";

    lines.push(`model ${toPascalCase(name)} {`);

    // Fields
    for (const field of model.fields) {
      lines.push(`  ${this.emitField(field, model, name)}`);
    }

    // State field (if entity has a state machine)
    const hasSM = mod.state_machines.some(sm => sm.entity === name);
    const hasStateField = model.fields.some(f => f.name === "state");
    if (hasSM && !hasStateField) {
      lines.push(`  state         String`);
    }

    // Relation fields
    for (const rel of relationsFrom) {
      if (rel.kind === "belongs_to") {
        // The FK field is already in the model fields. Add the relation object.
        const targetModel = toPascalCase(rel.to_entity);
        const fieldName = toSnakeCase(rel.to_entity);
        lines.push(`  ${fieldName}   ${targetModel}  @relation(fields: [${rel.foreign_key}], references: [id], onDelete: Cascade)`);
      } else if (rel.kind === "has_many") {
        const targetModel = toPascalCase(rel.to_entity);
        const fieldName = toSnakeCase(rel.to_entity) + "s";
        lines.push(`  ${fieldName}  ${targetModel}[]`);
      } else if (rel.kind === "has_one") {
        const targetModel = toPascalCase(rel.to_entity);
        const fieldName = toSnakeCase(rel.to_entity);
        lines.push(`  ${fieldName}   ${targetModel}?`);
      }
    }

    // Inverse relations (where this model is the "to" side)
    for (const rel of relationsTo) {
      if (rel.kind === "belongs_to") {
        // This model is the target of a belongs_to — add the inverse has_many
        const sourceModel = toPascalCase(rel.from_entity);
        const fieldName = toSnakeCase(rel.from_entity) + "s";
        // Only add if not already covered by relationsFrom
        const alreadyCovered = relationsFrom.some(r =>
          r.to_entity === rel.from_entity && r.kind === "has_many"
        );
        if (!alreadyCovered) {
          lines.push(`  ${fieldName}  ${sourceModel}[]`);
        }
      }
    }

    // Table mapping
    lines.push(``);
    lines.push(`  @@map("${tableName}")`);

    // Indexes
    for (const idx of model.indexes) {
      if (idx.unique) {
        lines.push(`  @@unique([${idx.fields.join(", ")}])`);
      } else {
        lines.push(`  @@index([${idx.fields.join(", ")}])`);
      }
    }

    lines.push(`}`);
    return lines.join("\n");
  }

  private emitField(field: IR.IRField, model: IR.IRModel, entityName: string): string {
    const parts: string[] = [];

    // Field name (padded for alignment)
    parts.push(field.name.padEnd(14));

    // Type
    let prismaType = toPrismaType(field.type);
    if (field.nullable) prismaType += "?";
    parts.push(prismaType.padEnd(12));

    // Attributes
    const attrs: string[] = [];

    // Primary key
    if (field.name === model.primary_key) {
      attrs.push("@id");
    }

    // Default values
    if (field.name === "id" && field.type === "uuid") {
      attrs.push("@default(uuid())");
    } else if (field.name === "created_at" || (field.type === "timestamp" && field.name.includes("created"))) {
      attrs.push("@default(now())");
    } else if (field.name === "updated_at") {
      // @updatedAt only fires on update — we also need a default for create
      // or the NOT NULL column has no value at INSERT time.
      attrs.push("@default(now())");
      attrs.push("@updatedAt");
    } else if (field.default_value) {
      const dv = this.mapDefaultValue(field.default_value, field.type);
      if (dv) attrs.push(dv);
    }

    // Unique constraint (skip if already primary key — @id implies uniqueness)
    if (field.unique && field.name !== model.primary_key) {
      attrs.push("@unique");
    }

    // Native type annotation
    const nativeType = toPrismaNativeType(field.type);
    if (nativeType) {
      attrs.push(nativeType);
    }

    if (attrs.length > 0) {
      parts.push(attrs.join(" "));
    }

    return parts.join(" ").trimEnd();
  }

  private mapDefaultValue(value: string, type: string): string | null {
    if (value === "gen_random_uuid()" || value === "uuid()") return "@default(uuid())";
    if (value === "now()") return "@default(now())";
    if (value === "true" || value === "false") return `@default(${value})`;
    if (/^\d+$/.test(value)) return `@default(${value})`;
    if (/^\d+\.\d+$/.test(value)) return `@default(${value})`;
    if (value.startsWith('"') && value.endsWith('"')) return `@default(${value})`;
    return null;
  }

  private emitJunctionModel(rel: IR.IRRelation): string {
    const lines: string[] = [];
    const fromCol = toSnakeCase(rel.from_entity) + "_id";
    const toCol = toSnakeCase(rel.to_entity) + "_id";

    lines.push(`model ${toPascalCase(rel.junction_table!)} {`);
    lines.push(`  ${fromCol.padEnd(14)} String       @db.Uuid`);
    lines.push(`  ${toCol.padEnd(14)} String       @db.Uuid`);
    lines.push(`  created_at     DateTime     @default(now()) @db.Timestamptz`);
    lines.push(``);
    lines.push(`  ${toSnakeCase(rel.from_entity).padEnd(14)} ${toPascalCase(rel.from_entity)}  @relation(fields: [${fromCol}], references: [id], onDelete: Cascade)`);
    lines.push(`  ${toSnakeCase(rel.to_entity).padEnd(14)} ${toPascalCase(rel.to_entity)}  @relation(fields: [${toCol}], references: [id], onDelete: Cascade)`);
    lines.push(``);
    lines.push(`  @@id([${fromCol}, ${toCol}])`);
    lines.push(`  @@index([${fromCol}])`);
    lines.push(`  @@index([${toCol}])`);
    lines.push(`  @@map("${rel.junction_table}")`);
    lines.push(`}`);
    return lines.join("\n");
  }

  private emitAuditLogModel(): string {
    return `model AuditLog {
  id             String       @id @default(uuid()) @db.Uuid
  actor_id       String?      @db.Uuid
  action         String
  entity_type    String
  entity_id      String?      @db.Uuid
  payload        Json?
  ip             String?
  user_agent     String?
  trace_id       String?      @db.Uuid
  created_at     DateTime     @default(now()) @db.Timestamptz

  @@index([actor_id])
  @@index([entity_type, entity_id])
  @@index([created_at])
  @@map("audit_log")
}`;
  }

  private emitEventOutboxModel(): string {
    return `model EventOutbox {
  id             String       @id @default(uuid()) @db.Uuid
  event_type     String
  payload        Json
  status         String       @default("pending")
  attempts       Int          @default(0)
  created_at     DateTime     @default(now()) @db.Timestamptz
  processed_at   DateTime?    @db.Timestamptz
  error          String?

  @@index([status, created_at])
  @@map("event_outbox")
}`;
  }
}
