/**
 * MarrowScript Trace Viewer CLI (Phase 27)
 *
 * Generates a `marrowc traces` subcommand that queries cognition_traces
 * from SQLite and displays them in a human-readable format.
 *
 * Commands:
 *   marrowc traces list [--failed] [--last=24h] [--prompt=name] [--limit=20]
 *   marrowc traces show <trace_id>
 *   marrowc traces stats [--last=7d]
 *   marrowc traces clear [--before=7d]
 *
 * This emits: bin/traces.ts (CLI tool that queries the runtime DB)
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function emitTraceViewer(system: IR.IRSystem): EmittedFile | null {
  if (system.prompts.length === 0) return null;

  const lines: string[] = [];
  lines.push("#!/usr/bin/env ts-node");
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Trace Viewer CLI — query and display cognition traces.");
  lines.push("//");
  lines.push("// Usage:");
  lines.push("//   npx ts-node bin/traces.ts list [--failed] [--last=24h] [--prompt=name]");
  lines.push("//   npx ts-node bin/traces.ts show <trace_id>");
  lines.push("//   npx ts-node bin/traces.ts stats");
  lines.push("//   npx ts-node bin/traces.ts clear --before=7d");
  lines.push("");
  lines.push("import Database from \"better-sqlite3\";");
  lines.push("import * as path from \"path\";");
  lines.push("import * as fs from \"fs\";");
  lines.push("");

  // ─── DB connection ───────────────────────────────────────────────────
  lines.push("const DB_PATH = process.env.SQLITE_PATH || path.resolve(process.cwd(), \"*.db\");");
  lines.push("function openDb(): Database.Database {");
  lines.push("  // Find the .db file in cwd");
  lines.push("  const cwd = process.cwd();");
  lines.push("  const dbFiles = fs.readdirSync(cwd).filter(f => f.endsWith(\".db\") && !f.startsWith(\".\"));");
  lines.push("  if (dbFiles.length === 0) {");
  lines.push("    console.error(\"No .db file found in current directory. Run from your project root.\");");
  lines.push("    process.exit(1);");
  lines.push("  }");
  lines.push("  const dbPath = process.env.SQLITE_PATH || path.join(cwd, dbFiles[0]);");
  lines.push("  return new Database(dbPath, { readonly: true });");
  lines.push("}");
  lines.push("");

  // ─── Duration parser ─────────────────────────────────────────────────
  lines.push("function parseDuration(dur: string): number {");
  lines.push("  const m = dur.match(/^(\\d+)(m|h|d)$/);");
  lines.push("  if (!m) return 24 * 60 * 60 * 1000; // default 24h");
  lines.push("  const n = parseInt(m[1]);");
  lines.push("  switch (m[2]) {");
  lines.push("    case \"m\": return n * 60 * 1000;");
  lines.push("    case \"h\": return n * 60 * 60 * 1000;");
  lines.push("    case \"d\": return n * 24 * 60 * 60 * 1000;");
  lines.push("    default: return 24 * 60 * 60 * 1000;");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // ─── List command ────────────────────────────────────────────────────
  lines.push("function cmdList(args: string[]) {");
  lines.push("  const db = openDb();");
  lines.push("  let failed = false;");
  lines.push("  let lastDur = \"24h\";");
  lines.push("  let promptFilter = \"\";");
  lines.push("  let limit = 20;");
  lines.push("");
  lines.push("  for (const arg of args) {");
  lines.push("    if (arg === \"--failed\") failed = true;");
  lines.push("    if (arg.startsWith(\"--last=\")) lastDur = arg.slice(7);");
  lines.push("    if (arg.startsWith(\"--prompt=\")) promptFilter = arg.slice(9);");
  lines.push("    if (arg.startsWith(\"--limit=\")) limit = parseInt(arg.slice(8));");
  lines.push("  }");
  lines.push("");
  lines.push("  const sinceMs = Date.now() - parseDuration(lastDur);");
  lines.push("  const since = new Date(sinceMs).toISOString();");
  lines.push("");
  lines.push("  let sql = \"SELECT * FROM cognition_traces WHERE created_at >= ?\";");
  lines.push("  const params: any[] = [since];");
  lines.push("  if (failed) { sql += \" AND status != 'ok'\"; }");
  lines.push("  if (promptFilter) { sql += \" AND name = ?\"; params.push(promptFilter); }");
  lines.push("  sql += \" ORDER BY created_at DESC LIMIT ?\";");
  lines.push("  params.push(limit);");
  lines.push("");
  lines.push("  try {");
  lines.push("    const rows = db.prepare(sql).all(...params) as any[];");
  lines.push("    if (rows.length === 0) { console.log(\"No traces found.\"); return; }");
  lines.push("");
  lines.push("    console.log(`\\n  Traces (last ${lastDur}${failed ? \", failed only\" : \"\"}${promptFilter ? \", prompt=\" + promptFilter : \"\"})\\n`);");
  lines.push("    console.log(\"  \" + \"-\".repeat(90));");
  lines.push("    console.log(\"  \" + \"ID\".padEnd(18) + \"Prompt\".padEnd(28) + \"Status\".padEnd(10) + \"Duration\".padEnd(10) + \"Time\");");
  lines.push("    console.log(\"  \" + \"-\".repeat(90));");
  lines.push("");
  lines.push("    for (const row of rows) {");
  lines.push("      const id = (row.trace_id || row.id || \"\").slice(0, 16);");
  lines.push("      const name = (row.name || \"\").slice(0, 26);");
  lines.push("      const status = row.status === \"ok\" ? \"\\x1b[32m✓ ok\\x1b[0m\" : \"\\x1b[31m✗ \" + (row.status || \"err\").slice(0, 6) + \"\\x1b[0m\";");
  lines.push("      const dur = row.duration_ms ? row.duration_ms + \"ms\" : \"?\";");
  lines.push("      const time = row.created_at ? row.created_at.slice(11, 19) : \"\";");
  lines.push("      console.log(\"  \" + id.padEnd(18) + name.padEnd(28) + status.padEnd(18) + dur.padEnd(10) + time);");
  lines.push("    }");
  lines.push("    console.log(\"  \" + \"-\".repeat(90));");
  lines.push("    console.log(`  ${rows.length} trace(s) shown\\n`);");
  lines.push("  } catch (e: any) {");
  lines.push("    if (e.message.includes(\"no such table\")) {");
  lines.push("      console.log(\"No cognition_traces table found. Run the app first to generate traces.\");");
  lines.push("    } else { throw e; }");
  lines.push("  }");
  lines.push("  db.close();");
  lines.push("}");
  lines.push("");

  // ─── Show command ────────────────────────────────────────────────────
  lines.push("function cmdShow(traceId: string) {");
  lines.push("  const db = openDb();");
  lines.push("  try {");
  lines.push("    const row = db.prepare(\"SELECT * FROM cognition_traces WHERE trace_id = ? OR id = ?\").get(traceId, traceId) as any;");
  lines.push("    if (!row) { console.log(\"Trace not found: \" + traceId); return; }");
  lines.push("");
  lines.push("    console.log(\"\\n  Trace: \" + (row.trace_id || row.id));");
  lines.push("    console.log(\"  \" + \"=\".repeat(60));");
  lines.push("    console.log(\"  Prompt:    \" + row.name);");
  lines.push("    console.log(\"  Status:    \" + row.status);");
  lines.push("    console.log(\"  Duration:  \" + (row.duration_ms || \"?\") + \"ms\");");
  lines.push("    console.log(\"  Model:     \" + (row.model || \"?\"));");
  lines.push("    console.log(\"  Provider:  \" + (row.provider || \"?\"));");
  lines.push("    console.log(\"  Tier:      \" + (row.tier || \"?\"));");
  lines.push("    console.log(\"  Created:   \" + row.created_at);");
  lines.push("    if (row.metadata) {");
  lines.push("      console.log(\"  Metadata:  \" + row.metadata);");
  lines.push("    }");
  lines.push("    if (row.error) {");
  lines.push("      console.log(\"  Error:     \\x1b[31m\" + row.error + \"\\x1b[0m\");");
  lines.push("    }");
  lines.push("    console.log(\"\");");
  lines.push("  } catch (e: any) {");
  lines.push("    if (e.message.includes(\"no such table\")) {");
  lines.push("      console.log(\"No cognition_traces table found.\");");
  lines.push("    } else { throw e; }");
  lines.push("  }");
  lines.push("  db.close();");
  lines.push("}");
  lines.push("");

  // ─── Stats command ───────────────────────────────────────────────────
  lines.push("function cmdStats(args: string[]) {");
  lines.push("  const db = openDb();");
  lines.push("  let lastDur = \"7d\";");
  lines.push("  for (const arg of args) { if (arg.startsWith(\"--last=\")) lastDur = arg.slice(7); }");
  lines.push("  const since = new Date(Date.now() - parseDuration(lastDur)).toISOString();");
  lines.push("");
  lines.push("  try {");
  lines.push("    const total = db.prepare(\"SELECT COUNT(*) as c FROM cognition_traces WHERE created_at >= ?\").get(since) as any;");
  lines.push("    const failed = db.prepare(\"SELECT COUNT(*) as c FROM cognition_traces WHERE created_at >= ? AND status != 'ok'\").get(since) as any;");
  lines.push("    const byPrompt = db.prepare(\"SELECT name, COUNT(*) as calls, AVG(duration_ms) as avg_ms, SUM(CASE WHEN status='ok' THEN 1 ELSE 0 END) as ok FROM cognition_traces WHERE created_at >= ? GROUP BY name ORDER BY calls DESC\").all(since) as any[];");
  lines.push("    const avgDur = db.prepare(\"SELECT AVG(duration_ms) as avg FROM cognition_traces WHERE created_at >= ?\").get(since) as any;");
  lines.push("");
  lines.push("    console.log(`\\n  Cognition Stats (last ${lastDur})\\n`);");
  lines.push("    console.log(\"  Total calls:    \" + (total?.c || 0));");
  lines.push("    console.log(\"  Failed:         \" + (failed?.c || 0) + \" (\" + (total?.c ? Math.round(failed.c / total.c * 100) : 0) + \"%)\");");
  lines.push("    console.log(\"  Avg latency:    \" + Math.round(avgDur?.avg || 0) + \"ms\");");
  lines.push("    console.log(\"\");");
  lines.push("");
  lines.push("    if (byPrompt.length > 0) {");
  lines.push("      console.log(\"  \" + \"Prompt\".padEnd(30) + \"Calls\".padEnd(8) + \"Pass%\".padEnd(8) + \"Avg ms\");");
  lines.push("      console.log(\"  \" + \"-\".repeat(60));");
  lines.push("      for (const row of byPrompt) {");
  lines.push("        const passRate = row.calls > 0 ? Math.round(row.ok / row.calls * 100) : 0;");
  lines.push("        console.log(\"  \" + (row.name || \"?\").padEnd(30) + String(row.calls).padEnd(8) + (passRate + \"%\").padEnd(8) + Math.round(row.avg_ms || 0) + \"ms\");");
  lines.push("      }");
  lines.push("    }");
  lines.push("    console.log(\"\");");
  lines.push("  } catch (e: any) {");
  lines.push("    if (e.message.includes(\"no such table\")) {");
  lines.push("      console.log(\"No cognition_traces table found. Run the app first.\");");
  lines.push("    } else { throw e; }");
  lines.push("  }");
  lines.push("  db.close();");
  lines.push("}");
  lines.push("");

  // ─── Clear command ───────────────────────────────────────────────────
  lines.push("function cmdClear(args: string[]) {");
  lines.push("  // Open writable");
  lines.push("  const cwd = process.cwd();");
  lines.push("  const dbFiles = fs.readdirSync(cwd).filter(f => f.endsWith(\".db\") && !f.startsWith(\".\"));");
  lines.push("  if (dbFiles.length === 0) { console.log(\"No .db file found.\"); return; }");
  lines.push("  const db = new Database(path.join(cwd, dbFiles[0]));");
  lines.push("");
  lines.push("  let beforeDur = \"7d\";");
  lines.push("  for (const arg of args) { if (arg.startsWith(\"--before=\")) beforeDur = arg.slice(9); }");
  lines.push("  const before = new Date(Date.now() - parseDuration(beforeDur)).toISOString();");
  lines.push("");
  lines.push("  try {");
  lines.push("    const result = db.prepare(\"DELETE FROM cognition_traces WHERE created_at < ?\").run(before);");
  lines.push("    console.log(`Cleared ${result.changes} trace(s) older than ${beforeDur}.`);");
  lines.push("  } catch (e: any) {");
  lines.push("    if (e.message.includes(\"no such table\")) {");
  lines.push("      console.log(\"No cognition_traces table found.\");");
  lines.push("    } else { throw e; }");
  lines.push("  }");
  lines.push("  db.close();");
  lines.push("}");
  lines.push("");

  // ─── Main ────────────────────────────────────────────────────────────
  lines.push("const [,, cmd, ...rest] = process.argv;");
  lines.push("switch (cmd) {");
  lines.push("  case \"list\": cmdList(rest); break;");
  lines.push("  case \"show\": cmdShow(rest[0] || \"\"); break;");
  lines.push("  case \"stats\": cmdStats(rest); break;");
  lines.push("  case \"clear\": cmdClear(rest); break;");
  lines.push("  default:");
  lines.push("    console.log(\"Usage:\");");
  lines.push("    console.log(\"  npx ts-node bin/traces.ts list [--failed] [--last=24h] [--prompt=name]\");");
  lines.push("    console.log(\"  npx ts-node bin/traces.ts show <trace_id>\");");
  lines.push("    console.log(\"  npx ts-node bin/traces.ts stats [--last=7d]\");");
  lines.push("    console.log(\"  npx ts-node bin/traces.ts clear --before=7d\");");
  lines.push("}");

  return {
    path: "bin/traces.ts",
    content: lines.join("\n"),
    language: "typescript",
    source_module: "cognition",
  };
}
