/**
 * MarrowScript Cognition Traces Emitter (LLM Harness, Phase 6)
 *
 * Generates two artifacts when a system has any prompts:
 *
 *   migrations/cognition_traces.sql   — durable trace store
 *   src/cognition/traces.ts           — span writer + reader
 *   src/traces/exporter.ts            — optional OTLP/JSON exporter
 *
 * Every prompt invocation produces one or more spans:
 *   - one "prompt_call" span per provider chat() round-trip
 *   - one "cache_hit" span when the result was served from the cache
 *   - one "validate" span when validation succeeded or failed
 *   - one "repair" span when the on_invalid recovery branch fired
 *   - one "escalate" span when a router moved up a tier
 *   - one "low_confidence" span when the response confidence fell below
 *     the router's threshold (Phase 7)
 *   - one "budget_exceeded" span when the budget guard pre-empted a call
 *
 * Spans are linked by (trace_id, parent_span_id). The writer never throws
 * on persistence failures — observability must never block a prompt.
 *
 * Determinism:
 *   - schema generation is content-only
 *   - the runtime writer uses crypto.randomUUID for span ids (one of the few
 *     legitimate random sources in this codebase, since spans are by design
 *     unique-per-call)
 *   - redaction reuses emit_audit.ts's @sensitive-aware logic so consistent
 *     fields don't leak into traces
 *
 * Backends, switched by LLM_TRACES_BACKEND:
 *   memory  — in-process ring buffer; useful for tests and dev (default)
 *   pg      — Postgres-backed via the existing src/db pool
 *   none    — drop spans on the floor (cheap escape hatch for production
 *             when a separate observability pipeline is the source of truth)
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

export function tracesNeeded(system: IR.IRSystem): boolean {
  return system.prompts.length > 0;
}

export function emitTraceFiles(system: IR.IRSystem): EmittedFile[] {
  if (!tracesNeeded(system)) return [];
  return [
    {
      path: "migrations/cognition_traces.sql",
      content: emitTraceSchema(),
      language: "sql",
      source_module: "traces",
    },
    {
      path: "src/cognition/traces.ts",
      content: emitTraceRuntime(system),
      language: "typescript",
      source_module: "traces",
    },
    {
      path: "src/traces/exporter.ts",
      content: emitOtelExporter(system),
      language: "typescript",
      source_module: "traces",
    },
    {
      path: "src/routes/cognition_traces.ts",
      content: emitTracesRoute(),
      language: "typescript",
      source_module: "traces",
    },
  ];
}

// ─── HTTP route: GET /cognition_traces/:trace_id ─────────────────────────────
//
// Read-only endpoint that returns every span for a given trace_id, sorted by
// start time. The frontend uses this to render the prompt-by-prompt timeline
// returned alongside a forge_from_repos result. Auth is required (the trace
// payload is redacted but still operationally sensitive).

function emitTracesRoute(): string {
  return `// Generated by MarrowScript compiler. DO NOT EDIT.
// HTTP read API for cognition traces (Phase 6 / frontend-ready).
//
// Routes:
//   GET /cognition_traces/:trace_id   — every span for a trace_id, ordered.
//
// Spans contain redacted projections of the prompt input/output (the full
// payload is never persisted), the model + provider used, the validate
// result, and per-call latency / token usage. The frontend renders this as
// a "what just happened" timeline alongside the forge result.

import { Router, Request, Response } from "express";
import { requireAuth } from "../auth";
import { loadTrace } from "../cognition/traces";
import rateLimit from "express-rate-limit";

export const cognitionTracesRouter = Router();

const __routeRateLimit = rateLimit({ windowMs: 60000, max: 60, standardHeaders: true, legacyHeaders: false });

cognitionTracesRouter.get("/:trace_id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  const { trace_id } = req.params;
  if (!/^[0-9a-f-]{8,}$/i.test(trace_id)) {
    return res.status(400).json({ error: { code: "INVALID_TRACE_ID", message: "trace_id must be a UUID-like string" } });
  }
  try {
    const spans = await loadTrace(trace_id);
    res.json({
      trace_id,
      span_count: spans.length,
      spans,
    });
  } catch (e: any) {
    res.status(500).json({ error: { code: "TRACE_LOAD_FAILED", message: e.message } });
  }
});
`;
}

// ─── Schema ──────────────────────────────────────────────────────────────────

function emitTraceSchema(): string {
  return `-- MarrowScript Cognition Traces (Phase 6)
-- Generated by MarrowScript compiler. DO NOT EDIT.
--
-- One row per cognition span. Spans link via (trace_id, parent_span_id) and
-- form a tree per workflow. The status enum mirrors the failure modes the
-- prompt body emits: ok, validate_failed, timeout, provider_error,
-- budget_exceeded, repair_accepted, repair_rejected, cache_hit,
-- low_confidence, escalated.
--
-- input_redacted and output_redacted are the @sensitive-aware projections of
-- the prompt's actual input / output. The full payload is never persisted.

CREATE TABLE IF NOT EXISTS cognition_traces (
  span_id          UUID         PRIMARY KEY,
  trace_id         UUID         NOT NULL,
  parent_span_id   UUID,
  workflow         VARCHAR      NOT NULL,
  step             VARCHAR      NOT NULL,
  kind             VARCHAR      NOT NULL,
  prompt           VARCHAR,
  model            VARCHAR,
  provider         VARCHAR,
  input_redacted   JSONB,
  output_redacted  JSONB,
  validate_result  VARCHAR,
  confidence       FLOAT,
  prompt_tokens    INT,
  completion_tokens INT,
  cost_usd         NUMERIC(10,6),
  latency_ms       INT,
  cache_hit        BOOLEAN      NOT NULL DEFAULT false,
  status           VARCHAR      NOT NULL,
  error_code       VARCHAR,
  metadata         JSONB,
  started_at       TIMESTAMPTZ  NOT NULL,
  finished_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_cognition_traces_trace
  ON cognition_traces (trace_id, started_at);

CREATE INDEX IF NOT EXISTS idx_cognition_traces_prompt
  ON cognition_traces (prompt, started_at);

CREATE INDEX IF NOT EXISTS idx_cognition_traces_status
  ON cognition_traces (status, started_at);

CREATE INDEX IF NOT EXISTS idx_cognition_traces_model
  ON cognition_traces (model, started_at);
`;
}

// ─── Runtime writer ──────────────────────────────────────────────────────────

function emitTraceRuntime(system: IR.IRSystem): string {
  // Collect always-redact field names from the system. We reuse the same
  // "always redact" set as the audit middleware (passwords, tokens, keys)
  // and union it with @sensitive fields declared on entity / prompt-input
  // models so the same field never leaks just because it's in a prompt input.
  const sensitiveByEntity: Record<string, string[]> = {};
  for (const mod of system.modules) {
    for (const model of mod.models) {
      const fields = model.fields.filter(f => f.sensitive).map(f => f.name);
      if (fields.length > 0) {
        const existing = sensitiveByEntity[model.name] || [];
        sensitiveByEntity[model.name] = Array.from(new Set([...existing, ...fields]));
      }
    }
  }

  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 6 — span writer.");
  lines.push("//");
  lines.push("// Every prompt invocation emits one or more spans through writeSpan().");
  lines.push("// Spans never block the caller: persistence failures are logged and");
  lines.push("// swallowed so a broken DB can't take down inference.");
  lines.push("//");
  lines.push("// Three backends, switched by LLM_TRACES_BACKEND env var:");
  lines.push("//   memory (default)  — in-process ring buffer, capped at 10k spans");
  lines.push("//   pg                — Postgres-backed via src/db pool");
  lines.push("//   none              — drop everything (silent)");
  lines.push("//");
  lines.push("// Redaction mirrors src/audit.ts: any key in ALWAYS_REDACT (case-insensitive)");
  lines.push("// or a @sensitive-tagged field is replaced with \"[REDACTED]\".");
  lines.push("");
  lines.push("import { randomUUID } from \"crypto\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("");
  lines.push("export type SpanKind =");
  lines.push("  | \"prompt_call\"");
  lines.push("  | \"cache_hit\"");
  lines.push("  | \"validate\"");
  lines.push("  | \"repair\"");
  lines.push("  | \"escalate\"");
  lines.push("  | \"low_confidence\"");
  lines.push("  | \"budget_exceeded\"");
  lines.push("  | \"tool_call\";");
  lines.push("");
  lines.push("export type SpanStatus =");
  lines.push("  | \"ok\"");
  lines.push("  | \"validate_failed\"");
  lines.push("  | \"timeout\"");
  lines.push("  | \"provider_error\"");
  lines.push("  | \"budget_exceeded\"");
  lines.push("  | \"repair_accepted\"");
  lines.push("  | \"repair_rejected\"");
  lines.push("  | \"cache_hit\"");
  lines.push("  | \"low_confidence\"");
  lines.push("  | \"escalated\"");
  lines.push("  | \"failed\";");
  lines.push("");
  lines.push("export interface CognitionSpan {");
  lines.push("  span_id: string;");
  lines.push("  trace_id: string;");
  lines.push("  parent_span_id: string | null;");
  lines.push("  workflow: string;");
  lines.push("  step: string;");
  lines.push("  kind: SpanKind;");
  lines.push("  prompt: string | null;");
  lines.push("  model: string | null;");
  lines.push("  provider: string | null;");
  lines.push("  input_redacted: unknown;");
  lines.push("  output_redacted: unknown;");
  lines.push("  validate_result: string | null;");
  lines.push("  confidence: number | null;");
  lines.push("  prompt_tokens: number | null;");
  lines.push("  completion_tokens: number | null;");
  lines.push("  cost_usd: number | null;");
  lines.push("  latency_ms: number;");
  lines.push("  cache_hit: boolean;");
  lines.push("  status: SpanStatus;");
  lines.push("  error_code: string | null;");
  lines.push("  metadata: Record<string, unknown>;");
  lines.push("  started_at: number; // ms epoch");
  lines.push("  finished_at: number | null; // ms epoch");
  lines.push("}");
  lines.push("");
  // Redaction.
  lines.push(`// Per-entity @sensitive field map, derived at compile time.`);
  lines.push(`const SENSITIVE_FIELDS: Record<string, ReadonlyArray<string>> = ${JSON.stringify(sensitiveByEntity, null, 2)};`);
  lines.push("");
  lines.push("// Always-redacted keys regardless of entity. Names matched case-insensitively.");
  lines.push("const ALWAYS_REDACT = new Set([");
  lines.push("  \"password\", \"passwd\", \"pwd\", \"secret\", \"token\", \"api_key\", \"apikey\",");
  lines.push("  \"authorization\", \"bearer\", \"ssn\", \"card_number\", \"cvv\",");
  lines.push("]);");
  lines.push("");
  lines.push("function redactValue(value: unknown, entityHint?: string): unknown {");
  lines.push("  if (value === null || value === undefined) return value;");
  lines.push("  if (typeof value !== \"object\") return value;");
  lines.push("  if (Array.isArray(value)) return value.map(v => redactValue(v, entityHint));");
  lines.push("  const out: Record<string, unknown> = {};");
  lines.push("  const sensitiveSet = entityHint ? new Set(SENSITIVE_FIELDS[entityHint] || []) : new Set<string>();");
  lines.push("  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {");
  lines.push("    if (ALWAYS_REDACT.has(k.toLowerCase()) || sensitiveSet.has(k)) {");
  lines.push("      out[k] = \"[REDACTED]\";");
  lines.push("    } else {");
  lines.push("      out[k] = redactValue(v, entityHint);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return out;");
  lines.push("}");
  lines.push("");
  lines.push("export function redactForTrace(value: unknown, entityHint?: string): unknown {");
  lines.push("  return redactValue(value, entityHint);");
  lines.push("}");
  lines.push("");
  // Backends.
  lines.push("export interface SpanBackend {");
  lines.push("  write(span: CognitionSpan): Promise<void>;");
  lines.push("  /** Read all spans for a trace. */");
  lines.push("  loadTrace(trace_id: string): Promise<CognitionSpan[]>;");
  lines.push("  /** For tests. */");
  lines.push("  __reset?(): void;");
  lines.push("}");
  lines.push("");
  lines.push("class MemoryBackend implements SpanBackend {");
  lines.push("  private buffer: CognitionSpan[] = [];");
  lines.push("  private readonly cap = 10_000;");
  lines.push("  async write(span: CognitionSpan): Promise<void> {");
  lines.push("    this.buffer.push(span);");
  lines.push("    if (this.buffer.length > this.cap) {");
  lines.push("      this.buffer.splice(0, this.buffer.length - this.cap);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  async loadTrace(trace_id: string): Promise<CognitionSpan[]> {");
  lines.push("    return this.buffer.filter(s => s.trace_id === trace_id).sort((a, b) => a.started_at - b.started_at);");
  lines.push("  }");
  lines.push("  __reset(): void { this.buffer = []; }");
  lines.push("}");
  lines.push("");
  lines.push("class PgBackend implements SpanBackend {");
  lines.push("  async write(span: CognitionSpan): Promise<void> {");
  lines.push("    // Lazy import — keeps tests that don't exercise PG free of pg.");
  lines.push("    // eslint-disable-next-line @typescript-eslint/no-require-imports");
  lines.push("    const { query } = require(\"../db\") as { query: (sql: string, args: unknown[]) => Promise<unknown> };");
  lines.push("    await query(");
  lines.push("      `INSERT INTO cognition_traces (");
  lines.push("        span_id, trace_id, parent_span_id, workflow, step, kind, prompt, model, provider,");
  lines.push("        input_redacted, output_redacted, validate_result, confidence,");
  lines.push("        prompt_tokens, completion_tokens, cost_usd, latency_ms, cache_hit,");
  lines.push("        status, error_code, metadata, started_at, finished_at");
  lines.push("      ) VALUES (");
  lines.push("        $1, $2, $3, $4, $5, $6, $7, $8, $9,");
  lines.push("        $10, $11, $12, $13, $14, $15, $16, $17, $18,");
  lines.push("        $19, $20, $21, to_timestamp($22 / 1000.0), to_timestamp($23 / 1000.0)");
  lines.push("      )");
  lines.push("      ON CONFLICT (span_id) DO NOTHING`,");
  lines.push("      [");
  lines.push("        span.span_id, span.trace_id, span.parent_span_id,");
  lines.push("        span.workflow, span.step, span.kind, span.prompt, span.model, span.provider,");
  lines.push("        JSON.stringify(span.input_redacted), JSON.stringify(span.output_redacted),");
  lines.push("        span.validate_result, span.confidence,");
  lines.push("        span.prompt_tokens, span.completion_tokens, span.cost_usd, span.latency_ms, span.cache_hit,");
  lines.push("        span.status, span.error_code, JSON.stringify(span.metadata),");
  lines.push("        span.started_at, span.finished_at,");
  lines.push("      ],");
  lines.push("    );");
  lines.push("  }");
  lines.push("  async loadTrace(trace_id: string): Promise<CognitionSpan[]> {");
  lines.push("    // eslint-disable-next-line @typescript-eslint/no-require-imports");
  lines.push("    const { query } = require(\"../db\") as { query: (sql: string, args: unknown[]) => Promise<Record<string, unknown>[]> };");
  lines.push("    const rows = await query(");
  lines.push("      \"SELECT * FROM cognition_traces WHERE trace_id = $1 ORDER BY started_at\",");
  lines.push("      [trace_id],");
  lines.push("    );");
  lines.push("    return rows.map(rowToSpan);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("class NoopBackend implements SpanBackend {");
  lines.push("  async write(_span: CognitionSpan): Promise<void> { /* drop */ }");
  lines.push("  async loadTrace(_trace_id: string): Promise<CognitionSpan[]> { return []; }");
  lines.push("}");
  lines.push("");
  lines.push("function rowToSpan(r: Record<string, unknown>): CognitionSpan {");
  lines.push("  return {");
  lines.push("    span_id: String(r.span_id),");
  lines.push("    trace_id: String(r.trace_id),");
  lines.push("    parent_span_id: r.parent_span_id == null ? null : String(r.parent_span_id),");
  lines.push("    workflow: String(r.workflow),");
  lines.push("    step: String(r.step),");
  lines.push("    kind: r.kind as SpanKind,");
  lines.push("    prompt: r.prompt == null ? null : String(r.prompt),");
  lines.push("    model: r.model == null ? null : String(r.model),");
  lines.push("    provider: r.provider == null ? null : String(r.provider),");
  lines.push("    input_redacted: r.input_redacted ?? null,");
  lines.push("    output_redacted: r.output_redacted ?? null,");
  lines.push("    validate_result: r.validate_result == null ? null : String(r.validate_result),");
  lines.push("    confidence: r.confidence == null ? null : Number(r.confidence),");
  lines.push("    prompt_tokens: r.prompt_tokens == null ? null : Number(r.prompt_tokens),");
  lines.push("    completion_tokens: r.completion_tokens == null ? null : Number(r.completion_tokens),");
  lines.push("    cost_usd: r.cost_usd == null ? null : Number(r.cost_usd),");
  lines.push("    latency_ms: Number(r.latency_ms ?? 0),");
  lines.push("    cache_hit: Boolean(r.cache_hit),");
  lines.push("    status: r.status as SpanStatus,");
  lines.push("    error_code: r.error_code == null ? null : String(r.error_code),");
  lines.push("    metadata: (r.metadata as Record<string, unknown>) ?? {},");
  lines.push("    started_at: r.started_at instanceof Date ? r.started_at.getTime() : Number(r.started_at),");
  lines.push("    finished_at: r.finished_at == null ? null : (r.finished_at instanceof Date ? r.finished_at.getTime() : Number(r.finished_at)),");
  lines.push("  };");
  lines.push("}");
  lines.push("");
  lines.push("function chooseBackend(): SpanBackend {");
  lines.push("  const mode = process.env.LLM_TRACES_BACKEND || \"memory\";");
  lines.push("  if (mode === \"pg\") return new PgBackend();");
  lines.push("  if (mode === \"none\") return new NoopBackend();");
  lines.push("  if (mode !== \"memory\") {");
  lines.push("    logger.warn(\"traces_unknown_backend\", { event: \"traces\", status: \"rejected\", metadata: { mode } });");
  lines.push("  }");
  lines.push("  return new MemoryBackend();");
  lines.push("}");
  lines.push("");
  lines.push("const __backend: SpanBackend = chooseBackend();");
  lines.push("");
  // Public writer / reader.
  lines.push("export interface SpanInit {");
  lines.push("  trace_id: string;");
  lines.push("  parent_span_id?: string | null;");
  lines.push("  workflow: string;");
  lines.push("  step: string;");
  lines.push("  kind: SpanKind;");
  lines.push("  prompt?: string;");
  lines.push("  model?: string;");
  lines.push("  provider?: string;");
  lines.push("  input?: unknown;");
  lines.push("  output?: unknown;");
  lines.push("  input_entity_hint?: string;");
  lines.push("  output_entity_hint?: string;");
  lines.push("  validate_result?: \"ok\" | \"failed\" | \"skipped\";");
  lines.push("  confidence?: number;");
  lines.push("  prompt_tokens?: number;");
  lines.push("  completion_tokens?: number;");
  lines.push("  cost_usd?: number;");
  lines.push("  latency_ms: number;");
  lines.push("  cache_hit?: boolean;");
  lines.push("  status: SpanStatus;");
  lines.push("  error_code?: string;");
  lines.push("  metadata?: Record<string, unknown>;");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Persist a cognition span. Never throws — failures are logged and counted.");
  lines.push(" * The span_id is generated here so callers don't have to reach for randomUUID.");
  lines.push(" */");
  lines.push("export async function writeSpan(init: SpanInit): Promise<string> {");
  lines.push("  const now = Date.now();");
  lines.push("  const span: CognitionSpan = {");
  lines.push("    span_id: randomUUID(),");
  lines.push("    trace_id: init.trace_id,");
  lines.push("    parent_span_id: init.parent_span_id ?? null,");
  lines.push("    workflow: init.workflow,");
  lines.push("    step: init.step,");
  lines.push("    kind: init.kind,");
  lines.push("    prompt: init.prompt ?? null,");
  lines.push("    model: init.model ?? null,");
  lines.push("    provider: init.provider ?? null,");
  lines.push("    input_redacted: init.input === undefined ? null : redactValue(init.input, init.input_entity_hint),");
  lines.push("    output_redacted: init.output === undefined ? null : redactValue(init.output, init.output_entity_hint),");
  lines.push("    validate_result: init.validate_result ?? null,");
  lines.push("    confidence: init.confidence ?? null,");
  lines.push("    prompt_tokens: init.prompt_tokens ?? null,");
  lines.push("    completion_tokens: init.completion_tokens ?? null,");
  lines.push("    cost_usd: init.cost_usd ?? null,");
  lines.push("    latency_ms: init.latency_ms,");
  lines.push("    cache_hit: init.cache_hit ?? false,");
  lines.push("    status: init.status,");
  lines.push("    error_code: init.error_code ?? null,");
  lines.push("    metadata: init.metadata ?? {},");
  lines.push("    started_at: now - init.latency_ms,");
  lines.push("    finished_at: now,");
  lines.push("  };");
  lines.push("  try {");
  lines.push("    await __backend.write(span);");
  lines.push("    counter(\"cognition.span_written\", { kind: init.kind, status: init.status });");
  lines.push("  } catch (e) {");
  lines.push("    counter(\"cognition.span_write_failed\");");
  lines.push("    const msg = e instanceof Error ? e.message : String(e);");
  lines.push("    logger.warn(\"cognition_span_write_failed\", { event: \"traces\", status: \"rejected\", trace_id: span.trace_id, metadata: { error: msg.slice(0, 256) } });");
  lines.push("  }");
  lines.push("  return span.span_id;");
  lines.push("}");
  lines.push("");
  lines.push("/** Load all spans for a trace, sorted by start time. */");
  lines.push("export async function loadTrace(trace_id: string): Promise<CognitionSpan[]> {");
  lines.push("  return __backend.loadTrace(trace_id);");
  lines.push("}");
  lines.push("");
  lines.push("/** For tests: reset the in-memory backend. */");
  lines.push("export function __resetTraces(): void {");
  lines.push("  if (__backend.__reset) __backend.__reset();");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── OTLP exporter ───────────────────────────────────────────────────────────

function emitOtelExporter(_system: IR.IRSystem): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 6 — OTLP/JSON span exporter.");
  lines.push("//");
  lines.push("// Translates CognitionSpan into the OpenTelemetry resource-spans JSON shape");
  lines.push("// (https://opentelemetry.io/docs/specs/otlp/#otlphttp-request) and POSTs it");
  lines.push("// to OTEL_EXPORTER_OTLP_ENDPOINT (default disabled). Bring-your-own-collector;");
  lines.push("// we keep the dependency surface to fetch and JSON only so this file works in");
  lines.push("// any node 18+ runtime.");
  lines.push("");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("import type { CognitionSpan } from \"../cognition/traces\";");
  lines.push("");
  // OTLP shape uses 16-byte trace_id / 8-byte span_id hex strings. Cognition
  // span ids are full UUIDs; we hash them down to fit OTLP without collisions
  // for any realistic span volume. The brief explicitly says this exporter is
  // bring-your-own-collector, so collisions across very large traces are out
  // of scope here.
  lines.push("import { createHash } from \"crypto\";");
  lines.push("");
  lines.push("function uuidToBytes(uuid: string, length: number): string {");
  lines.push("  return createHash(\"sha256\").update(uuid).digest(\"hex\").slice(0, length * 2);");
  lines.push("}");
  lines.push("");
  lines.push("const ENDPOINT = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || \"\";");
  lines.push("const SERVICE_NAME = process.env.OTEL_SERVICE_NAME || \"marrowscript-harness\";");
  lines.push("const HEADERS = (() => {");
  lines.push("  const raw = process.env.OTEL_EXPORTER_OTLP_HEADERS || \"\";");
  lines.push("  const out: Record<string, string> = { \"Content-Type\": \"application/json\" };");
  lines.push("  for (const part of raw.split(\",\")) {");
  lines.push("    const eq = part.indexOf(\"=\");");
  lines.push("    if (eq <= 0) continue;");
  lines.push("    out[part.slice(0, eq).trim()] = part.slice(eq + 1).trim();");
  lines.push("  }");
  lines.push("  return out;");
  lines.push("})();");
  lines.push("");
  lines.push("function spanToOtlp(span: CognitionSpan): Record<string, unknown> {");
  lines.push("  // OTLP span Status: 0=Unset, 1=Ok, 2=Error");
  lines.push("  const statusCode = span.status === \"ok\" || span.status === \"cache_hit\" || span.status === \"repair_accepted\" ? 1 : 2;");
  lines.push("  const attributes: Record<string, unknown>[] = [");
  lines.push("    { key: \"cognition.workflow\", value: { stringValue: span.workflow } },");
  lines.push("    { key: \"cognition.step\", value: { stringValue: span.step } },");
  lines.push("    { key: \"cognition.kind\", value: { stringValue: span.kind } },");
  lines.push("    { key: \"cognition.cache_hit\", value: { boolValue: span.cache_hit } },");
  lines.push("    { key: \"cognition.status\", value: { stringValue: span.status } },");
  lines.push("  ];");
  lines.push("  if (span.prompt) attributes.push({ key: \"cognition.prompt\", value: { stringValue: span.prompt } });");
  lines.push("  if (span.model) attributes.push({ key: \"llm.model\", value: { stringValue: span.model } });");
  lines.push("  if (span.provider) attributes.push({ key: \"llm.provider\", value: { stringValue: span.provider } });");
  lines.push("  if (span.prompt_tokens != null) attributes.push({ key: \"llm.usage.prompt_tokens\", value: { intValue: span.prompt_tokens } });");
  lines.push("  if (span.completion_tokens != null) attributes.push({ key: \"llm.usage.completion_tokens\", value: { intValue: span.completion_tokens } });");
  lines.push("  if (span.cost_usd != null) attributes.push({ key: \"llm.usage.cost_usd\", value: { doubleValue: span.cost_usd } });");
  lines.push("  if (span.confidence != null) attributes.push({ key: \"cognition.confidence\", value: { doubleValue: span.confidence } });");
  lines.push("  if (span.error_code) attributes.push({ key: \"cognition.error_code\", value: { stringValue: span.error_code } });");
  lines.push("  return {");
  lines.push("    traceId: uuidToBytes(span.trace_id, 16),");
  lines.push("    spanId: uuidToBytes(span.span_id, 8),");
  lines.push("    parentSpanId: span.parent_span_id ? uuidToBytes(span.parent_span_id, 8) : undefined,");
  lines.push("    name: `${span.workflow}.${span.step}`,");
  lines.push("    kind: 1, // INTERNAL");
  lines.push("    startTimeUnixNano: String(BigInt(span.started_at) * 1_000_000n),");
  lines.push("    endTimeUnixNano: String(BigInt(span.finished_at ?? span.started_at) * 1_000_000n),");
  lines.push("    attributes,");
  lines.push("    status: { code: statusCode, message: span.error_code ?? \"\" },");
  lines.push("  };");
  lines.push("}");
  lines.push("");
  lines.push("/** Build the OTLP/JSON request body for a batch of spans. Exposed for testing. */");
  lines.push("export function buildOtlpPayload(spans: CognitionSpan[]): Record<string, unknown> {");
  lines.push("  return {");
  lines.push("    resourceSpans: [{");
  lines.push("      resource: {");
  lines.push("        attributes: [");
  lines.push("          { key: \"service.name\", value: { stringValue: SERVICE_NAME } },");
  lines.push("        ],");
  lines.push("      },");
  lines.push("      scopeSpans: [{");
  lines.push("        scope: { name: \"marrowscript.cognition\", version: \"1\" },");
  lines.push("        spans: spans.map(spanToOtlp),");
  lines.push("      }],");
  lines.push("    }],");
  lines.push("  };");
  lines.push("}");
  lines.push("");
  lines.push("/** Send a batch. No-op when OTEL_EXPORTER_OTLP_ENDPOINT is unset. */");
  lines.push("export async function exportBatch(spans: CognitionSpan[]): Promise<{ ok: boolean; status?: number }> {");
  lines.push("  if (!ENDPOINT) {");
  lines.push("    counter(\"otel.export.skipped\");");
  lines.push("    return { ok: true };");
  lines.push("  }");
  lines.push("  if (spans.length === 0) return { ok: true };");
  lines.push("  const body = JSON.stringify(buildOtlpPayload(spans));");
  lines.push("  try {");
  lines.push("    const res = await fetch(ENDPOINT.replace(/\\/+$/, \"\") + \"/v1/traces\", {");
  lines.push("      method: \"POST\",");
  lines.push("      headers: HEADERS,");
  lines.push("      body,");
  lines.push("    });");
  lines.push("    counter(res.ok ? \"otel.export.ok\" : \"otel.export.failed\", { status: String(res.status) });");
  lines.push("    if (!res.ok) {");
  lines.push("      logger.warn(\"otel_export_failed\", { event: \"otel\", status: \"rejected\", metadata: { http_status: res.status } });");
  lines.push("    }");
  lines.push("    return { ok: res.ok, status: res.status };");
  lines.push("  } catch (e) {");
  lines.push("    counter(\"otel.export.error\");");
  lines.push("    const msg = e instanceof Error ? e.message : String(e);");
  lines.push("    logger.warn(\"otel_export_error\", { event: \"otel\", status: \"rejected\", metadata: { error: msg.slice(0, 256) } });");
  lines.push("    return { ok: false };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
