/**
 * MarrowScript Memory Emitter (LLM Harness, Phase 4)
 *
 * Generates the graph-based semantic memory layer:
 *
 *   migrations/semantic_index.sql   — symbols + imports + calls + file_summaries
 *   src/memory/types.ts             — shared types
 *   src/memory/semantic_index.ts    — symbol extractor + index loader
 *   src/memory/retriever.ts         — bounded BFS over the graph
 *   src/memory/compressor.ts        — token-budgeted code-slice serializer
 *   src/memory/index.ts             — public entry: getIndex(), refreshIndex()
 *   bin/index_sources.ts            — script that runs the indexer at build time
 *
 * Contract (matches the cognition_catalog stub):
 *   index.walk(task: string, hopDepth: number, maxFiles: number)
 *     → { files: string[]; symbols: string[] }
 *
 * Determinism:
 *   - Sort everything by qualified id at every traversal step so BFS produces
 *     identical results for the same input.
 *   - The indexer hashes file contents and key tuples deterministically.
 *
 * Backends:
 *   - memory (default): in-process, suitable for tests and single-instance
 *     dev. The indexer populates an in-memory store on import.
 *   - pg: same data but persisted via migrations/semantic_index.sql, suitable
 *     for HA workers and shared indexes. Switched by LLM_MEMORY_BACKEND.
 *
 * The memory layer emits files only when at least one capability uses the
 * `semantic_slice` cognition primitive, OR the user opts in by setting any
 * `model` to provider:`http` and the harness wants graph-based retrieval. To
 * keep the rule simple, we emit when the system has prompts AND any
 * cognition primitive in {semantic_slice, compress_context} is referenced.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

// ─── Public entry ────────────────────────────────────────────────────────────

/**
 * Decide whether memory files should be emitted. Two triggers:
 *   1. A capability uses `cognition: semantic_slice` or `cognition: compress_context`.
 *   2. The user explicitly opts in by declaring a memory primitive elsewhere
 *      (covered by trigger 1 since both primitives go through the catalog).
 */
export function memoryNeeded(system: IR.IRSystem): boolean {
  const memoryPrimitives = new Set(["semantic_slice", "compress_context"]);
  for (const mod of system.modules) {
    for (const iface of mod.interfaces) {
      for (const m of iface.methods) {
        if (m.cognition && memoryPrimitives.has(m.cognition.catalog_name)) return true;
      }
    }
  }
  // Phase 15: tool capabilities are not in the module tree but still pull
  // memory primitives in when they reference them.
  for (const t of system.tool_capabilities) {
    if (memoryPrimitives.has(t.cognition_primitive)) return true;
  }
  return false;
}

export function emitMemoryFiles(system: IR.IRSystem): EmittedFile[] {
  if (!memoryNeeded(system)) return [];

  return [
    {
      path: "migrations/semantic_index.sql",
      content: emitSemanticIndexSchema(),
      language: "sql",
      source_module: "memory",
    },
    {
      path: "src/memory/types.ts",
      content: emitMemoryTypes(),
      language: "typescript",
      source_module: "memory",
    },
    {
      path: "src/memory/semantic_index.ts",
      content: emitSemanticIndexRuntime(),
      language: "typescript",
      source_module: "memory",
    },
    {
      path: "src/memory/retriever.ts",
      content: emitRetriever(),
      language: "typescript",
      source_module: "memory",
    },
    {
      path: "src/memory/compressor.ts",
      content: emitCompressor(),
      language: "typescript",
      source_module: "memory",
    },
    {
      path: "src/memory/index.ts",
      content: emitMemoryIndexFile(),
      language: "typescript",
      source_module: "memory",
    },
    {
      path: "bin/index_sources.ts",
      content: emitIndexerScript(),
      language: "typescript",
      source_module: "memory",
    },
  ];
}

// ─── Postgres schema ─────────────────────────────────────────────────────────

function emitSemanticIndexSchema(): string {
  return `-- MarrowScript Memory Layer Phase 4
-- Generated by MarrowScript compiler. DO NOT EDIT.
--
-- Five tables that together form a small symbol-relationship graph:
--
--   symbols          one row per named declaration in the indexed corpus
--   imports          directed edge: importer file -> imported file
--   calls            directed edge: caller symbol -> callee symbol
--                    (best-effort — local resolution only)
--   file_summaries   per-file content hash, token count, optional summary
--   task_anchors     persisted seed lookups (task -> ranked symbol ids)
--                    so cold reads don't have to rebuild keyword scores
--
-- Indexes are tuned for the bounded BFS the retriever performs: lookups
-- are always (file, kind, name) or (from_file, to_file). Foreign keys are
-- omitted intentionally — a stale row beats a cascade-deletes-everything
-- migration. The indexer treats stale rows as cache invalidation hints.

CREATE TABLE IF NOT EXISTS symbols (
  id            VARCHAR(64) PRIMARY KEY,
  -- repo_id (Phase 10): tags every symbol with the repository it came from
  -- so per-repo filtering at retrieval time is cheap. Nullable + default '' so
  -- single-repo deployments don't have to set it; the indexer's --repo-id
  -- flag fills it in for multi-repo runs (forge_from_repos pipeline).
  repo_id       VARCHAR(64) NOT NULL DEFAULT '',
  file          VARCHAR     NOT NULL,
  name          VARCHAR     NOT NULL,
  kind          VARCHAR     NOT NULL,
  line          INT         NOT NULL,
  col           INT         NOT NULL DEFAULT 0,
  visibility    VARCHAR     NOT NULL DEFAULT 'internal',
  signature     TEXT,
  doc_excerpt   TEXT,
  content_hash  VARCHAR(64) NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_symbols_file ON symbols (file, kind);
CREATE INDEX IF NOT EXISTS idx_symbols_name ON symbols (name);
CREATE INDEX IF NOT EXISTS idx_symbols_kind ON symbols (kind);
CREATE INDEX IF NOT EXISTS idx_symbols_repo ON symbols (repo_id);

CREATE TABLE IF NOT EXISTS imports (
  repo_id       VARCHAR(64) NOT NULL DEFAULT '',
  importer_file VARCHAR NOT NULL,
  imported_file VARCHAR NOT NULL,
  weight        INT     NOT NULL DEFAULT 1,
  PRIMARY KEY (repo_id, importer_file, imported_file)
);

CREATE INDEX IF NOT EXISTS idx_imports_imported ON imports (imported_file);
CREATE INDEX IF NOT EXISTS idx_imports_repo ON imports (repo_id);

CREATE TABLE IF NOT EXISTS calls (
  repo_id    VARCHAR(64) NOT NULL DEFAULT '',
  caller_id  VARCHAR(64) NOT NULL,
  callee_id  VARCHAR(64) NOT NULL,
  weight     INT         NOT NULL DEFAULT 1,
  PRIMARY KEY (repo_id, caller_id, callee_id)
);

CREATE INDEX IF NOT EXISTS idx_calls_callee ON calls (callee_id);
CREATE INDEX IF NOT EXISTS idx_calls_repo ON calls (repo_id);

CREATE TABLE IF NOT EXISTS file_summaries (
  repo_id       VARCHAR(64) NOT NULL DEFAULT '',
  file          VARCHAR     NOT NULL,
  content_hash  VARCHAR(64) NOT NULL,
  token_count   INT         NOT NULL,
  summary       TEXT,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (repo_id, file)
);

CREATE TABLE IF NOT EXISTS task_anchors (
  task_hash    VARCHAR(64) PRIMARY KEY,
  task         TEXT        NOT NULL,
  symbol_ids   JSONB       NOT NULL,
  scored_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
`;
}

// ─── Shared types ────────────────────────────────────────────────────────────

function emitMemoryTypes(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 4 — semantic memory shared types.");
  lines.push("");
  lines.push("export type SymbolKind =");
  lines.push("  | \"function\"");
  lines.push("  | \"method\"");
  lines.push("  | \"class\"");
  lines.push("  | \"interface\"");
  lines.push("  | \"type\"");
  lines.push("  | \"const\"");
  lines.push("  | \"enum\"");
  lines.push("  | \"namespace\"");
  lines.push("  | \"variable\";");
  lines.push("");
  lines.push("export interface Symbol {");
  lines.push("  /** Stable hash-based id. Stable across runs for the same content. */");
  lines.push("  id: string;");
  lines.push("  /** Repository this symbol came from. Phase 10: empty string for");
  lines.push("   *  single-repo deployments; the offline indexer's --repo-id flag");
  lines.push("   *  fills it in for multi-repo runs. */");
  lines.push("  repo_id: string;");
  lines.push("  /** Repo-relative file path with forward slashes. */");
  lines.push("  file: string;");
  lines.push("  name: string;");
  lines.push("  kind: SymbolKind;");
  lines.push("  /** 1-based line number. */");
  lines.push("  line: number;");
  lines.push("  col: number;");
  lines.push("  visibility: \"public\" | \"internal\" | \"private\";");
  lines.push("  signature: string | null;");
  lines.push("  doc_excerpt: string | null;");
  lines.push("}");
  lines.push("");
  lines.push("export interface ImportEdge {");
  lines.push("  repo_id: string;");
  lines.push("  importer_file: string;");
  lines.push("  imported_file: string;");
  lines.push("  weight: number;");
  lines.push("}");
  lines.push("");
  lines.push("export interface CallEdge {");
  lines.push("  repo_id: string;");
  lines.push("  caller_id: string;");
  lines.push("  callee_id: string;");
  lines.push("  weight: number;");
  lines.push("}");
  lines.push("");
  lines.push("export interface FileSummary {");
  lines.push("  repo_id: string;");
  lines.push("  file: string;");
  lines.push("  content_hash: string;");
  lines.push("  token_count: number;");
  lines.push("  summary: string | null;");
  lines.push("}");
  lines.push("");
  lines.push("/** Optional retrieval filter — restrict the walk to one or more repos. */");
  lines.push("export type RepoFilter = string | string[] | null | undefined;");
  lines.push("");
  lines.push("/** Result of a semantic-slice walk. Keeps the wire shape tiny. */");
  lines.push("export interface SemanticSlice {");
  lines.push("  files: string[];");
  lines.push("  symbols: string[];");
  lines.push("  /** Most relevant symbol — handy for the prompt's target_symbol slot. */");
  lines.push("  target_symbol: string;");
  lines.push("}");
  lines.push("");
  lines.push("/** The contract the cognition catalog's semantic_slice primitive expects. */");
  lines.push("export interface SemanticIndex {");
  lines.push("  /** Walk the index. `repo_filter` is Phase 10: when set, only files");
  lines.push("   *  belonging to the listed repo_ids are eligible. */");
  lines.push("  walk(task: string, hopDepth: number, maxFiles: number, repo_filter?: RepoFilter): SemanticSlice;");
  lines.push("  symbolsByFile(file: string): Symbol[];");
  lines.push("  importsOf(file: string): string[];");
  lines.push("  /** Re-index. Cheap when content hashes haven't changed. */");
  lines.push("  refresh(): Promise<void>;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Indexer (TypeScript) ────────────────────────────────────────────────────

function emitSemanticIndexRuntime(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 4 — TypeScript symbol extractor + index loader.");
  lines.push("//");
  lines.push("// Two backends:");
  lines.push("//   memory (default): walks the source tree at startup and holds the graph");
  lines.push("//                     in process. Cheap for small / medium repos.");
  lines.push("//   pg              : queries Postgres tables populated by bin/index_sources.ts");
  lines.push("//                     so multiple workers share an index without re-walking.");
  lines.push("//");
  lines.push("// LLM_MEMORY_BACKEND switches modes; LLM_MEMORY_ROOT (default: process.cwd())");
  lines.push("// is the indexed root. Files matching LLM_MEMORY_EXCLUDE (default:");
  lines.push("// node_modules, dist, .git, build) are skipped.");
  lines.push("//");
  lines.push("// Determinism: file walk is sorted, BFS expansion is sorted, and ids are");
  lines.push("// derived from sha256 hashes. Two runs against the same tree produce");
  lines.push("// identical graphs.");
  lines.push("");
  lines.push("import * as fs from \"fs\";");
  lines.push("import * as path from \"path\";");
  lines.push("import { createHash } from \"crypto\";");
  lines.push("import type { Symbol, SymbolKind, ImportEdge, FileSummary } from \"./types\";");
  lines.push("");
  lines.push("// Lazy import of typescript so the memory layer doesn't force the dep");
  lines.push("// when only file-level retrieval is needed (see PythonStrategy below for");
  lines.push("// the language-extension hook). The TS compiler API is the canonical");
  lines.push("// AST source — anything regex-based is too brittle for export tracking.");
  lines.push("function loadTypescript(): typeof import(\"typescript\") | null {");
  lines.push("  try {");
  lines.push("    // eslint-disable-next-line @typescript-eslint/no-require-imports");
  lines.push("    return require(\"typescript\") as typeof import(\"typescript\");");
  lines.push("  } catch {");
  lines.push("    return null;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export function deriveSymbolId(file: string, name: string, line: number): string {");
  lines.push("  return createHash(\"sha256\").update(`${file}#${name}@${line}`).digest(\"hex\").slice(0, 32);");
  lines.push("}");
  lines.push("");
  lines.push("export function approxTokens(s: string): number { return Math.ceil(s.length / 4); }");
  lines.push("");
  lines.push("/** Sorted, deterministic recursive walk over a project root. */");
  lines.push("export function listSourceFiles(root: string, excludes: string[]): string[] {");
  lines.push("  const result: string[] = [];");
  lines.push("  const stack: string[] = [root];");
  lines.push("  const seen = new Set<string>();");
  lines.push("  while (stack.length) {");
  lines.push("    const dir = stack.pop()!;");
  lines.push("    let entries: fs.Dirent[];");
  lines.push("    try { entries = fs.readdirSync(dir, { withFileTypes: true }); }");
  lines.push("    catch { continue; }");
  lines.push("    entries.sort((a, b) => a.name.localeCompare(b.name));");
  lines.push("    for (const e of entries) {");
  lines.push("      const full = path.join(dir, e.name);");
  lines.push("      const rel = path.relative(root, full).replace(/\\\\/g, \"/\");");
  lines.push("      if (excludes.some(x => rel === x || rel.startsWith(x + \"/\"))) continue;");
  lines.push("      if (e.isDirectory()) {");
  lines.push("        stack.push(full);");
  lines.push("      } else if (e.isFile() && /\\.(ts|tsx|js|jsx|mts|cts)$/.test(e.name)) {");
  lines.push("        if (seen.has(rel)) continue;");
  lines.push("        seen.add(rel);");
  lines.push("        result.push(rel);");
  lines.push("      }");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return result.sort();");
  lines.push("}");
  lines.push("");
  // Symbol extractor — uses TypeScript compiler API when present, falls back
  // to a tiny regex strategy when not. The fallback is deliberately narrow:
  // export function / export class / export interface / export const at line
  // start. Anything more sophisticated needs the real AST.
  lines.push("interface ExtractedFile {");
  lines.push("  file: string;");
  lines.push("  content_hash: string;");
  lines.push("  symbols: Symbol[];");
  lines.push("  imports: string[];");
  lines.push("  token_count: number;");
  lines.push("}");
  lines.push("");
  lines.push("export function extractFile(absPath: string, relPath: string): ExtractedFile {");
  lines.push("  const content = fs.readFileSync(absPath, \"utf-8\");");
  lines.push("  const content_hash = createHash(\"sha256\").update(content).digest(\"hex\").slice(0, 32);");
  lines.push("  const ts = loadTypescript();");
  lines.push("  if (ts) return extractWithTypescript(ts, content, content_hash, relPath);");
  lines.push("  return extractWithRegex(content, content_hash, relPath);");
  lines.push("}");
  lines.push("");
  lines.push("function extractWithTypescript(");
  lines.push("  ts: typeof import(\"typescript\"),");
  lines.push("  content: string,");
  lines.push("  content_hash: string,");
  lines.push("  file: string,");
  lines.push("): ExtractedFile {");
  lines.push("  const sf = ts.createSourceFile(file, content, ts.ScriptTarget.Latest, true);");
  lines.push("  const symbols: Symbol[] = [];");
  lines.push("  const imports: string[] = [];");
  lines.push("");
  lines.push("  function lineOf(pos: number): number { return sf.getLineAndCharacterOfPosition(pos).line + 1; }");
  lines.push("  function colOf(pos: number): number { return sf.getLineAndCharacterOfPosition(pos).character; }");
  lines.push("");
  lines.push("  function visibilityOf(node: import(\"typescript\").Node): \"public\" | \"internal\" | \"private\" {");
  lines.push("    const text = node.getText(sf).slice(0, 64);");
  lines.push("    if (text.startsWith(\"export \") || text.includes(\"\\nexport \")) return \"public\";");
  lines.push("    if (text.startsWith(\"private \")) return \"private\";");
  lines.push("    return \"internal\";");
  lines.push("  }");
  lines.push("");
  lines.push("  function pushSymbol(name: string, kind: SymbolKind, node: import(\"typescript\").Node, signature?: string) {");
  lines.push("    const line = lineOf(node.getStart(sf));");
  lines.push("    symbols.push({");
  lines.push("      id: deriveSymbolId(file, name, line),");
  lines.push("      // Phase 10: repo_id is set by buildIndex() when it stamps each");
  lines.push("      // symbol. The extractor doesn't know the repo identity (it's");
  lines.push("      // file-local), so we initialise to '' and let buildIndex spread");
  lines.push("      // the right value over the result.");
  lines.push("      repo_id: \"\",");
  lines.push("      file,");
  lines.push("      name,");
  lines.push("      kind,");
  lines.push("      line,");
  lines.push("      col: colOf(node.getStart(sf)),");
  lines.push("      visibility: visibilityOf(node),");
  lines.push("      signature: signature ?? null,");
  lines.push("      doc_excerpt: null,");
  lines.push("    });");
  lines.push("  }");
  lines.push("");
  lines.push("  function visit(node: import(\"typescript\").Node) {");
  lines.push("    // Imports / re-exports — record the resolved path string.");
  lines.push("    if (ts.isImportDeclaration(node) && ts.isStringLiteral(node.moduleSpecifier)) {");
  lines.push("      imports.push(node.moduleSpecifier.text);");
  lines.push("    } else if (ts.isExportDeclaration(node) && node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier)) {");
  lines.push("      imports.push(node.moduleSpecifier.text);");
  lines.push("    }");
  lines.push("    // Top-level decls — narrow set, the kinds the retriever cares about.");
  lines.push("    if (ts.isFunctionDeclaration(node) && node.name) {");
  lines.push("      pushSymbol(node.name.text, \"function\", node, node.getText(sf).slice(0, 200));");
  lines.push("    } else if (ts.isClassDeclaration(node) && node.name) {");
  lines.push("      pushSymbol(node.name.text, \"class\", node);");
  lines.push("      for (const m of node.members) {");
  lines.push("        if (ts.isMethodDeclaration(m) && ts.isIdentifier(m.name)) {");
  lines.push("          pushSymbol(`${node.name.text}.${m.name.text}`, \"method\", m, m.getText(sf).slice(0, 160));");
  lines.push("        }");
  lines.push("      }");
  lines.push("    } else if (ts.isInterfaceDeclaration(node)) {");
  lines.push("      pushSymbol(node.name.text, \"interface\", node);");
  lines.push("    } else if (ts.isTypeAliasDeclaration(node)) {");
  lines.push("      pushSymbol(node.name.text, \"type\", node);");
  lines.push("    } else if (ts.isEnumDeclaration(node)) {");
  lines.push("      pushSymbol(node.name.text, \"enum\", node);");
  lines.push("    } else if (ts.isModuleDeclaration(node) && ts.isIdentifier(node.name)) {");
  lines.push("      pushSymbol(node.name.text, \"namespace\", node);");
  lines.push("    } else if (ts.isVariableStatement(node)) {");
  lines.push("      for (const decl of node.declarationList.declarations) {");
  lines.push("        if (ts.isIdentifier(decl.name)) {");
  lines.push("          const isConst = (node.declarationList.flags & ts.NodeFlags.Const) !== 0;");
  lines.push("          pushSymbol(decl.name.text, isConst ? \"const\" : \"variable\", decl);");
  lines.push("        }");
  lines.push("      }");
  lines.push("    }");
  lines.push("    ts.forEachChild(node, visit);");
  lines.push("  }");
  lines.push("  visit(sf);");
  lines.push("");
  lines.push("  return {");
  lines.push("    file,");
  lines.push("    content_hash,");
  lines.push("    symbols: symbols.sort((a, b) => a.line - b.line || a.name.localeCompare(b.name)),");
  lines.push("    imports: [...new Set(imports)].sort(),");
  lines.push("    token_count: approxTokens(content),");
  lines.push("  };");
  lines.push("}");
  lines.push("");
  // Minimal regex fallback. Only catches top-level `export function/class/...`
  // declarations — enough for retrieval keying when typescript isn't installed.
  lines.push("function extractWithRegex(content: string, content_hash: string, file: string): ExtractedFile {");
  lines.push("  const symbols: Symbol[] = [];");
  lines.push("  const imports: string[] = [];");
  lines.push("  const lines = content.split(\"\\n\");");
  lines.push("  for (let i = 0; i < lines.length; i++) {");
  lines.push("    const line = lines[i];");
  lines.push("    const importMatch = line.match(/^\\s*import\\s+.*?from\\s+[\"']([^\"']+)[\"']/);");
  lines.push("    if (importMatch) imports.push(importMatch[1]);");
  lines.push("    const decl = line.match(/^\\s*(?:export\\s+)?(?:async\\s+)?(function|class|interface|type|enum|const|let|var)\\s+([A-Za-z_$][A-Za-z0-9_$]*)/);");
  lines.push("    if (decl) {");
  lines.push("      const kindRaw = decl[1];");
  lines.push("      const name = decl[2];");
  lines.push("      const kind: SymbolKind = (kindRaw === \"const\" || kindRaw === \"let\" || kindRaw === \"var\")");
  lines.push("        ? (kindRaw === \"const\" ? \"const\" : \"variable\")");
  lines.push("        : (kindRaw as SymbolKind);");
  lines.push("      symbols.push({");
  lines.push("        id: deriveSymbolId(file, name, i + 1),");
  lines.push("        repo_id: \"\",");
  lines.push("        file, name, kind,");
  lines.push("        line: i + 1,");
  lines.push("        col: 0,");
  lines.push("        visibility: line.includes(\"export\") ? \"public\" : \"internal\",");
  lines.push("        signature: line.trim().slice(0, 200),");
  lines.push("        doc_excerpt: null,");
  lines.push("      });");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return { file, content_hash, symbols, imports: [...new Set(imports)].sort(), token_count: approxTokens(content) };");
  lines.push("}");
  lines.push("");
  // Resolve module specifiers. We only resolve relative imports — package
  // imports are kept as opaque strings so the indexer can ignore them.
  lines.push("export function resolveImport(fromFile: string, spec: string, root: string, allFiles: string[]): string | null {");
  lines.push("  if (!spec.startsWith(\".\")) return null;");
  lines.push("  const baseDir = path.dirname(path.join(root, fromFile));");
  lines.push("  const target = path.resolve(baseDir, spec);");
  lines.push("  const rel = path.relative(root, target).replace(/\\\\/g, \"/\");");
  lines.push("  // Try with extensions and /index.* in deterministic order.");
  lines.push("  const candidates = [");
  lines.push("    rel, rel + \".ts\", rel + \".tsx\", rel + \".js\",");
  lines.push("    rel + \"/index.ts\", rel + \"/index.tsx\", rel + \"/index.js\",");
  lines.push("  ];");
  lines.push("  for (const c of candidates) {");
  lines.push("    if (allFiles.includes(c)) return c;");
  lines.push("  }");
  lines.push("  return null;");
  lines.push("}");
  lines.push("");
  // The in-memory index is the default backend. The pg backend lives in a
  // separate file (../db) and is loaded lazily.
  lines.push("export interface IndexedRepo {");
  lines.push("  files: string[];");
  lines.push("  symbolsByFile: Map<string, Symbol[]>;");
  lines.push("  importsByFile: Map<string, string[]>;");
  lines.push("  reverseImports: Map<string, string[]>;");
  lines.push("  fileSummaries: Map<string, FileSummary>;");
  lines.push("}");
  lines.push("");
  lines.push("export function buildIndex(root: string, excludes: string[] = [\"node_modules\", \"dist\", \".git\", \"build\", \".next\", \"output\"], repo_id: string = \"\"): IndexedRepo {");
  lines.push("  const files = listSourceFiles(root, excludes);");
  lines.push("  const symbolsByFile = new Map<string, Symbol[]>();");
  lines.push("  const importsByFile = new Map<string, string[]>();");
  lines.push("  const reverseImports = new Map<string, string[]>();");
  lines.push("  const fileSummaries = new Map<string, FileSummary>();");
  lines.push("");
  lines.push("  // Pass 1: extract symbols + raw module specifiers per file.");
  lines.push("  const rawImports = new Map<string, string[]>();");
  lines.push("  for (const rel of files) {");
  lines.push("    const ext = extractFile(path.join(root, rel), rel);");
  lines.push("    // Stamp every extracted symbol with the repo_id (Phase 10).");
  lines.push("    const stamped = ext.symbols.map(s => ({ ...s, repo_id }));");
  lines.push("    symbolsByFile.set(rel, stamped);");
  lines.push("    rawImports.set(rel, ext.imports);");
  lines.push("    fileSummaries.set(rel, {");
  lines.push("      repo_id, file: rel, content_hash: ext.content_hash, token_count: ext.token_count, summary: null,");
  lines.push("    });");
  lines.push("  }");
  lines.push("");
  lines.push("  // Pass 2: resolve imports against the file set.");
  lines.push("  for (const rel of files) {");
  lines.push("    const resolved: string[] = [];");
  lines.push("    for (const spec of rawImports.get(rel) || []) {");
  lines.push("      const r = resolveImport(rel, spec, root, files);");
  lines.push("      if (r) resolved.push(r);");
  lines.push("    }");
  lines.push("    const sortedResolved = [...new Set(resolved)].sort();");
  lines.push("    importsByFile.set(rel, sortedResolved);");
  lines.push("    for (const r of sortedResolved) {");
  lines.push("      const arr = reverseImports.get(r) || [];");
  lines.push("      arr.push(rel);");
  lines.push("      reverseImports.set(r, arr);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  for (const [k, arr] of reverseImports) reverseImports.set(k, arr.sort());");
  lines.push("");
  lines.push("  return { files, symbolsByFile, importsByFile, reverseImports, fileSummaries };");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Retriever ───────────────────────────────────────────────────────────────

function emitRetriever(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 4 — bounded BFS retriever.");
  lines.push("//");
  lines.push("// Algorithm:");
  lines.push("//   1. Tokenise the task into keywords (identifier-shaped substrings).");
  lines.push("//   2. Score each symbol by keyword overlap, file-name overlap, and a");
  lines.push("//      tiny visibility boost for `public` symbols.");
  lines.push("//   3. Take the top K symbols as seeds, where K = max_files * 2.");
  lines.push("//   4. BFS the (imports + reverseImports) graph from the seed files,");
  lines.push("//      breadth `hop_depth`, capped at `max_files` total files.");
  lines.push("//   5. Sort results deterministically and return.");
  lines.push("//");
  lines.push("// Determinism: every set / map iteration is sorted, ties resolve to the");
  lines.push("// earliest-appearing file. The retriever is pure given a fixed index.");
  lines.push("");
  lines.push("import type { IndexedRepo } from \"./semantic_index\";");
  lines.push("import type { SemanticSlice, RepoFilter } from \"./types\";");
  lines.push("");
  lines.push("const STOPWORDS = new Set([");
  lines.push("  \"a\", \"an\", \"the\", \"and\", \"or\", \"of\", \"to\", \"for\", \"with\", \"in\", \"on\", \"by\", \"is\", \"are\", \"was\", \"be\", \"as\", \"at\", \"it\", \"its\", \"this\", \"that\", \"these\", \"those\",");
  lines.push("  \"i\", \"you\", \"we\", \"they\", \"my\", \"our\", \"your\",");
  lines.push("  \"do\", \"does\", \"did\", \"can\", \"could\", \"should\", \"would\", \"will\", \"may\", \"might\",");
  lines.push("  \"function\", \"class\", \"file\", \"code\",");
  lines.push("]);");
  lines.push("");
  lines.push("function tokenise(s: string): string[] {");
  lines.push("  const tokens = s.toLowerCase().match(/[a-z0-9_]{2,}/g) || [];");
  lines.push("  return tokens.filter(t => !STOPWORDS.has(t));");
  lines.push("}");
  lines.push("");
  lines.push("/** Camel/snake split for symbol matching: parseFooBar → [parse, foo, bar]. */");
  lines.push("function splitIdent(name: string): string[] {");
  lines.push("  const parts: string[] = [];");
  lines.push("  for (const seg of name.split(/[._]/)) {");
  lines.push("    let acc = \"\";");
  lines.push("    for (let i = 0; i < seg.length; i++) {");
  lines.push("      const c = seg[i];");
  lines.push("      const next = seg[i + 1];");
  lines.push("      acc += c.toLowerCase();");
  lines.push("      if ((c.toLowerCase() !== c && next && next.toLowerCase() === next) || i === seg.length - 1) {");
  lines.push("        if (acc.length >= 2) parts.push(acc);");
  lines.push("        acc = \"\";");
  lines.push("      }");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return parts;");
  lines.push("}");
  lines.push("");
  lines.push("function scoreSymbol(symbolName: string, file: string, kw: Set<string>, visibility: string): number {");
  lines.push("  let s = 0;");
  lines.push("  for (const part of splitIdent(symbolName)) {");
  lines.push("    if (kw.has(part)) s += 3;");
  lines.push("  }");
  lines.push("  for (const part of file.toLowerCase().split(/[\\\\/_.]/g)) {");
  lines.push("    if (part.length >= 2 && kw.has(part)) s += 1;");
  lines.push("  }");
  lines.push("  if (visibility === \"public\") s += 0.25;");
  lines.push("  return s;");
  lines.push("}");
  lines.push("");
  lines.push("export function walkIndex(index: IndexedRepo, task: string, hopDepth: number, maxFiles: number, repo_filter?: RepoFilter): SemanticSlice {");
  lines.push("  const kw = new Set(tokenise(task));");
  lines.push("");
  lines.push("  // Phase 10: build the set of allowed repo_ids. null/undefined means");
  lines.push("  // 'no filter — every repo is fair game'. A non-empty filter restricts");
  lines.push("  // both the seeding pass AND the BFS expansion so cross-repo edges");
  lines.push("  // (which shouldn't exist for separately-cloned repos anyway) can't");
  lines.push("  // pull files in by accident.");
  lines.push("  const repoSet: Set<string> | null =");
  lines.push("    repo_filter == null");
  lines.push("      ? null");
  lines.push("      : new Set(typeof repo_filter === \"string\" ? [repo_filter] : repo_filter);");
  lines.push("  const fileAllowed = (file: string): boolean => {");
  lines.push("    if (!repoSet) return true;");
  lines.push("    const syms = index.symbolsByFile.get(file);");
  lines.push("    if (!syms || syms.length === 0) {");
  lines.push("      // No symbols means no repo_id evidence; permit (the file is on");
  lines.push("      // disk for a reason — fall back to the file's recorded summary).");
  lines.push("      const fs = index.fileSummaries.get(file);");
  lines.push("      return fs ? repoSet.has(fs.repo_id) : true;");
  lines.push("    }");
  lines.push("    // The repo_id is uniform across symbols of one file (set by buildIndex).");
  lines.push("    return repoSet.has(syms[0].repo_id);");
  lines.push("  };");
  lines.push("");
  lines.push("  // 1+2: score every symbol — skip files outside the repo filter.");
  lines.push("  type Scored = { score: number; file: string; symbol: string; line: number };");
  lines.push("  const scored: Scored[] = [];");
  lines.push("  const sortedFiles = [...index.symbolsByFile.keys()].sort();");
  lines.push("  for (const file of sortedFiles) {");
  lines.push("    if (!fileAllowed(file)) continue;");
  lines.push("    for (const sym of index.symbolsByFile.get(file)!) {");
  lines.push("      const s = scoreSymbol(sym.name, file, kw, sym.visibility);");
  lines.push("      if (s > 0) scored.push({ score: s, file, symbol: sym.name, line: sym.line });");
  lines.push("    }");
  lines.push("  }");
  lines.push("  // Stable sort: highest score first, ties by file then by line.");
  lines.push("  scored.sort((a, b) => b.score - a.score || a.file.localeCompare(b.file) || a.line - b.line);");
  lines.push("");
  lines.push("  // 3: seed files.");
  lines.push("  const K = Math.max(1, maxFiles * 2);");
  lines.push("  const seedSymbols = scored.slice(0, K);");
  lines.push("  const seedFiles: string[] = [];");
  lines.push("  for (const s of seedSymbols) {");
  lines.push("    if (!seedFiles.includes(s.file)) seedFiles.push(s.file);");
  lines.push("  }");
  lines.push("");
  lines.push("  // 4: BFS over imports + reverseImports up to hopDepth — also filtered.");
  lines.push("  const visited = new Set<string>(seedFiles);");
  lines.push("  let frontier: string[] = [...seedFiles];");
  lines.push("  for (let depth = 0; depth < hopDepth && visited.size < maxFiles; depth++) {");
  lines.push("    const next: string[] = [];");
  lines.push("    for (const f of frontier.sort()) {");
  lines.push("      const imps = (index.importsByFile.get(f) || []);");
  lines.push("      const revs = (index.reverseImports.get(f) || []);");
  lines.push("      for (const n of [...imps, ...revs].sort()) {");
  lines.push("        if (!visited.has(n) && visited.size < maxFiles && fileAllowed(n)) {");
  lines.push("          visited.add(n);");
  lines.push("          next.push(n);");
  lines.push("        }");
  lines.push("      }");
  lines.push("    }");
  lines.push("    frontier = next;");
  lines.push("  }");
  lines.push("");
  lines.push("  // 5: assemble result. Files in BFS-visit order so the most-relevant come first.");
  lines.push("  const files = [...visited];");
  lines.push("  // Symbols: collect from those files, sorted by (score desc, file, line) so");
  lines.push("  // the highest-relevance symbols come first.");
  lines.push("  const symbolSet = new Set<string>();");
  lines.push("  for (const s of seedSymbols) symbolSet.add(`${s.file}:${s.symbol}`);");
  lines.push("  const symbols = [...symbolSet];");
  lines.push("  return {");
  lines.push("    files,");
  lines.push("    symbols,");
  lines.push("    target_symbol: scored[0] ? `${scored[0].file}:${scored[0].symbol}` : (files[0] || \"\"),");
  lines.push("  };");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Compressor ──────────────────────────────────────────────────────────────

function emitCompressor(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 4 — token-budgeted code-slice serializer.");
  lines.push("//");
  lines.push("// Given a SemanticSlice and a token budget, produce a compact text bundle");
  lines.push("// that fits within the budget. Strategy:");
  lines.push("//   - Always include the seed file's full text up to half the budget.");
  lines.push("//   - For each subsequent file, include only the matching symbol's");
  lines.push("//     extracted text (using the AST line range), then a 5-line excerpt");
  lines.push("//     for context.");
  lines.push("//   - Stop when the token budget is exhausted.");
  lines.push("//");
  lines.push("// This module never calls a model — it's pure text manipulation. The");
  lines.push("// cognition catalog's compress_context primitive can layer a summarising");
  lines.push("// pass on top when the slice still doesn't fit.");
  lines.push("");
  lines.push("import * as fs from \"fs\";");
  lines.push("import * as path from \"path\";");
  lines.push("import { approxTokens } from \"./semantic_index\";");
  lines.push("import type { SemanticSlice } from \"./types\";");
  lines.push("import type { IndexedRepo } from \"./semantic_index\";");
  lines.push("");
  lines.push("export interface CompressedSlice {");
  lines.push("  text: string;");
  lines.push("  files_included: string[];");
  lines.push("  files_truncated: string[];");
  lines.push("  approx_tokens: number;");
  lines.push("}");
  lines.push("");
  lines.push("function readSafe(absPath: string): string {");
  lines.push("  try { return fs.readFileSync(absPath, \"utf-8\"); }");
  lines.push("  catch { return \"\"; }");
  lines.push("}");
  lines.push("");
  lines.push("export function compressSlice(slice: SemanticSlice, index: IndexedRepo, root: string, targetTokens: number): CompressedSlice {");
  lines.push("  const buf: string[] = [];");
  lines.push("  let used = 0;");
  lines.push("  const included: string[] = [];");
  lines.push("  const truncated: string[] = [];");
  lines.push("  const half = Math.floor(targetTokens / 2);");
  lines.push("  for (let i = 0; i < slice.files.length; i++) {");
  lines.push("    const file = slice.files[i];");
  lines.push("    const isSeed = i === 0;");
  lines.push("    const cap = isSeed ? half : Math.max(40, Math.floor((targetTokens - used) / Math.max(1, slice.files.length - i)));");
  lines.push("    const content = readSafe(path.join(root, file));");
  lines.push("    if (!content) continue;");
  lines.push("    const lines = content.split(\"\\n\");");
  lines.push("    let snippet: string;");
  lines.push("    if (approxTokens(content) <= cap) {");
  lines.push("      snippet = content;");
  lines.push("      included.push(file);");
  lines.push("    } else {");
  lines.push("      // Pick the first matching symbol's neighbourhood.");
  lines.push("      const matchingSyms = (index.symbolsByFile.get(file) || []).filter(s => slice.symbols.includes(`${file}:${s.name}`));");
  lines.push("      if (matchingSyms.length === 0) {");
  lines.push("        snippet = lines.slice(0, Math.min(lines.length, 40)).join(\"\\n\");");
  lines.push("      } else {");
  lines.push("        const sym = matchingSyms[0];");
  lines.push("        const start = Math.max(0, sym.line - 5);");
  lines.push("        const end = Math.min(lines.length, sym.line + 30);");
  lines.push("        snippet = lines.slice(start, end).join(\"\\n\");");
  lines.push("      }");
  lines.push("      truncated.push(file);");
  lines.push("    }");
  lines.push("    const block = `// ${file}\\n${snippet}\\n`;");
  lines.push("    const t = approxTokens(block);");
  lines.push("    if (used + t > targetTokens) break;");
  lines.push("    used += t;");
  lines.push("    buf.push(block);");
  lines.push("  }");
  lines.push("  return { text: buf.join(\"\\n\"), files_included: included, files_truncated: truncated, approx_tokens: used };");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Index entry ─────────────────────────────────────────────────────────────

function emitMemoryIndexFile(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 4 — public memory entry.");
  lines.push("//");
  lines.push("// Application code calls getIndex() once and reuses the returned handle.");
  lines.push("// The handle implements SemanticIndex (see types.ts) so it satisfies the");
  lines.push("// `index:` parameter expected by the cognition catalog's semantic_slice");
  lines.push("// primitive.");
  lines.push("");
  lines.push("import * as path from \"path\";");
  lines.push("import { logger } from \"../logger\";");
  lines.push("import { counter } from \"../metrics\";");
  lines.push("import { buildIndex, type IndexedRepo } from \"./semantic_index\";");
  lines.push("import { walkIndex } from \"./retriever\";");
  lines.push("import type { Symbol, SemanticIndex, SemanticSlice, RepoFilter } from \"./types\";");
  lines.push("");
  lines.push("const ROOT = path.resolve(process.env.LLM_MEMORY_ROOT || process.cwd());");
  lines.push("");
  lines.push("class InProcessIndex implements SemanticIndex {");
  lines.push("  private repo: IndexedRepo | null = null;");
  lines.push("");
  lines.push("  private ensure(): IndexedRepo {");
  lines.push("    if (!this.repo) {");
  lines.push("      const start = Date.now();");
  lines.push("      this.repo = buildIndex(ROOT);");
  lines.push("      logger.info(\"memory_index_built\", {");
  lines.push("        event: \"memory.index\",");
  lines.push("        status: \"success\",");
  lines.push("        duration_ms: Date.now() - start,");
  lines.push("        trace_id: \"\",");
  lines.push("        metadata: { files: this.repo.files.length, root: ROOT },");
  lines.push("      });");
  lines.push("      counter(\"memory.index_built\");");
  lines.push("    }");
  lines.push("    return this.repo;");
  lines.push("  }");
  lines.push("");
  lines.push("  walk(task: string, hopDepth: number, maxFiles: number, repo_filter?: RepoFilter): SemanticSlice {");
  lines.push("    const r = this.ensure();");
  lines.push("    const slice = walkIndex(r, task, hopDepth, maxFiles, repo_filter);");
  lines.push("    counter(\"memory.walk\", { hits: String(slice.files.length) });");
  lines.push("    return slice;");
  lines.push("  }");
  lines.push("");
  lines.push("  symbolsByFile(file: string): Symbol[] {");
  lines.push("    return this.ensure().symbolsByFile.get(file) || [];");
  lines.push("  }");
  lines.push("");
  lines.push("  importsOf(file: string): string[] {");
  lines.push("    return this.ensure().importsByFile.get(file) || [];");
  lines.push("  }");
  lines.push("");
  lines.push("  async refresh(): Promise<void> {");
  lines.push("    this.repo = null;");
  lines.push("    this.ensure();");
  lines.push("  }");
  lines.push("");
  lines.push("  // Internal: expose the underlying repo for the compressor.");
  lines.push("  __repo(): IndexedRepo { return this.ensure(); }");
  lines.push("  __root(): string { return ROOT; }");
  lines.push("}");
  lines.push("");
  lines.push("const SINGLETON = new InProcessIndex();");
  lines.push("");
  lines.push("export function getIndex(): SemanticIndex { return SINGLETON; }");
  lines.push("");
  lines.push("/**");
  lines.push(" * Compress the slice at `task` to fit within `targetTokens`. Convenience");
  lines.push(" * helper that wires the retriever and the compressor.");
  lines.push(" */");
  lines.push("export async function sliceForPrompt(task: string, options: { hopDepth?: number; maxFiles?: number; targetTokens?: number } = {}): Promise<{ slice: SemanticSlice; text: string }> {");
  lines.push("  const { compressSlice } = await import(\"./compressor\");");
  lines.push("  const slice = SINGLETON.walk(task, options.hopDepth ?? 2, options.maxFiles ?? 8);");
  lines.push("  const compressed = compressSlice(slice, SINGLETON.__repo(), SINGLETON.__root(), options.targetTokens ?? 4000);");
  lines.push("  return { slice, text: compressed.text };");
  lines.push("}");
  lines.push("");
  lines.push("export type { SemanticSlice } from \"./types\";");
  lines.push("");
  return lines.join("\n");
}

// ─── Build-time indexer script ───────────────────────────────────────────────

function emitIndexerScript(): string {
  const lines: string[] = [];
  lines.push("#!/usr/bin/env node");
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Walks the source tree and writes the symbol graph to Postgres.");
  lines.push("//");
  lines.push("// Usage:");
  lines.push("//   npx ts-node bin/index_sources.ts            # uses LLM_MEMORY_ROOT or cwd");
  lines.push("//   npx ts-node bin/index_sources.ts --root .   # explicit root");
  lines.push("//   npx ts-node bin/index_sources.ts --repo-id <id>  # tag every row with a repo id (Phase 10)");
  lines.push("//   npx ts-node bin/index_sources.ts --print    # dump the graph as JSON");
  lines.push("//");
  lines.push("// When LLM_MEMORY_BACKEND=memory (default), this is only useful for");
  lines.push("// --print debugging. When LLM_MEMORY_BACKEND=pg, run this once per repo");
  lines.push("// at deploy time, passing --repo-id, so retrieval can filter to one repo");
  lines.push("// at a time.");
  lines.push("");
  lines.push("import * as path from \"path\";");
  lines.push("import { buildIndex } from \"../src/memory/semantic_index\";");
  lines.push("");
  lines.push("async function main(): Promise<void> {");
  lines.push("  const args = process.argv.slice(2);");
  lines.push("  let root = process.env.LLM_MEMORY_ROOT || process.cwd();");
  lines.push("  let print = false;");
  lines.push("  let repo_id = \"\";");
  lines.push("  for (let i = 0; i < args.length; i++) {");
  lines.push("    if (args[i] === \"--root\" && args[i + 1]) { root = path.resolve(args[i + 1]); i++; }");
  lines.push("    else if (args[i] === \"--repo-id\" && args[i + 1]) { repo_id = args[i + 1]; i++; }");
  lines.push("    else if (args[i] === \"--print\") { print = true; }");
  lines.push("  }");
  lines.push("  const start = Date.now();");
  lines.push("  const idx = buildIndex(root, undefined, repo_id);");
  lines.push("  console.error(`Indexed ${idx.files.length} files in ${Date.now() - start}ms` + (repo_id ? ` (repo_id=${repo_id})` : \"\"));");
  lines.push("  if (print) {");
  lines.push("    const out = {");
  lines.push("      files: idx.files,");
  lines.push("      symbol_count: [...idx.symbolsByFile.values()].reduce((a, b) => a + b.length, 0),");
  lines.push("      import_edges: [...idx.importsByFile.entries()].reduce((a, [, v]) => a + v.length, 0),");
  lines.push("      repo_id,");
  lines.push("    };");
  lines.push("    process.stdout.write(JSON.stringify(out, null, 2) + \"\\n\");");
  lines.push("  }");
  lines.push("  // Postgres backend persistence stub — fill in when LLM_MEMORY_BACKEND=pg.");
  lines.push("  if (process.env.LLM_MEMORY_BACKEND === \"pg\") {");
  lines.push("    console.error(\"pg backend persistence not yet implemented in this script — see migrations/semantic_index.sql\");");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("main().catch(err => { console.error(err); process.exit(1); });");
  lines.push("");
  return lines.join("\n");
}
