/**
 * MarrowScript GraphQL Schema Emitter
 * Generates schema.graphql from an IRSystem.
 */

import * as IR from "./ir";

function toCamelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

function toCamelCasePlural(s: string): string {
  const camel = toCamelCase(s);
  // Simple pluralisation: append 's' (good enough for generated stubs)
  return camel.endsWith("s") ? camel : camel + "s";
}

function toGraphQLType(irType: string): string {
  // Handle optional<X> — nullable in GraphQL (just unwrap, no !)
  const optMatch = irType.match(/^optional<(.+)>$/);
  if (optMatch) return toGraphQLType(optMatch[1]);

  // Handle list<X> / set<X>
  const listMatch = irType.match(/^(list|set)<(.+)>$/);
  if (listMatch) return `[${toGraphQLType(listMatch[2])}]`;

  switch (irType) {
    case "string":    return "String";
    case "uint":
    case "int":       return "Int";
    case "float":     return "Float";
    case "bool":      return "Boolean";
    case "timestamp": return "String";
    case "uuid":      return "ID";
    case "bytes":     return "String";
    case "json":      return "String";
    default:          return "String";
  }
}

function isOptional(irType: string): boolean {
  return irType.startsWith("optional<");
}

function fieldLine(field: IR.IRField): string {
  const gqlType = toGraphQLType(field.type);
  const nullable = isOptional(field.type) || field.nullable;
  return `  ${field.name}: ${gqlType}${nullable ? "" : "!"}`;
}

export function emitGraphQLSchema(system: IR.IRSystem): string {
  const lines: string[] = [];

  lines.push(`# Generated by MarrowScript compiler. DO NOT EDIT.`);
  lines.push(`# System: ${system.name} v${system.version}`);
  lines.push(``);

  // Collect all models from api_service modules
  const apiModules = system.modules.filter(m => m.kind === "api_service" && m.models.length > 0);

  const queryFields: string[] = [];
  const mutationFields: string[] = [];
  const extraTypes: string[] = [];

  for (const mod of apiModules) {
    const model = mod.models[0];
    const modelName = model.name;
    const camelName = toCamelCase(modelName.charAt(0).toLowerCase() + modelName.slice(1));
    const camelPlural = toCamelCasePlural(modelName.charAt(0).toLowerCase() + modelName.slice(1));

    // ─── type {ModelName} ───
    lines.push(`type ${modelName} {`);
    // Always include id, created_at, updated_at
    lines.push(`  id: ID!`);
    for (const field of model.fields) {
      if (field.name === "id") continue; // already emitted
      lines.push(fieldLine(field));
    }
    lines.push(`}`);
    lines.push(``);

    // ─── type {ModelName}Page ───
    lines.push(`type ${modelName}Page {`);
    lines.push(`  items: [${modelName}!]!`);
    lines.push(`  total: Int!`);
    lines.push(`  page: Int!`);
    lines.push(`  pageSize: Int!`);
    lines.push(`}`);
    lines.push(``);

    // ─── input {ModelName}Input ───
    const inputFields = model.fields.filter(
      f => !["id", "created_at", "updated_at"].includes(f.name)
    );
    lines.push(`input ${modelName}Input {`);
    for (const field of inputFields) {
      lines.push(fieldLine(field));
    }
    lines.push(`}`);
    lines.push(``);

    // Capability inputs + results
    const capabilities = mod.interfaces.flatMap(i => i.methods)
      .filter(m => !["create", "read", "update", "delete", "list"].includes(m.name));

    for (const cap of capabilities) {
      const capPascal = cap.name.charAt(0).toUpperCase() + toCamelCase(cap.name).slice(1);
      extraTypes.push(`input ${modelName}${capPascal}Input {`);
      for (const param of cap.input) {
        extraTypes.push(fieldLine(param));
      }
      extraTypes.push(`}`);
      extraTypes.push(``);
    }

    // ─── Query fields ───
    queryFields.push(`  ${camelName}(id: ID!): ${modelName}`);
    queryFields.push(`  ${camelPlural}(page: Int, pageSize: Int): ${modelName}Page`);

    // ─── Mutation fields ───
    mutationFields.push(`  create${modelName}(input: ${modelName}Input!): ${modelName}!`);
    mutationFields.push(`  update${modelName}(id: ID!, input: ${modelName}Input!): ${modelName}!`);
    mutationFields.push(`  delete${modelName}(id: ID!): Boolean!`);

    for (const cap of capabilities) {
      const capCamel = toCamelCase(cap.name);
      const capPascal = cap.name.charAt(0).toUpperCase() + capCamel.slice(1);
      mutationFields.push(`  ${capCamel}(input: ${modelName}${capPascal}Input): CapabilityResult!`);
    }
  }

  // ─── type CapabilityResult ───
  lines.push(`type CapabilityResult {`);
  lines.push(`  ok: Boolean!`);
  lines.push(`  action: String!`);
  lines.push(`}`);
  lines.push(``);

  // ─── Extra capability input types ───
  for (const l of extraTypes) {
    lines.push(l);
  }

  // ─── type Query ───
  // GraphQL spec requires every schema to define a non-empty Query type.
  // For systems with no API modules (event-only or channel-only), emit a
  // placeholder _service field so the schema parses.
  lines.push(`type Query {`);
  if (queryFields.length === 0) {
    lines.push(`  _service: String!`);
  } else {
    for (const f of queryFields) {
      lines.push(f);
    }
  }
  lines.push(`}`);
  lines.push(``);

  // ─── type Mutation ───
  // Mutation is technically optional in GraphQL, but emitting an empty body
  // is a syntax error. Skip the type entirely if there's nothing to mutate.
  if (mutationFields.length > 0) {
    lines.push(`type Mutation {`);
    for (const f of mutationFields) {
      lines.push(f);
    }
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n");
}
