/**
 * MarrowScript Provider Emitter (LLM Harness, Phase 2)
 *
 * Generates one adapter file per provider in src/providers/. Each adapter
 * implements a uniform IModelProvider interface so the cognition runtime
 * can swap models with no callsite changes.
 *
 * Mirrors the multi-provider switching pattern from compiler/src/emit_notify.ts:
 *   - one shared provider union, env-driven selection
 *   - SSRF guard for the http adapter (loopback / RFC1918 allowlist by default)
 *   - per-provider adapter file kept small, focused, and side-effect free
 *
 * Determinism: every emit_*() returns hand-built strings via lines.push(...).
 * No Date.now(), no Math.random(), no template-literal interpolation that
 * depends on runtime state.
 */

import * as IR from "./ir";
import { EmittedFile } from "./emitter";

/**
 * Collect the set of providers actually referenced by declared models.
 * We only emit adapters that are used, mirroring how the algorithm emitter
 * only writes implementations for catalog entries that are referenced.
 */
export function collectUsedProviders(system: IR.IRSystem): Set<IR.IRProviderKind> {
  const used = new Set<IR.IRProviderKind>();
  for (const m of system.models) used.add(m.provider);
  return used;
}

/**
 * Emit all provider files for a system. Returns an empty array when the
 * system has no `model` declarations (i.e. no harness in use), so existing
 * non-cognition systems get zero new files.
 */
export function emitProviders(system: IR.IRSystem): EmittedFile[] {
  const used = collectUsedProviders(system);
  if (used.size === 0) return [];

  const files: EmittedFile[] = [];
  files.push({
    path: "src/providers/types.ts",
    content: emitProviderTypes(),
    language: "typescript",
    source_module: "cognition",
  });
  files.push({
    path: "src/providers/ssrf_guard.ts",
    content: emitSsrfGuard(),
    language: "typescript",
    source_module: "cognition",
  });
  if (used.has("ollama")) {
    files.push({ path: "src/providers/ollama.ts", content: emitOllamaAdapter(), language: "typescript", source_module: "cognition" });
  }
  if (used.has("openai_compat")) {
    files.push({ path: "src/providers/openai_compat.ts", content: emitOpenAICompatAdapter(), language: "typescript", source_module: "cognition" });
  }
  if (used.has("llamacpp")) {
    files.push({ path: "src/providers/llamacpp.ts", content: emitLlamaCppAdapter(), language: "typescript", source_module: "cognition" });
  }
  if (used.has("koboldcpp")) {
    files.push({ path: "src/providers/koboldcpp.ts", content: emitKoboldCppAdapter(), language: "typescript", source_module: "cognition" });
  }
  if (used.has("http")) {
    files.push({ path: "src/providers/http.ts", content: emitGenericHttpAdapter(), language: "typescript", source_module: "cognition" });
  }
  files.push({
    path: "src/providers/index.ts",
    content: emitProviderRegistry(system, used),
    language: "typescript",
    source_module: "cognition",
  });
  return files;
}

// ─── Shared interface ────────────────────────────────────────────────────────

function emitProviderTypes(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 2 — provider interface.");
  lines.push("//");
  lines.push("// All provider adapters implement IModelProvider. The cognition runtime");
  lines.push("// (src/cognition/prompts.ts) talks to this interface only — never to a");
  lines.push("// concrete provider — so swapping local Ollama for vLLM is a config change.");
  lines.push("");
  lines.push("export interface ChatMessage {");
  lines.push("  role: \"system\" | \"user\" | \"assistant\" | \"tool\";");
  lines.push("  content: string;");
  lines.push("  /** Phase 15: when role=\"assistant\" and the model invoked tools, */");
  lines.push("  /** these are the tool calls. The runtime executes each one and */");
  lines.push("  /** appends a follow-up role:\"tool\" message with the result. */");
  lines.push("  tool_calls?: ChatToolCall[];");
  lines.push("  /** Phase 15: when role=\"tool\", which call this message answers. */");
  lines.push("  tool_call_id?: string;");
  lines.push("  /** Phase 15: when role=\"tool\", the name of the tool. Some providers */");
  lines.push("  /** require this on the result message. */");
  lines.push("  name?: string;");
  lines.push("}");
  lines.push("");
  lines.push("/** Phase 15: a single tool call returned by the model. */");
  lines.push("export interface ChatToolCall {");
  lines.push("  /** Provider-supplied call id; the runtime echoes it back on the result. */");
  lines.push("  id: string;");
  lines.push("  /** Tool name. Must match a declared capability. */");
  lines.push("  name: string;");
  lines.push("  /** Raw JSON arguments string from the model. The runtime parses + validates. */");
  lines.push("  arguments: string;");
  lines.push("}");
  lines.push("");
  lines.push("/** Phase 15: tool spec sent in the chat request. */");
  lines.push("export interface ChatToolSpec {");
  lines.push("  /** Capability name; the runtime uses this to dispatch via runCognition. */");
  lines.push("  name: string;");
  lines.push("  /** Short human-readable description shown to the model. */");
  lines.push("  description: string;");
  lines.push("  /** JSON Schema for the tool's input arguments. Compile-time generated */");
  lines.push("  /** from the capability's declared parameter list. */");
  lines.push("  parameters: { type: \"object\"; properties: Record<string, unknown>; required?: string[] };");
  lines.push("}");
  lines.push("");
  lines.push("export interface ChatRequest {");
  lines.push("  /** Provider-specific model identifier (e.g. \"qwen2.5-coder:1.5b\"). */");
  lines.push("  model: string;");
  lines.push("  messages: ChatMessage[];");
  lines.push("  temperature?: number;");
  lines.push("  top_p?: number;");
  lines.push("  max_output?: number;");
  lines.push("  stop?: string[];");
  lines.push("  /** When set, the runtime expects strict JSON output. Adapters may pass through to a `format: \"json\"` field if the provider supports it. */");
  lines.push("  json?: boolean;");
  lines.push("  /** Phase 15: closed list of tools the model may invoke. Adapters that */");
  lines.push("  /** support function-calling forward this; others ignore it (the runtime */");
  lines.push("  /** treats a no-op response as a normal content reply). */");
  lines.push("  tools?: ChatToolSpec[];");
  lines.push("  /** Phase 15: \"auto\" | \"required\" | \"none\". Default is auto. */");
  lines.push("  tool_choice?: \"auto\" | \"required\" | \"none\";");
  lines.push("}");
  lines.push("");
  lines.push("export interface ChatUsage {");
  lines.push("  prompt_tokens?: number;");
  lines.push("  completion_tokens?: number;");
  lines.push("}");
  lines.push("");
  lines.push("export interface ChatResponse {");
  lines.push("  content: string;");
  lines.push("  usage: ChatUsage;");
  lines.push("  /** Optional confidence in [0, 1]. Providers populate this from logprobs");
  lines.push("   * (or vendor-specific metadata) when available; null otherwise. The");
  lines.push("   * cognition runtime uses it for `router.on_low_confidence` decisions. */");
  lines.push("  confidence?: number | null;");
  lines.push("  /** Phase 15: when the model invoked tools, the parsed list. The */");
  lines.push("  /** cognition runtime executes each call and re-prompts. Empty / undefined */");
  lines.push("  /** means \"this is the final answer; trust .content\". */");
  lines.push("  tool_calls?: ChatToolCall[];");
  lines.push("  /** Raw provider response — for tracing / debugging only, never inspected by the cognition layer. */");
  lines.push("  raw?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export interface IModelProvider {");
  lines.push("  /** Name that appears in traces and metrics. */");
  lines.push("  readonly name: string;");
  lines.push("  /** One round trip. Honors AbortSignal so the per-prompt `timeout:` works. */");
  lines.push("  chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse>;");
  lines.push("  /** Best-effort token count. Used only for budget gauges, never as a security boundary. */");
  lines.push("  countTokens(text: string): number;");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Conservative tokenizer. 4 chars/token is the rule of thumb for English");
  lines.push(" * across Llama / Qwen / Phi / Gemma families. Off by ~20% in either");
  lines.push(" * direction; that's fine for budget gauges, never for billing.");
  lines.push(" */");
  lines.push("export function approxTokens(text: string): number {");
  lines.push("  if (!text) return 0;");
  lines.push("  return Math.ceil(text.length / 4);");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── SSRF guard (shared with emit_notify.ts in spirit) ──────────────────────

function emitSsrfGuard(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Endpoint allowlist for openai_compat / http providers.");
  lines.push("//");
  lines.push("// Default policy: only loopback (127.0.0.0/8, ::1, localhost) and RFC1918");
  lines.push("// (10/8, 172.16/12, 192.168/16) are allowed without an explicit env override.");
  lines.push("// Set LLM_ENDPOINT_ALLOWLIST=https://api.example.com,http://internal:8080");
  lines.push("// to permit additional endpoints. Setting LLM_ALLOW_PUBLIC_ENDPOINTS=1");
  lines.push("// disables the host filter entirely (production-only opt-in).");
  lines.push("");
  lines.push("function isLoopback(host: string): boolean {");
  lines.push("  const h = host.toLowerCase();");
  lines.push("  if (h === \"localhost\" || h === \"::1\" || h === \"::\") return true;");
  lines.push("  if (h.startsWith(\"127.\")) return true;");
  lines.push("  return false;");
  lines.push("}");
  lines.push("");
  lines.push("function isRfc1918(host: string): boolean {");
  lines.push("  const m = host.match(/^(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})$/);");
  lines.push("  if (!m) return false;");
  lines.push("  const a = Number(m[1]), b = Number(m[2]);");
  lines.push("  if (a === 10) return true;");
  lines.push("  if (a === 172 && b >= 16 && b <= 31) return true;");
  lines.push("  if (a === 192 && b === 168) return true;");
  lines.push("  return false;");
  lines.push("}");
  lines.push("");
  lines.push("export function assertEndpointAllowed(endpoint: string): void {");
  lines.push("  if (process.env.LLM_ALLOW_PUBLIC_ENDPOINTS === \"1\") return;");
  lines.push("  let url: URL;");
  lines.push("  try { url = new URL(endpoint); } catch { throw new Error(`Invalid endpoint URL: ${endpoint}`); }");
  lines.push("  if (url.protocol !== \"http:\" && url.protocol !== \"https:\") {");
  lines.push("    throw new Error(`Endpoint must use http(s): ${endpoint}`);");
  lines.push("  }");
  lines.push("  const allow = (process.env.LLM_ENDPOINT_ALLOWLIST || \"\").split(\",\").map(s => s.trim()).filter(Boolean);");
  lines.push("  for (const a of allow) {");
  lines.push("    if (endpoint.startsWith(a)) return;");
  lines.push("  }");
  lines.push("  if (isLoopback(url.hostname) || isRfc1918(url.hostname)) return;");
  lines.push("  throw new Error(");
  lines.push("    `Endpoint ${endpoint} is not in LLM_ENDPOINT_ALLOWLIST and is not a private host. ` +");
  lines.push("    `Set LLM_ENDPOINT_ALLOWLIST=<comma-separated prefixes> or LLM_ALLOW_PUBLIC_ENDPOINTS=1 to permit.`");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Ollama ──────────────────────────────────────────────────────────────────

function emitOllamaAdapter(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Ollama adapter — talks to /api/chat on a local Ollama server.");
  lines.push("// Default host is OLLAMA_HOST (default http://127.0.0.1:11434).");
  lines.push("");
  lines.push("import type { ChatRequest, ChatResponse, IModelProvider } from \"./types\";");
  lines.push("import { approxTokens } from \"./types\";");
  lines.push("");
  lines.push("export class OllamaProvider implements IModelProvider {");
  lines.push("  readonly name = \"ollama\";");
  lines.push("  private host: string;");
  lines.push("");
  lines.push("  constructor(host?: string) {");
  lines.push("    const raw = host || process.env.OLLAMA_HOST || \"http://127.0.0.1:11434\";");
  lines.push("    // Normalise — drop trailing slash so we can append paths cleanly.");
  lines.push("    this.host = raw.replace(/\\/+$/, \"\");");
  lines.push("  }");
  lines.push("");
  lines.push("  countTokens(text: string): number { return approxTokens(text); }");
  lines.push("");
  lines.push("  async chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {");
  lines.push("    const body = {");
  lines.push("      model: req.model,");
  lines.push("      messages: req.messages,");
  lines.push("      stream: false,");
  lines.push("      format: req.json ? \"json\" : undefined,");
  lines.push("      options: {");
  lines.push("        temperature: req.temperature ?? 0,");
  lines.push("        top_p: req.top_p,");
  lines.push("        num_predict: req.max_output,");
  lines.push("        stop: req.stop,");
  lines.push("      },");
  lines.push("    };");
  lines.push("    const res = await fetch(`${this.host}/api/chat`, {");
  lines.push("      method: \"POST\",");
  lines.push("      headers: { \"Content-Type\": \"application/json\" },");
  lines.push("      body: JSON.stringify(body),");
  lines.push("      signal,");
  lines.push("    });");
  lines.push("    if (!res.ok) {");
  lines.push("      const text = await res.text().catch(() => \"\");");
  lines.push("      throw new Error(`Ollama ${res.status}: ${text.slice(0, 256)}`);");
  lines.push("    }");
  lines.push("    const data = await res.json() as {");
  lines.push("      message?: { content?: string };");
  lines.push("      prompt_eval_count?: number;");
  lines.push("      eval_count?: number;");
  lines.push("    };");
  lines.push("    return {");
  lines.push("      content: data.message?.content || \"\",");
  lines.push("      usage: {");
  lines.push("        prompt_tokens: data.prompt_eval_count,");
  lines.push("        completion_tokens: data.eval_count,");
  lines.push("      },");
  lines.push("      raw: data,");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── OpenAI-compatible (vLLM, LM Studio, KoboldCPP shim, text-gen-webui) ────

function emitOpenAICompatAdapter(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// OpenAI-compatible adapter — hits /v1/chat/completions on the configured");
  lines.push("// endpoint. Covers vLLM, LM Studio, text-generation-webui, KoboldCPP's OAI");
  lines.push("// shim, and OpenAI itself when API key is set.");
  lines.push("");
  lines.push("import type { ChatRequest, ChatResponse, ChatToolCall, IModelProvider } from \"./types\";");
  lines.push("import { approxTokens } from \"./types\";");
  lines.push("import { assertEndpointAllowed } from \"./ssrf_guard\";");
  lines.push("");
  lines.push("export class OpenAICompatProvider implements IModelProvider {");
  lines.push("  readonly name = \"openai_compat\";");
  lines.push("  private endpoint: string;");
  lines.push("  private apiKey: string;");
  lines.push("");
  lines.push("  constructor(endpoint: string, apiKey?: string) {");
  lines.push("    assertEndpointAllowed(endpoint);");
  lines.push("    this.endpoint = endpoint.replace(/\\/+$/, \"\");");
  lines.push("    this.apiKey = apiKey || process.env.OPENAI_COMPAT_API_KEY || \"\";");
  lines.push("  }");
  lines.push("");
  lines.push("  countTokens(text: string): number { return approxTokens(text); }");
  lines.push("");
  lines.push("  async chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {");
  lines.push("    const body: Record<string, unknown> = {");
  lines.push("      model: req.model,");
  lines.push("      messages: req.messages,");
  lines.push("      temperature: req.temperature ?? 0,");
  lines.push("      top_p: req.top_p,");
  lines.push("      max_tokens: req.max_output,");
  lines.push("      stop: req.stop,");
  lines.push("      stream: false,");
  lines.push("    };");
  lines.push("    if (req.json) body.response_format = { type: \"json_object\" };");
  lines.push("    // Phase 15: forward tools as OpenAI's `tools` array. Each tool maps to");
  lines.push("    // OpenAI's function-calling shape: { type: \"function\", function: { name,");
  lines.push("    // description, parameters: <JSON Schema> } }. We never pass `tools` and");
  lines.push("    // `response_format: json_object` together — providers that support both");
  lines.push("    // tend to ignore one when both are set; the cognition runtime turns off");
  lines.push("    // json mode when tools are present and the parser handles raw text.");
  lines.push("    if (req.tools && req.tools.length > 0) {");
  lines.push("      body.tools = req.tools.map(t => ({");
  lines.push("        type: \"function\",");
  lines.push("        function: { name: t.name, description: t.description, parameters: t.parameters },");
  lines.push("      }));");
  lines.push("      if (req.tool_choice) body.tool_choice = req.tool_choice;");
  lines.push("      // Disable response_format when tools are present so providers don't");
  lines.push("      // get confused (LM Studio, vLLM both refuse the combination).");
  lines.push("      delete body.response_format;");
  lines.push("    }");
  lines.push("    // Phase 7: ask for top-1 logprobs so we can derive a confidence signal");
  lines.push("    // for `router.confidence_threshold`. Many openai-compatible servers");
  lines.push("    // (vLLM, LM Studio, text-gen-webui) honour this; those that don't");
  lines.push("    // simply ignore it and we fall back to confidence: null.");
  lines.push("    body.logprobs = true;");
  lines.push("    body.top_logprobs = 1;");
  lines.push("    const headers: Record<string, string> = { \"Content-Type\": \"application/json\" };");
  lines.push("    if (this.apiKey) headers[\"Authorization\"] = `Bearer ${this.apiKey}`;");
  lines.push("    const res = await fetch(`${this.endpoint}/chat/completions`, {");
  lines.push("      method: \"POST\",");
  lines.push("      headers,");
  lines.push("      body: JSON.stringify(body),");
  lines.push("      signal,");
  lines.push("    });");
  lines.push("    if (!res.ok) {");
  lines.push("      const text = await res.text().catch(() => \"\");");
  lines.push("      throw new Error(`openai_compat ${res.status}: ${text.slice(0, 256)}`);");
  lines.push("    }");
  lines.push("    const data = await res.json() as {");
  lines.push("      choices?: {");
  lines.push("        message?: {");
  lines.push("          content?: string;");
  lines.push("          tool_calls?: { id?: string; function?: { name?: string; arguments?: string } }[];");
  lines.push("        };");
  lines.push("        logprobs?: { content?: { logprob?: number }[] };");
  lines.push("      }[];");
  lines.push("      usage?: { prompt_tokens?: number; completion_tokens?: number };");
  lines.push("    };");
  lines.push("    const msg = data.choices?.[0]?.message;");
  lines.push("    // Phase 15: parse tool_calls if the model invoked any. Defensive: skip");
  lines.push("    // entries with missing name or arguments rather than blow up the call.");
  lines.push("    const toolCalls: ChatToolCall[] | undefined = Array.isArray(msg?.tool_calls)");
  lines.push("      ? msg!.tool_calls!");
  lines.push("          .filter(tc => tc && tc.function && typeof tc.function.name === \"string\")");
  lines.push("          .map((tc, i) => ({");
  lines.push("            id: tc.id || `tool_${i}`,");
  lines.push("            name: tc.function!.name as string,");
  lines.push("            arguments: typeof tc.function!.arguments === \"string\" ? tc.function!.arguments : \"{}\",");
  lines.push("          }))");
  lines.push("      : undefined;");
  lines.push("    return {");
  lines.push("      content: msg?.content || \"\",");
  lines.push("      usage: {");
  lines.push("        prompt_tokens: data.usage?.prompt_tokens,");
  lines.push("        completion_tokens: data.usage?.completion_tokens,");
  lines.push("      },");
  lines.push("      confidence: openaiCompatConfidence(data.choices?.[0]?.logprobs?.content),");
  lines.push("      tool_calls: toolCalls && toolCalls.length > 0 ? toolCalls : undefined,");
  lines.push("      raw: data,");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Map a sequence of per-token logprobs to a single 0..1 confidence value.");
  lines.push(" * We use exp(mean(logprob)) — the geometric mean of per-token probabilities.");
  lines.push(" * That collapses cleanly to a number every router can compare against");
  lines.push(" * `confidence_threshold`. Returns null when no logprobs are present.");
  lines.push(" */");
  lines.push("function openaiCompatConfidence(content: { logprob?: number }[] | undefined): number | null {");
  lines.push("  if (!Array.isArray(content) || content.length === 0) return null;");
  lines.push("  let sum = 0;");
  lines.push("  let n = 0;");
  lines.push("  for (const tok of content) {");
  lines.push("    if (typeof tok.logprob === \"number\" && Number.isFinite(tok.logprob)) {");
  lines.push("      sum += tok.logprob;");
  lines.push("      n++;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  if (n === 0) return null;");
  lines.push("  const mean = sum / n;");
  lines.push("  // exp can underflow on very long sequences; clamp to [0, 1].");
  lines.push("  const c = Math.exp(mean);");
  lines.push("  return Number.isFinite(c) ? Math.max(0, Math.min(1, c)) : null;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── llama.cpp (legacy /completion endpoint) ─────────────────────────────────

function emitLlamaCppAdapter(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// llama.cpp adapter — talks to /completion on a llama.cpp server.");
  lines.push("// Conversation messages are flattened into a single prompt with simple");
  lines.push("// role markers; this matches the conventional template most local models");
  lines.push("// recognise. For exact chat-template control, prefer the openai_compat");
  lines.push("// shim which llama.cpp also exposes.");
  lines.push("");
  lines.push("import type { ChatRequest, ChatResponse, IModelProvider } from \"./types\";");
  lines.push("import { approxTokens } from \"./types\";");
  lines.push("import { assertEndpointAllowed } from \"./ssrf_guard\";");
  lines.push("");
  lines.push("function flatten(messages: ChatRequest[\"messages\"]): string {");
  lines.push("  return messages");
  lines.push("    .map(m => {");
  lines.push("      if (m.role === \"system\") return `[SYS] ${m.content}`;");
  lines.push("      if (m.role === \"user\") return `[USER] ${m.content}`;");
  lines.push("      return `[ASSISTANT] ${m.content}`;");
  lines.push("    })");
  lines.push("    .join(\"\\n\");");
  lines.push("}");
  lines.push("");
  lines.push("export class LlamaCppProvider implements IModelProvider {");
  lines.push("  readonly name = \"llamacpp\";");
  lines.push("  private endpoint: string;");
  lines.push("");
  lines.push("  constructor(endpoint: string) {");
  lines.push("    assertEndpointAllowed(endpoint);");
  lines.push("    this.endpoint = endpoint.replace(/\\/+$/, \"\");");
  lines.push("  }");
  lines.push("");
  lines.push("  countTokens(text: string): number { return approxTokens(text); }");
  lines.push("");
  lines.push("  async chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {");
  lines.push("    const prompt = flatten(req.messages) + \"\\n[ASSISTANT] \";");
  lines.push("    const body = {");
  lines.push("      prompt,");
  lines.push("      temperature: req.temperature ?? 0,");
  lines.push("      top_p: req.top_p,");
  lines.push("      n_predict: req.max_output ?? 256,");
  lines.push("      stop: req.stop || [\"[USER]\", \"[SYS]\"],");
  lines.push("      stream: false,");
  lines.push("      // Phase 7: ask llama.cpp for per-token probabilities. The /completion");
  lines.push("      // endpoint returns these on `completion_probabilities` when n_probs > 0.");
  lines.push("      n_probs: 1,");
  lines.push("    };");
  lines.push("    const res = await fetch(`${this.endpoint}/completion`, {");
  lines.push("      method: \"POST\",");
  lines.push("      headers: { \"Content-Type\": \"application/json\" },");
  lines.push("      body: JSON.stringify(body),");
  lines.push("      signal,");
  lines.push("    });");
  lines.push("    if (!res.ok) {");
  lines.push("      const text = await res.text().catch(() => \"\");");
  lines.push("      throw new Error(`llama.cpp ${res.status}: ${text.slice(0, 256)}`);");
  lines.push("    }");
  lines.push("    const data = await res.json() as {");
  lines.push("      content?: string;");
  lines.push("      tokens_predicted?: number;");
  lines.push("      tokens_evaluated?: number;");
  lines.push("      completion_probabilities?: { probs?: { prob?: number }[] }[];");
  lines.push("    };");
  lines.push("    return {");
  lines.push("      content: data.content || \"\",");
  lines.push("      usage: {");
  lines.push("        prompt_tokens: data.tokens_evaluated,");
  lines.push("        completion_tokens: data.tokens_predicted,");
  lines.push("      },");
  lines.push("      confidence: llamaCppConfidence(data.completion_probabilities),");
  lines.push("      raw: data,");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Average top-1 probability across emitted tokens. Same shape as the");
  lines.push(" * openai_compat helper so router thresholds behave identically across");
  lines.push(" * providers. Returns null when llama.cpp didn't include probabilities.");
  lines.push(" */");
  lines.push("function llamaCppConfidence(probs: { probs?: { prob?: number }[] }[] | undefined): number | null {");
  lines.push("  if (!Array.isArray(probs) || probs.length === 0) return null;");
  lines.push("  let sum = 0;");
  lines.push("  let n = 0;");
  lines.push("  for (const tok of probs) {");
  lines.push("    const top = Array.isArray(tok.probs) ? tok.probs[0] : undefined;");
  lines.push("    if (top && typeof top.prob === \"number\" && Number.isFinite(top.prob)) {");
  lines.push("      sum += top.prob;");
  lines.push("      n++;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  if (n === 0) return null;");
  lines.push("  const c = sum / n;");
  lines.push("  return Math.max(0, Math.min(1, c));");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── KoboldCPP (native /api/v1/generate) ─────────────────────────────────────

function emitKoboldCppAdapter(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// KoboldCPP adapter — talks to /api/v1/generate. Kept separate from the");
  lines.push("// openai_compat shim because the native API gives finer sampling control");
  lines.push("// (e.g. mirostat, sampler_order) that some users rely on.");
  lines.push("");
  lines.push("import type { ChatRequest, ChatResponse, IModelProvider } from \"./types\";");
  lines.push("import { approxTokens } from \"./types\";");
  lines.push("import { assertEndpointAllowed } from \"./ssrf_guard\";");
  lines.push("");
  lines.push("function flatten(messages: ChatRequest[\"messages\"]): string {");
  lines.push("  return messages");
  lines.push("    .map(m => `${m.role === \"system\" ? \"### Instruction:\" : m.role === \"user\" ? \"### User:\" : \"### Response:\"}\\n${m.content}`)");
  lines.push("    .join(\"\\n\\n\") + \"\\n\\n### Response:\\n\";");
  lines.push("}");
  lines.push("");
  lines.push("export class KoboldCppProvider implements IModelProvider {");
  lines.push("  readonly name = \"koboldcpp\";");
  lines.push("  private endpoint: string;");
  lines.push("");
  lines.push("  constructor(endpoint: string) {");
  lines.push("    assertEndpointAllowed(endpoint);");
  lines.push("    this.endpoint = endpoint.replace(/\\/+$/, \"\");");
  lines.push("  }");
  lines.push("");
  lines.push("  countTokens(text: string): number { return approxTokens(text); }");
  lines.push("");
  lines.push("  async chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {");
  lines.push("    const body = {");
  lines.push("      prompt: flatten(req.messages),");
  lines.push("      temperature: req.temperature ?? 0,");
  lines.push("      top_p: req.top_p,");
  lines.push("      max_length: req.max_output ?? 256,");
  lines.push("      stop_sequence: req.stop || [\"### User:\", \"### Instruction:\"],");
  lines.push("    };");
  lines.push("    const res = await fetch(`${this.endpoint}/api/v1/generate`, {");
  lines.push("      method: \"POST\",");
  lines.push("      headers: { \"Content-Type\": \"application/json\" },");
  lines.push("      body: JSON.stringify(body),");
  lines.push("      signal,");
  lines.push("    });");
  lines.push("    if (!res.ok) {");
  lines.push("      const text = await res.text().catch(() => \"\");");
  lines.push("      throw new Error(`KoboldCPP ${res.status}: ${text.slice(0, 256)}`);");
  lines.push("    }");
  lines.push("    const data = await res.json() as { results?: { text?: string }[] };");
  lines.push("    const content = data.results?.[0]?.text || \"\";");
  lines.push("    return {");
  lines.push("      content,");
  lines.push("      usage: { completion_tokens: approxTokens(content) },");
  lines.push("      raw: data,");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Generic HTTP ────────────────────────────────────────────────────────────

function emitGenericHttpAdapter(): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Generic HTTP adapter — for endpoints that don't match any known shape.");
  lines.push("// Sends a single JSON POST with { model, messages, temperature, ... }");
  lines.push("// and expects a response with a `content` string field. Override for");
  lines.push("// custom servers via the user's `extension_point` mechanism.");
  lines.push("");
  lines.push("import type { ChatRequest, ChatResponse, IModelProvider } from \"./types\";");
  lines.push("import { approxTokens } from \"./types\";");
  lines.push("import { assertEndpointAllowed } from \"./ssrf_guard\";");
  lines.push("");
  lines.push("export class HttpProvider implements IModelProvider {");
  lines.push("  readonly name = \"http\";");
  lines.push("  private endpoint: string;");
  lines.push("");
  lines.push("  constructor(endpoint: string) {");
  lines.push("    assertEndpointAllowed(endpoint);");
  lines.push("    this.endpoint = endpoint.replace(/\\/+$/, \"\");");
  lines.push("  }");
  lines.push("");
  lines.push("  countTokens(text: string): number { return approxTokens(text); }");
  lines.push("");
  lines.push("  async chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {");
  lines.push("    const res = await fetch(this.endpoint, {");
  lines.push("      method: \"POST\",");
  lines.push("      headers: { \"Content-Type\": \"application/json\" },");
  lines.push("      body: JSON.stringify(req),");
  lines.push("      signal,");
  lines.push("    });");
  lines.push("    if (!res.ok) {");
  lines.push("      const text = await res.text().catch(() => \"\");");
  lines.push("      throw new Error(`http ${res.status}: ${text.slice(0, 256)}`);");
  lines.push("    }");
  lines.push("    const data = await res.json() as { content?: string; usage?: { prompt_tokens?: number; completion_tokens?: number }; confidence?: number | null };");
  lines.push("    return {");
  lines.push("      content: data.content || \"\",");
  lines.push("      usage: data.usage || { completion_tokens: approxTokens(data.content || \"\") },");
  lines.push("      confidence: typeof data.confidence === \"number\" ? data.confidence : null,");
  lines.push("      raw: data,");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Registry ────────────────────────────────────────────────────────────────

function emitProviderRegistry(system: IR.IRSystem, used: Set<IR.IRProviderKind>): string {
  const lines: string[] = [];
  lines.push("// Generated by MarrowScript compiler. DO NOT EDIT.");
  lines.push("// Cognition Layer Phase 2 — provider registry.");
  lines.push("// One concrete provider instance per declared `model`. Resolved by id.");
  lines.push("");
  lines.push("import type { IModelProvider } from \"./types\";");
  if (used.has("ollama")) lines.push("import { OllamaProvider } from \"./ollama\";");
  if (used.has("openai_compat")) lines.push("import { OpenAICompatProvider } from \"./openai_compat\";");
  if (used.has("llamacpp")) lines.push("import { LlamaCppProvider } from \"./llamacpp\";");
  if (used.has("koboldcpp")) lines.push("import { KoboldCppProvider } from \"./koboldcpp\";");
  if (used.has("http")) lines.push("import { HttpProvider } from \"./http\";");
  lines.push("");
  lines.push("export interface ModelEntry {");
  lines.push("  /** Declared model name (e.g. \"TinyClassifier\"). */");
  lines.push("  name: string;");
  lines.push("  /** Provider-specific identifier (the `name:` field of the .marrow `model` decl). */");
  lines.push("  modelName: string;");
  lines.push("  provider: IModelProvider;");
  lines.push("  contextWindow: number;");
  lines.push("  maxOutput: number;");
  lines.push("  temperature: number;");
  lines.push("  topP: number | null;");
  lines.push("  stop: string[];");
  lines.push("  costClass: \"tiny\" | \"small\" | \"medium\" | \"large\";");
  lines.push("  latencyClass: \"fast\" | \"medium\" | \"slow\";");
  lines.push("}");
  lines.push("");
  lines.push("// One entry per model declared in the .marrow source. Sorted by name for determinism.");
  lines.push("export const MODELS: Record<string, ModelEntry> = {");

  // Sort models by name so the emitted file is deterministic regardless of
  // declaration order in the IR.
  const sorted = [...system.models].sort((a, b) => a.name.localeCompare(b.name));
  for (const m of sorted) {
    const ctor = providerConstructorCall(m);
    lines.push(`  ${JSON.stringify(m.name)}: {`);
    lines.push(`    name: ${JSON.stringify(m.name)},`);
    lines.push(`    modelName: ${JSON.stringify(m.model_name)},`);
    lines.push(`    provider: ${ctor},`);
    lines.push(`    contextWindow: ${m.context_window},`);
    lines.push(`    maxOutput: ${m.max_output},`);
    lines.push(`    temperature: ${m.temperature},`);
    lines.push(`    topP: ${m.top_p === null ? "null" : m.top_p},`);
    lines.push(`    stop: ${JSON.stringify(m.stop)},`);
    lines.push(`    costClass: ${JSON.stringify(m.cost_class)},`);
    lines.push(`    latencyClass: ${JSON.stringify(m.latency_class)},`);
    lines.push(`  },`);
  }
  lines.push("};");
  lines.push("");
  lines.push("export function getModel(name: string): ModelEntry {");
  lines.push("  const e = MODELS[name];");
  lines.push("  if (!e) throw new Error(`Unknown model: ${name}`);");
  lines.push("  return e;");
  lines.push("}");
  lines.push("");
  lines.push("export function listModelNames(): string[] {");
  lines.push("  return Object.keys(MODELS).sort();");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function providerConstructorCall(m: IR.IRCogModel): string {
  // Endpoint string — emit as JSON literal so escape-sensitive URLs survive.
  // Adapters that take an endpoint accept a string at construction time;
  // the Ollama adapter falls back to OLLAMA_HOST when none is provided.
  switch (m.provider) {
    case "ollama":
      return m.endpoint
        ? `new OllamaProvider(${JSON.stringify(m.endpoint)})`
        : `new OllamaProvider()`;
    case "openai_compat":
      return `new OpenAICompatProvider(${JSON.stringify(m.endpoint || "")})`;
    case "llamacpp":
      return `new LlamaCppProvider(${JSON.stringify(m.endpoint || "")})`;
    case "koboldcpp":
      return `new KoboldCppProvider(${JSON.stringify(m.endpoint || "")})`;
    case "http":
      return `new HttpProvider(${JSON.stringify(m.endpoint || "")})`;
  }
}
