-- MarrowScript: Prompt Cache Schema
-- Generated by MarrowScript compiler. DO NOT EDIT.
--
-- Content-addressed cache for prompt invocations. Entries are keyed by
-- a deterministic hash of (canonical input | model | template | output type).
-- TTL is enforced application-side (the runtime ignores rows with
-- expires_at < now()), and a janitor query can periodically delete expired
-- rows. Foreign keys are intentionally absent: the cache is a side-store.

CREATE TABLE IF NOT EXISTS prompt_cache (
  cache_key       VARCHAR(64) PRIMARY KEY,
  prompt_name     VARCHAR     NOT NULL,
  model_id        VARCHAR     NOT NULL,
  output_value    JSONB       NOT NULL,
  prompt_tokens   INT,
  completion_tokens INT,
  cost_usd        NUMERIC(10,6),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ NOT NULL,
  hits            INT         NOT NULL DEFAULT 0,
  last_hit_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_prompt_cache_expires
  ON prompt_cache (expires_at);

CREATE INDEX IF NOT EXISTS idx_prompt_cache_prompt
  ON prompt_cache (prompt_name, created_at);
