-- Generated by MarrowScript compiler. DO NOT EDIT.
-- Source: 7946deed60f4b04f
-- Module: RepoForgeRequestStore

CREATE TABLE IF NOT EXISTS repo_forge_requests (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  preset VARCHAR NOT NULL,
  repo_a_url VARCHAR NOT NULL,
  repo_b_url VARCHAR NOT NULL,
  repo_a_ref VARCHAR NOT NULL,
  repo_b_ref VARCHAR NOT NULL,
  target_path VARCHAR NOT NULL,
  complexity DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION update_repo_forge_requests_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_repo_forge_requests_updated_at
  BEFORE UPDATE ON repo_forge_requests
  FOR EACH ROW
  EXECUTE FUNCTION update_repo_forge_requests_updated_at();
