// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 3 — per-trace budget tracker.
//
// Two ceilings, both opt-in:
//   LLM_BUDGET_TOKENS_PER_TRACE  — absolute tokens (prompt + completion)
//   LLM_BUDGET_USD_PER_TRACE     — fractional USD (cost class lookup table
//                                   gives a pessimistic per-1k-tokens price)
//
// When neither is set, the tracker is permissive — it still records spend
// for observability but never throws.

import { counter, gauge } from "../metrics";

/** Pessimistic per-1k-tokens USD floor by cost class. Used when models
 * don't carry a cost-per-token annotation. Numbers are deliberately on the
 * high side so the gauge never under-bills.
 */
const COST_FLOOR: Record<string, number> = {
  tiny:   0.0001,
  small:  0.0010,
  medium: 0.0100,
  large:  0.0300,
};

export class BudgetExceededError extends Error {
  readonly code = "BUDGET_EXCEEDED";
  constructor(
    message: string,
    readonly trace_id: string,
    readonly kind: "tokens" | "usd",
    readonly limit: number,
    readonly observed: number,
  ) {
    super(message);
    this.name = "BudgetExceededError";
  }
}

export interface BudgetTracker {
  readonly trace_id: string;
  /** Cumulative tokens charged to this trace. */
  readonly tokens: number;
  /** Cumulative USD charged to this trace. */
  readonly usd: number;
  /** Throw if this trace cannot afford `tokens` more without exceeding the ceiling. */
  assertCanSpend(tokens: number, costClass: string): void;
  /** Record a completed call. Promotion `tokens=0` is allowed for cache hits. */
  charge(tokens: number, costClass: string): void;
  /** Refund a charge — used when a call was attempted and then rolled back (e.g. validation failed before billing). */
  refund(tokens: number, costClass: string): void;
}

function readLimit(envName: string): number | null {
  const raw = process.env[envName];
  if (!raw) return null;
  const v = Number(raw);
  if (!Number.isFinite(v) || v <= 0) return null;
  return v;
}

const TOKEN_LIMIT = readLimit("LLM_BUDGET_TOKENS_PER_TRACE");
const USD_LIMIT   = readLimit("LLM_BUDGET_USD_PER_TRACE");

class StandardBudget implements BudgetTracker {
  readonly trace_id: string;
  private _tokens = 0;
  private _usd = 0;

  constructor(trace_id: string) { this.trace_id = trace_id; }
  get tokens(): number { return this._tokens; }
  get usd(): number { return this._usd; }

  private projectedUsd(addTokens: number, costClass: string): number {
    const rate = COST_FLOOR[costClass] ?? COST_FLOOR.small;
    return this._usd + (addTokens / 1000) * rate;
  }

  assertCanSpend(tokens: number, costClass: string): void {
    if (TOKEN_LIMIT !== null && this._tokens + tokens > TOKEN_LIMIT) {
      counter("cognition.budget_exceeded", { kind: "tokens" });
      throw new BudgetExceededError(
        `Trace ${this.trace_id} would exceed token budget (${this._tokens + tokens} > ${TOKEN_LIMIT})`,
        this.trace_id, "tokens", TOKEN_LIMIT, this._tokens + tokens,
      );
    }
    if (USD_LIMIT !== null) {
      const projected = this.projectedUsd(tokens, costClass);
      if (projected > USD_LIMIT) {
        counter("cognition.budget_exceeded", { kind: "usd" });
        throw new BudgetExceededError(
          `Trace ${this.trace_id} would exceed USD budget ($${projected.toFixed(4)} > $${USD_LIMIT})`,
          this.trace_id, "usd", USD_LIMIT, projected,
        );
      }
    }
  }

  charge(tokens: number, costClass: string): void {
    if (tokens <= 0) return;
    this._tokens += tokens;
    const rate = COST_FLOOR[costClass] ?? COST_FLOOR.small;
    this._usd += (tokens / 1000) * rate;
    counter("cognition.tokens_charged", { cost_class: costClass });
    gauge("cognition.trace_tokens", this._tokens, { trace_id: this.trace_id });
    gauge("cognition.trace_usd", this._usd, { trace_id: this.trace_id });
  }

  refund(tokens: number, costClass: string): void {
    if (tokens <= 0) return;
    this._tokens = Math.max(0, this._tokens - tokens);
    const rate = COST_FLOOR[costClass] ?? COST_FLOOR.small;
    this._usd = Math.max(0, this._usd - (tokens / 1000) * rate);
    counter("cognition.tokens_refunded", { cost_class: costClass });
  }
}

export function newBudget(trace_id: string): BudgetTracker {
  return new StandardBudget(trace_id);
}

/** True if either ceiling is configured. Useful for callsite branching. */
export function budgetEnforced(): boolean {
  return TOKEN_LIMIT !== null || USD_LIMIT !== null;
}

/** Internal: expose the (immutable) limits for tests / observability. */
export function budgetLimits(): { tokens: number | null; usd: number | null } {
  return { tokens: TOKEN_LIMIT, usd: USD_LIMIT };
}
