// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 3 — prompt cache.
//
// Two storage modes, switched by env var LLM_CACHE_MODE:
//   memory  — in-process Map, useful for tests and single-instance dev (default)
//   pg      — Postgres-backed, durable across restarts and HA workers
//
// Both modes share the same get/put/deriveKey API. The cognition runtime
// always asks the cache, never the storage backend directly.

import { createHash } from "crypto";
import { counter } from "../metrics";
import { logger } from "../logger";

export interface CacheEntry {
  value: unknown;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  cost_usd: number | null;
  cached_at: number; // ms epoch
  expires_at: number; // ms epoch
}

export interface PromptCache {
  get(key: string): Promise<CacheEntry | null>;
  put(key: string, prompt_name: string, model_id: string, value: unknown, ttl_ms: number, usage: { prompt_tokens?: number; completion_tokens?: number; cost_usd?: number }): Promise<void>;
}

/**
 * Canonical-JSON stringify: keys are sorted at every level so two
 * objects with the same content produce identical strings regardless
 * of declaration order. Used as the basis for the cache key.
 */
function canonical(value: unknown): string {
  if (value === null || value === undefined) return JSON.stringify(value ?? null);
  if (typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return "{" + keys.map(k => JSON.stringify(k) + ":" + canonical(obj[k])).join(",") + "}";
}

/**
 * Derive a 64-char hex key. The runtime passes the rendered template
 * as `template_hash` so prompt rewordings invalidate the cache.
 */
export function deriveKey(args: {
  prompt_name: string;
  model_id: string;
  template_hash: string;
  output_type: string;
  input: unknown;
}): string {
  const composite = [
    args.prompt_name,
    args.model_id,
    args.template_hash,
    args.output_type,
    canonical(args.input),
  ].join("|");
  return createHash("sha256").update(composite).digest("hex");
}

class MemoryCache implements PromptCache {
  private store = new Map<string, CacheEntry>();

  async get(key: string): Promise<CacheEntry | null> {
    const e = this.store.get(key);
    if (!e) return null;
    if (e.expires_at < Date.now()) {
      this.store.delete(key);
      return null;
    }
    return e;
  }

  async put(key: string, _prompt: string, _model: string, value: unknown, ttl_ms: number, usage: { prompt_tokens?: number; completion_tokens?: number; cost_usd?: number }): Promise<void> {
    const now = Date.now();
    this.store.set(key, {
      value,
      prompt_tokens: usage.prompt_tokens ?? null,
      completion_tokens: usage.completion_tokens ?? null,
      cost_usd: usage.cost_usd ?? null,
      cached_at: now,
      expires_at: now + ttl_ms,
    });
  }
}

class PgCache implements PromptCache {
  async get(key: string): Promise<CacheEntry | null> {
    // Lazy import — keeps tests that don't exercise PG mode free of pg dependency.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { query } = require("../db") as { query: (sql: string, args: unknown[]) => Promise<Record<string, unknown>[]> };
    const rows = await query(
      `UPDATE prompt_cache SET hits = hits + 1, last_hit_at = NOW()
        WHERE cache_key = $1 AND expires_at > NOW() RETURNING *`,
      [key],
    );
    if (rows.length === 0) return null;
    const r = rows[0] as { output_value: unknown; prompt_tokens: number | null; completion_tokens: number | null; cost_usd: string | null; created_at: Date; expires_at: Date };
    return {
      value: r.output_value,
      prompt_tokens: r.prompt_tokens,
      completion_tokens: r.completion_tokens,
      cost_usd: r.cost_usd === null ? null : Number(r.cost_usd),
      cached_at: new Date(r.created_at).getTime(),
      expires_at: new Date(r.expires_at).getTime(),
    };
  }

  async put(key: string, prompt_name: string, model_id: string, value: unknown, ttl_ms: number, usage: { prompt_tokens?: number; completion_tokens?: number; cost_usd?: number }): Promise<void> {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { query } = require("../db") as { query: (sql: string, args: unknown[]) => Promise<unknown> };
    await query(
      `INSERT INTO prompt_cache (cache_key, prompt_name, model_id, output_value, prompt_tokens, completion_tokens, cost_usd, expires_at)
        VALUES ($1, $2, $3, $4, $5, $6, $7, NOW() + ($8 || ' milliseconds')::interval)
        ON CONFLICT (cache_key) DO UPDATE SET
          output_value = EXCLUDED.output_value,
          expires_at = EXCLUDED.expires_at,
          last_hit_at = NULL,
          hits = 0`,
      [key, prompt_name, model_id, JSON.stringify(value), usage.prompt_tokens ?? null, usage.completion_tokens ?? null, usage.cost_usd ?? null, ttl_ms],
    );
  }
}

function chooseBackend(): PromptCache {
  const mode = process.env.LLM_CACHE_MODE || "memory";
  if (mode === "pg") return new PgCache();
  if (mode !== "memory") {
    logger.warn("prompt_cache_unknown_mode", { event: "cache", status: "rejected", metadata: { mode } });
  }
  return new MemoryCache();
}

const __backend: PromptCache = chooseBackend();

/** Public cache. Counters are emitted on every get/put for hit-rate observability. */
export const cache: PromptCache = {
  async get(key: string): Promise<CacheEntry | null> {
    const e = await __backend.get(key);
    counter(e ? "cognition.cache_hit" : "cognition.cache_miss");
    return e;
  },
  async put(key, prompt_name, model_id, value, ttl_ms, usage): Promise<void> {
    await __backend.put(key, prompt_name, model_id, value, ttl_ms, usage);
    counter("cognition.cache_put", { prompt: prompt_name });
  },
};

/** For tests: clear the in-memory cache. No-op against PG mode. */
export function __resetMemoryCache(): void {
  if (__backend instanceof MemoryCache) {
    // @ts-expect-error — internal field for tests
    __backend.store.clear();
  }
}
