// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — public entry.
//
// Application code imports `getCognition` to get a CognitionCtx wired
// to all declared models, prompts, routers, and primitives.

import { logger } from "../logger";
import { counter } from "../metrics";
import { listModelNames, getModel } from "../providers";
import { PROMPTS, getPrompt, findSummarizer } from "./prompts";
import { ROUTERS, getRouter } from "./router";
import { PRIMITIVES, callCognition, type CognitionCtx, type CognitionPrimitive } from "./primitives";
import { getIndex as __getMemoryIndex } from "../memory";

import { randomUUID } from "crypto";

export function newTraceId(): string { return randomUUID(); }

export function buildCtx(trace_id?: string, signal?: AbortSignal): CognitionCtx {
  return {
    trace_id: trace_id ?? newTraceId(),
    signal,
    prompts: {
      get(name: string) { return PROMPTS[name] ?? null; },
      findSummarizer,
    },
    routers: {
      get(name: string) { return ROUTERS[name] ?? null; },
    },
    memory: {
      getIndex() { return __getMemoryIndex(); },
    },
    logger,
    metrics: { counter },
  };
}

export { PROMPTS, getPrompt, findSummarizer };
export { ROUTERS, getRouter };
export { PRIMITIVES, callCognition };
export { listModelNames, getModel };

export async function callPrompt(name: string, input: Record<string, unknown>): Promise<unknown> {
  const fn = getPrompt(name);
  return fn(input, { trace_id: newTraceId() });
}

export async function runCognition(name: string, args: Record<string, unknown>): Promise<unknown> {
  return callCognition(name, args, buildCtx());
}
