// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 9 — repository ingestion runtime.
//
// Provides ingestRepository(url, ref?) → IngestReport. Used by the
// `ingest_repository` cognition catalog primitive. Read-only sandbox,
// size-capped, deny-list-aware, deterministic by (url, ref) key.

import * as fs from "fs";
import * as path from "path";
import { createHash } from "crypto";
import { execFile } from "child_process";
import { promisify } from "util";
import { logger } from "../logger";
import { counter, histogram } from "../metrics";

const execFileAsync = promisify(execFile);

// ── Types ───────────────────────────────────────────────────────────

export interface IngestReport {
  /** Absolute path to the cloned repo on this host. Read-only. */
  local_path: string;
  /** Commit SHA of the cloned ref (full 40-char hex). */
  head_sha: string;
  /** Count of regular files inside local_path (after deny-list). */
  file_count: number;
  /** Total bytes across counted files. */
  total_bytes: number;
  /** The url we cloned from, with tokens stripped. */
  url_redacted: string;
  /** The ref we resolved (branch / tag / commit). */
  ref: string;
  /** When this report was produced (ms since epoch). */
  ingested_at: number;
  /** Hint for the indexer — root-level entry path used as the indexer working dir. */
  indexer_root: string;
}

export type IngestErrorKind =
  | "oversize"
  | "too_many_files"
  | "denied_extension"
  | "clone_failed"
  | "timeout"
  | "ssrf"
  | "escape"
  | "invalid_url"
  | "git_unavailable";

export class IngestError extends Error {
  readonly code = "INGEST_FAILED";
  constructor(public readonly kind: IngestErrorKind, message: string) {
    super(message);
    this.name = "IngestError";
  }
}

// ── Configuration ────────────────────────────────────────────────────

/** Default sandbox root. Override with LLM_INGEST_ROOT. */
const DEFAULT_SANDBOX = path.resolve(process.cwd(), ".forge-cache", "ingest");

/** 500 MB. Override with LLM_INGEST_MAX_BYTES. */
const DEFAULT_MAX_BYTES = 524288000;

/** 50,000 files. Override with LLM_INGEST_MAX_FILES. */
const DEFAULT_MAX_FILES = 50000;

/** Per-clone timeout (ms). Override with LLM_INGEST_TIMEOUT_MS. */
const DEFAULT_TIMEOUT_MS = 120000;

/** Default endpoint allowlist for ingest URLs. github.com is in by
 *  default; add more via LLM_INGEST_ALLOWLIST=https://github.com,https://gitlab.com
 *  Set LLM_INGEST_ALLOW_ANY=1 to disable the host check (NOT recommended). */
const DEFAULT_INGEST_ALLOWLIST = ["https://github.com", "https://gitlab.com", "https://codeberg.org", "https://bitbucket.org"];

/** File extensions excluded from file_count + total_bytes accounting and
 *  hidden from any downstream indexer. Sorted, deterministic. */
const DENY_EXTENSIONS: readonly string[] = [
  // archives
  ".7z", ".bz2", ".gz", ".rar", ".tar", ".tgz", ".xz", ".zip",
  // executables / binaries
  ".bin", ".dll", ".dylib", ".exe", ".o", ".obj", ".pdb", ".so",
  // compiled bytecode
  ".class", ".pyc", ".pyd", ".rmeta", ".rlib",
  // disk / vm images
  ".dmg", ".img", ".iso", ".vdi", ".vmdk",
  // media / fonts
  ".aac", ".avi", ".eot", ".flac", ".flv", ".gif", ".ico", ".jpeg", ".jpg", ".m4a", ".m4v", ".mkv", ".mov", ".mp3", ".mp4", ".mpeg", ".mpg", ".oga", ".ogg", ".ogv", ".opus", ".otf", ".png", ".tiff", ".ttf", ".wav", ".webm", ".webp", ".woff", ".woff2",
  // documents & data dumps that aren't useful to a code indexer
  ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
  ".sqlite", ".db",
];

function isDeniedFile(p: string): boolean {
  const ext = path.extname(p).toLowerCase();
  // Binary search would be overkill — deny list is < 50 entries.
  return DENY_EXTENSIONS.indexOf(ext) >= 0;
}

function readEnvNumber(name: string, fallback: number): number {
  const raw = process.env[name];
  if (!raw) return fallback;
  const v = Number(raw);
  if (!Number.isFinite(v) || v <= 0) return fallback;
  return v;
}

function readSandboxRoot(): string {
  const raw = (process.env.LLM_INGEST_ROOT || "").trim();
  if (!raw) return DEFAULT_SANDBOX;
  return path.resolve(raw);
}

// ── URL handling ────────────────────────────────────────────────────

/** Strip `x:TOKEN@host` userinfo from a URL so secrets don't end up in spans. */
export function redactUrl(url: string): string {
  try {
    const u = new URL(url);
    if (u.username || u.password) {
      u.username = "";
      u.password = "";
    }
    return u.toString();
  } catch {
    return "<invalid url>";
  }
}

/** Throws IngestError(ssrf) if the URL is not on the allowlist. */
export function assertIngestAllowed(url: string): void {
  if (process.env.LLM_INGEST_ALLOW_ANY === "1") return;
  let parsed: URL;
  try { parsed = new URL(url); } catch { throw new IngestError("invalid_url", `Invalid URL: ${redactUrl(url)}`); }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new IngestError("ssrf", `Only http(s):// URLs are accepted (got ${parsed.protocol})`);
  }
  const userAllow = (process.env.LLM_INGEST_ALLOWLIST || "").split(",").map(s => s.trim()).filter(Boolean);
  const allow = userAllow.length > 0 ? userAllow : DEFAULT_INGEST_ALLOWLIST;
  for (const a of allow) {
    if (url.startsWith(a)) return;
  }
  throw new IngestError("ssrf", `URL ${redactUrl(url)} is not in LLM_INGEST_ALLOWLIST. Add the host prefix or set LLM_INGEST_ALLOW_ANY=1.`);
}

// ── Sandbox path ────────────────────────────────────────────────────

/** Deterministic sandbox subdir name: sha256(url|ref).slice(0, 16). */
export function sandboxKey(url: string, ref: string): string {
  return createHash("sha256").update(redactUrl(url) + "|" + ref).digest("hex").slice(0, 16);
}

function ensureWithinSandbox(target: string, sandboxRoot: string): void {
  const resolved = path.resolve(target);
  const root = path.resolve(sandboxRoot);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw new IngestError("escape", `Path ${resolved} escapes sandbox ${root}`);
  }
}

// ── Git invocation ──────────────────────────────────────────────────

async function gitVersion(): Promise<string> {
  try {
    const { stdout } = await execFileAsync("git", ["--version"], { timeout: 5000, windowsHide: true });
    return stdout.trim();
  } catch {
    throw new IngestError("git_unavailable", "git is not installed or not on PATH");
  }
}

async function gitCloneShallow(url: string, ref: string, dest: string, timeoutMs: number): Promise<void> {
  // Args:
  //   --depth 1            shallow — we only want the working tree, not history
  //   --filter=blob:limit  cap individual blob size — drops giant binaries
  //   --single-branch      don't fetch other branches
  //   --no-tags            skip the tag refs
  //   --branch <ref>       resolve the ref at clone time so head_sha is stable
  //                        (only when ref != HEAD; `--branch HEAD` is invalid)
  //   -c core.autocrlf=false   keep line endings as committed (determinism)
  //   -c safe.directory=*  permit work in this user-owned dir without git's safe-dir warning
  const baseArgs: string[] = [
    "clone",
    "--depth", "1",
    "--filter=blob:limit=10m",
    "--single-branch",
    "--no-tags",
    "-c", "core.autocrlf=false",
    "-c", "safe.directory=*",
  ];
  // Only pass --branch when the user asked for a specific ref. HEAD is the
  // remote's default branch; git resolves it implicitly without --branch.
  const args = ref && ref !== "HEAD"
    ? [...baseArgs, "--branch", ref, url, dest]
    : [...baseArgs, url, dest];
  try {
    await execFileAsync("git", args, { timeout: timeoutMs, windowsHide: true, maxBuffer: 1024 * 1024 });
  } catch (e) {
    const err = e as Error & { signal?: string; code?: number; killed?: boolean };
    if (err.killed && err.signal === "SIGTERM") {
      throw new IngestError("timeout", `git clone timed out after ${timeoutMs}ms`);
    }
    // Some refs only exist as commit SHAs, not branches. Retry without --branch.
    // (Fall through to throw if that also fails.)
    if (ref !== "HEAD" && /Remote branch.*not found|fatal: Remote branch/i.test(err.message || "")) {
      try {
        await execFileAsync("git", [...baseArgs, url, dest], { timeout: timeoutMs, windowsHide: true, maxBuffer: 1024 * 1024 });
        return;
      } catch (e2) {
        const err2 = e2 as Error;
        throw new IngestError("clone_failed", `git clone failed: ${(err2.message || "").slice(0, 256)}`);
      }
    }
    throw new IngestError("clone_failed", `git clone failed: ${(err.message || "").slice(0, 256)}`);
  }
}

async function gitHeadSha(repoDir: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync("git", ["-C", repoDir, "rev-parse", "HEAD"], { timeout: 5000, windowsHide: true });
    return stdout.trim();
  } catch {
    return "unknown";
  }
}

// ── Tree walking ────────────────────────────────────────────────────

interface AccountingResult {
  file_count: number;
  total_bytes: number;
  oversize: boolean;
  too_many_files: boolean;
}

async function walkAndCount(root: string, sandboxRoot: string, maxFiles: number, maxBytes: number): Promise<AccountingResult> {
  let file_count = 0;
  let total_bytes = 0;
  let oversize = false;
  let too_many_files = false;

  // Iterative walk with an explicit stack — avoids recursion blowing the
  // stack on deeply nested monorepos.
  const stack: string[] = [root];
  while (stack.length > 0) {
    const dir = stack.pop()!;
    let entries: fs.Dirent[];
    try {
      entries = await fs.promises.readdir(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    // Sort for determinism — same tree always walked in same order.
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const ent of entries) {
      // Skip the .git database — we want the working tree, not git internals.
      if (ent.name === ".git") continue;
      const full = path.join(dir, ent.name);
      // Cheap escape check for symlinks: ensureWithinSandbox after stat-resolve.
      if (ent.isSymbolicLink()) {
        try {
          const resolved = await fs.promises.realpath(full);
          ensureWithinSandbox(resolved, sandboxRoot);
        } catch {
          // unreadable / dangling symlink — skip silently, indexer will too
          continue;
        }
      }
      if (ent.isDirectory()) {
        stack.push(full);
        continue;
      }
      if (!ent.isFile()) continue;
      if (isDeniedFile(full)) continue;
      let size = 0;
      try {
        const st = await fs.promises.stat(full);
        size = st.size;
      } catch {
        continue;
      }
      file_count += 1;
      total_bytes += size;
      if (file_count > maxFiles) { too_many_files = true; break; }
      if (total_bytes > maxBytes) { oversize = true; break; }
    }
    if (oversize || too_many_files) break;
  }

  return { file_count, total_bytes, oversize, too_many_files };
}

// ── Public entry ────────────────────────────────────────────────────

export interface IngestOptions {
  /** Branch / tag / commit-ish. Defaults to HEAD. */
  ref?: string;
  /** Override LLM_INGEST_MAX_BYTES for this call. */
  max_bytes?: number;
  /** Override LLM_INGEST_MAX_FILES for this call. */
  max_files?: number;
  /** Override LLM_INGEST_TIMEOUT_MS for this call. */
  timeout_ms?: number;
  /** Force re-clone even when the sandbox dir already exists for this key. */
  force?: boolean;
}

export async function ingestRepository(url: string, opts: IngestOptions = {}): Promise<IngestReport> {
  const ref = (opts.ref || "HEAD").trim() || "HEAD";
  assertIngestAllowed(url);
  await gitVersion();

  const max_bytes = opts.max_bytes ?? readEnvNumber("LLM_INGEST_MAX_BYTES", DEFAULT_MAX_BYTES);
  const max_files = opts.max_files ?? readEnvNumber("LLM_INGEST_MAX_FILES", DEFAULT_MAX_FILES);
  const timeout_ms = opts.timeout_ms ?? readEnvNumber("LLM_INGEST_TIMEOUT_MS", DEFAULT_TIMEOUT_MS);

  const root = readSandboxRoot();
  await fs.promises.mkdir(root, { recursive: true });
  const key = sandboxKey(url, ref);
  const dest = path.join(root, key);
  ensureWithinSandbox(dest, root);

  const t0 = Date.now();
  const alreadyCloned = fs.existsSync(path.join(dest, ".git"));
  if (opts.force && fs.existsSync(dest)) {
    await fs.promises.rm(dest, { recursive: true, force: true });
  }

  if (!fs.existsSync(path.join(dest, ".git"))) {
    counter("cognition.ingest.clone", { ref });
    await gitCloneShallow(url, ref, dest, timeout_ms);
  } else {
    counter("cognition.ingest.cache_hit", { ref });
  }

  // Account for size + file count after the clone — the --filter flag
  // already drops blobs over 10MB, but we still need a hard ceiling on
  // the total tree before the indexer touches it.
  const acc = await walkAndCount(dest, root, max_files, max_bytes);
  if (acc.oversize) {
    throw new IngestError("oversize", `Repo exceeds ${max_bytes} bytes (counted ${acc.total_bytes}+).`);
  }
  if (acc.too_many_files) {
    throw new IngestError("too_many_files", `Repo exceeds ${max_files} files (counted ${acc.file_count}+).`);
  }

  const head_sha = await gitHeadSha(dest);
  const elapsed = Date.now() - t0;
  histogram("cognition.ingest.latency_ms", elapsed, { ref });

  const report: IngestReport = {
    local_path: dest,
    head_sha,
    file_count: acc.file_count,
    total_bytes: acc.total_bytes,
    url_redacted: redactUrl(url),
    ref,
    ingested_at: t0,
    indexer_root: dest,
  };

  logger.info("cognition_ingest_completed", {
    event: "ingest_repository",
    status: "success",
    duration_ms: elapsed,
    metadata: {
      url: report.url_redacted,
      ref: report.ref,
      head_sha: report.head_sha,
      file_count: report.file_count,
      total_bytes: report.total_bytes,
      cached: alreadyCloned,
    },
  });
  return report;
}
