// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition primitives — closed catalog implementations.
// Only the primitives referenced by capabilities in the system are emitted.

import { logger } from "../logger";
import { counter } from "../metrics";
import { getPrompt, type PromptFn, findSummarizer } from "./prompts";
import { getRouter, type CompiledRouter } from "./router";

export interface CognitionCtx {
  trace_id: string;
  signal?: AbortSignal;
  prompts: {
    get(name: string): PromptFn | null;
    findSummarizer(): PromptFn | null;
  };
  routers: {
    get(name: string): CompiledRouter | null;
  };
  memory: {
    /** Returns the singleton SemanticIndex, or null when memory is not configured. */
    getIndex(): { walk(task: string, hopDepth: number, maxFiles: number, repo_filter?: string | string[]): { files: string[]; symbols: string[]; target_symbol: string }; symbolsByFile(file: string): unknown[]; importsOf(file: string): string[]; refresh(): Promise<void>; } | null;
  };
  logger: typeof logger;
  metrics: { counter: typeof counter };
}

// ingest_repository (ingestion, cost=free, callsModel=false)
// Clone a Git repository into a sandboxed local cache and run safety checks before any downstream cognition primitive (indexer / compressor / generator) touches the tree. Bounded by size + file-count ce
async function ingest_repository(args: Record<string, unknown>, ctx: CognitionCtx): Promise<unknown> {
  // The actual implementation lives in src/cognition/ingest.ts so it can be
  // unit-tested and audited outside the catalog spec template. We just wire
  // the typed binding values into the runtime call here.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { ingestRepository } = require("./ingest") as typeof import("./ingest");
  const url = String(args.url || "");
  if (!url) throw new Error("ingest_repository: missing required input 'url'");
  const opts: Record<string, unknown> = {};
  if (args.ref !== undefined) opts.ref = String(args.ref);
  if (typeof args.max_bytes === "number") opts.max_bytes = args.max_bytes;
  if (typeof args.max_files === "number") opts.max_files = args.max_files;
  if (typeof args.timeout_ms === "number") opts.timeout_ms = args.timeout_ms;
  ctx.metrics.counter("cognition.ingest_repository", { ref: String(args.ref || "HEAD") });
  return await ingestRepository(url, opts);
}


// semantic_slice (retrieval, cost=tiny, callsModel=false)
// Bounded graph-based retrieval: walk the symbol/dependency graph from a task description outward to `hop_depth`, capped at `max_files`. Never dumps the whole repo. The graph itself is built by the memo
async function semantic_slice(args: Record<string, unknown>, ctx: CognitionCtx): Promise<unknown> {
  const task = String(args.task || "");
  const maxFiles = Number(args.max_files) || 8;
  const hopDepth = Number(args.hop_depth) || 2;
  // Phase 10: optional repo filter — single string or array. Threaded through
  // the index's walk() so the BFS never crosses repo_id boundaries.
  const repoFilter = args.repos === undefined
    ? undefined
    : (typeof args.repos === "string" ? args.repos : (Array.isArray(args.repos) ? args.repos as string[] : undefined));
  // Either the user passes an index handle, or we fall back to the memory layer's singleton.
  const passed = (args.index as { walk?: (task: string, hops: number, cap: number, repos?: string | string[]) => { files: string[]; symbols: string[]; target_symbol?: string } }) || {};
  const useIndex = (typeof passed.walk === "function" ? passed : ctx.memory.getIndex()) as { walk?: (task: string, hops: number, cap: number, repos?: string | string[]) => { files: string[]; symbols: string[]; target_symbol?: string } } | null;

  if (useIndex && typeof useIndex.walk === "function") {
    const r = useIndex.walk(task, hopDepth, maxFiles, repoFilter);
    ctx.metrics.counter("cognition.semantic_slice", { source: "index", filtered: repoFilter ? "yes" : "no" });
    return { files: r.files, symbols: r.symbols, target_symbol: r.target_symbol ?? r.symbols[0] ?? "" };
  }

  // No index — return the empty slice. Phase 4 emits the memory layer when
  // a capability uses semantic_slice, so this branch is mostly defensive.
  ctx.metrics.counter("cognition.semantic_slice", { source: "stub" });
  return { files: [], symbols: [], target_symbol: "" };
}


export type CognitionPrimitive = (args: Record<string, unknown>, ctx: CognitionCtx) => Promise<unknown>;

export const PRIMITIVES: Record<string, CognitionPrimitive> = {
  "ingest_repository": ingest_repository,
  "semantic_slice": semantic_slice,
};

export function callCognition(name: string, args: Record<string, unknown>, ctx: CognitionCtx): Promise<unknown> {
  const fn = PRIMITIVES[name];
  if (!fn) throw new Error(`Unknown cognition primitive: ${name}`);
  return fn(args, ctx);
}
