/**
 * One-shot rename pass: BoneScript → MarrowScript.
 *
 * Substitutions (case-sensitive, longest-first to avoid partial overlaps):
 *
 *   BoneScript                    → MarrowScript
 *   bonescript                    → marrowscript
 *   bonescript-compiler           → marrowscript-compiler   (npm pkg)
 *   bonec\b                       → marrowc                 (CLI binary)
 *   \.bone\b                      → .marrow                 (file extension)
 *   X-BoneScript-Signature        → X-MarrowScript-Signature
 *   X-BoneScript-Event            → X-MarrowScript-Event
 *   <bonescript:ext:NAME:begin>   → <marrowscript:ext:NAME:begin>
 *   <bonescript:ext:NAME:end>     → <marrowscript:ext:NAME:end>
 *
 * Excluded paths:
 *   - node_modules / dist / .git / build / output / output-nakama / output-sqlite
 *   - tmp_phase*_e2e/ (transient test scratch)
 *   - package-lock.json (lock files; npm regenerates on next install)
 *   - examples/marketplace/output/ — will be regenerated cleanly post-rename
 *
 * After substitutions, rename .bone files to .marrow.
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");

// Order matters: longer / more-specific patterns come first so we don't
// rewrite the inside of a longer phrase before catching it whole.
const REPLACEMENTS: Array<[RegExp, string]> = [
  // Compound headers (must come before plain BoneScript replacement).
  [/X-BoneScript-Signature/g, "X-MarrowScript-Signature"],
  [/X-BoneScript-Event/g, "X-MarrowScript-Event"],
  // Sentinel comments — preserve the NAME group.
  [/<bonescript:ext:([a-zA-Z_][a-zA-Z0-9_]*):begin>/g, "<marrowscript:ext:$1:begin>"],
  [/<bonescript:ext:([a-zA-Z_][a-zA-Z0-9_]*):end>/g, "<marrowscript:ext:$1:end>"],
  // npm package name (more specific than 'bonescript' alone).
  [/bonescript-compiler/g, "marrowscript-compiler"],
  // Bare brand strings.
  [/BoneScript/g, "MarrowScript"],
  [/bonescript/g, "marrowscript"],
  // CLI binary — \b is word boundary.
  [/\bbonec\b/g, "marrowc"],
  // File extension — match only when followed by a non-word char or end of line.
  // We do NOT match '.bone' inside identifiers like 'someBone' or 'phone'.
  [/\.bone(?=[^a-zA-Z0-9_]|$)/g, ".marrow"],
];

// Directories never touched.
const SKIP_DIRS = new Set([
  "node_modules",
  "dist",
  "build",
  ".git",
  "output",
  "output-nakama",
  "output-sqlite",
  "tmp_phase2_e2e",
  "tmp_phase3_e2e",
  "tmp_phase4_e2e",
  "tmp_phase5_e2e",
  "tmp_phase6_e2e",
  "scripts",  // including this file itself — we don't rewrite the rename script
]);

// Specific files never touched (lock files regenerate, generated marketplace
// fixture rebuilds from source).
const SKIP_FILES = new Set([
  "package-lock.json",
]);

const SKIP_PATH_FRAGMENTS = [
  // The checked-in marketplace fixture will be regenerated by `marrowc compile`
  // after the rename so headers and sentinels match the new identity.
  path.join("examples", "marketplace", "output").replace(/\\/g, "/"),
];

function isExtensionRewritable(name: string): boolean {
  return /\.(ts|md|json|yaml|yml|sql|peg|bone|tmLanguage\.json|js|tsx|jsx)$/i.test(name);
}

function shouldSkipPath(rel: string): boolean {
  const normalised = rel.replace(/\\/g, "/");
  if (SKIP_FILES.has(path.basename(rel))) return true;
  for (const fragment of SKIP_PATH_FRAGMENTS) {
    if (normalised.includes(fragment)) return true;
  }
  return false;
}

function walk(dir: string, files: string[]): void {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const e of entries) {
    if (e.isDirectory()) {
      if (SKIP_DIRS.has(e.name)) continue;
      walk(path.join(dir, e.name), files);
    } else if (e.isFile()) {
      const rel = path.relative(ROOT, path.join(dir, e.name));
      if (shouldSkipPath(rel)) continue;
      if (!isExtensionRewritable(e.name)) continue;
      files.push(path.join(dir, e.name));
    }
  }
}

function rewrite(filePath: string): { changed: boolean; renames?: { from: string; to: string } } {
  const original = fs.readFileSync(filePath, "utf-8");
  let result = original;
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  const changed = result !== original;
  if (changed) {
    fs.writeFileSync(filePath, result, "utf-8");
  }

  // Now check for .bone → .marrow file rename.
  const ext = path.extname(filePath);
  if (ext === ".bone") {
    const newPath = filePath.slice(0, -ext.length) + ".marrow";
    fs.renameSync(filePath, newPath);
    return { changed, renames: { from: filePath, to: newPath } };
  }
  // Also rename bone.map / .bone.tmLanguage.json patterns living in filenames.
  const base = path.basename(filePath);
  if (/^bone\.tmLanguage\.json$/i.test(base)) {
    const newPath = path.join(path.dirname(filePath), "marrow.tmLanguage.json");
    fs.renameSync(filePath, newPath);
    return { changed, renames: { from: filePath, to: newPath } };
  }
  return { changed };
}

function main(): void {
  const files: string[] = [];
  walk(ROOT, files);
  let changed = 0;
  let renamed = 0;
  for (const f of files) {
    const r = rewrite(f);
    if (r.changed) changed++;
    if (r.renames) {
      renamed++;
      console.log(`renamed: ${path.relative(ROOT, r.renames.from)} → ${path.relative(ROOT, r.renames.to)}`);
    }
  }
  console.log(`\nDone: ${changed} files rewritten, ${renamed} files renamed.`);
}

main();
