// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 4 — public memory entry.
//
// Application code calls getIndex() once and reuses the returned handle.
// The handle implements SemanticIndex (see types.ts) so it satisfies the
// `index:` parameter expected by the cognition catalog's semantic_slice
// primitive.

import * as path from "path";
import { logger } from "../logger";
import { counter } from "../metrics";
import { buildIndex, type IndexedRepo } from "./semantic_index";
import { walkIndex } from "./retriever";
import type { Symbol, SemanticIndex, SemanticSlice, RepoFilter } from "./types";

const ROOT = path.resolve(process.env.LLM_MEMORY_ROOT || process.cwd());

class InProcessIndex implements SemanticIndex {
  private repo: IndexedRepo | null = null;

  private ensure(): IndexedRepo {
    if (!this.repo) {
      const start = Date.now();
      this.repo = buildIndex(ROOT);
      logger.info("memory_index_built", {
        event: "memory.index",
        status: "success",
        duration_ms: Date.now() - start,
        trace_id: "",
        metadata: { files: this.repo.files.length, root: ROOT },
      });
      counter("memory.index_built");
    }
    return this.repo;
  }

  walk(task: string, hopDepth: number, maxFiles: number, repo_filter?: RepoFilter): SemanticSlice {
    const r = this.ensure();
    const slice = walkIndex(r, task, hopDepth, maxFiles, repo_filter);
    counter("memory.walk", { hits: String(slice.files.length) });
    return slice;
  }

  symbolsByFile(file: string): Symbol[] {
    return this.ensure().symbolsByFile.get(file) || [];
  }

  importsOf(file: string): string[] {
    return this.ensure().importsByFile.get(file) || [];
  }

  async refresh(): Promise<void> {
    this.repo = null;
    this.ensure();
  }

  // Internal: expose the underlying repo for the compressor.
  __repo(): IndexedRepo { return this.ensure(); }
  __root(): string { return ROOT; }
}

const SINGLETON = new InProcessIndex();

export function getIndex(): SemanticIndex { return SINGLETON; }

/**
 * Compress the slice at `task` to fit within `targetTokens`. Convenience
 * helper that wires the retriever and the compressor.
 */
export async function sliceForPrompt(task: string, options: { hopDepth?: number; maxFiles?: number; targetTokens?: number } = {}): Promise<{ slice: SemanticSlice; text: string }> {
  const { compressSlice } = await import("./compressor");
  const slice = SINGLETON.walk(task, options.hopDepth ?? 2, options.maxFiles ?? 8);
  const compressed = compressSlice(slice, SINGLETON.__repo(), SINGLETON.__root(), options.targetTokens ?? 4000);
  return { slice, text: compressed.text };
}

export type { SemanticSlice } from "./types";
