// Generated by MarrowScript compiler. DO NOT EDIT.
// Phase 21 — admin routes for budget inspection + reset.

import { Router, Request, Response } from "express";
import { requireAuth, AuthContext } from "../auth";
import { getBudgetState, resetBudgetForScope } from "../policy/budgets";

export const adminBudgetsRouter = Router();

// GET /admin/budgets/:tenant_id?  — read counters for one tenant or all
adminBudgetsRouter.get("/:tenant_id?", requireAuth, async (req: Request, res: Response) => {
  const tenantId = (req.params as { tenant_id?: string }).tenant_id ?? null;
  const state = await getBudgetState(tenantId);
  return res.json({ tenant_id: tenantId, counters: state });
});

// POST /admin/budgets/:scope_value/reset
adminBudgetsRouter.post("/:scope_value/reset", requireAuth, async (req: Request, res: Response) => {
  const auth = (req as Request & { auth?: AuthContext }).auth;
  const actorId = auth?.actor_id || "unknown";
  const sv = String(req.params.scope_value);
  const r = await resetBudgetForScope(sv, actorId);
  return res.json({ ok: true, removed: r.removed });
});
