// Generated by MarrowScript compiler. DO NOT EDIT.
// HTTP read API for cognition traces (Phase 6 / frontend-ready).
//
// Routes:
//   GET /cognition_traces/:trace_id   — every span for a trace_id, ordered.
//
// Spans contain redacted projections of the prompt input/output (the full
// payload is never persisted), the model + provider used, the validate
// result, and per-call latency / token usage. The frontend renders this as
// a "what just happened" timeline alongside the forge result.

import { Router, Request, Response } from "express";
import { requireAuth } from "../auth";
import { loadTrace } from "../cognition/traces";
import rateLimit from "express-rate-limit";

export const cognitionTracesRouter = Router();

const __routeRateLimit = rateLimit({ windowMs: 60000, max: 60, standardHeaders: true, legacyHeaders: false });

cognitionTracesRouter.get("/:trace_id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  const { trace_id } = req.params;
  if (!/^[0-9a-f-]{8,}$/i.test(trace_id)) {
    return res.status(400).json({ error: { code: "INVALID_TRACE_ID", message: "trace_id must be a UUID-like string" } });
  }
  try {
    const spans = await loadTrace(trace_id);
    res.json({
      trace_id,
      span_count: spans.length,
      spans,
    });
  } catch (e: any) {
    res.status(500).json({ error: { code: "TRACE_LOAD_FAILED", message: e.message } });
  }
});
