// Generated by MarrowScript compiler. DO NOT EDIT.
// Service: RepoForgeRequestService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import rateLimit from "express-rate-limit";
import { auditLog } from "../audit";
import { logger } from "../logger";
import { counter } from "../metrics";
import { RepoForgeRequestCreateSchema, RepoForgeRequestUpdateSchema } from "../schemas";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

export const repoForgeRequestsRouter = Router();

// Rate limiter from policy declaration
const __routeRateLimit = rateLimit({ windowMs: 60000, max: 30, standardHeaders: true, legacyHeaders: false });

// CREATE
repoForgeRequestsRouter.post("/", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  // Validate the request body against the generated Zod schema.
  const __parsed = RepoForgeRequestCreateSchema.safeParse(req.body);
  if (!__parsed.success) {
    return res.status(400).json({ error: { code: "VALIDATION_FAILED", message: "Invalid request body", issues: __parsed.error.flatten() } });
  }
  const __body = __parsed.data;
  try {
    const id = uuid();
    const { title, description, preset, repo_a_url, repo_b_url, repo_a_ref, repo_b_ref, target_path, complexity } = __body as any;
    const sql = `INSERT INTO repo_forge_requests (id, title, description, preset, repo_a_url, repo_b_url, repo_a_ref, repo_b_ref, target_path, complexity) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING *`;
    const rows = await query(sql, [id, title, description, preset, repo_a_url, repo_b_url, repo_a_ref, repo_b_ref, target_path, complexity]);
    counter("entity.created", { entity: "RepoForgeRequest" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
repoForgeRequestsRouter.get("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const row = await queryOne(`SELECT * FROM repo_forge_requests WHERE id = $1`, [req.params.id]);
    if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.json(row);
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// LIST
repoForgeRequestsRouter.get("/", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
    const offset = (page - 1) * pageSize;
    const rows = await query(`SELECT * FROM repo_forge_requests ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
    const [{ count }] = await query(`SELECT COUNT(*) as count FROM repo_forge_requests`);
    res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// UPDATE
const __repoForgeRequestsUpdatable = new Set<string>(["title","description","preset","repo_a_url","repo_b_url","repo_a_ref","repo_b_ref","target_path","complexity"]);
repoForgeRequestsRouter.put("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  // 1. Validate body shape and types via Zod (UpdateSchema is partial).
  const __parsed = RepoForgeRequestUpdateSchema.safeParse(req.body);
  if (!__parsed.success) {
    return res.status(400).json({ error: { code: "VALIDATION_FAILED", message: "Invalid request body", issues: __parsed.error.flatten() } });
  }
  // 2. Reject unknown columns (defense in depth — Zod would already strip them).
  const __unknown = Object.keys(req.body || {}).filter(k => !__repoForgeRequestsUpdatable.has(k));
  if (__unknown.length > 0) {
    return res.status(400).json({ error: { code: "UNKNOWN_FIELDS", message: `Unknown fields: ${__unknown.join(", ")}`, fields: __unknown } });
  }
  // 3. Use the Zod-parsed object as the update set.
  const fields: Record<string, unknown> = __parsed.data as Record<string, unknown>;
  if (Object.keys(fields).length === 0) {
    return res.status(400).json({ error: { code: "NO_FIELDS", message: "No updatable fields supplied" } });
  }
  const keys = Object.keys(fields);
  const sets = keys.map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = keys.map(k => fields[k]);
  const sql = `UPDATE repo_forge_requests SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
repoForgeRequestsRouter.delete("/:id", __routeRateLimit, requireAuth, async (req: Request, res: Response) => {
  try {
    const count = await execute(`DELETE FROM repo_forge_requests WHERE id = $1`, [req.params.id]);
    if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.status(204).send();
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// CAPABILITY: ingest_repo_a
repoForgeRequestsRouter.post("/ingest-repo-a", __routeRateLimit, requireAuth, auditLog("ingest_repo_a", "RepoForgeRequest"), async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  try {
    // sync: eventual — effects applied, events queued via outbox
    // Fetch entities
    const r = await queryOne(`SELECT * FROM repo_forge_requests WHERE id = $1`, [req.body.r_id || req.params.id]);
    if (!r) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "r not found" } });
    }

    res.json({ ok: true, action: "ingest_repo_a", entity: r });
  } catch (e: any) {
    if (!res.headersSent) {
      res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
    } else {
      logger.error("late_error_after_response", { event: "ingest_repo_a", status: "rejected", metadata: { error: String(e?.message || e).slice(0, 256) } });
    }
  }
});

// CAPABILITY: ingest_repo_b
repoForgeRequestsRouter.post("/ingest-repo-b", __routeRateLimit, requireAuth, auditLog("ingest_repo_b", "RepoForgeRequest"), async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  try {
    // sync: eventual — effects applied, events queued via outbox
    // Fetch entities
    const r = await queryOne(`SELECT * FROM repo_forge_requests WHERE id = $1`, [req.body.r_id || req.params.id]);
    if (!r) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "r not found" } });
    }

    res.json({ ok: true, action: "ingest_repo_b", entity: r });
  } catch (e: any) {
    if (!res.headersSent) {
      res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
    } else {
      logger.error("late_error_after_response", { event: "ingest_repo_b", status: "rejected", metadata: { error: String(e?.message || e).slice(0, 256) } });
    }
  }
});

// CAPABILITY: forge_from_repos [transactional declared, sql-tx skipped: pure cognition pipeline]
repoForgeRequestsRouter.post("/forge-from-repos", __routeRateLimit, requireAuth, auditLog("forge_from_repos", "RepoForgeRequest"), async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  try {
    // Pipeline: 5 step(s), sequential
    let r: any;
    if (req.body && req.body.r_id) {
      r = await queryOne(`SELECT * FROM repo_forge_requests WHERE id = $1`, [req.body.r_id]);
      if (!r) {
        return res.status(404).json({ error: { code: "NOT_FOUND", message: "r not found" } });
      }
    } else if (req.params && req.params.id) {
      r = await queryOne(`SELECT * FROM repo_forge_requests WHERE id = $1`, [req.params.id]);
      if (!r) {
        return res.status(404).json({ error: { code: "NOT_FOUND", message: "r not found" } });
      }
    } else if (req.body && typeof req.body === "object") {
      // Inline mode: treat the body as the entity itself.
      r = req.body;
    } else {
      return res.status(400).json({ error: { code: "MISSING_INPUT", message: "Provide r_id or the r body" } });
    }
    const { randomUUID: __randomUUID } = require("crypto");
    const __cogCtx = { trace_id: __randomUUID() };
    const { getPrompt: __getPrompt } = require("../cognition");
    const { runCognition: __runCog } = require("../cognition");
    const __pipeline_completed: { step: string; rollback: (() => Promise<void>) | null }[] = [];
    const __pipeline_results: Record<string, unknown> = {};

    try {
      __pipeline_results["repo_a"] = await __runCog("ingest_repository", { url: r.repo_a_url, ref: r.repo_a_ref });
      __pipeline_completed.push({ step: "ingest_repo_a", rollback: null });
      counter("pipeline.step_completed", { method: "forge_from_repos", step: "ingest_repo_a" });
      __pipeline_results["repo_b"] = await __runCog("ingest_repository", { url: r.repo_b_url, ref: r.repo_b_ref });
      __pipeline_completed.push({ step: "ingest_repo_b", rollback: null });
      counter("pipeline.step_completed", { method: "forge_from_repos", step: "ingest_repo_b" });
      __pipeline_results["analysis"] = await __getPrompt("analyze_repo_forge_request")({ title: r.title, description: r.description, preset: r.preset, repo_a_url: r.repo_a_url, repo_a_files: ((__pipeline_results["repo_a"] as any).file_count), repo_a_sha: ((__pipeline_results["repo_a"] as any).head_sha), repo_b_url: r.repo_b_url, repo_b_files: ((__pipeline_results["repo_b"] as any).file_count), repo_b_sha: ((__pipeline_results["repo_b"] as any).head_sha) }, __cogCtx);
      __pipeline_completed.push({ step: "analyze_repo_forge_request", rollback: null });
      counter("pipeline.step_completed", { method: "forge_from_repos", step: "analyze_repo_forge_request" });
      __pipeline_results["scoped"] = await __getPrompt("scope_for_typescript")({ description: r.description, preset: r.preset, analysis: (__pipeline_results["analysis"] as any) }, __cogCtx);
      __pipeline_completed.push({ step: "scope_for_typescript", rollback: null });
      counter("pipeline.step_completed", { method: "forge_from_repos", step: "scope_for_typescript" });
      // Phase 11: match dispatch on r.preset
      {
        const __match_key = r.preset;
        if (__match_key === "compare_apis") {
        __pipeline_results["artifact"] = await __getPrompt("generate_forge_report")({ plan: (__pipeline_results["analysis"] as any), target_symbol: "", files: "", desired_kind: r.preset, target_path: r.target_path, description: r.description, complexity: r.complexity }, __cogCtx);
        __pipeline_completed.push({ step: "generate_forge_report", rollback: null });
        counter("pipeline.step_completed", { method: "forge_from_repos", step: "generate_forge_report" });
        }
        else if (__match_key === "migrate") {
        __pipeline_results["artifact"] = await __getPrompt("generate_forge_report")({ plan: (__pipeline_results["analysis"] as any), target_symbol: "", files: "", desired_kind: r.preset, target_path: r.target_path, description: r.description, complexity: r.complexity }, __cogCtx);
        __pipeline_completed.push({ step: "generate_forge_report", rollback: null });
        counter("pipeline.step_completed", { method: "forge_from_repos", step: "generate_forge_report" });
        }
        else {
        __pipeline_results["artifact"] = await __getPrompt("generate_forge_artifact")({ plan: (__pipeline_results["scoped"] as any), target_symbol: "", files: "", desired_kind: r.preset, target_path: r.target_path, description: r.description, complexity: r.complexity }, __cogCtx);
        __pipeline_completed.push({ step: "generate_forge_artifact", rollback: null });
        counter("pipeline.step_completed", { method: "forge_from_repos", step: "generate_forge_artifact" });
        }
      }
      res.json({
        ok: true,
        action: "forge_from_repos",
        trace_id: __cogCtx.trace_id,
        results: __pipeline_results,
      });
    } catch (__err: any) {
      // on_error: rollback completed steps in reverse order
      for (const c of [...__pipeline_completed].reverse()) {
        if (c.rollback) await c.rollback().catch(() => {});
      }
      counter("pipeline.failed", { method: "forge_from_repos" });
      logger.error("pipeline_failed", { event: "forge_from_repos", metadata: { error: __err.message } });
      throw __err;
    }
  } catch (e: any) {
    if (!res.headersSent) {
      res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
    } else {
      logger.error("late_error_after_response", { event: "forge_from_repos", status: "rejected", metadata: { error: String(e?.message || e).slice(0, 256) } });
    }
  }
});
